/* ============================================================
   JUST A GIRL (Lia Levi) — BOOK STUDY APP DATA
   Content data only. No markup/behaviour lives in this file.
   Years 7–8 · NZ Curriculum Level 4 English
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Identity, Courage & Belonging", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 4 (Years 7–8).
   "Achieved" = the curriculum expectation has been met.
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    expect: "Explains the memoir's big ideas — the difference between an identity you choose and a label imposed on you, the cost and courage of hiding, found family — and supports them with events from more than one part of the book.",
    kid: "I can explain a big idea that runs through Lia's whole story, and back it up with events from more than one chapter.",
    ask: "Does the student connect an idea across chapters, not just retell a single scene?",
    na: "Retells events from a single chapter but cannot yet connect it to the wider book.",
    wt: "Names a shared idea (e.g. 'she had to hide who she was') with a general reason, but the connection across the book is thin.",
    ach: "Explains an idea that runs across at least two parts of the memoir and supports it with a specific, accurate event from each.",
    wtSample: "Lia had to pretend she wasn't Jewish so the Nazis wouldn't find her.",
    exemplar: "The book keeps circling back to the idea that a label is not the same as a self. Early on, Lia's school records say 'female student of Jewish race' — a label written by people in power to justify hurting her. By the very last chapter, Mama tears up Lia's letter and tells her she is 'just a girl,' meaning her Jewishness is hers to share or not, not a fact the State gets to weaponise. The same idea even appears in her fake name at the convent — Levi becomes Lenti — showing how identity can be hidden to survive, without ever actually disappearing.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-deeper reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features on a text's meaning.",
    expect: "Notices the author's structural choice — a grown woman narrating her own childhood directly to \"dear readers,\" often warning us in advance when something painful is coming, and mixing humour with history — and explains what effect that has on the reader.",
    kid: "I can explain why the author writes as if she is speaking directly to me, and what effect that has on how the story feels.",
    ask: "Does the student name the structural/language choice AND explain its effect, not just describe the plot?",
    na: "Comments only on what happens in the plot; does not yet notice how the book is narrated.",
    wt: "Notices the direct-address style (\"dear readers\") but cannot explain why, or the explanation is very general ('it's friendly').",
    ach: "Names a specific narrative technique — direct address, adult-Lia foreshadowing, comic child's-eye misunderstandings — and explains a specific effect it has, e.g. building trust before delivering hard news, or making a devastating historical event land harder because it arrives inside a funny, ordinary voice.",
    wtSample: "She talks to the reader like a friend which makes it feel less scary.",
    exemplar: "Before the worst news in the book — the October roundup — Lia-the-narrator stops and tells us in advance that Papa survives, \"so I'm going to tell you in advance: what Mama said was quite true.\" That's a deliberate structural choice: by softening the blow before it lands, the adult narrator protects her child readers the same way the adults in the story tried to protect her. It also makes the humour elsewhere (the newspaper story, Nonna Teresa's \"inventions\") feel earned rather than tone-deaf, because we trust this narrator knows exactly how much we can carry.",
    evidence: "Structure & language questions, inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, comparing, synthesising — and links an early detail to a later one (the peep-peep-peep voice, the lost teddy bear Nerino, the ribbon colours, the false name).",
    kid: "I can link something from earlier in the book to something later, and explain why the author placed both details there on purpose.",
    ach: "Independently draws a justified connection between an earlier and later moment in the memoir, without being told to.",
    wt: "Makes a link between two events only when prompted, or the link is superficial (both are 'sad').",
    ask: "Can the student explain WHY two moments echo each other, not just THAT they do?",
    wtSample: "Lia's voice was quiet at the start and then it got loud, that's a connection.",
    exemplar: "Lia compares Papa losing his job to her losing her teddy bear, Nerino — and she tells us straight out the comparison doesn't work, because 'you can't forget a job late one afternoon under a beach umbrella.' Recognising that this comparison is Lia's-child-logic, not the truth, helped me realise the author is showing us how a child makes sense of adult unfairness using the only tools she has — and that gap between what Lia understands and what we, as readers, understand is exactly how the author builds dramatic irony throughout the whole book.",
    evidence: "Predictions, cross-chapter comparison questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics, showing an increasing awareness of purpose and audience.",
    expect: "Writes and shares clear, developed opinions and explanations about the book — including on difficult questions (was Papa right to swear Lia to secrecy? did the nuns do the right thing hiding dozens of children?) — with supporting detail from the text and, where relevant, the historical record.",
    kid: "I can share a clear opinion about a hard question the book raises, and back it up with reasons and evidence.",
    ask: "Is there a clear position PLUS at least two reasons or pieces of evidence, including historical context where it's relevant?",
    na: "Answers are one-sided, unclear, or state an opinion with no supporting reason.",
    wt: "Shares a clear opinion but gives only one reason, or does not use evidence from the text.",
    ach: "Communicates a clear, considered opinion and develops it with at least two reasons or pieces of evidence, drawn from the text and/or the author's closing letter.",
    wtSample: "I think Papa was right to keep it a secret because it was dangerous.",
    exemplar: "I think Papa was right to make Lia promise never to repeat what he told her, even though it clearly frightened her. First, the text shows real consequences for anyone who spoke against Mussolini — arrest, or worse — so silence wasn't cowardice, it was survival. Second, Papa balances the fear by giving Lia something hopeful to hold onto too: he tells her to imagine herself as a secret agent from her books, which the text shows genuinely helps her cope later, when she has to live under a false name. Keeping the secret wasn't about not trusting Lia — it was the only way to keep her safe in a country where children could get their parents arrested.",
    evidence: "Go-deeper reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts for a range of purposes and audiences.",
    expect: "Chooses the right structure and language for the task — a diary entry, a letter, a persuasive poster, a script — and matches register and tone to 1938–45 Italy as appropriate, including the mix of a child's voice with an adult narrator's hindsight.",
    kid: "I can choose the right kind of writing and the right voice for the task, and make it sound like it belongs to the right time and place.",
    ach: "Uses a suitable structure and language features for the purpose and audience, and the voice/register fits the character's world (e.g. a child's confused, funny logic for an early diary entry; a more solemn, reflective adult voice for a closing letter).",
    wt: "Attempts the right form but the language or structure is inconsistent, or doesn't fit the era/character.",
    ask: "Does the writing look, sound, and feel like it belongs to the narrator and the time period it claims?",
    na: "Writing does not match the task; little attempt at structure or appropriate language features.",
    wtSample: "Dear diary, today was scary because we had to go and hide from the Germans.",
    exemplar: "16 October, before dawn — Rome. Mama's face when she says 'the Germans' is a face I have never seen on her before. I keep thinking: yesterday I was worrying about my admission-test photograph, and today Papa doesn't know where he will sleep. I am trying to imagine myself as one of the secret agents in my books, the way Papa said to. It is much harder to feel brave than to imagine it.",
    evidence: "Poster, comic, drama & journal projects; Week 9 opinion writing; Week 10 final project" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback (Glow & Grow) to improve it, and can explain a specific change made because of that feedback.",
    kid: "I can plan my work, improve a draft, and use feedback to make a specific, named improvement.",
    ach: "Independently plans, drafts and revises, and can point to a specific change made because of feedback.",
    wt: "Plans and drafts with support; makes only small, vague changes when prompted.",
    ask: "Can you see a plan AND one specific change the student can name and explain?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wtSample: "I finished my poster. My partner said to add more detail so I did.",
    exemplar: "My plan had three panels: the ribbon colours at Passover, the false name at the convent, and Mama tearing up my letter. My partner's 'grow' note said the middle panel didn't explain why the name mattered, so I added a small caption — 'Levi become Lenti so the Germans, who had written down every Jewish surname, would not recognise it' — which made the whole poster's argument about hidden identity actually hold together.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas — including views on sensitive, real-world issues.",
    expect: "Listens to and builds on others' ideas during group reading and projects, including when discussing difficult or sensitive topics (racial persecution, hiding, the Holocaust, war), and disagrees respectfully.",
    kid: "I can listen to my group, take turns, and build on — or respectfully challenge — other people's ideas, even about hard topics.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas, especially on sensitive real-world topics raised by the book.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ask: "Does the student respond to what others say — including disagreeing respectfully — rather than just waiting for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt, dismiss others, or opt out.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I see it a bit differently to Mia — I don't think Maria abandoning them for a while makes her a bad person, because the text shows she comes back and protects their whole apartment later. People can let you down and still truly love you. Can we look at the apple-in-the-bag part again?\" She then invited a quieter group member to share their reading of Maria.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects, discussion circles — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas, including recognising bias and perspective.",
    expect: "Makes inferences about characters' feelings and motives using clues from the text, and thinks critically about perspective and bias — whose viewpoint a scene is told from, and what is left out.",
    kid: "I can use clues in the story to work out things the author doesn't state directly, and notice whose point of view I'm not getting.",
    ach: "Independently infers feelings or motives and points to the textual clue, AND can identify a perspective the text does not show (the tired German soldier at the fountain, the nuns risking their own safety, the neighbour who agreed to pretend Maria worked for her) and speculate about it fairly.",
    wt: "Makes an inference with prompting but struggles to explain the clue, or does not yet consider perspectives beyond Lia's.",
    ask: "Has the student worked something out, pointed to the clue, AND considered an angle the text doesn't spell out?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wtSample: "The nun felt sorry for the German soldier because she said 'poor boy.'",
    exemplar: "The text never explains why Sister Maria Luisa's voice softens when she says goodbye to Mama at the convent gate, but the detail that she says it 'gently' — right after we've learned dozens of nuns are risking their own safety hiding Jewish children — tells me she already understood exactly how much this goodbye would cost Lia. That single word 'gently' is doing more work than a whole paragraph of explanation would. It also made me wonder about a perspective the book never gives us: what did it cost Sister Giacinta, as Mother Superior, to say yes to over thirty hidden children, knowing what would happen to her convent if the Germans found out?",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions, discussion" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility, including for topics that connect to real communities beyond the classroom.",
    expect: "Contributes ideas in class discussions and projects, takes responsibility for a role in group work, and connects the book to real communities and current events with care and accuracy — including the author's own point, made directly to readers, that \"racism continues to stain society today.\"",
    kid: "I can share my ideas, do my part in group work, and connect the book to the real world responsibly.",
    ach: "Offers ideas without being asked, takes responsibility for a role, encourages others, and makes an accurate, respectful connection between the book and a real-world issue of belonging or prejudice.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ask: "Does the student offer ideas and take on a job without being asked, and handle real-world connections with care rather than glib comparison?",
    na: "Rarely contributes to discussions or group projects.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 exhibit group, Ana researched the real October 1943 roundup mentioned in the author's note, made sure the group's facts were accurate and respectfully worded rather than sensationalised, and made sure every member had a speaking part in the final gallery walk.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Identity, Courage & Belonging", strand: "Values",
    curriculum: "Values: diversity, community and participation, respect, and care for others — recognising courage, identity beyond a single label, and what it means to belong.",
    expect: "Connects the book's values — that a person is never just one label, that quiet everyday courage matters as much as dramatic bravery, and that belonging is built through people who choose to protect and welcome you — to their own life, community or actions.",
    kid: "I can connect the book's message about identity, courage and belonging to my own life or community.",
    ach: "Explains a value from the book and connects it to a real experience, action, or current issue of their own — without minimising the seriousness of what Lia and her family go through.",
    wt: "Names a value (e.g. 'be kind to people who are different') when asked, with a simple or general link.",
    ask: "Has the student linked a value from the book to something real, while still respecting how serious Lia's experiences are?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wtSample: "The book teaches us not to judge people by one thing about them.",
    exemplar: "Mama's line — 'you're Jewish, but that's something personal... these facts are no longer of any importance to the State' — makes me think about how quick people still are to reduce someone to one label: their accent, their religion, where their family comes from. My own family speaks a different language at home, and sometimes people act like that's the only interesting thing about us. Lia's story reminds me that being 'just a girl' — or just a person — doesn't erase who you are; it just refuses to let one label be used against you.",
    evidence: "Go-deeper reflections, journal entries, Week 10 'connections' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 4 English, Years 7–8, NZ Curriculum",
  lrv: [
    "Ideas: Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics, with increasing awareness of purpose and audience.",
    "Structure and Language: Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Identity beyond a single label, quiet everyday courage, found family and community protection, resilience, remembrance.",
  crossCurricular: "Social Sciences — history and human rights (Fascist Italy's 1938 racial laws, the German occupation of Italy, the October 1943 roundup of Roman Jews, the Holocaust, and the Allied liberation of Rome in 1944), since Lia's entire personal story is shaped directly by real laws and real historical events of 1938–1945 Italy, as her closing letter confirms.",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "The Voice Nobody Could Hear", chapters: "Chapters 1–2",
  LI: "We are learning to notice how an author uses humour and a child's-eye view to introduce a big historical injustice.",
  SC: "I can describe what Lia's shy \"peep peep peep\" voice reveals about her personality, and explain the real reason she is banned from school.",
  rubricTags: ["R1","R2","R8"],
  days: {
    mon: D("Chapter 1", "Meeting Lia at the seaside — the newspaper-stand story that reveals just how shy she is",
      "Think of something that felt terrifying to you as a six-year-old but seems small now. What made it feel so big at the time?",
      "Why do Lia's parents send her to buy the newspaper by herself?",
      "What does the phrase \"peep...peep...peep\" suggest about the sound of Lia's voice, and why might the author compare it to a baby bird instead of just saying \"she was quiet\"?",
      "Write two sentences describing something ordinary (like buying a newspaper) that once felt like a huge challenge to you."),
    tue: D("Chapter 2 (first half)", "Mama tells Lia she cannot go back to school — and explains, carefully, why",
      "Imagine being told you can't go to school anymore, for a reason that has nothing to do with anything you did. How would you react?",
      "What reason does Mama give for why Lia can't return to school?",
      "Lia is secretly relieved at first. Why? What does her reaction tell us about how well she understands the seriousness of the news?",
      "In your own words, explain what Papa means later when he says blaming a group of people is \"a way of keeping people quiet.\""),
    wed: D("Chapter 2 (second half)", "Papa's serious conversation with Lia about Mussolini, prejudice, and scapegoating",
      "Why might people in power look for someone else to blame when things go wrong in a country?",
      "What promise does Papa ask Lia to make, and why is that promise so important?",
      "This whole conversation is shown through Lia's confused, funny inner voice (\"Help! This is all I need after what happened with the newspaper!\"). What effect does that humour have on how we experience a very serious topic?",
      "Rewrite this moment from Papa's point of view instead of Lia's — what might he be feeling as he explains this to his daughter?"),
    thu: D("Chapter 2 (ending)", "The Jewish school is announced, ending Lia's short-lived freedom from school",
      "Have you ever been given news that was meant to sound like a fix, but wasn't quite what you wanted?",
      "What solution do Lia's parents find so she can keep learning?",
      "Why is it darkly funny that Lia briefly believes Mussolini has done her a favour?",
      "Predict: what do you think Lia's new Jewish school will be like? Give one reason for your prediction."),
  },
  projects: [
    P("poster", "Two Voices", "Design a before/after poster showing Lia's \"peep peep peep\" voice next to how you predict it might change, with one quote from the text for each side."),
    P("comic", "The Newspaper Stand", "A 4–6 panel comic retelling the newspaper story from Chapter 1, including at least one panel from the newspaper seller's point of view."),
    P("drama", "Papa's Warning", "In pairs, act out Papa's conversation with Lia about Mussolini and blame, keeping the balance of humour and seriousness the author uses."),
    P("journal", "A Rule That Wasn't Fair", "Write about a rule or decision you've experienced or heard about that punished you, or someone else, for something that wasn't their fault."),
  ],
  quiz: [
    Q("Where does Lia's family live at the start of the book?", "Turin, Italy."),
    Q("Who are Lia's two younger sisters?", "Gabriella and Vera."),
    Q("Why do Lia's parents send her to buy the newspaper alone?", "To force her to talk to someone else, because she is painfully shy."),
    Q("What sound does the author compare Lia's voice to?", "A baby bird's peep...peep...peep."),
    Q("True or False: The newspaper seller gives Lia the correct change.", "False — he claims she never paid, and Papa ends up paying for the newspaper twice.", "tf"),
    Q("What does Mama tell Lia she won't be able to do this year?", "Go back to school."),
    Q("Why does Mussolini not want Jewish children in Italian schools?", "Because of new antisemitic laws that treat Jewish people as scapegoats/targets."),
    Q("Vocabulary: What does \"scapegoat\" mean, based on Papa's explanation?", "Someone blamed for problems that aren't really their fault, often to distract from real issues."),
    Q("What promise does Papa ask Lia to make?", "To never repeat what he told her about Mussolini and the Jews to anyone."),
    Q("True or False: Lia is upset when she first hears she can't go to school.", "False — she is secretly relieved, since it means escaping the classroom where she felt unable to speak.", "tf"),
    Q("What solution do Lia's parents find so she can still be educated?", "A newly organised Jewish school near the synagogue in Turin."),
    Q("What does Lia used to call Mussolini in the songs and poems recited at her old school?", "\"Duce! Duce!\""),
    Q("Inference: Why might Papa seem \"angry\" when Lia declares she'll never chant \"Duce\" again, even though he agrees with her?", "He's afraid for her safety — saying so out loud, where others could hear, could put the family in danger."),
    Q("What is happening on the beach right before Mama and Papa announce the Jewish school news?", "A sandcastle-building contest."),
    Q("Structure: The story is narrated as if Lia is speaking directly to the reader (\"dear readers\"). What effect does this have?", "Open-ended — makes the story feel personal, warm and trustworthy, like being told a secret by a friend."),
    Q("Why might the author use humour (like the newspaper mix-up) right at the start of a book about a serious historical topic?", "Open-ended — draws the reader in, establishes Lia's voice and personality, and makes the seriousness that follows land harder by contrast."),
    Q("What does Papa mean when he says people in charge sometimes blame \"people who are different from them\" for a country's problems?", "Open-ended — describes scapegoating/prejudice used to distract from real problems and unite people against a target."),
    Q("Vocabulary: What does \"antisemitic\" mean (a word the book's ideas describe, even if it doesn't use the term itself)?", "Prejudiced against or hostile toward Jewish people."),
    Q("Predict: Why do you think a government would target children as well as adults with unfair laws?", "Open-ended, text-supported prediction — e.g. to affect every part of a family's life, or to normalise prejudice from a young age."),
    Q("What do you think the title \"Just a Girl\" might come to mean by the end of the book, based on Chapters 1–2?", "Open-ended prediction — accept references to identity, labels, or being seen as more than one thing."),
  ],
},
{
  num: 2, title: "Lending My Voice", chapters: "Chapters 3–4",
  LI: "We are learning to explain how a build-up of small details creates a powerful turning-point moment, and to track an idea (unfairness) across two very different kinds of loss.",
  SC: "I can retell what happens during the Four Questions and explain why it becomes a turning point for Lia's voice, and I can explain how the antisemitic laws affect adults like Papa, not just children.",
  rubricTags: ["R1","R3","R8"],
  days: {
    mon: D("Chapter 3 (first half)", "Cousin Annarosa becomes Lia's fierce protector at the new Jewish school",
      "What does it feel like to have someone older stick up for you, even if you didn't ask them to?",
      "How does cousin Annarosa become Lia's \"protector,\" and what do the other children do because of it?",
      "What does it suggest about Maestra Ginetta that she smiles at Lia's peep-peep-peep voice, compared to Lia's old teacher, who got \"bored\" of trying to understand her?",
      "Write about someone — real or from a story — who stuck up for you or someone else without being asked."),
    tue: D("Chapter 3 (Passover / the Four Questions)", "At the Passover dinner, Lia is unexpectedly asked to recite the Four Questions in front of everyone",
      "Has anyone ever believed in you so much that you managed to do something you didn't think you could?",
      "What are \"the Four Questions,\" and why does the youngest child at the table traditionally have to ask them?",
      "How does Maestra Ginetta help Lia recite the questions, and what happens to Lia's voice by the end of the scene?",
      "Write the moment Lia's voice changes for the first time, from her parents' point of view, watching from across the room."),
    wed: D("Chapter 4 (first half)", "Papa \"loses\" his job — and Lia compares it to losing her teddy bear, Nerino",
      "Why might it be easier for a child to make sense of a hard truth by comparing it to something simpler they already understand?",
      "What comparison does Lia make between losing Nerino and Papa losing his job — and why does she realise the comparison doesn't quite work?",
      "What does Mama mean when she says, \"They sent him away, just like they sent you away from your school\"?",
      "Explain in your own words the connection between the school ban from Week 1 and the job ban in this chapter."),
    thu: D("Chapter 4 (second half)", "The family's savings begin to run out, and Papa looks for a \"secret job\"",
      "What might it feel like to realise your family is running out of money, as a kid who doesn't fully understand how money works?",
      "What does Papa's plan for a \"secret job\" mean, and how is it different from a normal job?",
      "Why does Mama wait to tell Lia the truth about the bank savings running out?",
      "Predict what the family might have to do next if the money situation gets worse."),
  },
  projects: [
    P("poster", "My Voice, My Turning Point", "Illustrate the Four Questions scene as a turning point in Lia's life, comparing her voice before and after using two quotes from the text."),
    P("comic", "Losing a Job Isn't Losing a Teddy Bear", "A comic contrasting Lia's two \"losses\" — Nerino the teddy bear, and Papa's job — showing why one comparison works and the other doesn't."),
    P("drama", "The Four Questions", "Perform the Passover Seder scene, including Maestra Ginetta's whispered cues and the moment Lia's voice grows louder."),
    P("journal", "A Moment I Found My Voice", "Write about a real moment when you had to speak up, perform, or be brave in front of others, and what it felt like afterward."),
  ],
  quiz: [
    Q("Who becomes Lia's fierce protector at the Jewish school?", "Her cousin Annarosa."),
    Q("What game do the other children make Lia play at recess, thanks to Annarosa's protection?", "They refuse to let her be the \"donkey\"/loser, and sometimes give her gifts instead."),
    Q("What is the teacher's name at the Jewish school in Turin?", "Maestra Ginetta."),
    Q("What Jewish festival is being celebrated in this chapter?", "Passover (Pesach)."),
    Q("True or False: Lia already knows the Four Questions by heart before she is called up.", "False — Maestra Ginetta has to whisper each line to her first.", "tf"),
    Q("Vocabulary: What are \"the Four Questions\" traditionally asked at Passover?", "Questions asked by the youngest child at the table, beginning with \"Why is tonight different from all other nights?\", that prompt the retelling of the Passover story."),
    Q("What happens to Lia's voice by the end of the Four Questions scene?", "It grows loud and confident — and stays that way from then on."),
    Q("What does Mama tie in Lia's hair for the Passover dinner, and what do the colours represent?", "A white and light-blue ribbon bow — the colours of the Jewish flag."),
    Q("What has \"happened\" to Papa's job, according to what Lia overhears?", "He has lost it/been forced out because Jewish people were banned from many jobs."),
    Q("What is the name of Lia's lost teddy bear, and why does she compare him to Papa's job?", "Nerino — she initially thinks a job can be \"lost\" the same simple way a toy can be."),
    Q("Why does Lia realise the Nerino comparison doesn't really work?", "You can't accidentally forget or lose a job the way you lose a toy; it was taken from Papa on purpose, by unfair laws."),
    Q("Vocabulary: What does \"discriminate\" begin to mean in this section of the book?", "To treat a person or group unfairly/differently because of who they are."),
    Q("What does Papa decide to do while he searches for a new way to earn money?", "He starts painting Lia's portrait, considering becoming a painter."),
    Q("True or False: Mama tells Lia immediately that the family's savings are completely gone.", "False — she waits, and Lia finds out the full truth only later.", "tf"),
    Q("What kind of job is Papa hoping to find, given that Jewish people are banned from ordinary workplaces?", "A \"secret\" job — working quietly for one person, without anyone official finding out."),
    Q("Inference: Why might the author include Lia's mistaken belief that Mussolini invented \"Jewish jobs\" for Jewish fathers?", "Open-ended — shows how a child tries logically, if wrongly, to make sense of adult unfairness, and highlights how absurd the real laws actually are."),
    Q("Structure: How does the Four Questions scene use build-up (repetition, whispering, growing volume) to create its emotional impact?", "Open-ended — the whispered cues and rising volume mirror Lia literally finding and growing into her voice in real time."),
    Q("Why do you think the author places Lia's proudest moment (the Four Questions) in the same week as Papa's unfair job loss?", "Open-ended — contrast between a personal triumph and an injustice, showing life continuing to hold both joy and hardship at once."),
    Q("What do you think will happen to the family if Papa cannot find any work at all?", "Open-ended, text-supported prediction."),
    Q("What is one piece of evidence so far that antisemitic laws in Italy affect whole families, not just children?", "Open — accept Papa's job loss, the family's shrinking savings, or the earlier ban on Jewish children in schools."),
  ],
},
{
  num: 3, title: "When the War Came Home", chapters: "Chapters 5–6",
  LI: "We are learning to explain how setting and mood work together to build tension, and to contrast that with a lighter, hopeful mood elsewhere in the same section.",
  SC: "I can describe the bombing of Turin using evidence from the text, and explain how the mood of the Milan chapters offers a contrast to it.",
  rubricTags: ["R2","R7","R8"],
  days: {
    mon: D("Chapter 5 (first half)", "Mussolini's radio speech booms through the park; nanny Maria is introduced properly",
      "Have you ever heard a leader's speech, or watched a big public event, that felt exciting to the crowd around you but confusing or worrying to you personally?",
      "Who is Maria, and what has her role been in Lia's family since Lia was born?",
      "What does Mussolini's radio speech (\"Do you want war?\") reveal about how the government whips up public support?",
      "Write two sentences describing what it might feel like to be a child standing in a crowd shouting \"We do! We do!\" for a war you don't understand."),
    tue: D("Chapter 5 (second half)", "The bombing of Turin — explosions, sirens, and hiding in the basement \"shelter\"",
      "If someone you trusted told you something frightening was \"just pretend,\" when you suspected it wasn't, how would that make you feel?",
      "Describe what happens the night the French planes bomb Turin, using specific details from the text.",
      "Why does Maria keep telling the children \"it's just pretend\"? Is this a real lie, or something else — and does it work?",
      "Write about the \"shelter\" the family discovers, and what its ordinariness (sacks of coal, wine flasks) tells us about how unprepared people were for the war reaching their own street."),
    wed: D("Chapter 6 (first half)", "Money runs out; Papa finds a secret job — in Milan, a city they've never lived in",
      "How would you feel about moving somewhere you know nothing about, with only a few weeks' notice?",
      "Why does Papa's new job mean the whole family has to move to Milan?",
      "What does Lia decide is the most important thing to ask Papa about before agreeing to move (hint: it's not about the city)?",
      "List three things Lia's family will have to leave behind in Turin, and explain which one you think would be hardest to lose."),
    thu: D("Chapter 6 (second half)", "Milan's fog and the Jewish school where Lia's imagination flourishes",
      "Has a change of school, teacher, or environment ever made you feel more free to be yourself?",
      "How does Lia's writing change once she's at her new school in Milan, and why?",
      "The author writes, \"I feel like a bird whose wings have grown stronger so it can fly better.\" What does this metaphor suggest about Lia's growth, and how does it connect to the peep-peep-peep bird image from Week 1?",
      "Predict: Papa's job in Milan suddenly \"falls through.\" What do you think this might mean for the family?"),
  },
  projects: [
    P("poster", "Two Cities, Two Moods", "Create a split poster contrasting the fearful mood of bombed Turin with the hopeful, foggy, imaginative mood of Milan, using colour and quotations."),
    P("comic", "Boom! Boom!", "A comic retelling the night Turin is bombed, from the moment the sirens sound to the family reaching the basement shelter."),
    P("drama", "It's Just Pretend", "Act out Maria's reassurance scene during the bombing, then discuss as a class: was it right for her to say this?"),
    P("journal", "A Lie Told Out of Love", "Reflect on a time someone told you something wasn't as bad as it seemed, to protect you. Was it the right choice? Explain."),
  ],
  quiz: [
    Q("What does the family hear coming from speakers hidden in the trees at the public gardens?", "Mussolini's radio speech declaring Italy's readiness for war."),
    Q("Who is Maria, and how long has she been part of Lia's family?", "The family's nanny, with them since Lia was born."),
    Q("True or False: Italy declares war and is bombed by the same country the same night.", "True — the French bomb Turin only hours after Italy enters the war.", "tf"),
    Q("What does Maria repeatedly tell the frightened children during the bombing?", "That it's \"just pretend\"/fireworks, just practice for the war."),
    Q("What turns out to be the building's actual bomb shelter?", "The basement where they store coal and wine flasks."),
    Q("Vocabulary: What does \"shelter\" mean in this context?", "A safe place to hide from danger, especially bombing."),
    Q("Why are Mama and Papa \"a little angry\" with Maria the morning after the first bombing?", "She didn't know where the shelter was, so the children weren't taken to safety in time."),
    Q("Why does Papa need to find a new job so urgently in Chapter 6?", "The family's bank savings are about to run out."),
    Q("Where does Papa's new secret job take the family?", "Milan."),
    Q("What is the first thing Lia insists on before agreeing to the move?", "That she must be able to keep going to a Jewish school."),
    Q("True or False: Lia's writing style changes for the worse once she's at her new school in Milan.", "False — her teacher loves her imaginative writing, and she flourishes.", "tf"),
    Q("What does Lia compare herself to, to describe how free she feels writing in Milan?", "A bird whose wings have grown stronger so it can fly better."),
    Q("Vocabulary: What does \"flourish\" mean, and how does it apply to Lia in Milan?", "To grow or develop successfully; her confidence and imagination grow in this new environment."),
    Q("What natural weather feature is Milan famous for in this chapter, and what mood does it create?", "Fog — a mood of mystery, softness, and even fun (Lia and Maria laughing as they get lost in it)."),
    Q("Structure: Why might the author place the terrifying bombing chapter directly before the gentle, foggy Milan chapter?", "Open-ended — the contrast in mood shows life continuing to hold both danger and joy, and offers the reader (and Lia) some relief."),
    Q("What news does Mama deliver to Lia at the end of Chapter 6?", "Papa's Milan job has fallen through, and the family must move again, this time to Rome."),
    Q("How does Lia react to the news about moving to Rome?", "She is furious and runs away, upset about leaving her school and everyone she knows again."),
    Q("Why might repeatedly having to change schools and cities be especially hard for someone like Lia, who has only just found her voice?", "Open-ended — she has to keep rebuilding her confidence and sense of belonging from scratch each time."),
    Q("What real historical event is being referenced when French planes bomb Turin right after Italy enters the war?", "Open — accept general reference to the early bombing raids on northern Italy at the start of Italy's involvement in WWII."),
    Q("Predict: How do you think Lia will adjust to yet another new city and school in Rome?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 4, title: "New City, New Rules", chapters: "Chapters 7–8",
  LI: "We are learning to compare perspectives and recognise irony — including how a law can be worked around, and the difference between a harmful lie and a harmless \"invention.\"",
  SC: "I can explain how Nonna Teresa's plan works and why it's only possible because she isn't Jewish, and I can discuss the difference between a real lie and an \"invention.\"",
  rubricTags: ["R1","R8","R9"],
  days: {
    mon: D("Chapter 7 (first half)", "Arrival at \"the skyscraper\" in Rome; a new, chaotic Jewish school; teased for her Northern accent",
      "Have you ever moved somewhere new and been teased for sounding or acting differently to everyone else?",
      "Describe the apartment building the family moves into in Rome, and how it's different from anywhere they've lived before.",
      "Why do the children at Lia's new school make fun of her, and how is this new school different in character to her old ones in Turin and Milan?",
      "Write a short paragraph describing what it might feel like to be seen as a \"show-off\" for something you can't help (like your accent)."),
    tue: D("Chapter 7 (second half)", "Lia's friendship with Fiorella begins; at school, everyone openly mocks Mussolini",
      "Have you ever formed a fast, strong friendship with someone because your families already got along?",
      "How does Lia's friendship with Fiorella begin, and what metaphor does the author use to describe it forming?",
      "Lia is shocked that everyone at this school, even the teachers, openly makes fun of Mussolini. Why is this surprising, given what Papa swore her to secrecy about back in Week 1?",
      "Explain, using evidence, how the war bulletin on the radio is really just a way of hiding bad news for the fascist government."),
    wed: D("Chapter 8 (first half)", "A law bans Jewish people from holidays — but non-Jewish Nonna Teresa has a plan",
      "If a rule seemed obviously unfair and pointless, and you found a way around it that didn't hurt anyone, would you take it? Why or why not?",
      "What does the new law say Jewish families are no longer allowed to do?",
      "How does Nonna Teresa's plan get around this law completely legally, and why does it work only because of who she is?",
      "Design a simple diagram or map showing how Gabriella and Lia are able to reach the seaside despite the ban."),
    thu: D("Chapter 8 (second half)", "Nonna Teresa's \"inventions,\" secret cinema trips, and the diary Mama asked Lia to keep",
      "Is there a difference between telling a lie to get out of trouble, and telling a story purely for fun? What is it?",
      "What distinction does Nonna Teresa draw between a \"real lie\" and an \"invention\"?",
      "Why does Lia choose not to write about the secret cinema trips, or her private thoughts, in the diary she promised Mama she'd keep?",
      "Write one \"invention\" of your own — a fun, harmless made-up story you could tell, in the spirit of Nonna Teresa."),
  },
  projects: [
    P("poster", "Rules with Loopholes", "Design a poster explaining the vacation ban law and exactly how Nonna Teresa's plan works around it, using arrows or a flowchart."),
    P("comic", "Best Friends Like Bread Dough", "Illustrate the forming of Lia and Fiorella's friendship, using the \"kneading dough\" metaphor from the text as your visual concept."),
    P("drama", "Nonna's Secret Cinema Trip", "Act out the scene where Nonna sneaks Lia out to the outdoor movies, and Gabriella's reaction the next day when she finds out."),
    P("journal", "A Good Lie? An Invention?", "Reflect on Nonna Teresa's distinction between a real lie and an invention. Do you agree there's a meaningful difference? Give an example from your own life."),
  ],
  quiz: [
    Q("What nickname does everyone give the tall apartment building the family moves into in Rome?", "\"The skyscraper.\""),
    Q("What is the name of the Rome neighbourhood the family moves to, and what does it mean?", "Monteverde, meaning \"green mountain.\""),
    Q("True or False: The children at the Rome Jewish school are quiet and orderly compared to Lia's old schools.", "False — the school is loud, chaotic, and full of confusion and laughter.", "tf"),
    Q("Why do the other children tease Lia at her new school?", "Because of her Piedmontese (Northern) accent and correct grammar, which they see as showing off."),
    Q("What is the name of Lia's new best friend in Rome?", "Fiorella."),
    Q("What metaphor does the author use to describe how Lia and Fiorella's friendship forms?", "Like kneading dough — mixing ingredients together to make something new."),
    Q("Vocabulary: What is a \"war bulletin,\" and what does the coded phrase \"attested to positions that are more favourable\" actually mean?", "An official radio update on the war; it's a way of saying the fascist soldiers have had to retreat/withdraw, without admitting defeat directly."),
    Q("True or False: At Lia's new school, even the teachers secretly enjoy jokes made against Mussolini.", "True — the teacher pretends to be angry but is \"quite pleased.\"", "tf"),
    Q("What new law does Chapter 8 introduce regarding Jewish families?", "Jewish people are banned from going on vacation, including to the seaside."),
    Q("Who helps Lia and her sister Gabriella get around the vacation ban, and how?", "Their non-Jewish grandmother, Nonna Teresa, who rents the seaside apartment herself and invites her granddaughters to stay."),
    Q("Who is Cesarina, and what is she known for?", "Nonna Teresa's housekeeper, who is really more of an inventive cook, making a new dessert every night."),
    Q("What distinction does Nonna Teresa draw between a \"real lie\" and an \"invention\"?", "A real lie is told to defend yourself when you've done something wrong; an \"invention\" is a made-up story told purely for fun, like something a poet or fairy-tale writer might create."),
    Q("What does Mama ask Lia to keep, to stay informed about the girls' summer while they're apart?", "A diary, written a little every day."),
    Q("True or False: Lia writes down every detail of her summer, including the secret cinema trips, in her diary for Mama.", "False — she leaves out anything \"secret\" or private, including the cinema trips and her own private thoughts.", "tf"),
    Q("Why does Lia choose to leave the secret cinema trips out of her diary?", "Open-ended — accept that she knows Mama wouldn't approve, or that she wants to protect the fun secret she shares with Nonna Teresa and Gabriella."),
    Q("Structure: What effect does it have that the same law (the vacation ban) can be avoided so easily by a non-Jewish relative?", "Open-ended — highlights the arbitrary unfairness of laws based on identity, and shows how families found small, resourceful ways to resist them."),
    Q("Why might the author choose to include a joyful, funny chapter about ice cream and secret movies right after introducing such an unfair law?", "Open-ended — shows that even under persecution, children's lives still held real joy, and it makes the unfairness of the ban even clearer by contrast."),
    Q("What do you think it means that people at Lia's new school openly mock Mussolini, when Papa swore Lia to total secrecy about criticising him back in Turin?", "Open-ended — accept that attitudes/safety in speaking out may vary by place, community or as the war goes worse for Italy, or that children's schools can be spaces where quiet resistance is more open."),
    Q("Predict: Now that the family has found small ways around unfair laws, what do you think might happen as the laws get stricter?", "Open-ended, text-supported prediction."),
    Q("Vocabulary: What does \"loophole\" mean, and how does Nonna Teresa's plan act as one?", "A way of legally avoiding the effect of a rule without breaking it; her non-Jewish status lets her rent the holiday apartment for her granddaughters."),
  ],
},
{
  num: 5, title: "Taken Away, Piece by Piece", chapters: "Chapters 9–10",
  LI: "We are learning to explain the double meaning of a key vocabulary word, and to evaluate whether an event marks real change or false hope.",
  SC: "I can explain both meanings of \"discriminate\" using evidence from the text, and I can explain why Mussolini's fall doesn't actually make the family safe.",
  rubricTags: ["R1","R2","R8"],
  days: {
    mon: D("Chapter 9 (first half)", "The family's radio is confiscated; a new law says Christians can't work for Jewish families — threatening beloved nanny Maria",
      "How would you feel if a rule suddenly meant someone you loved, who felt like family, had to leave your home?",
      "What two things does the family lose in this chapter because of new laws — one an object, one a person?",
      "Papa explains the word \"discriminate\" can work against you, or in your favour. What does he mean, and how has it worked in this family's favour so far (their war-orphan status)?",
      "Write a paragraph explaining, in your own words, both meanings of \"discriminate,\" using an example from the text for each."),
    tue: D("Chapter 9 (second half)", "The family finds a workaround for Maria — but she slowly starts to drift away",
      "Have you ever watched a relationship change slowly, in small steps, rather than all at once?",
      "What plan does Mama come up with to keep Maria nearby, technically working for the neighbour instead?",
      "How does Maria's behaviour change over time in this new arrangement, and what small details show her drifting away from the family?",
      "Predict whether you think Maria's relationship with the family will be repaired, and explain your reasoning using evidence so far."),
    wed: D("Chapter 10 (first half)", "The Americans land in Sicily; Mussolini is overthrown, and there is dancing and celebration",
      "Imagine hearing news that something terrible in your life might finally be ending. How might people's reactions be complicated rather than simply happy?",
      "What news causes Mama, Papa, and the neighbours to burst into Lia's room at night, dancing and singing?",
      "Why does the author say people look \"half cheerful and half worried\" rather than simply celebrating?",
      "Explain why Mussolini's fall does not automatically mean the war — or the danger to Jewish families — is over."),
    thu: D("Chapter 10 (second half) — the demand for gold", "Germany occupies Italy; Jewish leaders in Rome are forced to hand over fifty kilos of gold in exchange for a promise of safety",
      "If someone in power made you a promise in exchange for something valuable, how would you decide whether to trust them?",
      "What do the Germans demand from Rome's Jewish community, and how does Lia's family contribute?",
      "Why might the author end this chapter with the line, \"Don't believe it, though, because that's not how things go...\"?",
      "Predict what you think will happen despite the Jewish community meeting the Germans' demand."),
  },
  projects: [
    P("poster", "Two Meanings of Discriminate", "Design a poster with two sides — \"discrimination against\" and \"discrimination in favour of\" — each with a real example from the text."),
    P("comic", "The Workaround", "Illustrate the family's plan to keep Maria nearby by having her \"work\" for the neighbour, and show how it slowly stops working."),
    P("drama", "The Night Mussolini Fell", "Act out the scene of Mama and Papa dancing into the girls' bedroom with the news, capturing both the joy and the underlying worry."),
    P("journal", "When Good News Turns Out Not to Be", "Write about a time you or someone you know celebrated news that turned out to be more complicated than it first seemed."),
  ],
  quiz: [
    Q("What object is taken from the family's home by a police officer in this chapter?", "Their radio."),
    Q("What new law directly threatens Maria's place in the family?", "A law banning non-Jewish people (\"Christians\") from working for Jewish families."),
    Q("Why has the family been allowed a Christian nanny up until now, despite earlier laws?", "Because of a special \"discrimination\" (advantage) — Papa's father died as an Italian war-orphan's father, an officer killed fighting for Italy."),
    Q("Vocabulary: Give both meanings of the word \"discriminate\" as Papa explains it.", "To treat someone worse because of a difference (working against them), or to treat someone better because of an advantage (working in their favour)."),
    Q("What plan does Mama devise to keep Maria near the family?", "Having a neighbour pretend Maria works for them, while she still secretly spends most of her time with Lia's family, who continue to pay her."),
    Q("True or False: Maria's connection to the family grows stronger under this new arrangement.", "False — she slowly drifts away, becoming busier and more distant.", "tf"),
    Q("What historic event does the family celebrate at the start of Chapter 10?", "The Allied (American) landing in Sicily, seen as a sign the war might soon turn in their favour."),
    Q("What happens to Mussolini early in Chapter 10?", "He is removed from power (\"Mussolini's gone\") by the king, and people celebrate in the streets."),
    Q("Why does the author say people are \"half cheerful and half worried\" rather than simply happy about Mussolini's fall?", "Because the war is still ongoing, and Italy is still allied with Germany, so the danger isn't actually over."),
    Q("Which country's soldiers occupy Italy immediately after Mussolini's fall, and why?", "German soldiers, because Italy's switch of sides angered its former ally."),
    Q("What do the Germans demand from Rome's Jewish community in exchange for a promise of safety?", "Fifty kilos of gold."),
    Q("How does Lia's family contribute to the fifty kilos of gold?", "They gather gold chains with Star of David pendants and other jewellery from around the house."),
    Q("True or False: The Germans keep their promise once they receive the gold.", "False — the chapter ends with a warning that this is not how things will go.", "tf"),
    Q("Structure: What effect does the line \"Don't believe it, though, because that's not how things go\" have on the reader, coming right after a moment of relief?", "Open-ended — creates dread/foreshadowing, and undercuts the family's hope, preparing the reader for worse to come."),
    Q("Why might Lia's admission-test photograph (for middle school) matter, even amid all this political upheaval?", "Open-ended — shows that ordinary childhood milestones continue alongside historical events, and grounds the story in everyday detail."),
    Q("What does the gold demand suggest about how the Nazis used false promises as a tactic?", "Open-ended — extracting resources/compliance through hope, without any real intention to keep the promise."),
    Q("Why do you think the author includes the detail that Papa \"doubts very much\" the clasp on Mama's velvet handbag is really gold?", "Open-ended — a touch of dark humour, and shows the family scraping together anything of value, however small, out of fear."),
    Q("How does this section of the book build on the idea of \"discrimination\" introduced in Chapter 9, by the end of Chapter 10?", "Open-ended — shows how quickly even a special legal \"advantage\" (like the war-orphan status) can stop protecting a family once the situation worsens."),
    Q("Predict: Given the warning at the end of Chapter 10, what do you think the family will need to do next?", "Open-ended, text-supported prediction — accept references to needing to hide or flee."),
    Q("What is one piece of evidence that the adults around Lia are trying to protect her from the full truth of how dangerous things have become?", "Open — accept Mama delaying telling her about the savings, or the adults' careful, calm tone even while making desperate plans."),
  ],
},
{
  num: 6, title: "Say Goodbye to Your Mama", chapters: "Chapters 11–12",
  LI: "We are learning to explain how a real historical event is woven into a personal memoir, and to analyse a pivotal, high-stakes scene with care and sensitivity.",
  SC: "I can explain the real historical event behind Chapter 12 using evidence from the text, and I can explain why parents chose to send their children into hiding.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 11 (first half)", "Mama and Papa reveal the plan: the girls will hide at a convent boarding school, under a false name",
      "If your parents told you that you had to keep a huge secret — even your own name — to stay safe, how do you think you'd feel?",
      "What plan have Mama, Papa, and the school's headmistress arranged with the nuns?",
      "What three safety rules must Lia and the other hidden girls follow (their name, their religion, their prayers)?",
      "Write about how you imagine it would feel to be told you must pretend not to be yourself, even in small ways, to stay safe."),
    tue: D("Chapter 11 (second half)", "Arrival at the convent — and the devastating moment Lia realises she must say goodbye to Mama",
      "Has a piece of information ever been so big that, even though you understood the words, your feelings couldn't quite catch up?",
      "How does Papa convince Lia to see the situation differently, by connecting it to something she already loves (her books)?",
      "The author writes, \"My mind refuses to pass the message on to my heart.\" What does this sentence mean, and why is it such a powerful way to describe this moment?",
      "Write a short diary entry as Lia, on the night after Mama leaves the convent without her."),
    wed: D("Chapter 12 (first half)", "One morning in October, everything changes — Mama arrives at the convent in a panic",
      "Why might real, historical tragedies sometimes be hardest to write and read about through the eyes of someone who was a child at the time?",
      "What does Mama tell Lia has happened \"this morning,\" and how does she and Papa manage to escape it?",
      "Why does the author choose to tell us — before this scene even happens — that Papa survives? What effect does that have on how we read this chapter?",
      "Explain, using evidence from the text and your own background knowledge, what real historical event this chapter is describing."),
    thu: D("Chapter 12 (second half)", "Papa survives on the run, moving between boarding houses under a false name",
      "What qualities do you think someone would need to survive on the run, alone, under a false identity, for months?",
      "How does Papa manage to avoid capture while living under a false name in the city?",
      "What does Papa do with the notebook he keeps during this time, and what does it reveal about how he copes with fear?",
      "Explain the connection between this chapter and the very first time we saw Papa \"lose\" his job and start painting, back in Week 2."),
  },
  projects: [
    P("poster", "Levi Becomes Lenti", "Design a poster exploring the false-identity theme — the family's real name, their false name, and why the false name had to sound similar."),
    P("comic", "One Morning in October", "Retell the moment Mama arrives at the convent with the terrible news, handling the historical event with care and accuracy."),
    P("drama", "Say Goodbye to Your Mama", "Perform the goodbye scene at the convent gate with sensitivity, focusing on what is said and left unsaid between Lia and Mama."),
    P("journal", "What Would I Take Into Hiding?", "If you had to leave home quickly and hide your identity to stay safe, what would you take, and what parts of \"you\" would be hardest to hide?"),
  ],
  quiz: [
    Q("Who arranges the plan to hide the girls at a convent boarding school?", "Mama, together with the headmistress of the Jewish school, who speaks to the nuns."),
    Q("What false surname does the family adopt at the convent?", "Lenti (their real surname is Levi)."),
    Q("Why must the false name sound similar to the real one?", "So the girls don't forget to respond to it, or accidentally give themselves away."),
    Q("What must the hidden girls learn to do that goes against their own religion, in order to blend in?", "Recite Christian prayers, like the rosary, alongside the other boarding-school girls."),
    Q("How does Papa convince Lia to feel differently about hiding at the convent?", "He tells her to imagine herself as one of the heroic children from her adventure books, who are secret agents."),
    Q("True or False: Mama and Papa plan to hide at the convent together with the girls from the very start.", "False — they explain that two adults can escape more easily without children, so the girls go first, hidden separately.", "tf"),
    Q("What does the nun, Sister Maria Luisa, say to Lia that makes the goodbye suddenly feel real?", "\"Say goodbye to your mama.\""),
    Q("What does the line \"my mind refuses to pass the message on to my heart\" mean?", "Lia understands the facts logically, but emotionally cannot yet accept what is happening."),
    Q("What real historical event does Mama describe happening \"this morning\" in Chapter 12?", "The October 1943 roundup of Jewish people in Rome by German forces, in which many Roman Jews were arrested and deported."),
    Q("How do Mama and Papa avoid being caught during the roundup?", "They are warned in time and manage to escape, though they become separated from each other."),
    Q("True or False: The author waits until after this chapter to reveal whether Papa survives, to build maximum suspense.", "False — she tells us in advance that Papa survives, choosing to soften the blow rather than build suspense.", "tf"),
    Q("Structure: Why might the author choose to reassure readers about Papa's safety before telling us what happens to him?", "Open-ended — protects young readers from unbearable suspense on a topic this serious, and reflects the caring, careful narrator we've come to trust."),
    Q("How does Papa manage to survive while on the run under a false identity?", "By moving frequently between boarding houses whenever other boarders became too curious or suspicious."),
    Q("What does Papa do with a notebook during this time, and what does this reveal about him?", "He draws the funny faces of people he meets, showing how he copes with fear through his art and sense of humour."),
    Q("What connection can you draw between this chapter and Papa's earlier decision to start painting (Week 2)?", "Open-ended — his hobby, born from losing his job, becomes a lasting coping mechanism and eventually his lifelong passion, \"a painter forever.\""),
    Q("Why do you think the nuns agreed to hide dozens of Jewish children and their mothers, risking their own safety?", "Open-ended — accept references to compassion, moral courage, religious duty, or solidarity, while respecting that the text doesn't fully explain their reasoning."),
    Q("Vocabulary: What does it mean that Lia's family and the other hidden girls are \"in hiding\"?", "Living secretly, concealing their identity and location to avoid being found and arrested."),
    Q("Whose perspective does this section not show us directly, even though their choices shaped everything that happens?", "Open — accept the nuns, the headmistress, the German soldiers/officials, or others who made high-stakes decisions off the page."),
    Q("Why is it important, when learning about real historical events like this one, to remember that they happened to real people?", "Open-ended, reflective — respectful engagement with the historical seriousness of the roundup and the Holocaust."),
    Q("Predict: Now that so many more families are in danger, what do you think convent life will be like for Lia going forward?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 7, title: "More Than Thirty Hiding", chapters: "Chapters 13–14",
  LI: "We are learning to compare found-family relationships and evaluate the emotional cost of keeping a secret from a close friend.",
  SC: "I can explain why Lia keeps her Jewish identity secret from her best friend Pina, and I can explain what the moment with baby Rossana reveals about how Lia has grown.",
  rubricTags: ["R1","R7","R10"],
  days: {
    mon: D("Chapter 13 (first half)", "More than thirty girls now hide at the convent; daily life, rules, and the sash-reward system",
      "How do you think a community changes when it suddenly has to make room for many more people who are all frightened and in danger?",
      "How does the number of hidden Jewish girls at the convent change over the course of this chapter, and why?",
      "What are the pink and blue sashes given for, and what does Mama's comment about which one is \"worth more\" reveal about her values?",
      "Design a simple daily timetable for convent life, based on the details given in the chapter."),
    tue: D("Chapter 13 (second half)", "Hunger becomes a daily reality; the girls parody a song about spaghetti; St Joseph's Day brings a rare feast",
      "Have you ever used humour to cope with something difficult, like the girls' spaghetti song?",
      "What details show how hungry the girls are at the convent, and how do they cope with it through humour?",
      "Why does St Joseph's Day feast feel so significant to Lia, even more memorable than the seaside dinner from Week 4?",
      "Write your own parody song lyric, in the spirit of the girls' \"Oh lovely plate of spaghetti,\" about something you wish you had more of."),
    wed: D("Chapter 14 (first half)", "Lia's close friendship with Pina, and the poem Pina writes for Lia's parents' anniversary",
      "What makes a friendship feel like a true, deep connection, even under difficult circumstances?",
      "Who is Pina, and what makes her different from the other girls at the convent?",
      "How does Pina help Lia and her sisters mark their parents' wedding anniversary while they're separated?",
      "Write your own short anniversary or thinking-of-you poem, in the style of Pina's jonquil poem."),
    thu: D("Chapter 14 (second half)", "Lia keeps her Jewish identity secret from Pina; the tender moment with toddler Rossana (\"Spepetto\")",
      "Is it possible to be truly close to someone while still keeping one important thing hidden from them? Why might someone do that?",
      "Why does Lia never tell Pina that she is Jewish, even though they share almost everything else?",
      "What happens the night Lia comforts three-year-old Rossana, and what does Lia mean when she says, \"For the first time in my life, I felt like a mama\"?",
      "Reflect on the twist we learn \"afterward\" — that Pina actually knew Lia was Jewish the whole time, but never said anything. Why might Pina have made that choice?"),
  },
  projects: [
    P("poster", "Convent Community", "Map out everyone now hiding at the convent (the original five, the new arrivals, Rossana, Mama, the nuns), showing how the community has grown and changed."),
    P("comic", "The Poem for Mama and Papa", "Illustrate Pina writing the anniversary poem and the moment Papa reads it and cries, using the jonquil flowers as a visual motif."),
    P("drama", "A Secret Kept from a Best Friend", "Respectfully act out a scene where Lia almost tells Pina the truth about being Jewish, and decides not to — then perform the \"afterward\" reveal that Pina knew all along."),
    P("journal", "Keeping Someone Safe", "Reflect on the night Lia comforts Rossana. Write about a time you looked after or protected someone younger or more vulnerable than you."),
  ],
  quiz: [
    Q("How many Jewish girls and women end up hiding at the convent by this point in the book?", "More than thirty."),
    Q("What are the pink and blue sashes awarded for at the convent?", "Pink for good behaviour, blue for doing well at school."),
    Q("According to Mama, which sash is \"worth more,\" and why?", "The blue one, because it represents hard work at school."),
    Q("What food shortage becomes a major topic of daily convent life?", "Hunger — there is very little food, and what there is (like frozen German potatoes) tastes bad."),
    Q("What song do the girls secretly parody, and what do they change the words to?", "A song about a \"lovely farm girl,\" changed to \"Oh lovely plate of spaghetti.\""),
    Q("What historical feast day results in a rare, joyful meal of real spaghetti?", "Saint Joseph's Day, celebrated by the Sisters of Saint Joseph."),
    Q("Who is Pina, and where is she from?", "A brilliant, kind girl from Sicily who becomes Lia's close friend at the convent."),
    Q("Why is Pina unable to go home to Sicily for now?", "Because the Americans have landed there, and the war has cut off her ability to travel home."),
    Q("What does Pina write for Lia and her sisters, and for what occasion?", "A poem, for their parents' wedding anniversary, using jonquil flowers as its central image."),
    Q("True or False: Lia tells Pina the truth about being Jewish and living under a false name.", "False — she keeps it secret, out of loyalty to the promise she made Papa.", "tf"),
    Q("What do we learn \"afterward,\" many years later, about what Pina actually knew?", "Pina had known Lia was Jewish the whole time, but never mentioned it because she didn't want to upset her."),
    Q("Who is Rossana, and what nickname do the nuns give her?", "A very young (three-year-old) hidden girl, nicknamed \"Spepetto\" (linked to the word for pepper)."),
    Q("What happens the night Lia hears Rossana crying secretly into her pillow?", "Lia quietly takes her into her own bed and comforts her until she falls asleep."),
    Q("What does Lia mean when she says she \"felt like a mama\" that night, comparing herself to \"a she-wolf\"?", "For the first time, she experiences a fierce, protective love for someone more vulnerable than herself."),
    Q("Vocabulary: What does it mean that Lia sometimes acts like a \"know-it-all\" or \"snob\" toward the newer girls?", "She shows off her greater knowledge of convent life in a way that can come across as rude or unkind, something she later regrets."),
    Q("Structure: Why might the author choose to admit that Lia was sometimes unkind, rather than only showing her as a perfect hero?", "Open-ended — makes Lia feel like a real, complex person, not a flawless symbol, which builds trust with the reader."),
    Q("Why do you think Pina chose never to mention what she knew about Lia's secret?", "Open-ended — accept respect for Lia's privacy, protecting the friendship, or not wanting to add to Lia's fear."),
    Q("What does the moment with Rossana suggest about how extreme circumstances can cause someone to grow up quickly?", "Open-ended — Lia, only twelve, takes on a caretaking, almost parental role."),
    Q("How does the found-family feeling at the convent compare to Lia's relationship with her own family so far in the book?", "Open-ended — accept comparisons to Maria, Nonna Teresa, or the community formed among the hidden girls and the nuns."),
    Q("What is one value you think this section of the book is teaching, based on Pina's silence and Lia's care for Rossana?", "Open-ended — accept references to loyalty, quiet kindness, protecting others, or the courage of everyday compassion."),
  ],
},
{
  num: 8, title: "Six Months of Waiting", chapters: "Chapter 15",
  LI: "We are learning to explain how hope and disappointment are shown through a repeated pattern in a text, and to explore how people find joy during hardship.",
  SC: "I can explain why Mama's repeated promise of \"next week\" changes in meaning over the chapter, and I can identify small moments of joy the text includes even during a difficult wait.",
  rubricTags: ["R2","R3","R10"],
  days: {
    mon: D("Chapter 15 (opening)", "The Americans land at Anzio — everyone believes liberation is only days away",
      "Have you ever been told good news was \"almost here,\" only for the wait to drag on much longer than expected?",
      "What news arrives that makes Mama tell the girls to start packing their suitcases?",
      "Why does the family end up having to unpack their suitcases again, and how long does the wait actually last?",
      "Track the pattern of Mama's answer, \"next week,\" across the chapter. What does the repetition of this phrase suggest about hope and disappointment?"),
    tue: D("Chapter 15 (Maria's return)", "Maria moves back into the family's empty apartment to protect it, with her fiancé Tarcisio",
      "What would motivate someone to take a risk to protect a home that isn't even theirs?",
      "Why does Maria decide to move into the family's empty apartment, and who moves in with her?",
      "How does Mama feel about Tarcisio moving in too, and why might she feel that way?",
      "Describe what Maria brings when she visits the convent, and what these small gifts (like tiny red apples) mean to the girls during wartime scarcity."),
    wed: D("Chapter 15 (the school play)", "The convent stages a play, \"Captainesses Courageous,\" and Lia plays a role she loves",
      "Why might performing in a play feel especially meaningful during a difficult, uncertain time?",
      "What is the play about, and what role does Lia play in it?",
      "What does the wordplay in the title \"Captainesses Courageous\" (meaning \"just girls\") suggest about the play's themes, and how might this connect to the book's title?",
      "Design a costume sketch for Lia's character, based on the blue velvet dress described in the text."),
    thu: D("Chapter 15 (review)", "Reflecting on hardship and joy existing side by side during the long wait",
      "Why do you think people can experience real joy even during genuinely hard times, rather than one feeling cancelling out the other?",
      "List three hardships and three moments of joy from this chapter, side by side.",
      "How does this \"both/and\" pattern (hardship and joy together) compare to earlier moments in the book, like the bombing of Turin followed by hopeful Milan?",
      "Write a paragraph explaining what this chapter teaches about resilience during a long, uncertain wait."),
  },
  projects: [
    P("poster", "Hope Deferred", "Create a timeline poster tracking the promises and disappointments across the six-month wait, from the Anzio landing to news of Rome's liberation."),
    P("comic", "Captainesses Courageous", "Illustrate key moments from the convent's play, including Lia in her blue velvet costume."),
    P("drama", "An Excerpt from Captainesses Courageous", "Write and perform a short excerpt of the invented play, imagining what a scene from it might include, based on the description in the text."),
    P("journal", "Finding Joy in a Hard Time", "Write about a difficult period in your own life (or a period you've learned about) where small moments of joy still existed alongside the hardship."),
  ],
  quiz: [
    Q("Where do the Americans land at the start of this chapter, giving the family sudden hope?", "Anzio, close to Rome."),
    Q("What does Mama tell the girls to do as soon as she hears the news?", "Start packing their suitcases."),
    Q("True or False: The Americans reach Rome only a few days after landing at Anzio, as everyone expects.", "False — it actually takes six months, because German forces block their advance.", "tf"),
    Q("What repeated phrase does Mama use whenever Vera asks when they're going home?", "\"Next week.\""),
    Q("Why does Maria move back into the family's empty Rome apartment?", "To stop strangers or burglars from moving in or breaking in while it's empty."),
    Q("Who moves in with Maria to help protect the apartment, and how does Mama feel about it?", "Her fiancé, Tarcisio; Mama isn't entirely happy about it since she doesn't know him."),
    Q("What small treat does Maria bring the girls whenever she visits the convent?", "Tiny, oddly shaped red apples, which are hard to get during wartime."),
    Q("What is the name of the play performed at the convent for Mardi Gras?", "\"Captainesses Courageous.\""),
    Q("What does the title \"Captainesses Courageous\" playfully mean, according to Lia?", "\"Just girls\" — clever, capable women/girls who solve problems themselves."),
    Q("What role does Lia play in the production, and what does she wear?", "The main character's younger sister, in a blue velvet dress with a gold-embroidered jacket."),
    Q("Vocabulary: What does it mean that Papa \"can't come to see us\" during this time, but Maria can?", "Papa remains in hiding under a false identity and it's too dangerous for him to visit; Maria isn't in the same danger."),
    Q("Structure: Why might the author choose to track the repeated phrase \"next week\" throughout this chapter?", "Open-ended — shows the slow, painful passage of time and the gap between hope and reality, building empathy for the family's endurance."),
    Q("What does Maria's choice to protect the apartment (and later, to visit every week) suggest about her true feelings for the family, despite drifting away earlier?", "Open-ended — shows her loyalty and love re-emerging, especially in a crisis."),
    Q("List one hardship and one moment of joy from this chapter.", "Open — accept any accurate pair, e.g. the six-month wait / the school play, or cold with no coal / Maria's apple gifts."),
    Q("Why might staging a play have been an especially meaningful activity for hidden children during this period?", "Open-ended — offers a sense of normality, creativity, and control during an uncertain, restricted time."),
    Q("How does this chapter's \"hardship and joy together\" pattern connect to earlier parts of the book (e.g. the bombing of Turin followed by the Milan chapters)?", "Open-ended — the whole memoir repeatedly shows difficult and joyful moments coexisting rather than being separated."),
    Q("What do you think Vera, the youngest sister, understands about the long wait, compared to Lia?", "Open-ended — accept that Vera is shielded more, or that even young children sense delay and disappointment."),
    Q("Predict: Given how long the wait has already been, how do you think the family will finally learn that liberation has come?", "Open-ended, text-supported prediction."),
    Q("Why might the author choose to include such a specific, joyful detail as Lia's blue velvet costume, in a book about hiding from danger?", "Open-ended — reminds the reader that childhood joys and milestones continued even during extremely difficult circumstances."),
    Q("What connection can you draw between the play's title (meaning \"just girls\") and the book's own title, \"Just a Girl\"?", "Open-ended — both play with the idea that being \"just\" something isn't a limitation, but can be a source of strength or identity."),
  ],
},
{
  num: 9, title: "Just a Girl, Just Free", chapters: "Chapters 16–17 + A Letter From the Other Side of the Ocean",
  LI: "We are learning to explain the difference between a label imposed on someone and an identity someone chooses for themselves, and to evaluate an author's direct message to the reader.",
  SC: "I can explain what Mama means by \"you're not a Jewish girl, you're just a girl,\" and I can summarise the key messages in Lia Levi's closing letter to readers.",
  rubricTags: ["R1","R4","R10"],
  days: {
    mon: D("Chapter 16 (first half)", "Retreating, exhausted German soldiers pass by; then, sudden silence, and news that the Americans have arrived",
      "How might seeing an enemy soldier looking tired, dusty, and human — rather than fearsome — change how you feel about war?",
      "How do the German soldiers look and behave differently by this point in the war, compared to earlier in the book?",
      "Why does a nun say \"poor boy\" about a German soldier, and what does Lia find confusing about this reaction?",
      "Write a short paragraph explaining why the author might include a moment of unexpected sympathy for an \"enemy\" soldier."),
    tue: D("Chapter 16 (second half)", "Liberation Day — Americans throw chocolate from trucks; the family finally goes home",
      "What do you imagine it would feel like to walk back into a home you haven't seen in many months, not knowing what to expect?",
      "Describe the celebrations that break out once word spreads that \"the Americans are here.\"",
      "What has changed about the family's apartment while they were away, and how does the reality compare to how Lia remembered it?",
      "Write about the small, ordinary freedoms Lia describes feeling on her first walk alone to the fountain — why do these small things matter so much after such a long time?"),
    wed: D("Chapter 17", "Lia writes a letter to a radio show describing herself as \"a Jewish girl\" — and Mama tears it up, laughing",
      "Do you think a label (like nationality, religion, or background) should ever be the very first thing people learn about you? Why or why not?",
      "What does Lia write in her letter to the radio station, and how does Mama react?",
      "What does Mama mean when she says, \"You're not a Jewish girl... you're a girl. Just a girl\"?",
      "Explain, in your own words, the difference Mama draws between something being personal to you and something being used as an official label against you."),
    thu: D("A Letter From the Other Side of the Ocean (author's closing letter)", "The grown-up Lia Levi speaks directly to readers about memory, gratitude, and racism today",
      "Why might an author choose to end a childhood memoir with a direct, personal letter written as an adult, rather than just stopping the story?",
      "What does Lia Levi say about whether she had an \"unhappy\" childhood, and how does she explain this, given everything she went through?",
      "What does she ask readers to do for her, and why does she feel so strongly about American soldiers?",
      "What message does she give young readers today about racism, and why do you think she chooses to end her book with this point?"),
  },
  projects: [
    P("poster", "Label vs Identity", "Create a poster contrasting the official label used against Lia (\"female student of Jewish race\") with Mama's phrase (\"just a girl\"), explaining the difference in your own words."),
    P("comic", "Freedom Day", "Retell Liberation Day — the retreating soldiers, the silence, the Americans arriving, and the walk home — in a 6-panel comic."),
    P("drama", "You're Just a Girl", "Perform the closing scene between Lia and Mama with care, capturing both the confusion and the warmth of the moment."),
    P("journal", "A Letter to Lia", "Write a reply letter to the real, adult Lia Levi, responding to her closing letter and reflecting on what her story has taught you."),
  ],
  quiz: [
    Q("How do the German soldiers look as they retreat past the convent, compared to earlier in the book?", "Dusty, tired, and disorganised, rather than smart and threatening."),
    Q("What does one of the nuns say about a tired German soldier who stops for water, and how does Lia react to this?", "She says \"poor boy\"; Lia is confused, since she'd always thought of them simply as the enemy."),
    Q("What is the first sign that the Germans have truly gone?", "A sudden, frightening silence — no more shooting or planes."),
    Q("How does the news of liberation spread through the convent?", "People simply start shouting, \"They're here! The Americans are here! We're free!\", with no clear source."),
    Q("What do the American soldiers throw to children from their trucks?", "Chocolates and candies."),
    Q("Vocabulary: What does \"liberation\" mean, and why is it the right word for this moment?", "Being set free from control or occupation; it captures both the political and the deeply personal freedom the family experiences."),
    Q("What does Maria's coffee-maker story reveal when the family finally returns home?", "It exploded and stained the kitchen while she was staying there, leaving the apartment even shabbier than Lia remembered."),
    Q("True or False: The family's apartment feels exactly as wonderful as Lia remembered it.", "False — it feels small and shabby compared to her memory and to the convent.", "tf"),
    Q("What small act of freedom does Lia describe enjoying on her walk to the fountain?", "Taking a longer route home just because she can, and reading by candlelight in secret at night."),
    Q("What does Lia write in her letter to the radio station in Chapter 17?", "\"I am a Jewish girl...\""),
    Q("How does Mama react when she reads the start of Lia's letter?", "She tears it into pieces, laughing, rather than being angry."),
    Q("What does Mama mean by, \"You're not a Jewish girl... you're a girl. Just a girl\"?", "Being Jewish is a true, personal fact about Lia, but it should never again be used by the State as a label to control or harm her."),
    Q("Vocabulary: What is the difference between a fact about yourself and a label, according to Mama's explanation?", "A fact is personal and yours to share if you choose; a label is something imposed on you by others, often to justify unfair treatment."),
    Q("What does the closing author's letter reveal about when and where these events really happened?", "They really happened to Lia Levi, in Italy, between 1938 and 1945."),
    Q("What does Lia Levi say about whether her childhood was \"unhappy\"?", "She says no — it was difficult and sometimes stormy, but still filled with games, friendships, reading, and joy, not simple unhappiness."),
    Q("Who does the author ask young readers to remember with a moment of respect, before answering questions about her own childhood?", "The six million Jewish people murdered in the Holocaust, including a million and a half children."),
    Q("What does Lia Levi thank American soldiers for, in her closing letter?", "Arriving as liberators and helping defeat Hitler's plan to take over Europe, without which she says she wouldn't be alive to tell her story."),
    Q("What does Lia Levi say about racism today, in her final message to readers?", "That it \"continues to stain society today,\" and she asks young readers to condemn and fight against it."),
    Q("Structure: Why might the author choose to end a childhood memoir with a direct letter from her adult self, rather than ending the story with Chapter 17?", "Open-ended — allows her to speak with the full weight of hindsight, connect history to the present, and make a direct call to action for young readers today."),
    Q("What is the one big idea from this whole book that you will remember most, and why?", "Open-ended, personal response, referencing evidence from the text."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "My Family's \"Just a...\" Story", desc: "Create an anthology page about a label or expectation placed on someone in your own family's history (an accent, a background, a first job, an era they grew up in), and how that person is \"just a person\" underneath it, echoing the book's ending." },
    { title: "Character Case File: Lia's Journey", desc: "An in-depth profile (poster + written report + panels) tracking Lia's whole arc — from her silent \"peep peep peep\" voice to \"just a girl\" — with evidence from the beginning, middle and end of the memoir." },
    { title: "Hidden History Exhibit", desc: "A museum-style poster and short report connecting the fictionalised memoir to the real historical events behind it (the 1938 Italian racial laws, the October 1943 Rome roundup, the Allied liberation of Rome), using the author's closing letter as a source." },
    { title: "Extended Scene: An Untold Perspective", desc: "Write and perform a new scene from a perspective the book doesn't fully show us — Maria, Sister Giacinta, the German soldier who says \"poor boy,\" or the neighbour who agreed to shelter Maria — told with empathy, not as a simple villain or footnote." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: a moment of respectful silence for the six million, as the author's letter asks, and a class discussion on standing against prejudice today.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events from one part of the memoir.",
      wt: "Explains some of Lia's experiences or relationships, with limited evidence, or from only one section of the book.",
      a: "Explains a theme (identity, courage, belonging) and supports it with clear evidence from at least two different parts of the memoir.",
      example: "A Character Case File showing Lia changing from a silent, shy child to a girl who has \"found her voice,\" with an event from the beginning, middle and end of her story." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "An exhibit poster with a clear message, three accurate facts drawn from the author's closing letter, and imagery that matches the message respectfully." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A scene from an untold perspective (like Sister Giacinta's) that is historically plausible, empathetic, and rehearsed/improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
