/* ============================================================
   HATCHET (Gary Paulsen) — BOOK STUDY APP DATA
   Content data only. No markup/behaviour lives in this file.
   Years 7–8 · NZ Curriculum Level 4 English
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Tough Hope & Resilience", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 4 (Years 7–8).
   "Achieved" = the curriculum expectation has been met.
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas that run through Brian's survival — self-reliance, the danger of self-pity, and the way physical survival and emotional healing (from the divorce and 'the Secret') happen at the same time — and supports them with events from more than one part of the book.",
    kid: "I can explain a big idea from Brian's story and back it up with events from at least two different parts of the book.",
    ask: "Does the student connect an idea across different parts of the text, not just retell one scene?",
    na: "Retells a single event from the book but cannot yet connect it to a bigger idea.",
    wt: "Names an idea (e.g. 'he learns to survive') with a general reason, but the connection to the text is thin.",
    ach: "Explains an idea that runs across the book and supports it with specific, accurate events from at least two different weeks of reading.",
    wtSample: "Brian gets better at surviving because he keeps trying different things.",
    exemplar: "Brian's survival and his emotional recovery happen together, not separately. Early on he wastes energy hating his mother and crying over the Secret, and it gets him nowhere — the porcupine still hurts, the hunger is still there. But after the search plane flies over and leaves without seeing him, something in him actually changes, and afterwards his 'tough hope' lets him build fire, catch fish, and even survive a moose and a tornado in the same day. The wilderness doesn't fix his family — but learning to stop feeling sorry for himself is what lets him survive both problems at once.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-deeper reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features on a text's meaning.",
    expect: "Notices the author's structural and language choices — present-tense-feeling interior monologue, short sentence fragments during panic, repeated motifs ('there were these things to do', 'mistakes') — and explains what effect they have on the reader.",
    kid: "I can name a specific way the author writes Brian's thoughts, and explain what effect that has on me as a reader.",
    ask: "Does the student name the technique AND explain its effect, not just describe what happens in the plot?",
    na: "Comments only on what happens in the plot; does not yet notice how the writing itself is built.",
    wt: "Notices the writing feels 'urgent' or 'jumpy' but cannot explain how the author creates that effect.",
    ach: "Names a specific technique (short fragmented sentences during panic, repeated phrases like 'Mistakes' or 'There were these things to do', present-focused interior monologue) and explains a specific effect it has — for example, that it makes the reader feel as scattered and overwhelmed as Brian.",
    wtSample: "The writing is really short and choppy when scary things happen, which makes it feel scary.",
    exemplar: "When the pilot has his heart attack, Paulsen writes in short, broken sentences — 'Stopped. Seconds passed... Stopped.' — instead of one flowing description. That repetition of 'stopped' mirrors exactly what panic does to a thirteen-year-old's mind: thought doesn't move in neat sentences when you're terrified, it snags and repeats. The technique makes the reader's own reading feel breathless, almost like we're the ones in the cockpit.",
    evidence: "Structure & language questions, inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, comparing, synthesising — and links an earlier event in Brian's survival to a later one (e.g. an early mistake to a later success).",
    kid: "I can use reading strategies to link something Brian learns early on to something that happens later in the book.",
    ach: "Independently draws a justified connection between an earlier and a later event in the book, without being told to.",
    wt: "Makes a link between events only when prompted, or the link is superficial (both involve fire, or both involve animals).",
    ask: "Can the student explain WHY two events are connected, not just THAT they both happened?",
    wtSample: "The porcupine hurts him and later the moose hurts him too.",
    exemplar: "Throwing the hatchet at the porcupine in a panic — and nearly losing his only tool in the dark — is the exact mistake Brian almost repeats when he drops the hatchet into the lake while cutting into the plane. The first time, panic made him careless with the one thing that keeps him alive; the second time, he's learned enough to stay calm, dive, and get it back rather than giving up. Predicting that the hatchet would matter again helped me see how much Brian has grown between those two moments.",
    evidence: "Predictions, cross-chapter comparison questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics, showing an increasing awareness of purpose and audience.",
    expect: "Writes and shares clear, developed opinions and explanations about the book — including on difficult questions (was Brian right to keep the rifle he found? does the book's ending feel earned?) — with supporting detail from the text.",
    kid: "I can share a clear opinion about a hard question the book raises, and back it up with reasons and evidence.",
    ask: "Is there a clear position PLUS at least two reasons or pieces of evidence from the text?",
    na: "Answers are one-sided, unclear, or state an opinion with no supporting reason.",
    wt: "Shares a clear opinion but gives only one reason, or does not use evidence from the text.",
    ach: "Communicates a clear, considered opinion and develops it with at least two reasons or pieces of evidence from the text.",
    wtSample: "I think Brian should use the rifle because it would make hunting easier.",
    exemplar: "I think it makes sense that Brian feels uneasy about the rifle, even though it would make hunting easier. First, the text says holding it 'removed him from everything around him' — it lets him stop understanding the animals and the woods, which is exactly the skill that kept him alive for fifty-four days. Second, everything good that happens to him up to that point comes from patience and observation, not from a shortcut, so leaning on the rifle would undo the 'tough hope' he worked so hard to build.",
    evidence: "Go-deeper reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts for a range of purposes and audiences.",
    expect: "Chooses the right structure and language for the task — a survival log entry, a persuasive poster, a script, a reflective letter — and matches Brian's voice (plain, observant, increasingly calm under pressure) where relevant.",
    kid: "I can choose the right kind of writing and the right voice for the task, and make it sound like it belongs in Brian's world.",
    ach: "Uses a suitable structure and language features for the purpose and audience, and the voice/register fits the task (e.g. short, present-focused survival-log sentences; persuasive language for a poster; stage directions for drama).",
    wt: "Attempts the right form but the language or structure is inconsistent, or doesn't fit the task.",
    ask: "Does the writing look, sound, and feel like it fits the purpose and Brian's world, not just any generic story?",
    na: "Writing does not match the task; little attempt at structure or appropriate language features.",
    wtSample: "Day 12. Today I got a fish. It was hard but I did it and I felt happy.",
    exemplar: "Day 12. Sun. Fish pond holding. Speared two before the light changed — aim low, always low, the water lies about where things are. Ribs still ache from nothing, from nothing at all, just carrying wood. Note for Dad: bows split if you rush them. Everything here is patience or it is nothing.",
    evidence: "Poster, comic, drama & journal projects; Week 9 opinion writing; Week 10 campaign/anthology" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback (Glow & Grow) to improve it, and can explain a specific change made because of that feedback.",
    kid: "I can plan my work, improve a draft, and use feedback to make a specific, named improvement.",
    ach: "Independently plans, drafts and revises, and can point to a specific change made because of feedback.",
    wt: "Plans and drafts with support; makes only small, vague changes when prompted.",
    ask: "Can you see a plan AND one specific change the student can name and explain?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wtSample: "I finished my comic about the tornado. My partner said to add more panels so I did.",
    exemplar: "My plan had four panels: calm camp, the low roar, the wind hitting, the aftermath. My partner's 'grow' note said the moment the shelter is destroyed felt rushed, so I added a wordless panel of just Brian's hands gripping the rock — a detail straight from the text — which made the loss feel real instead of just stated.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas — including views on sensitive, real-world issues.",
    expect: "Listens to and builds on others' ideas during group reading and projects, including when discussing difficult or personal topics (divorce, grief, family secrets, mental toughness), and disagrees respectfully.",
    kid: "I can listen to my group, take turns, and build on — or respectfully challenge — other people's ideas, even about hard topics.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas, especially on sensitive real-world topics raised by the book.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ask: "Does the student respond to what others say — including disagreeing respectfully — rather than just waiting for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt, dismiss others, or opt out.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I actually don't think Brian's anger at his mum ever fully goes away — I see it differently to Aroha. Can we check what he says right at the end, in the epilogue?\" He then invited a quieter group member to find the page.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects, discussion circles — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas, including recognising bias and perspective.",
    expect: "Makes inferences about Brian's feelings and motives using clues from the text, and thinks critically about why the author structures the survival story the way he does.",
    kid: "I can use clues in the story to work out things the author doesn't state directly, and think about why the author made certain choices.",
    ach: "Independently infers feelings or motives and points to the textual clue, AND can explain an authorial choice (why give Brian a hatchet and not a knife; why the Secret is revealed slowly; why the rescue happens almost by accident).",
    wt: "Makes an inference with prompting but struggles to explain the clue, or does not yet consider the author's choices.",
    ask: "Has the student worked something out, pointed to the clue, AND considered why the author might have made a particular choice?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wtSample: "Brian feels proud when he gets his first fish.",
    exemplar: "The text never says Brian has stopped hating his mother, but by the end he can watch a beautiful sunset and just wish he could share it with somebody — not specifically her, not specifically anyone — which is a quieter, less angry kind of longing than the 'hot white hate' from Week 2. That's a clue the author trusts us to notice. It also made me think about why Paulsen never lets Brian actually resolve the Secret — the wilderness changes how Brian carries it, but it doesn't erase it, which feels more honest than a tidy apology scene would have been.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions, discussion" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility, including for topics that connect to real communities beyond the classroom.",
    expect: "Contributes ideas in class discussions and projects, takes responsibility for a role in group work, and connects the book to real ideas about wellbeing, resilience and risk with care and accuracy.",
    kid: "I can share my ideas, do my part in group work, and connect the book to real life responsibly.",
    ach: "Offers ideas without being asked, takes responsibility for a role, encourages others, and makes an accurate, thoughtful connection between the book and real ideas about mental toughness, outdoor safety, or coping with hard family situations.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ask: "Does the student offer ideas and take on a job without being asked, and handle personal/real-world connections with care rather than glib comparison?",
    na: "Rarely contributes to discussions or group projects.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 campaign group, Manaia researched real outdoor-safety advice (the NZ Land Search and Rescue 'three-plus rule'), made sure the group's facts matched what search-and-rescue experts actually recommend rather than exaggerating the drama, and made sure everyone had a speaking part in the final presentation.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Tough Hope & Resilience", strand: "Values",
    curriculum: "Values: community and participation, integrity, respect, and care for others — recognising resilience, self-reliance, and the courage to keep going without giving up hope.",
    expect: "Connects the book's core value — 'tough hope', the kind of hope that comes from knowledge and effort rather than luck or rescue — to their own life, community or actions.",
    kid: "I can connect the book's idea of 'tough hope' to something real in my own life.",
    ach: "Explains what 'tough hope' means in the book and connects it to a real experience, action, or challenge of their own — without pretending hard things are easy.",
    wt: "Names the idea (e.g. 'never give up') when asked, with a simple or general link.",
    ask: "Has the student linked 'tough hope' to something real, while still respecting how hard Brian's situation actually was?",
    na: "Cannot yet explain what 'tough hope' means or connect it to themselves.",
    wtSample: "The book teaches us to never give up, like Brian never gave up.",
    exemplar: "After the moose and the tornado destroy everything in one day, Brian doesn't hope things will magically get better — he says 'I might be hit but I'm not done', and hope for him means having the skill and the fire-starting knowledge to rebuild, not just wishing. That's different from the hope I had before a hard maths test, where I was just hoping for luck. Reading this made me realise 'tough hope' — believing you can handle whatever comes because you've actually built the skills for it — is something I could practise before things go wrong, not just during.",
    evidence: "Go-deeper reflections, journal entries, Week 10 'connections' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 4 English, Years 7–8, NZ Curriculum",
  lrv: [
    "Ideas: Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics, with increasing awareness of purpose and audience.",
    "Structure and Language: Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Resilience and self-reliance, integrity, perseverance without denial ('tough hope' rather than blind optimism), respect for the natural world, and honest processing of family change and grief.",
  crossCurricular: "Health & Physical Education — Hauora (the four dimensions of wellbeing: physical, mental/emotional, social and spiritual) is a natural cross-curricular link, since Brian's survival depends as much on managing fear, grief and self-pity as on physical skill; the unit also connects to outdoor-education risk-management thinking (the NZ Search and Rescue 'plan, prepare, tell someone' message) and to Science (basic ecology — food chains, adaptation, weather systems such as the tornado).",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "Falling Alone", chapters: "Chapters 1–2",
  LI: "We are learning to understand how an author uses a character's interior thoughts and physical detail to build tension in an emergency.",
  SC: "I can describe what happens to Brian in the crash and explain how the writing makes the danger feel real, using evidence from the text.",
  rubricTags: ["R1","R2","R8"],
  days: {
    mon: D("Chapter 1 (opening – the heart attack)", "Brian boards the bushplane to visit his father, and the pilot begins showing strange signs of pain",
      "If you were the only other person in a small plane and the pilot suddenly became too sick to fly, what is the very first thing you think you'd try to do?",
      "Why is Brian flying north this summer, and what does the repeated word 'Divorce' tell us about how he feels?",
      "The pilot rubs his shoulder and complains of 'aches' more than once before the heart attack fully hits. Why might the author give us these small warning signs first, instead of the heart attack happening with no warning at all?",
      "Write two or three sentences describing exactly how you think you would feel in the first ten seconds after realising the pilot could no longer fly the plane."),
    tue: D("Chapter 1 (heart attack – crash)", "The pilot suffers a massive heart attack and dies at the controls; Brian is left alone in the cockpit",
      "Brian has never flown a plane. What do you think would be racing through someone's mind in the minutes before trying something they've never done, with no one there to help?",
      "What had the pilot shown Brian how to do earlier in the flight that suddenly matters a great deal?",
      "The chapter ends with the crash itself described very fast, in only a few lines. Why might the author choose to rush past the crash rather than describing it in slow motion?",
      "Write about a time you had to do something you had never done before because there was genuinely no one else who could do it."),
    wed: D("Chapter 2 (opening)", "Brian wakes from the crash mid-scream, in the middle of a flashback to 'the Secret' that has been haunting him",
      "Why do you think our minds sometimes flash back to old memories at the exact moment we're in the middle of something frightening?",
      "What does Brian discover about his physical injuries when he checks himself over after the crash?",
      "Brian keeps calling it 'the Secret' instead of explaining exactly what it is straight away. What effect does this have on you as a reader?",
      "Write about a memory that sometimes resurfaces for you at unexpected moments, and why you think it does."),
    thu: D("Chapter 2 (mosquitoes – taking stock of the lake)", "Morning comes, and Brian is swarmed by insects while getting his first real look at where he has landed",
      "The book spends a long time describing mosquitoes rather than something more dramatic. Why might tiny, ordinary annoyances matter just as much as big dangers in a real survival story?",
      "What does Brian see when he studies the lake and the land around him for the first time in daylight?",
      "Brian thinks that 'nobody ever mentioned the mosquitoes' when he compares this to nature documentaries. What is the author suggesting about the gap between how survival looks on screen and how it really feels?",
      "Write about a time reality turned out to be far less glamorous than how you'd imagined it from a movie, show or book."),
  },
  projects: [
    P("poster", "The Descent", "Design a labelled diagram or map showing the sequence of the crash — from the heart attack to the plane hitting the lake — with a key fact at each stage."),
    P("comic", "Ten Seconds of Silence", "6 panels showing the moment Brian realises the pilot is incapacitated through to the crash, focusing on his thoughts, not just the action."),
    P("drama", "Mayday", "Act out the radio call the pilot never got to finish, or the tense seconds Brian spends alone at the controls before the crash."),
    P("journal", "My Version of the Secret", "Write about a memory that resurfaces for you at difficult times, and compare it honestly to how Brian carries the Secret."),
  ],
  quiz: [
    Q("What is the main character's full name?", "Brian Robeson."),
    Q("How old is Brian?", "Thirteen."),
    Q("What kind of plane is Brian flying in?", "A small single-engine bushplane."),
    Q("Why is Brian travelling to see his father this particular summer?", "His parents have recently divorced, and this is his first summer of court-ordered \"visitation\" with his father, who works in the Canadian oil fields."),
    Q("True or False: Brian's parents are still married.", "False — they are recently divorced.", "tf"),
    Q("What does Brian call the thing he knows about his mother but hasn't told anyone?", "\"The Secret.\""),
    Q("What gift does Brian's mother give him just before he boards the plane?", "A hatchet, with a steel handle and rubber grip, in a leather belt sheath."),
    Q("Vocabulary: what does \"visitation rights\" mean?", "The legally arranged time a child spends with the parent they don't live with full-time."),
    Q("What happens to the pilot mid-flight?", "He suffers a massive heart attack and dies at the controls."),
    Q("What early warning signs does the pilot show before the heart attack fully hits?", "Complaints of shoulder and stomach pain, grimacing, and passing gas, which he blames on something he ate."),
    Q("What had the pilot shown Brian how to do earlier in the flight?", "Briefly fly the plane himself, using the wheel and rudder pedals."),
    Q("Where does the plane crash?", "Into a lake in the northern Canadian wilderness."),
    Q("True or False: Brian breaks several bones in the crash.", "False — he is bruised, battered and has a badly swollen forehead, but nothing is broken.", "tf"),
    Q("What memory keeps replaying in Brian's mind that reveals part of the Secret?", "Seeing his mother kissing another man in a station wagon outside a shopping mall."),
    Q("Vocabulary: why might the author always write \"the Secret\" with a capital letter?", "It shows how enormous and central the memory feels to Brian — almost like a proper noun, or an open wound."),
    Q("What is the first thing that torments Brian after he wakes from the crash, even before hunger?", "Swarms of mosquitoes and other biting insects."),
    Q("What does Brian notice living in the lake near his crash site?", "A beaver lodge."),
    Q("Why might the author choose to reveal the Secret in small fragments rather than all at once?", "Open-ended — builds mystery, mirrors how memory and trauma actually surface, keeps the reader invested in finding out more."),
    Q("Predict: what do you think Brian will need to figure out first now that he is alone?", "Open-ended, text-supported prediction — accept water, shelter, food, or being found."),
    Q("Whole-section check: name two things that are now true about Brian's situation by the end of Chapter 2.", "Open — accept: he is alone, injured, has no food, has no matches, is in deep wilderness, the pilot has died, the plane has sunk, etc."),
  ],
},
{
  num: 2, title: "The Secret", chapters: "Chapters 3–4",
  LI: "We are learning to analyse how an author reveals a character's backstory through fragmented flashback, and how past and present intertwine.",
  SC: "I can explain what the Secret actually is, and describe how flashback is used to reveal it gradually rather than all at once.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapter 3", "Brian's panic nearly overwhelms him as the reality of being alone, injured, and stranded fully sets in",
      "Have you ever had a moment where fear seemed to multiply the longer you thought about it? What helped it stop?",
      "What thoughts does Brian repeat to himself as panic threatens to take over completely?",
      "Why might the author write this chapter as a short, almost breathless one, compared to the chapters around it?",
      "Write about a strategy you use (or could use) to stop a spiral of fear or panic from getting worse."),
    tue: D("Chapter 4 (the Secret revealed in full)", "The full flashback plays out: Brian sees his mother kissing another man at the mall, and understands what caused the divorce",
      "Why do you think Brian has never told anyone — not even his father — what he saw?",
      "What exact details does Brian remember from the moment at the mall, and why might those specific details have stuck with him so vividly?",
      "The chapter says Brian 'remembered everything in incredible detail' about that day. What does this tell us about how trauma or shock affects memory?",
      "Write about a moment that you remember in unusually sharp detail, and think about why that particular moment stuck."),
    wed: D("Chapter 4 (after the flashback)", "Brian wakes from sleep by the lake and begins to fully process that the crash really happened",
      "What is the difference between knowing something happened and truly believing it happened? Has that ever taken you time to catch up on?",
      "What physical evidence keeps reminding Brian that the crash was real and not a dream?",
      "Brian thinks about how close he came to hitting the rocky ridge instead of the lake. Why might the author include this detail about luck?",
      "Write about a time you were lucky in a way that only became clear to you afterwards, when you thought about what could have gone wrong."),
    thu: D("Chapter 4 (mosquitoes, first look at the lake in daylight)", "Insects attack again in the cool morning air, and Brian studies the lake, the beaver lodge, and the rocky ridge more closely",
      "Why might the same danger (like mosquitoes) feel worse the second time, once you know it's coming?",
      "What do the fish jumping and the beaver swimming suggest about how much life is actually around Brian, even though he feels utterly alone?",
      "Why might the author deliberately mention thriving wildlife right after describing Brian's loneliness and fear?",
      "Write a short paragraph noticing something ordinary that suddenly seems remarkable when you really pay attention to it, the way Brian starts to notice the lake."),
  },
  projects: [
    P("poster", "Fragments of the Secret", "Design a poster made of \"memory fragments\" (small labelled panels) showing the pieces of the Secret revealed so far, in the order the reader learns them."),
    P("comic", "The Mall", "Show the flashback at the mall panel by panel, from Brian's point of view, including the ordinary details he remembers (the time, the temperature)."),
    P("drama", "Talking It Out", "Act out the conversation Brian's mother tries to start in the car (\"Can't we talk this out?\") and the conversation Brian wishes he could have instead."),
    P("journal", "What I Remember in Detail", "Write about a memory you recall with unusually sharp, specific detail, and reflect on why that particular moment stayed so vivid."),
  ],
  quiz: [
    Q("What does Brian nearly lose control of at the start of Chapter 3?", "His composure — he is close to a full panic spiral about being alone and stranded."),
    Q("True or False: Brian is completely calm and rational for the entire first three days.", "False — he swings between panic, denial and small moments of clear thinking.", "tf"),
    Q("Who is Terry, and why does he matter to the flashback in Chapter 4?", "Terry is Brian's friend who was riding bikes with him the day Brian saw his mother with another man."),
    Q("What exactly does Brian see his mother doing in the flashback?", "Kissing a man with short blond hair in a parked station wagon, who is not Brian's father."),
    Q("Vocabulary: what does it mean that Brian remembers the scene \"in incredible detail\"?", "He recalls small, specific facts (the time, the temperature) alongside the emotional shock — a common effect of a traumatic memory."),
    Q("True or False: Brian has already told his father about the Secret.", "False — he has told no one, not even his father, who still doesn't know.", "tf"),
    Q("What does Brian discover about his body when he checks himself over after the crash?", "He is bruised and sore, with a badly swollen forehead, but nothing appears broken."),
    Q("What geographical feature could have destroyed the plane if it had come down slightly differently?", "A rocky ridge to the left of where the plane actually landed in the lake."),
    Q("Vocabulary: what does \"luck\" mean to Brian in this context, and why does he then doubt it?", "Surviving by chance; he doubts calling it \"good luck\" because bad luck (the divorce, the heart attack) is what put him in danger in the first place."),
    Q("What creature's home does Brian notice across the lake?", "A beaver's lodge."),
    Q("What happens to Brian's face and skin overnight and into the morning?", "It is bitten badly by mosquitoes and other insects, and his forehead remains swollen."),
    Q("Why might the author choose to reveal the Secret through a flashback rather than having Brian simply explain it to the reader?", "Open-ended — flashback mirrors real memory, creates suspense, and shows rather than tells the emotional weight."),
    Q("What effect does the extreme, specific detail of the flashback (the clock, the temperature) have on how real the memory feels?", "Open — makes the memory feel burned-in and inescapable, like trauma rather than an ordinary memory."),
    Q("Why might Brian's mother's attempt to \"talk it out\" in the car have failed?", "Open — Brian can't tell her he knows the Secret, so honest conversation isn't possible yet."),
    Q("What does the abundance of fish, birds and wildlife around the lake suggest, placed right after Brian's loneliness?", "Open — contrast between his isolation and the thriving natural world; foreshadows that this world could sustain him."),
    Q("Predict: how do you think Brian's feelings about his mother might change (or not change) over the course of the book?", "Open-ended, text-supported prediction."),
    Q("Why might Paulsen choose interior monologue (Brian's inner thoughts) rather than an outside narrator describing events?", "Open — keeps the reader trapped inside Brian's isolation and panic, building empathy."),
    Q("What do you think is the significance of Brian's mind returning to \"the Secret\" specifically during a life-threatening crisis?", "Open-ended — suggests unresolved emotional pain surfaces under extreme stress."),
    Q("Whole-section check: what two separate kinds of pain is Brian dealing with at this point in the book?", "Physical pain from the crash and injuries, and emotional pain from the divorce and the Secret."),
    Q("Why is \"The Secret\" a fitting title for this week's reading?", "Open-ended — the central reveal of this week is the full flashback explaining what the Secret is."),
  ],
},
{
  num: 3, title: "Thirst, Hunger, Shelter", chapters: "Chapters 5–6",
  LI: "We are learning to track how a character's language changes as he becomes more self-reliant and solves problems methodically.",
  SC: "I can find evidence of Brian starting to think and speak like a problem-solver, and explain what has caused that shift.",
  rubricTags: ["R1","R3","R8"],
  days: {
    mon: D("Chapter 5 (thirst, taking stock)", "Brian wakes desperately thirsty, drinks lake water, and forces himself to take stock of everything he actually has",
      "If you suddenly had almost nothing except the clothes on your back, how would you go about figuring out what you could actually work with?",
      "What items does Brian lay out in the grass, and how much (or little) do they add up to?",
      "Brian remembers his old teacher Mr Perpich saying \"you are your most valuable asset.\" Why might this thought matter so much right now?",
      "Write your own list of five things you would want to check you had if you were suddenly stranded somewhere remote."),
    tue: D("Chapter 5 (the flight path problem)", "Brian works out that the plane may have drifted far off its filed course before crashing, meaning rescue could take far longer than he hopes",
      "How would it feel to realise that the people searching for you might be looking in completely the wrong place?",
      "Why does Brian think the search might not find him quickly, even though a flight plan was filed?",
      "What does this realisation change about how Brian has to think about his situation?",
      "Write about a moment you realised a plan you were counting on might not work the way you expected."),
    wed: D("Chapter 6 (finding shelter)", "Brian discovers a natural rock overhang that will make a far better shelter than a simple lean-to",
      "What makes a good shelter, in your opinion, if you had to build or find one quickly with no tools?",
      "What natural features make the rock overhang such a lucky find for Brian?",
      "Why does the author call this \"his first good luck\" and then correct himself to include the landing itself?",
      "Design in words a shelter you would build using only natural materials around you, and explain your choices."),
    thu: D("Chapter 6 (berries, the shelter wall, the first illness)", "Brian finds and eats \"gut cherries\" (choke cherries) to fight off hunger, then builds a wall for his shelter",
      "Have you ever eaten far too much of something because you were extremely hungry, and regretted it afterwards?",
      "What mistake does Brian make with the berries, and what physical consequence does it bring later that night?",
      "Why might the author include a moment of Brian getting sick, rather than only showing his successes?",
      "Write about a time being overly eager or impatient caused a problem you had to deal with afterwards."),
  },
  projects: [
    P("poster", "What I've Got", "Design a poster listing and illustrating everything Brian actually has after the crash — and how little it is."),
    P("comic", "Finding the Overhang", "Show, panel by panel, Brian discovering and recognising the rock overhang as the perfect shelter."),
    P("drama", "Perpich's Voice", "Act out a scene where Brian's old teacher's advice (\"get motivated\", \"you are your most valuable asset\") plays like a voice in his head while he takes stock of his situation."),
    P("journal", "Too Much of a Good Thing", "Write about a time you overdid something out of hunger, excitement or impatience, and what you learned from the consequences."),
  ],
  quiz: [
    Q("What is the very first physical need Brian must deal with when he wakes on the second day?", "Extreme thirst."),
    Q("True or False: Brian immediately knows for certain that lake water is safe to drink.", "False — he isn't sure, but his thirst overrides his caution.", "tf"),
    Q("List two items Brian finds when he empties his pockets to take stock.", "Accept any two: coins, a fingernail clipper, a billfold with a twenty-dollar bill, a broken digital watch, the hatchet."),
    Q("Who is Mr Perpich, and what advice of his does Brian recall?", "Brian's old English teacher, who always told students to \"stay positive\", \"stay on top of things\" and \"get motivated\", and that \"you are your most valuable asset.\""),
    Q("Vocabulary: what does \"motivated\" mean in the context Brian uses it?", "Driven or determined to take action, rather than giving up or freezing."),
    Q("What realisation does Brian have about the plane's flight path?", "The pilot's foot jerked the rudder pedal during the heart attack, likely sending the plane hundreds of miles off its recorded flight plan."),
    Q("Why does this flight-path realisation matter so much?", "It means search planes may be looking in the wrong area, so rescue could take much longer than Brian hoped."),
    Q("What kind of shelter does Brian originally consider building, before finding something better?", "A simple lean-to."),
    Q("What natural feature does Brian find instead, and what caused it to form?", "A rock overhang/bowl, likely scooped out long ago by a glacier."),
    Q("True or False: The rock overhang is a full cave that Brian can stand up straight inside.", "False — it's a shallow overhang, not a deep cave, and he has to tip his head forward at the front.", "tf"),
    Q("What does Brian build to close off the front of the shelter?", "A woven wall of sticks and branches, with a small doorway opening."),
    Q("What berries does Brian find and eat, and what does he later nickname them?", "Small tart red-to-black berries he later calls \"gut cherries\" (choke cherries)."),
    Q("Vocabulary: what does it mean that Brian ate the berries \"pits and all\"?", "He was so hungry he swallowed the hard seed centres along with the fruit, without stopping to remove them."),
    Q("What happens to Brian later that night because of the berries?", "He becomes violently sick, with severe stomach pain (this is described fully at the start of the next chapter)."),
    Q("Why might the author choose to show Brian's early food-finding as a mixed success (finding food, but the wrong amount)?", "Open-ended — realistic survival is full of trial and error, not instant mastery."),
    Q("What does listing out his meagre possessions (a few coins, a broken watch) suggest about how differently Brian must now measure \"wealth\"?", "Open — value is now about usefulness for survival, not money or things."),
    Q("Why might finding a naturally-formed shelter feel different to Brian than building one from scratch would have?", "Open-ended — accept: less effort/more security, but also luck feels less within his control than skill does."),
    Q("Predict: how do you think Brian's understanding of what is \"lucky\" or \"safe\" will keep changing as the book goes on?", "Open-ended, text-supported prediction."),
    Q("What internal voice does Brian rely on to keep himself moving forward this week?", "Open — accept Mr Perpich's remembered advice, or his own repeated self-talk (\"I have to do something\")."),
    Q("Whole-section check: name two separate \"lessons\" Brian learns the hard way this week.", "Open — accept: lake water can be drunk but should be treated cautiously; eating too many unfamiliar berries makes you sick; shelter location matters."),
  ],
},
{
  num: 4, title: "Bear, Porcupine, Spark", chapters: "Chapters 7–8",
  LI: "We are learning to explore how setbacks and self-pity function as turning points, and how a symbol (the hatchet) begins to develop meaning.",
  SC: "I can describe a setback Brian faces this week and explain how his response to it starts to change him.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 7 (getting sick, self-pity, the bear)", "The gut cherries make Brian violently ill; afterwards he finds raspberries — and comes face to face with a bear",
      "Have you ever felt so low that it seemed like everything was against you at once? What helped you climb back out of that feeling?",
      "What does Brian do differently when he eats the raspberries, having learned from the gut cherry mistake?",
      "How does Brian's reaction to seeing the bear change from the moment of pure terror to a few minutes later, and what does that shift suggest?",
      "Write about a moment of pure fear you've experienced, and how quickly (or slowly) your mind found a way to think clearly again afterwards."),
    tue: D("Chapter 8 (the porcupine, crying, the discovery of fire)", "A porcupine attacks Brian in the night; afterwards, a devastated Brian cries — then makes the discovery that changes everything",
      "Why do you think people sometimes need to fully break down and cry before they can find the strength to keep going?",
      "What mistake does Brian make with the hatchet during the porcupine attack, and why does this scare him afterwards?",
      "What does Brian realise, almost by accident, about the connection between the hatchet and fire?",
      "Write about a small, almost accidental discovery you've made that ended up being far more useful than you expected."),
    wed: D("Chapter 7 (deeper look at the bear encounter)", "Return to the moment with the bear, focusing on what Brian learns about danger versus real threat",
      "How do you decide whether something that looks scary is actually dangerous, versus just unfamiliar?",
      "What does Brian conclude about why the bear didn't attack him?",
      "Why might learning to correctly judge real danger (instead of just being afraid of everything) be one of the most important survival skills of all?",
      "Write about a time something looked frightening at first but turned out not to be a real threat once you understood it better."),
    thu: D("Chapter 8 (the dream, and understanding the hatchet's meaning)", "Brian dreams of his father and Terry trying to tell him something important, and wakes to understand what it means",
      "Do you ever find that your brain works out a problem while you're asleep, one you couldn't solve while awake?",
      "What are Brian's father and Terry doing in the dream, and what are they both, in different ways, pointing him toward?",
      "Why might the author use a dream, rather than Brian simply figuring it out logically while awake, to lead him to the discovery of fire?",
      "Write about a problem you eventually solved by stepping away from it for a while, rather than by forcing an answer."),
  },
  projects: [
    P("poster", "Danger vs. Fear", "Design a poster comparing something that felt dangerous but wasn't (the bear) with something that was genuinely dangerous (the porcupine's quills, or a future threat), and explain the difference."),
    P("comic", "Sparks in the Dark", "Show, panel by panel, the porcupine attack through to Brian's discovery that the hatchet can make fire."),
    P("drama", "The Dream", "Act out Brian's dream of his father and Terry both trying to point him toward fire, using gesture rather than speech, as the text describes."),
    P("journal", "Crying It Out", "Write about a time overwhelming emotion needed to be fully felt before you could move forward, and connect it honestly to Brian's night in the dark."),
  ],
  quiz: [
    Q("What physical illness does Brian suffer from at the start of Chapter 7, and what caused it?", "Severe stomach pain, vomiting and diarrhoea, caused by eating too many unripe gut cherries, pits and all."),
    Q("True or False: After being sick, Brian avoids the gut cherry bushes completely for the rest of the book.", "False — he later returns and eats the fully ripe ones more carefully.", "tf"),
    Q("What new berry does Brian discover that is much easier to eat than the gut cherries?", "Raspberries."),
    Q("What animal does Brian encounter while picking raspberries?", "A large black bear."),
    Q("Vocabulary: what does it mean that the bear \"studied\" Brian?", "It paused and looked at him closely, assessing him, rather than immediately reacting with aggression."),
    Q("What does Brian eventually conclude about why the bear didn't attack him?", "It wasn't interested in him as a threat or as food — it was simply eating berries and moved on peacefully."),
    Q("What animal attacks Brian in his shelter during the night in Chapter 8?", "A porcupine."),
    Q("What mistake does Brian make when startled by the porcupine, and why is it dangerous?", "He throws his hatchet at it in a panic, risking losing his one essential tool in the dark."),
    Q("True or False: The porcupine bites Brian.", "False — it strikes him with its tail full of quills, which become embedded in his leg.", "tf"),
    Q("What does Brian realise is the \"most important rule of survival\" after his night of crying in the shelter?", "That feeling sorry for yourself doesn't work — self-pity doesn't change your situation."),
    Q("What accidental event leads Brian to discover fire can come from the hatchet?", "Sparks fly when the thrown hatchet strikes the stone wall of the shelter."),
    Q("What do Brian's father and Terry do in his dream that hints at the discovery?", "They gesture toward things related to fire — his father miming something and Terry pointing at a barbecue fire — though Brian can't understand at first."),
    Q("Vocabulary: what is a \"symbol\" in a story, and how might the hatchet be becoming one?", "An object that represents a bigger idea; the hatchet is coming to represent survival, self-reliance and the connection to his mother's gift."),
    Q("Why might the author choose to have Brian discover fire almost by accident, rather than through careful planning?", "Open-ended — realistic; also shows that observation and being open to noticing things matters as much as deliberate effort."),
    Q("How does Brian's response to fear evolve between the bear encounter and the porcupine attack?", "Open — with the bear he freezes then reasons calmly once safe; with the porcupine, panic causes a costly overreaction, showing his judgement is still developing."),
    Q("Why might crying \"until he was cried out\" be presented as a turning point rather than a weakness?", "Open-ended — releasing emotion fully allows him to move past self-pity rather than staying stuck in it."),
    Q("What does the phrase \"so fast things change\" suggest about how Brian is learning to see his situation?", "Open — that safety and danger can flip almost instantly, so vigilance and adaptability matter."),
    Q("Predict: how do you think Brian's discovery about the hatchet and sparks will change the chapters ahead?", "Open-ended, text-supported prediction — accept fire for warmth, cooking, protection, signalling."),
    Q("Why is \"Bear, Porcupine, Spark\" a fitting title for this week's reading?", "Open-ended — names the week's key events and their rising significance, ending on the turning-point discovery."),
    Q("Whole-section check: what has Brian learned this week about the difference between a real threat and a false alarm?", "Open — accept that not every large or frightening animal is actively dangerous, but small mistakes (throwing the hatchet) can have serious consequences."),
  ],
},
{
  num: 5, title: "Fire, and the First Feast", chapters: "Chapters 9–10",
  LI: "We are learning to examine how the author uses careful, step-by-step process writing to build both realism and tension.",
  SC: "I can describe the process Brian goes through to make fire, and explain why the author slows down to show every step.",
  rubricTags: ["R2","R3","R6"],
  days: {
    mon: D("Chapter 9 (trial and error with sparks)", "Brian discovers that getting a spark is easy — but turning a spark into a flame takes real trial and error",
      "Have you ever had to keep adjusting your approach to something, again and again, before it finally worked?",
      "What different materials does Brian try before finding one that will actually catch a spark?",
      "Why does the birchbark work when the grass, twigs and even the twenty-dollar bill did not?",
      "Write step-by-step instructions for something you know how to do well, the way Brian is essentially figuring out fire-making step by step."),
    tue: D("Chapter 9 (the breath of life — making the flame)", "Brian finally coaxes his spark nest into a real flame, and feeds it carefully until it becomes a fire he can rely on",
      "Why do you think something as simple as blowing gently, rather than hard, can make such a big difference to a delicate new flame?",
      "What specific technique finally works to turn the glowing spark into an actual flame?",
      "Brian says \"I have a friend named fire.\" Why might he think of fire almost as a companion, rather than just a tool?",
      "Write about something ordinary that became far more meaningful to you once you had to work hard to get it."),
    wed: D("Chapter 10 (opening – keeping the fire alive, finding turtle eggs)", "Brian learns how much effort it takes to keep a fire fed, and stumbles onto a new food source: turtle eggs",
      "What do you think is harder: starting something difficult, or maintaining it once you've got it going?",
      "What does Brian discover buried near the beach, and how does he figure out what it is?",
      "Why might the author show Brian being so careful and disciplined about not eating all the eggs at once?",
      "Write about a time you had to show restraint (not use up something all at once) even though you badly wanted to."),
    thu: D("Chapter 10 (continued – noticing change in himself)", "Brian begins to notice that surviving has started to change how his mind and body work",
      "Have you ever noticed yourself getting better at paying attention to small details the more practice you get at something?",
      "What specific changes does Brian notice in how he sees, hears and moves through the world now?",
      "Why might the author choose this moment — right after the triumph of fire — to show Brian reflecting on how much he has already changed?",
      "Write about a skill or habit where you've noticed yourself changing, even in small ways, the more you practise it."),
  },
  projects: [
    P("poster", "The Steps to Fire", "Design a step-by-step poster showing exactly how Brian makes fire from the hatchet and stone, from spark to flame to feeding it."),
    P("comic", "Turtle Eggs", "Show, panel by panel, Brian discovering, identifying, and carefully rationing the turtle eggs he finds."),
    P("drama", "Hello, Fire", "Act out the moment Brian talks to his new fire as if it were a friend, showing both the relief and the slightly strange loneliness of the moment."),
    P("journal", "Getting Good At Something Hard", "Write about a skill that took you many failed attempts before it finally worked, and what finally made the difference."),
  ],
  quiz: [
    Q("What two things does Brian discover he needs, besides sparks, to make fire?", "The right kind of tinder (fine, dry material) and air (blown gently to feed the glow)."),
    Q("What material does Brian try first that fails to catch a spark?", "Dried grass and small twigs."),
    Q("What unusual material does Brian try, out of desperation, that also fails?", "Shredded pieces of his twenty-dollar bill."),
    Q("What material finally works as tinder?", "Fine, fluffy shavings of birchbark."),
    Q("Vocabulary: what does Brian mean by his \"spark nest\"?", "The carefully prepared ball of fine, dry birchbark fluff designed to catch and hold a spark."),
    Q("What technique does Brian discover is key to turning a spark into a flame?", "Blowing gently (not too hard) on the glowing embers to add oxygen without extinguishing them."),
    Q("True or False: Brian gets fire on his very first attempt.", "False — it takes many failed attempts and careful adjustment before it works.", "tf"),
    Q("What does Brian say to the fire once he has it going, showing how he feels about it?", "\"Hello, fire\" — treating it almost like a friend or companion."),
    Q("What food discovery does Brian make at the start of Chapter 10?", "A nest of turtle eggs buried near the beach."),
    Q("How does Brian control himself around the turtle eggs, despite his hunger?", "He rations them carefully rather than eating them all at once, reburying the rest."),
    Q("Vocabulary: what does \"ration\" mean?", "To limit or carefully control the amount of something used, especially food, so it lasts longer."),
    Q("What changes does Brian start to notice in his own senses and body?", "He notices sounds and sights more fully and specifically than before, and his mind and body seem to work together in new ways."),
    Q("Why does keeping a fire going require so much extra work, according to the text?", "It needs a constant supply of wood, and Brian learns to gather enough for several days at a time."),
    Q("Why might the author dedicate so much careful, step-by-step detail to the process of making fire?", "Open-ended — builds tension and realism, and reflects how significant and hard-won the achievement actually is."),
    Q("What does the phrase \"a friend and a guard\" suggest about the multiple roles fire now plays for Brian?", "Open — fire provides warmth/comfort (friend) and protection from animals like the porcupine (guard)."),
    Q("Why might discovering turtle eggs matter just as much as discovering fire, in terms of Brian's survival?", "Open-ended — food and fire are both essential; the eggs provide protein/nutrition he badly needs."),
    Q("How does Brian's growing self-discipline around food (rationing the eggs) reflect his overall character growth this week?", "Open — shows patience and forward-thinking replacing his earlier impulsiveness (e.g. with the gut cherries)."),
    Q("Predict: how do you think fire will change the dangers Brian faces going forward?", "Open-ended, text-supported prediction — accept protection from animals, ability to cook food, signalling for rescue."),
    Q("Whole-section check: what two major survival breakthroughs happen this week?", "Making fire, and discovering a reliable food source (turtle eggs)."),
    Q("Why is \"Fire, and the First Feast\" a fitting title for this week's reading?", "Open-ended — names the week's two central achievements and the turning point they represent."),
  ],
},
{
  num: 6, title: "The Plane That Didn't Turn", chapters: "Chapters 11–12",
  LI: "We are learning to evaluate how hope and despair are built up and then dismantled through pacing, and how this affects the reader.",
  SC: "I can trace how hope builds across this week's reading, and explain how the author uses the search plane scene to tear it back down.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapter 11", "Brian notices real changes in himself, prepares a signal fire on the ridge, and discovers fish are food he can reach",
      "Have you ever built yourself up with hope for something, piece by piece, without realising how much you were relying on it?",
      "What does Brian build on the rock bluff above his shelter, and why does he decide not to light it every single day?",
      "What does watching the kingfisher catch a fish teach Brian, and how does he apply that lesson to himself?",
      "Write about a lesson you learned from watching an animal, or from noticing how nature solves a problem."),
    tue: D("Chapter 12 (fish spear fails, the plan for a bow)", "Brian's fish spear fails completely, leading him toward inventing a bow and arrow",
      "Why do you think inventing something new sometimes only happens after a simpler method has completely failed?",
      "What specific problem with speed and reaction time does Brian identify as the reason his spear keeps failing?",
      "Brian imagines that this might be how early humans really invented tools — through necessity. What do you think of this idea?",
      "Write about a time an initial idea totally failed, and how that failure led you (or could have led you) toward a better idea."),
    wed: D("Chapter 12 (the search plane)", "A search plane's engine is heard in the distance; Brian races to light his signal fire, but the plane turns away before it can see him",
      "How would it feel to be so close to rescue, only to have it slip away because of bad timing?",
      "What does Brian do the moment he hears the plane, and why does he ultimately fail to signal it in time?",
      "Why might the author choose to have the plane turn away just before Brian's fire is fully lit, rather than earlier or later?",
      "Write about a moment you came agonisingly close to something you wanted badly, only to have it taken away at the last second."),
    thu: D("Chapter 12 (the collapse of hope)", "Brian's hope collapses entirely once the plane's engine fades into silence, leaving him in complete despair",
      "What is the difference between losing something you never expected to have, and losing something you were sure was coming?",
      "How does the text describe the change in Brian's thinking and feeling once he realises the plane isn't coming back?",
      "Why might total despair sometimes need to happen before a character can find a different, stronger kind of hope?",
      "Write about the lowest point you can imagine a person reaching, and what you think it might take to climb back out of it."),
  },
  projects: [
    P("poster", "Rising and Falling", "Design a poster using a rising-then-falling line or arrow to show how Brian's hope builds and then collapses across this week's reading, with a labelled event at each point."),
    P("comic", "The Sound in the Trees", "Show, panel by panel, the moment Brian hears the plane, races for his fire, and watches it turn away."),
    P("drama", "Turn Back", "Act out Brian's desperate, silent plea (\"Look back... turn now\") as the plane fades into the distance, focusing on physical stillness and internal urgency rather than shouting."),
    P("journal", "So Close", "Write about your own experience of coming close to something important and having it slip away, connecting it honestly to Brian's despair in this chapter."),
  ],
  quiz: [
    Q("What does Brian build on top of the rock bluff overlooking his shelter?", "A signal fire, kept ready in case he hears or sees a plane."),
    Q("True or False: Brian decides to keep his signal fire burning at all times.", "False — he keeps it ready but unlit, because he can't sustain enough wood to burn it constantly.", "tf"),
    Q("What bird does Brian watch catch a fish, giving him an idea?", "A kingfisher."),
    Q("What does Brian realise about fish as a food source after watching the kingfisher?", "That fish in the lake are a reachable, reliable food source, not just something to watch."),
    Q("Why does Brian's original fish spear fail to catch any fish?", "The fish are too fast and see his arm movement before he can strike."),
    Q("What invention does Brian begin to plan because the spear doesn't work?", "A bow and arrow, which can move faster than his arm alone."),
    Q("Vocabulary: what does it mean that necessity might have driven early tool invention, as Brian imagines?", "The idea that people invent solutions specifically because an existing method has failed and a real need remains."),
    Q("What sound does Brian suddenly hear while chopping wood for his bow?", "The distant engine of a plane."),
    Q("What does Brian do the instant he realises it might be a search plane?", "He drops everything and runs for his camp to light the signal fire."),
    Q("True or False: Brian successfully lights the signal fire before the plane flies out of sight.", "False — the plane turns away just as he gets the fire blazing, and it never sees him.", "tf"),
    Q("How does Brian feel and behave once the plane's engine fades completely?", "He collapses into despair, believing he will never be rescued, and feels that hope itself is now gone."),
    Q("Vocabulary: what does \"despair\" mean, and how is it different from ordinary sadness?", "A complete loss of hope; more overwhelming and hopeless than sadness alone."),
    Q("Why might the author choose to have the plane turn away at the worst possible moment, rather than simply not appearing at all?", "Open-ended — maximises emotional impact and tension; makes the loss of hope feel earned and devastating rather than just expected."),
    Q("What does Brian mean when he thinks it was all \"just a game\" without hope of rescue?", "Open — without the possibility of being found, his survival efforts momentarily feel pointless to him."),
    Q("How does this week's structure (steady hope-building, then sudden collapse) affect you as a reader?", "Open-ended, personal response — accept discussion of tension, empathy, emotional investment."),
    Q("Why might inventing the bow and arrow matter just as much, structurally, as the plane's arrival — even though the plane is the bigger emotional event?", "Open — shows Brian's growing self-reliance and problem-solving continuing regardless of rescue hopes."),
    Q("What do you predict will happen to Brian's motivation to survive after this devastating low point?", "Open-ended, text-supported prediction."),
    Q("Whole-section check: name the two very different emotional directions this week's reading takes (an upward one and a downward one).", "Upward: growing skill, self-reliance, a possible new invention (the bow); downward: the crushing disappointment of the missed search plane."),
    Q("Why is \"The Plane That Didn't Turn\" an especially fitting title for this week?", "Open-ended — names the exact devastating event and centres the week's emotional turning point."),
    Q("What do you think Brian will need in order to keep going after this low point?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 7, title: "Tough Hope", chapters: "Chapters 13–14",
  LI: "We are learning to understand character transformation over time and to identify a 'rebirth' motif in a text.",
  SC: "I can explain what changes in Brian after the search plane leaves, and describe what 'tough hope' means using evidence from the text.",
  rubricTags: ["R1","R4","R8"],
  days: {
    mon: D("Chapter 13 (the darkest night, revealed)", "We learn, in flashback, just how far into despair Brian fell the night the plane left — and how he decided he would not let death in again",
      "Why do you think authors sometimes reveal a character's very darkest moment slightly after it happened, rather than in the exact moment?",
      "What does Brian nearly do to himself on the night the plane leaves, and what stops him from following through?",
      "What two important realisations does Brian have the next morning that mark him as \"not the same\"?",
      "Write about a moment (in your own life, or imagined) where hitting a true low point led — eventually — to a real turning point."),
    tue: D("Chapter 13 (mastering the bow, the wolves)", "Brian finally succeeds with the bow and arrow after understanding light refraction, and encounters a pack of wolves without fear",
      "What is the difference between fear based on real understanding and fear based on not understanding something at all?",
      "What does Brian learn about water and light that finally lets his bow and arrow work on fish?",
      "How does Brian's reaction to the wolf differ from how he might have reacted to it back in Week 1, and what does this reveal about his growth?",
      "Write about a moment you finally understood something (in science, or in life) that had been confusing or frightening you before."),
    wed: D("Chapter 14 (the skunk disaster)", "A skunk sprays Brian directly in the face while stealing his stored turtle eggs, teaching him a painful lesson about protecting food",
      "Do you think it's possible to learn an important lesson through something that's almost comical, as well as painful?",
      "What does the skunk do, and how badly does it affect Brian physically?",
      "Why does the author point out that cartoons about skunks are \"nothing funny\" once you actually experience it?",
      "Write about a time a mistake taught you something important, even though (looking back) parts of it were a little bit funny."),
    thu: D("Chapter 14 (rebuilding – the fortress shelter and fish pond)", "Brian rebuilds his shelter to be far more secure, and invents a way to store live fish for later",
      "What is the value of rebuilding something stronger after it fails you once, rather than just patching the same weak version?",
      "What specific improvements does Brian make to his shelter, and to his food storage, after the skunk incident?",
      "Why might inventing a way to keep fish alive and stored (rather than just catching them fresh each time) be such an important step forward?",
      "Write about an area of your own life (a habit, a system, a routine) that you've had to rebuild stronger after it let you down once."),
  },
  projects: [
    P("poster", "Tough Hope", "Design a poster explaining, in Brian's own words and images, what \"tough hope\" means and how it's different from ordinary hope or luck."),
    P("comic", "First Real Fish", "Show, panel by panel, Brian working out the refraction problem and finally succeeding with the bow and arrow."),
    P("drama", "The Skunk", "Act out — for comic timing as well as accuracy — the moment the skunk sprays Brian, and the chaos that follows."),
    P("journal", "The Night I Nearly Gave Up", "Write about (your own experience, or an imagined one) reaching a true low point, and what \"tough hope\" might look like in getting back up from it."),
  ],
  quiz: [
    Q("What does Brian nearly do to himself on the night after the plane leaves?", "In despair, he takes the hatchet up onto the ridge and tries, unsuccessfully, to harm himself."),
    Q("True or False: Brian goes through with seriously harming himself that night.", "False — he is unable to follow through, and survives the night, deeply changed by the experience.", "tf"),
    Q("What two realisations does Brian wake up with the next morning?", "That he is not the same person he was, and that he will not let despair (\"death\") take him again."),
    Q("What scientific fact does Brian finally understand that lets his bow and arrow work on fish?", "Light refracts (bends) in water, so fish appear higher than they actually are — he must aim lower than where they seem to be."),
    Q("What animal pack does Brian encounter calmly this week, without panic?", "A pack of wolves."),
    Q("Vocabulary: what does it mean that the wolf \"claimed\" the area as its own, in Brian's eyes?", "It behaved with total confidence and ownership of its territory, and Brian recognised and respected that rather than fearing it."),
    Q("What phrase does Brian use to describe the new kind of hope he now carries?", "\"Tough hope.\""),
    Q("What animal disaster happens to Brian at the start of Chapter 14?", "A skunk sprays him directly in the face while digging up his stored turtle eggs."),
    Q("True or False: The skunk spray only causes mild, brief discomfort.", "False — it temporarily blinds him for almost two hours and causes pain that lasts for weeks.", "tf"),
    Q("What does Brian lose completely because of the skunk?", "All of his remaining stored turtle eggs, which the skunk eats."),
    Q("What is the \"most important thing that drives nature\", according to what Brian learns this week?", "Food — the constant, universal drive of every creature to find and protect food."),
    Q("What major improvement does Brian make to his shelter after the skunk incident?", "He rebuilds it with a much tighter, stronger woven wall and a secure, hard-to-breach door."),
    Q("What clever storage system does Brian invent for fish?", "A rock-walled \"fish pond\" pen in the shallows, where live fish can be kept until needed."),
    Q("Vocabulary: what does it mean to \"store ahead\" or \"think ahead\", as Brian starts doing with fish?", "Planning and preparing resources in advance, rather than only meeting immediate needs."),
    Q("Why might the author place the darkest moment of the whole book (the self-harm attempt) right before Brian's biggest growth spurt?", "Open-ended — shows that hitting rock bottom can be the turning point that forces real change; classic \"rebirth\" structure."),
    Q("How does Brian's response to the wolves demonstrate the personal growth described at the start of the chapter?", "Open — he responds with calm understanding rather than instinctive fear, reflecting his new maturity and connection to the wild."),
    Q("Why might understanding refraction be presented as such a triumphant moment, given it's \"only\" a science fact?", "Open-ended — shows that knowledge and patience, not luck, is what finally provides food; a milestone in self-reliance."),
    Q("What does the skunk incident suggest about how nature humbles even a much-improved Brian?", "Open — no matter how much he's learned, mistakes and setbacks are still part of survival; growth isn't a straight line."),
    Q("Whole-section check: identify one moment of despair and one moment of triumph from this week's reading.", "Despair: the self-harm attempt after the plane leaves; triumph: catching his first fish with the bow, or the wolf encounter, or rebuilding a stronger shelter."),
    Q("Why is \"Tough Hope\" the ideal title for this week, connecting both of its chapters?", "Open-ended — the phrase captures Brian's transformation from despair into a hard-won, knowledge-based hope that carries through both the wolf and skunk episodes."),
  ],
},
{
  num: 8, title: "First Meat, and the Moose", chapters: "Chapters 15–16",
  LI: "We are learning to compare celebration and catastrophe placed side by side, and to explore how nature is shown as both nurturing and violent.",
  SC: "I can describe Brian's triumph with the foolbird and explain how the moose and tornado disaster that follows changes the mood of the story.",
  rubricTags: ["R1","R2","R10"],
  days: {
    mon: D("Chapter 15 (learning to see the foolbirds)", "Brian finally works out how to spot the camouflaged foolbirds by their shape, not their colour, leading to his first real meat",
      "Have you ever had to completely change how you were looking for something before you could finally see it?",
      "What breakthrough does Brian have about how to actually see the foolbirds before they fly away startled?",
      "Why does the author call this moment \"like turning on a television\" for how Brian's eyes now work?",
      "Write about a time you had to change your whole approach to noticing or finding something before you finally succeeded."),
    tue: D("Chapter 15 (First Meat)", "Brian kills, cleans and cooks his first bird, in a scene the chapter calls simply 'First Meat'",
      "What do you imagine it would be like to have to prepare an animal for food yourself, having never done it before?",
      "What does Brian have to figure out, with no help, in order to clean and cook the bird?",
      "Why might this moment be described with such reverence (almost like a ceremony), rather than just as another meal?",
      "Write about the most memorable meal of your life, and try to explain what made it so much more than \"just food\"."),
    wed: D("Chapter 16 (the moose attack)", "Without warning, a female moose attacks Brian twice near the lakeshore, badly injuring his ribs",
      "How do you think you would react if a large, dangerous animal attacked you completely without warning, for no clear reason?",
      "Why does the moose attack Brian, based on what the text tells us (or doesn't tell us)?",
      "What does Brian have to do, physically and mentally, to survive the attack and get away safely?",
      "Write about an experience (yours or imagined) where something dangerous happened for no reason you could fully explain."),
    thu: D("Chapter 16 (the tornado)", "That same night, a tornado tears through the camp, destroying Brian's shelter, fire and tools completely",
      "What would it feel like to lose everything you had built, in one single night, right after already being badly hurt?",
      "What exactly does Brian lose to the tornado, and what is the one thing that survives with him?",
      "Why might the author choose to have the moose and the tornado happen on the very same day?",
      "Write about the difference between giving up after a disaster and deciding, like Brian, that you are \"tough where it counts\"."),
  },
  projects: [
    P("poster", "Celebration and Catastrophe", "Design a split poster showing the joy of First Meat on one side and the devastation of the moose-and-tornado day on the other."),
    P("comic", "The Shape, Not the Colour", "Show, panel by panel, Brian's breakthrough in learning to see the foolbirds by their outline rather than their camouflage."),
    P("drama", "One Terrible Day", "Act out — with control, not chaos — the sequence of the moose attack followed by the tornado, focusing on Brian's internal resolve (\"I might be hit but I'm not done\") rather than just the destruction."),
    P("journal", "Tough Where It Counts", "Write about what it means to be \"tough in the head\" rather than just physically tough, using evidence from this week's reading and your own life."),
  ],
  quiz: [
    Q("What breakthrough finally lets Brian spot the camouflaged foolbirds before they fly?", "He learns to look for their outline/shape (a pointed head, streamlined body) rather than trying to spot their colours or feathers."),
    Q("What method does Brian ultimately use to get close enough to kill a foolbird?", "He approaches at an angle, moving only when the bird relaxes, using his fish spear to lunge at it."),
    Q("Vocabulary: what does \"camouflage\" mean, and why does it make the foolbirds so hard to see?", "Colouring or patterning that blends an animal into its surroundings, making it difficult to spot even close up."),
    Q("What is significant about the chapter section titled \"First Meat\"?", "It marks the first time Brian successfully hunts, cleans, cooks and eats a substantial piece of meat, a major survival milestone."),
    Q("What does Brian have to figure out, with no prior experience, in order to eat the bird?", "How to remove the feathers and clean out the insides, and how to cook it evenly over the fire."),
    Q("True or False: Brian finds cleaning the bird easy and pleasant.", "False — it involves an unpleasant smell and process, though the eventual meat is deeply satisfying.", "tf"),
    Q("What animal attacks Brian without warning at the start of Chapter 16?", "A cow moose."),
    Q("How many times does the moose attack Brian, and how does he finally escape?", "It attacks him twice, driving him into the water and mud; he escapes by staying still and moving away extremely slowly while it calms down and eats."),
    Q("What part of Brian's body is seriously hurt by the moose?", "His ribs (along with a wrenched shoulder)."),
    Q("Vocabulary: what does Brian mean when he repeatedly calls the moose attack \"insane\"?", "That it seemed to happen for no clear or logical reason, unlike most animal encounters he'd had, which had understandable explanations."),
    Q("What natural disaster strikes Brian's camp later that same night?", "A tornado."),
    Q("What does the tornado destroy?", "Brian's shelter wall, his bed, his fire, and most of his tools and weapons — all swept into the lake."),
    Q("What is the one thing Brian still has after the tornado passes?", "His hatchet, still on his belt."),
    Q("True or False: After the tornado, Brian gives up and decides he cannot rebuild.", "False — he declares himself \"tough where it counts\" and resolves to start rebuilding at first light.", "tf"),
    Q("What does Brian discover sticking out of the lake the morning after the tornado?", "The tail section of the crashed plane, which the storm has shifted and raised partly above the surface."),
    Q("Why might the author place Brian's greatest triumph (First Meat) directly before his worst disaster (the moose and tornado)?", "Open-ended — heightens the emotional whiplash for the reader and tests whether Brian's new resilience (\"tough hope\") can hold up under real pressure."),
    Q("What does Brian's phrase \"I might be hit but I'm not done\" reveal about how much he has changed since Week 1?", "Open — shows resilience and determination replacing the panic and self-pity he showed earlier in the book."),
    Q("Why might the moose attack be described as \"insane\" and without clear explanation, rather than given a tidy reason?", "Open-ended — reflects how nature doesn't always make sense or follow human logic; danger can be random."),
    Q("Predict: what do you think Brian will do about the newly discovered plane tail?", "Open-ended, text-supported prediction — accept trying to reach it, hoping for supplies."),
    Q("Whole-section check: what three separate crises does Brian face this week, and in what order?", "The moose attack, then the tornado, then discovering the plane tail — all within about a day."),
  ],
},
{
  num: 9, title: "Treasure and Rescue", chapters: "Chapters 17–19 & Epilogue",
  LI: "We are learning to evaluate how an author resolves a survival narrative and reflects on lasting change, and to form our own justified opinion about the ending.",
  SC: "I can explain how Brian is finally rescued, and give my own opinion about what the book's ending suggests about who Brian has become.",
  rubricTags: ["R4","R6","R10"],
  days: {
    mon: D("Chapter 17", "Brian rebuilds his shelter after the tornado, and becomes fixated on the idea of reaching the survival pack inside the sunken plane",
      "If you knew there might be food, tools or matches within reach, but getting to them was genuinely dangerous, how would you weigh up the risk?",
      "What does Brian have to rebuild first, before he allows himself to focus on the plane?",
      "Why does Brian remind himself \"first food, then thought, then action\" before chasing the survival pack?",
      "Write about a time you had to force yourself to deal with the boring, necessary task first, before the exciting thing you really wanted to do."),
    tue: D("Chapter 18 (building the raft, the dive)", "Brian builds a crude raft, cuts into the plane's tail with the hatchet, and dives repeatedly to retrieve it after dropping it in the lake",
      "What would it take, mentally, to force yourself back into cold, murky water again and again after a frightening mistake?",
      "What mistake does Brian make with the hatchet while cutting into the plane, and what must he do to fix it?",
      "Why might the author focus on such small, physical details (how many breaths, how many feet down) during the diving scenes?",
      "Write about a time a small mistake forced you to redo something difficult, and how you felt going back to try again."),
    wed: D("Chapter 18 (finding the pilot, retrieving the bag)", "Brian finally finds and frees the survival pack from inside the plane — but the discovery comes with a horrifying sight",
      "How do you imagine it would feel to make a discovery you desperately wanted, but have it paired with something deeply disturbing?",
      "What horrifying thing does Brian see inside the plane while retrieving the survival bag?",
      "Why might the author include this disturbing detail rather than keeping the scene purely triumphant?",
      "Write about a moment (real or imagined) where getting something you wanted came bundled together with something difficult to process."),
    thu: D("Chapters 19 & Epilogue (the treasure, the rescue, and looking back)", "Brian discovers the riches inside the survival pack, is unexpectedly rescued by a passing pilot, and the epilogue reflects on how the experience changed him",
      "If you were suddenly rescued after weeks of surviving completely alone, what do you imagine the very first thing you would want to say or do would be?",
      "What useful (and surprisingly conflicting) items does Brian find inside the survival pack, and how does he feel about the rifle and the lighter?",
      "How is Brian actually found and rescued, and what role does luck versus his own actions play in it?",
      "Write your own opinion on whether Brian's rescue feels like it was \"earned\" through his skills, or whether it came down mostly to luck — use evidence from the text to support your view."),
  },
  projects: [
    P("poster", "The Survival Pack", "Design a labelled poster of everything Brian finds inside the survival pack, and note which items he feels uneasy about using and why."),
    P("comic", "Into the Tail", "Show, panel by panel, Brian building the raft, cutting into the plane, and diving to retrieve first the dropped hatchet and then the survival bag."),
    P("drama", "The Rescue", "Act out the arrival of the fur-buyer's floatplane and Brian's first words to the pilot — staying true to the calm, almost surreal tone of the real scene."),
    P("journal", "Fifty-Four Days Later", "Write your own reflective 'epilogue' page in Brian's voice, a year after the rescue, describing one way he has changed for good."),
  ],
  quiz: [
    Q("What does Brian do first, before chasing the survival pack, after the tornado?", "He rebuilds his fire and shelter, and eats, following his own rule of \"first food, then thought, then action\"."),
    Q("What does Brian build in order to reach the plane's tail out in the lake?", "A crude raft made from driftwood logs woven together (which he nicknames \"Brushpile One\")."),
    Q("What tool does Brian use to cut into the plane's aluminium body?", "His hatchet, which cuts through the thin metal skin surprisingly easily."),
    Q("What serious mistake does Brian make while cutting into the plane?", "He drops the hatchet, and it sinks into the lake below the wreck."),
    Q("True or False: Brian gives up on retrieving the hatchet because the water is too deep and dangerous.", "False — he dives repeatedly and manages to recover it.", "tf"),
    Q("What horrifying sight does Brian see once he finally gets inside the plane's tail section?", "The pilot's body, now reduced mostly to a skull, having been fed on by fish over the many weeks underwater."),
    Q("Vocabulary: why might this discovery be described as almost ending Brian's dive, rather than just upsetting him?", "The shock nearly causes him to breathe in water/lose consciousness underwater, which could have been fatal."),
    Q("What is Brian ultimately trying to retrieve from inside the plane?", "The survival pack/bag."),
    Q("Name three items Brian finds inside the survival pack.", "Accept any three: a sleeping bag and foam pad, a cookset, matches and lighters, a first-aid kit, a Cessna cap, a fishing kit, a .22 survival rifle, an emergency transmitter, soap, and freeze-dried food."),
    Q("Why does holding the survival rifle give Brian mixed feelings rather than pure relief?", "It would let him hunt without needing to fully understand or connect with the animals and the woods the way his hard-won skills have taught him to — it \"removes him\" from what he's learned."),
    Q("What is the small electronic device Brian finds, and what does it turn out to be?", "An emergency transmitter, which he doesn't realise is actually working."),
    Q("How is Brian eventually found and rescued?", "A fur-buyer pilot, flying a routine mapping route, picks up the signal from the emergency transmitter Brian had unknowingly left switched on, and spots the wreck and Brian himself."),
    Q("True or False: Brian deliberately calls for rescue using the transmitter, knowing exactly what it is.", "False — he doesn't realise the device is a working transmitter or that he has left it broadcasting.", "tf"),
    Q("How many days does Brian survive alone before he is rescued?", "Fifty-four days."),
    Q("According to the epilogue, what physical changes does Brian experience because of his time in the wild?", "He loses a significant percentage of his body weight and remains notably lean for years afterward."),
    Q("What lasting personal changes does the epilogue describe in Brian?", "He becomes more observant, more thoughtful (thinking before speaking), and finds a lasting, deep appreciation for food that never fades."),
    Q("What does Brian do to make sense of what he experienced, according to the epilogue?", "He researches and correctly identifies the plants and animals he encountered (choke cherries, hazelnuts, ruffled grouse, snapping turtle, timber wolves, and so on)."),
    Q("Why might the author choose to end the book with a factual, almost documentary-style epilogue rather than a purely emotional final scene?", "Open-ended — grounds the fictional survival story in believable, realistic detail; reflects Brian's own more measured, observant new way of thinking."),
    Q("In your own opinion, does Brian's rescue feel \"earned\" through his own skill, or does it come down mostly to luck? Explain, using evidence from the text.", "Open-ended, opinion-based, must reference the text — accept either position if well supported (e.g. his skills kept him alive long enough to be found; the transmitter and the pilot's presence were ultimately down to chance)."),
    Q("What is the one big idea from the whole book you will remember most, and why?", "Open-ended, personal response."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "Brian's Survival Manual", desc: "Create an illustrated field guide (poster + written report + panels) documenting the key survival skills Brian develops across the book — fire, shelter, food, signalling — with evidence of how each skill was learned, including the mistakes that came first." },
    { title: "Character Case File: Brian Robeson", desc: "An in-depth profile tracking Brian's whole emotional and physical journey — his fears, his relationship to the Secret and his family, and his growth — with evidence from the beginning, middle and end of the book." },
    { title: "Extended Scene: An Untold Perspective", desc: "Write and perform a new scene from a perspective the book doesn't fully show us — Brian's mother receiving the news, the fur-buyer pilot spotting the wreck, or Brian's father waiting to find out what happened — told with empathy, not as a simple villain or footnote." },
    { title: "\"My Own Tough Hope\" Class Anthology", desc: "Each student contributes one illustrated page titled \"My Own Tough Hope\", a real story of a time they had to keep going through something hard using knowledge, effort or resilience rather than luck, echoing the value at the heart of the book." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: connect with a real outdoor-safety or search-and-rescue organisation (e.g. Land Search and Rescue NZ) as a class action step, or discuss the NZ \"outdoor safety code\" in light of Brian's story.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events from the book.",
      wt: "Explains some of Brian's motivations or changes, with limited evidence.",
      a: "Explains a theme (resilience, self-reliance, grief, tough hope) and supports it with clear evidence from at least two different points in the book.",
      example: "A Character Case File showing Brian changing from panicked and self-pitying to calm and resourceful, with an event from the beginning, middle and end of the book." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A survival manual poster with clearly labelled steps, drawn directly from the text, in a logical order a real reader could follow." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A scene from an untold perspective that is emotionally plausible, empathetic, and rehearsed/improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
