/* ============================================================
   CRENSHAW — BOOK CLUB APP DATA
   Content data only. No markup/behaviour lives in this file.
   Book: "Crenshaw" by Katherine Applegate (52 chapters, 3 parts).
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Honesty, Empathy & Hope", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 3 (Years 5–6).
   "Achieved" = the curriculum expectation has been met.
   curriculum: the achievement objective / competency being assessed
   expect:     what the student should be able to do (teacher language)
   kid:        the same thing as a student "I can" statement
   ask:        one quick question the teacher can ask themselves when marking
   na/wt/ach:  level descriptors
   exemplar:   what an Achieved response looks like (student sample)
   wtSample:   a Working Towards response, for contrast
   evidence:   where in the unit to find the evidence
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas of the story (telling the truth, family love under pressure, hope, the value of imagination) and supports them with events from the book, making links beyond the text to self or the world.",
    kid: "I can explain a big idea from the story and back it up with something that happened in the book.",
    ask: "Does the student explain WHY an event matters — not just WHAT happened?",
    na: "Retells some events but cannot yet explain what they mean. Answers are mostly 'what happened'.",
    wt: "Names a big idea (e.g. 'it's about telling the truth') with a general reason, but the link to the book is vague or missing.",
    ach: "Explains a big idea and supports it with a specific event from the book. Makes a link beyond the text (to self or the world).",
    wtSample: "The book is about telling the truth because Jackson lies a lot and then he stops.",
    exemplar: "I think the biggest idea is that hiding the truth to protect people can actually leave them lonelier. Jackson tells Robin ‘everything’s fine’ when she is scared, but later she says ‘You lied.’ Only when he tells Marisol the truth does he feel better. It’s like when I hid that I was nervous about a new school and it felt lighter once I told my nan.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-away reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of how texts are shaped for different purposes and audiences, and how language features are used for effect.",
    expect: "Notices the choices the author makes — Jackson’s first-person ‘facts’ voice, humour used to soften sad moments, short chapters, flashbacks, the three-part structure with its epigraphs — and explains how they affect the reader.",
    kid: "I can notice how the author wrote the book and explain how it makes the reader think or feel.",
    ask: "Does the student name a writer's choice AND say what effect it has on the reader?",
    na: "Comments only on the plot; does not yet notice how the book is written.",
    wt: "Notices a feature (e.g. 'the chapters are short') but cannot explain its effect.",
    ach: "Names a writer's choice and explains its effect on the reader, using an example from the book.",
    wtSample: "The chapters are really short and Jackson tells it himself.",
    exemplar: "The author lets Jackson tell the story, so we only know what he chooses to say. He jokes about cerealball and burnt pancakes, which makes the hungry parts funny at first, but then sentences like ‘Those were just facts’ made me realise how hard it really was. The short chapters made me keep reading, like his thoughts were coming one at a time.",
    evidence: "Voice & language questions (esp. Weeks 1, 4 and 9), inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, making connections, summarising — and links earlier chapters to later ones (cause and effect across the book).",
    kid: "I can use reading strategies and link what happened earlier in the book to what happens later.",
    ask: "Can the student connect an earlier event to a later one without being told?",
    na: "Relies on the teacher to explain the story; does not yet connect chapters.",
    wt: "Uses a strategy when prompted (e.g. predicts when asked) and makes simple links between chapters.",
    ach: "Independently uses strategies and explains how an earlier event causes or sets up a later one.",
    wtSample: "Jackson stole a cookie and then he felt bad.",
    exemplar: "In Week 6 Jackson steals the cat-shaped cookie ‘without understanding why’. That’s why in Week 7 Crenshaw reminds him about the yo-yo he took when he was five — the yo-yo shows Jackson already knows what to do (take it back and apologise). At the end, his envelope with $7 and $3 is the payoff. I predicted he would try to pay it back when Crenshaw kept bringing it up.",
    evidence: "Predictions, cause-and-effect questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics.",
    expect: "Writes and shares clear, developed ideas about the book — opinions, explanations and reflections — with supporting detail.",
    kid: "I can share a clear idea or opinion and give reasons to support it.",
    ask: "Is there a clear idea PLUS at least two reasons or details?",
    na: "Answers are one word or unclear; ideas are not explained.",
    wt: "Shares a clear idea but gives little detail or only one reason.",
    ach: "Communicates a clear opinion or idea and develops it with at least two reasons or pieces of evidence.",
    wtSample: "I think Jackson should have told Robin the truth because lying is bad.",
    exemplar: "I think Jackson should have told Robin the truth in the hallway. First, she already knew a lot — she guessed about the minivan herself. Second, when he said everything was fine she cried without making any noise, so the lie didn’t help her feel safe. A kinder answer would be honest but gentle, like ‘We might have to move, but we’ll be together.’",
    evidence: "Go-away reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Use language features appropriately, showing a developing understanding of their effects; organise texts using a range of structures.",
    expect: "Chooses the right structure and language for the task — a ‘Here are the facts’ letter in Jackson’s voice, a persuasive poster, a comic, a script, a blues verse.",
    kid: "I can choose the right kind of writing and words for the job (like a letter, a poster or a script).",
    ask: "Does the writing look and sound like the form it's meant to be?",
    na: "Writing does not match the task; little attempt at structure or language features.",
    wt: "Attempts the right form (e.g. writes a letter) but the language or structure is inconsistent.",
    ach: "Uses a suitable structure and language features for the purpose and audience (e.g. numbered ‘facts’ and dry humour for Jackson’s notes; persuasive language for a campaign poster).",
    wtSample: "Dear Mom and Dad, I am sad about moving and I want to live with Marisol because it is better.",
    exemplar: "Dear Mom and Dad, Here are the facts. Fact one: I noticed the bills, the whispering and the empty cupboard. Fact two: I am old enough to know. Fact three: I love you, and I am tired of guessing. Please tell me the truth from now on. Love, Jackson. PS: Aretha needs her pillow.",
    evidence: "Poster, comic, drama & journal projects; Week 10 campaign / definitions book" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback to improve it.",
    kid: "I can plan my work, improve it, and use feedback to make it better.",
    ask: "Can you see a plan AND a change made because of feedback?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wt: "Plans and drafts with support; makes small changes when prompted.",
    ach: "Independently plans, drafts and revises, and uses feedback (e.g. Glow & Grow) to improve the work.",
    wtSample: "I finished my comic. My teacher told me to add colour so I did.",
    exemplar: "My plan had three parts: the note, Robin’s knock and the morning talk. My partner’s ‘grow’ said the ending felt rushed, so I added two panels showing Jackson’s face when he crumples the note. Now you can see him change his mind.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas.",
    expect: "Listens to and builds on others' ideas during group reading and projects, takes turns fairly, and handles the book's sensitive topics with respect.",
    kid: "I can listen to my group, take turns, and build on other people's ideas.",
    ask: "Does the student respond to what others say, not just wait for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt or opt out.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) “I kind of disagree with Aroha — I think Dad wasn’t being stubborn, I think he was scared of letting his family down.” She then asked the quieter group members what they thought about asking for help.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas.",
    expect: "Makes inferences — works out what characters feel and why — using clues from the text, and thinks creatively about possibilities.",
    kid: "I can use clues in the story to work out things the author doesn't tell me.",
    ask: "Has the student worked something out AND pointed to the clue?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wt: "Makes an inference with prompting but struggles to explain the clue.",
    ach: "Independently infers feelings or motives and points to the clue in the text that shows it.",
    wtSample: "Jackson is sad because they have no money.",
    exemplar: "The book never says Dad is ashamed, but he refuses to take Aretha as a ‘prop puppy’, he says ‘No, you won’t’ when Mom offers to take his place, and Jackson sees him cover his eyes in the rain. Those clues tell me Dad is proud and it hurts him to need help.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility.",
    expect: "Contributes ideas in class discussions and projects, and takes responsibility for a role in group work.",
    kid: "I can share my ideas and do my part in group work.",
    ask: "Does the student offer ideas and take on a job without being asked?",
    na: "Rarely contributes to discussions or group projects.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ach: "Offers ideas without being asked, takes responsibility for a role, and encourages others.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 drama group, Tane volunteered to direct, made a scene list, and made sure everyone had a line. He shared two ideas in the reflection circle without being asked.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Honesty, Empathy & Hope", strand: "Values",
    curriculum: "Values: integrity (being honest and accountable), community and participation, empathy and care for others, and resilience.",
    expect: "Connects the book's values — telling the truth, empathy for people facing hard times, hope, and being a friend — to their own life and actions.",
    kid: "I can connect the book's message about honesty, empathy and hope to my own life.",
    ask: "Has the student linked a value from the book to something real in their own life?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wt: "Names a value (e.g. 'be honest') when asked, with a simple or general link.",
    ach: "Explains a value from the book and connects it to a real experience or action of their own.",
    wtSample: "The book teaches us to be honest and kind.",
    exemplar: "Marisol shows empathy by listening without laughing, and she says she’ll still be Jackson’s friend even if he moves. I want to be like that. When a boy in my class was quiet and had no lunch, I didn’t make a big deal — I just shared mine and sat with him. It’s about being honest with the people who matter and kind to the people who are struggling.",
    evidence: "Go-away reflections, journal entries, Week 10 project, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 3–4 English, Years 5–6, NZ Curriculum",
  lrv: [
    "Ideas: Show understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show understanding of how texts are shaped for different purposes and audiences.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies confidently to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics.",
    "Structure and Language: Show understanding of language features, using them appropriately.",
    "Processes and Strategies: Select and use processes and strategies to communicate confidently.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Honesty and telling the truth, empathy and care for families facing hard times, resilience and hope, friendship and belonging, and the power of imagination.",
  crossCurricular: "Health & PE — Hauora and Relationships (talking honestly, asking for help, being a good friend); Science — Nature of Science and Living World (Jackson's observations, 'logical explanations' and animal facts model scientific thinking); Social Sciences — Community & Identity (how communities respond when families need support).",
};

/* Sensitive-content note for teachers (shown in the Teacher Pack & unit plan) */
const CARE_NOTE = {
  heading: "A note on sensitive content",
  points: [
    "Crenshaw is a gentle, funny book, but it deals with family homelessness, hunger, a parent's illness (multiple sclerosis), an eviction and shoplifting. Some students may have lived experiences close to Jackson's. Read the book yourself before you begin and decide how you will handle these topics with your class.",
    "Keep every discussion invitational. Never ask students to share their own family's circumstances; use ‘Jackson’, ‘imagine’ and ‘some families’ framing, and let students pass on any question.",
    "Model the book's own attitude: the family in this story is loving, resourceful and never ‘to blame’. Talk about hardship with respect and about generosity as something a community does together.",
    "Have a quiet way for students to check in with you privately (a sticky note, a walk-and-talk) and know your school's pastoral / counselling contacts.",
    "Jackson's shoplifting is presented honestly, with guilt and consequences. Use it to discuss choices, honesty and making things right — not to excuse or glamorise stealing.",
  ],
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "A Boy Who Likes Facts", chapters: "Chapters 1–8",
  LI: "We are learning to work out what a narrator is like from the way he tells his own story.",
  SC: "I can point to words and details in Jackson’s telling that show what he is like, and explain what they make me think about him.",
  rubricTags: ["R1","R2","R8"],
  days: {
    mon: D("Chapters 1–2", "A surfing cat on the beach; a boy who trusts facts",
      "If you saw something impossible — like a cat riding a surfboard — would you trust your eyes, or decide you must be mistaken? What would you do to check?",
      "What does Jackson do when the cat floats over him, and what is left behind on the sand when the cat disappears?",
      "Jackson says ‘facts are so much better than stories’. What do his Easter Bunny adventure and his two days as ‘mayor of Earth’ suggest about the kind of kid he is, and why might that make seeing Crenshaw especially hard for him?",
      "Write two ‘Thing number one… Thing number two…’ observations about something ordinary in your classroom, in Jackson’s careful, factual voice."),
    tue: D("Chapters 3–4", "Worried parents; cerealball and the purple jelly beans",
      "When you have to wait a long time for something you want, what tricks do you use to make the time pass?",
      "What is cerealball, and what unexpected thing does Jackson find in Robin’s T-ball cap?",
      "Jackson refuses to eat the jelly beans right away and lists many ‘logical explanations’ instead. What does this tell us about how he deals with things he can’t explain?",
      "Think of something strange that once happened to you or someone you know. Write the most logical explanation and the most magical explanation for it."),
    wed: D("Chapters 5–6", "The first meeting at the rest stop; naming Crenshaw",
      "What does it mean to give someone a name? Would you rather have a name that already belongs to someone in your family, or one that is brand-new? Why?",
      "Where and when did Jackson first meet Crenshaw, and what does Crenshaw ask him?",
      "Jackson says the name Crenshaw ‘felt like a blank piece of paper before you draw on it’. Why might that matter to a boy who was named after a guitar and given a middle name that was ‘already used up’?",
      "If you could invent an imaginary friend, what would you call them, and why would that be exactly the right name?"),
    thu: D("Chapters 7–8", "Memory is weird; keepsakes and a bedtime story",
      "Some of the things that matter most to us are small objects. What is one object you would never want to lose, and why?",
      "What are ‘keepsakes’, and what is the first thing Jackson puts in his keepsakes bag even though he says he is ‘way too old’ for it?",
      "Jackson stands in the doorway while his family squashes onto Robin’s mattress and says he felt ‘like a relative from out of town’. What does this tell us about how he sees his place in his family?",
      "Write a short definition in the style of Jackson’s favourite book — ‘A ____ is to ____’ — for the word ‘keepsake’ or the word ‘family’."),
  },
  projects: [
    P("poster", "Facts About Jackson", "Design a ‘nature facts’ poster the way Jackson would, but make every fact about Jackson himself (his likes, worries and habits), each one backed up by something from Chapters 1–8."),
    P("comic", "The Bumbershoot Mystery", "Draw 6 panels showing the surfing cat, the floating umbrella and Jackson’s ten-second counting trick, ending on the vanished umbrella."),
    P("drama", "Cerealball", "In pairs, act out a round of cerealball between Jackson and Robin, including their ‘conversation’ with their stomachs and the moment the jelly beans appear."),
    P("journal", "Jackson’s Field Notes", "Write a page from Jackson’s notebook listing his ‘observations’, ‘possible explanations’ and a conclusion about what he saw at the beach."),
  ],
  quiz: [
    Q("What does the T-shirt on the surfing cat say?", "CATS RULE, DOGS DROOL."),
    Q("What message is printed in crayon on the handle of the umbrella that lands in the sand?", "THIS BUMBERSHOOT BELONGS TO CRENSHAW."),
    Q("True or False: Lots of people on the beach wave back at the floating cat.", "False — no one else on the beach seems to see him.", "tf"),
    Q("What does Jackson want to be when he grows up?", "A scientist — an animal scientist (he mentions bats, cheetahs, cats, dogs, snakes, rats and manatees)."),
    Q("What is ‘See Spot Walk’?", "The dog-walking service Jackson and his friend Marisol started this summer."),
    Q("Why did the mall manager make Jackson’s family leave when he was little?", "Jackson pulled off the Easter Bunny’s paw, saw a man’s hand inside, and shouted ‘This man is not a rabbit!’ — a little girl started crying."),
    Q("Vocabulary: What does ‘logical’ mean in the phrase ‘a logical explanation’?", "Based on clear reasoning or facts; something that makes sense."),
    Q("What is cerealball, and why do Jackson and Robin play it?", "You throw one piece of cereal at a target and can’t eat it until you score. It takes so long that you forget you’re hungry when there isn’t much food."),
    Q("What does Jackson find in Robin’s T-ball cap instead of a piece of cereal?", "Four purple jelly beans."),
    Q("True or False: Robin thinks the jelly beans are magic.", "True — she says ‘It’s magic!’ and starts dividing them up.", "tf"),
    Q("Name two ‘logical explanations’ Jackson considers for the flying cat and the jelly beans.", "Any two of: he was tired/sick or delirious, he had sunstroke, he was asleep and dreaming, he was hungry."),
    Q("Where was Jackson when he first met Crenshaw, and how old was he?", "At a highway rest stop, about three years earlier, right after first grade ended (age seven)."),
    Q("What does Crenshaw ask Jackson the first time they meet?", "‘Do you have any purple jelly beans?’"),
    Q("How did Crenshaw get his name?", "Crenshaw asked what Jackson wanted his name to be, and Jackson said ‘Crenshaw would be a good name for a cat, I think.’"),
    Q("True or False: Jackson can explain where the name ‘Crenshaw’ came from.", "False — nobody in his family knew a Crenshaw and he has no idea; it just seemed right.", "tf"),
    Q("How did Jackson and Robin get their names?", "They were named after guitars — Jackson after Dad’s guitar (made by a company called Jackson) and Robin after the company that made Mom’s guitar."),
    Q("What is going to happen to many of the family’s belongings on Sunday, and why?", "They’ll be sold at a yard sale to make money to pay back rent and maybe the water bill."),
    Q("Why do you think Jackson puts A Hole Is to Dig in his keepsakes bag first, even though he says he’s too old for it?", "Open-ended — it is a comforting book from when he was little that his parents read a million times; it shows he still cares about it and about his family."),
    Q("Jackson says he felt like ‘a relative from out of town’ in Robin’s room. Explain what he means.", "Open-ended — he feels he belongs to his family but not quite as much as they belong to each other, partly because he looks and feels different (darker hair and eyes, darker moods)."),
    Q("Predict: Crenshaw comes back at a time when things are hard for Jackson’s family. What might he be there to help Jackson with? Use a clue from the text.", "Open-ended — accept any reasonable, text-supported prediction (e.g. the growing money troubles, or the parents not telling Jackson the truth)."),
  ],
},
{
  num: 2, title: "Reading the Signs", chapters: "Chapters 9–13",
  LI: "We are learning to infer what is really going on when characters don’t say it out loud.",
  SC: "I can use clues in what characters say and do to explain what they might be hiding or feeling, and name the clue that shows it.",
  rubricTags: ["R3","R7","R8"],
  days: {
    mon: D("Chapter 9", "Bright sides and hard questions",
      "Some people always look on the bright side, and others prefer to ‘just deal with the facts’. Which are you more like, and why?",
      "How do Jackson’s parents react to bad news — for example when Dad learns he has multiple sclerosis (MS) or when the vet bill arrives?",
      "Jackson says ‘I didn’t ask any more hard questions’ because his parents ‘didn’t want to give me hard answers’. What effect do his parents’ jokes have on Jackson, and what might they be trying to protect him from?",
      "Write a four-line blues verse about a small problem, the way Jackson’s dad might — sad words, but a happy feeling."),
    tue: D("Chapter 10", "The signs Jackson has been observing",
      "What clues tell you a friend is worried even when they say ‘I’m fine’?",
      "List four ‘signs’ Jackson has been observing that tell him his family is having money troubles.",
      "Jackson says ‘maybe you can’t judge a place by its swans’. What is he saying about Swanlake Village — and about people who look fine on the outside?",
      "Write a list of ‘observations’ in Jackson’s style about your own neighbourhood: the good things you can’t see from the outside."),
    wed: D("Chapter 11", "The argument in the living room",
      "Why is it sometimes hard to ask for help, even when you need it? Imagine a time when asking felt like admitting failure.",
      "What options do Jackson’s parents talk about for where the family could go, and why does Dad turn most of them down?",
      "Mom says ‘There’s nothing wrong with asking for help’; Dad says ‘There’s everything wrong with asking for help. It means we’ve failed.’ What does each parent’s belief show about how they feel about their family?",
      "Whose side would you take, Mom’s or Dad’s? Write two sentences giving a reason, then one sentence showing that you understand the other view."),
    thu: D("Chapters 12–13", "A cat in the bathtub",
      "If an imaginary friend you invented as a little kid suddenly turned up years later, what would you say first?",
      "What is Crenshaw doing in the bathroom, and how does Aretha react to him?",
      "Jackson tells Crenshaw ‘I invented you when I was seven, and that means I can un-invent you now.’ What does this show about how Jackson thinks about imagination and control — and how does Crenshaw respond?",
      "Write the funniest, most cat-like line of dialogue you can for Crenshaw, using a big word he might choose (like ‘flummoxed’ or ‘panache’)."),
  },
  projects: [
    P("poster", "Field Guide to Reading the Signs", "Make a ‘Field Guide’ poster showing five clues from Chapter 10 and what each one really means about the family."),
    P("comic", "The Overheard Argument", "Draw 6 panels from Jackson’s point of view as he hears his parents argue in the living room and slips into the bathroom."),
    P("drama", "The Muddy Shoes Blues", "Perform (or write and sing) a new blues song in the style of Jackson’s dad about a problem the family is facing, then share how it makes the audience feel."),
    P("journal", "I Know More Than They Think", "Write Jackson’s private notebook entry on the night of the argument, using his ‘facts’ style and his real feelings."),
  ],
  quiz: [
    Q("What illness does Jackson’s dad have, and what job did he have to quit because of it?", "Multiple sclerosis (MS); he had to quit building houses (construction)."),
    Q("What does the sign on the bathroom door say that Dad taped up, and what does Mom’s sign say?", "Dad’s: OFFICE OF MR. THOMAS WADE. Mom’s: I’D RATHER BE FISHING."),
    Q("True or False: Jackson’s parents look at a half-full glass of water and say it’s half empty.", "False — they are optimists and say it’s half full.", "tf"),
    Q("What did Aretha eat at the neighbourhood potluck, and what was the result?", "A baby’s disposable diaper; she spent two nights at the vet, and the bill made the rent late."),
    Q("Why does Jackson say scientists ‘can’t afford to be optimists or pessimists’?", "They just observe the world and see what is — they measure what is there and that’s the end of the discussion."),
    Q("Name three ‘signs’ of money trouble Jackson lists in Chapter 10.", "Any three of: big piles of bills; parents whispering/arguing; things sold (silver teapot, laptop); the power off for two days; not much food; digging under the couch cushions for coins; borrowing toilet paper; the landlord saying sorry."),
    Q("How many part-time jobs do Jackson’s mom and dad have?", "Mom has three; Dad has two."),
    Q("What job did Mom used to have before she was laid off?", "She taught music at a middle school until they cut her job."),
    Q("What is special about the street names in Swanlake Village?", "They all have two words — e.g. Quiet Moon, Sleepy Dove, Weeping Wood, Sunny Glen."),
    Q("True or False: Jackson’s school librarian likes to say you can’t judge a book by its cover.", "True.", "tf"),
    Q("Vocabulary: What does ‘optimist’ mean?", "A person who expects good things and looks on the bright side."),
    Q("Name two relatives or friends Jackson’s parents think of asking for help.", "Any two of: Dad’s parents Gladys and Joe in New Jersey; Dad’s cousin with a ranch in Idaho; Mom’s mom in Sarasota; Dad’s old buddy Cal in Maine."),
    Q("Why does Dad say he couldn’t live at his father’s house?", "He says his dad is ‘the most pigheaded man on the planet’."),
    Q("True or False: Dad says the family has never asked for help.", "False — he says they have asked and have been to the food pantry ‘more times than I care to admit’.", "tf"),
    Q("Where does Jackson hide when his mom storms down the hall after the argument?", "In the bathroom."),
    Q("What is Crenshaw doing when Jackson finds him at night, and what tune is he humming?", "Taking a bubble bath; it sounds like ‘How Much Is That Doggy in the Window?’"),
    Q("What does Crenshaw ask Jackson for when he sees him in the bathroom?", "Purple jelly beans (or red ones ‘in a pinch’)."),
    Q("Why do you think Jackson’s parents always joke instead of telling him the truth about the family’s money?", "Open-ended — they want to protect him and keep the family cheerful, but Jackson feels shut out and wants honest answers."),
    Q("Dad says asking for help ‘means we’ve failed’. Do you agree? Explain your thinking.", "Open-ended — accept reasoned answers that show understanding of Dad’s pride and Mom’s view that help is not failure."),
    Q("Predict: Jackson wants Crenshaw gone. What do you think will happen next between them?", "Open-ended — accept reasonable, text-supported predictions."),
  ],
},
{
  num: 3, title: "Truth in the Dark", chapters: "Chapters 14–17",
  LI: "We are learning to explain a character’s inner conflict — what he wants and what he fears — and how it shapes his choices.",
  SC: "I can say what a character wants, what stops him, and how that makes him act as he does, using evidence from the text.",
  rubricTags: ["R1","R4","R10"],
  days: {
    mon: D("Chapter 14", "A cat with a towel; the frozen hallway",
      "If you had to hide a huge secret in your house for one night, what would be the hardest part?",
      "What does Jackson learn about Crenshaw by touching him, and what does Crenshaw do when Robin steps into the hallway?",
      "Jackson keeps writing short lists like ‘I can see my imaginary friend. I can hear him. I can talk to him.’ What do these lists show about how his mind is coping?",
      "Write your own ‘Thoughts zapped through my brain’ list of five short sentences for a moment when you were completely surprised."),
    tue: D("Chapter 15", "Robin in the hallway",
      "Is it ever okay to tell a small lie to protect someone? What is the difference between a small lie and a big one?",
      "What lie does Jackson tell Robin in the hallway, and what does she say she misses at bedtime?",
      "Jackson says ‘I hated lying. But it wasn’t like I had a choice.’ Was he right? What other choices might he have had?",
      "Write what Robin might be thinking as she waits by Jackson’s door with Spot."),
    wed: D("Chapter 16", "‘You make the rules’",
      "Have you ever wanted something to go away and then felt strangely empty when it did?",
      "What does Jackson try to do to make Crenshaw leave, and what does Crenshaw say about why imaginary friends come and how long they stay?",
      "Crenshaw says Jackson needs to tell the truth ‘to the person who matters most of all’. Who do you think that person might be? Give a reason for your idea.",
      "Finish the sentence ‘If I could make one rule for my own life, it would be…’ and explain in three sentences."),
    thu: D("Chapter 17", "Lyle and the minivan question",
      "When a younger brother, sister or friend is scared, what do you say to them? What helps most?",
      "What does Robin ask Jackson about the minivan, and how does he answer her?",
      "Jackson knew Robin ‘needed to hear the facts’, but he didn’t tell her. What stopped him, and what does this show about the difference between wanting the truth for yourself and giving it to someone else?",
      "Write two versions of what Jackson could have said to Robin: one that protects her with a comfortable fib, and one that gives her a gentle, honest truth."),
  },
  projects: [
    P("poster", "Two Sides of the Truth", "Create a two-column poster: ‘Reasons to tell the truth’ and ‘Reasons Jackson gives for hiding it’, using evidence from Chapters 14–17."),
    P("comic", "Freeze!", "Draw the hallway moment when Robin appears and Crenshaw freezes like a stuffed animal, in 6 panels including Jackson’s thoughts."),
    P("drama", "Reading Lyle", "Act out the scene where Jackson reads to Robin, showing both the tender moment and what he is holding back."),
    P("journal", "The Letter I Didn’t Send", "Write a letter from Jackson to Robin telling her the truth about what he has noticed, then write how he feels afterwards."),
  ],
  quiz: [
    Q("What does Jackson hand Crenshaw to dry himself with?", "Robin’s faded pink Hello Kitty towel."),
    Q("What does Jackson say the little prickers on Crenshaw’s tongue are called?", "Papillae."),
    Q("True or False: Crenshaw says cats laugh with their tails.", "False — he says dogs laugh with their tails, humans with their mouths, and cats smirk or sneer but ‘do not laugh’.", "tf"),
    Q("Why can’t Crenshaw say for sure whether other people can see him?", "He is ‘a bit out of practice’; only Jackson should be able to see him, but he has been left alone and forgotten for a long time so ‘who knows?’"),
    Q("What does Crenshaw do when Robin steps out of her bedroom?", "He freezes in place with his mouth open and teeth bared, like a stuffed animal in a museum."),
    Q("What lie does Jackson tell Robin about who he was talking to?", "He says he was talking to Aretha and giving her a bath."),
    Q("What does Robin say she misses, and why is her room scary?", "She misses her trash can with blue bunnies, which Dad took to the yard sale; her room is scary without her things in it."),
    Q("True or False: Robin has an imaginary friend.", "False — she says she has real friends (LaSandra, Jimmy, Kylie) so she doesn’t need to pretend.", "tf"),
    Q("What is Robin’s favourite book, and what animal is the main character?", "The House on East 88th Street; Lyle is a crocodile."),
    Q("What is the name of Robin’s stuffed armadillo?", "Spot."),
    Q("How does Robin knock on Jackson’s door?", "Tap-tap-ta-ta-tap — the beginning of ‘Wheels on the Bus’."),
    Q("What does Jackson try to do to make Crenshaw leave?", "He opens his window, takes out the screen and tries to push or lift Crenshaw out of it."),
    Q("Vocabulary: What does ‘volition’ mean in ‘Imaginary friends don’t come of their own volition’?", "Free will — choosing something for yourself."),
    Q("According to Crenshaw, who makes the rules about when he goes?", "Jackson does — imaginary friends are invited and stay as long as they are needed."),
    Q("What tempts Crenshaw to leave through the window, and what does he do?", "A frog on the windowsill; he leaps out after it into the night."),
    Q("What advice does Crenshaw give Jackson before he goes?", "Tell the truth — the facts — ‘to the person who matters most of all’."),
    Q("True or False: Jackson tells Robin the whole truth about the family’s money problems.", "False — he tells her everything is fine and she worries too much.", "tf"),
    Q("Jackson feels chilly after Crenshaw leaves, ‘like I’d taken off an itchy sweater on a cold day’. Explain this comparison.", "Open-ended — he is relieved to be rid of Crenshaw (the itchy part) but surprised to feel lonely without him (the cold part)."),
    Q("Jackson hates lying but lies to Robin. Explain the conflict he feels.", "Open-ended — he believes in truth and facts, but he wants to protect his little sister from being scared, so what he believes and what he does clash."),
    Q("Predict: Who do you think ‘the person who matters most of all’ is? What clue in the text helps you?", "Open-ended — accept reasoned answers (e.g. Robin, his parents, Marisol, or Jackson himself)."),
  ],
},
{
  num: 4, title: "Car Camping", chapters: "Chapters 18–23",
  LI: "We are learning to explain how the author uses flashback to add meaning to what is happening in the present.",
  SC: "I can explain when a chapter is a flashback, what it tells us that we didn’t know, and how it changes the way we understand Jackson’s present.",
  rubricTags: ["R2","R3","R5"],
  days: {
    mon: D("Chapters 18–19", "It doesn’t happen all at once; moving day and the tail on the windshield",
      "Big changes often creep up slowly. What is something that changes so gradually you don’t notice until it has already happened?",
      "What comparison does Jackson’s mom use to explain how money problems build up, and what odd thing does Jackson notice on the back of the minivan?",
      "Part Two begins by going back three years in time. Why might the author open this flashback with the line ‘I guess becoming homeless doesn’t happen all at once’?",
      "In two sentences explain what a flashback is, and give an example from a book or film you know."),
    tue: D("Chapter 20", "Into the minivan",
      "What song or sound do you connect with a big moment in your life? Why that one?",
      "What do Jackson’s parents say about how long the family will stay in the minivan, and what kind of music does Dad put on?",
      "Jackson asks whether kids always have to love their mom and dad, and Dad answers ‘You can be mad at someone and still love them with all your heart.’ Why do you think Jackson asks this question now?",
      "Write about a time (real or imagined) when an adult said ‘It’s complicated’ or ‘You’ll understand when you’re older’. How did it feel, and what would you have liked them to say instead?"),
    wed: D("Chapters 21–22", "Feet problems, a sleeping box and the first nights",
      "If you had to share one small space with your whole family, what would be your best trick for making a private corner of your own?",
      "Describe the ‘feet problems’ and how Jackson solves them with a cardboard box. What does he write on the top?",
      "Jackson says ‘I wasn’t looking on the bright side… Those were just facts’, but he also says ‘we were lucky’. How can he be both realistic and grateful, and how is that different from Dad saying they are just ‘car camping’?",
      "Design and label (in words or a sketch) a private space for yourself made from one cardboard box. Where would the stars go?"),
    thu: D("Chapter 23", "The stolen purse, the policeman and ‘Ratman’",
      "Have you ever been surprised by an act of kindness from a stranger? What made it stand out?",
      "What is stolen from the family, and what does the policeman give Jackson to pass on to his dad? Why must Jackson wait until they’re in the car?",
      "The policeman calls Jackson ‘Ratman’ and asks about the rats’ jump shot. Why do you think he goes out of his way to be kind like this?",
      "Write a thank-you note from Jackson (or from Dad) to the policeman that says what the twenty dollars really meant."),
  },
  projects: [
    P("poster", "Home on Wheels", "Design a poster showing the inside of the minivan with labelled ‘spaces’ (sleeping box, sleeping bags, the dog’s spot…) and a caption about what makes a place feel like home."),
    P("comic", "Kep Out Jacksons Rum", "Draw a 6-panel comic of how Jackson makes his sleeping box, what he draws on it, and what happens when Robin kicks it in her sleep."),
    P("drama", "The Policeman and the Ratman", "Act out the conversation between Jackson, his parents and the policeman, ending with the folded-up twenty-dollar bill."),
    P("journal", "The First Night", "Write a diary entry from Jackson on the first night in the minivan, mixing real facts with real feelings."),
  ],
  quiz: [
    Q("What does Mom compare money problems to?", "Catching a cold — first a tickle in your throat, then a headache, then a cough, until you have ‘a pile of Kleenexes’."),
    Q("When did the family leave their house, and what grade had Jackson just finished?", "Right after first grade ended."),
    Q("What odd thing does Jackson notice on the back windshield of the minivan?", "A long, hairy windshield wiper that looks more like a tail; when he runs round to look, it isn’t moving and isn’t hairy."),
    Q("What does the bumper sticker on the minivan say, and what does it cover up?", "I BRAKE FOR DINOSAURS; it covers a dent from when Dad backed into a shopping cart at Costco."),
    Q("True or False: The family expects to live in the minivan for only a short time.", "True — ‘a few days’, ‘two weeks tops, maybe three or four’.", "tf"),
    Q("Which singer’s CD does Dad put on for ‘hitting-the-road music’?", "B.B. King."),
    Q("Vocabulary: According to Jackson, what is a ‘blues’ song?", "A song where somebody is sad about something, but when you hear it you feel happy."),
    Q("How does Dad explain the word ‘jiving’?", "It means lying — the joke is that your mom and dad always love you."),
    Q("What does Dad say about being mad at someone?", "You can be mad at someone and still love them with all your heart."),
    Q("How old is Aretha when the family sets off, and where does she sit?", "She is only a few months old (a puppy) and sits between Robin and Jackson."),
    Q("What does Jackson make to solve the ‘feet problem’?", "A sleeping box from a cardboard TV box he found behind Wal-Mart."),
    Q("What does Jackson write on top of his box?", "kep out jacksons rum."),
    Q("What does Jackson draw on the inside of the box, and why?", "Stars — a good thing to think about before you go to sleep."),
    Q("What does Dad insist the family is doing, instead of being homeless?", "Car camping."),
    Q("Where does the family sleep on their first night, and who helps them?", "A park near the Golden Gate Bridge until a security guard moves them on; then at Denny’s, where a cook Mom knew got the manager to let them park (and gave them burnt pancakes)."),
    Q("Why do Jackson’s parents take turns staying outside the library with Aretha?", "It’s dangerous to leave a dog in a hot car."),
    Q("True or False: Mom’s purse, holding most of their money, is stolen after four days in the van.", "True.", "tf"),
    Q("What does Jackson teach the policeman about rats?", "White lab rats like Harry and Hermione are clean, wild rats can make you sick, and his teacher uses ‘positive reinforcement’ (treats) to teach them basketball."),
    Q("Why does the policeman tell Jackson to wait until he’s in the car to give Dad the money?", "Because otherwise Dad would give it right back — Dad is too proud to accept it."),
    Q("Jackson says the family was lucky to have a Honda minivan with lots of room. What does this show about how he thinks about their situation?", "Open-ended — he compares their situation with people in worse situations (a kid in a tiny VW car, people living in boxes on the street) and chooses to stick to the facts rather than pretend it’s fine."),
  ],
},
{
  num: 5, title: "Singing for Supper", chapters: "Chapters 24–31",
  LI: "We are learning to identify a theme — pride and asking for help — and support it with evidence from several chapters.",
  SC: "I can state a theme in one sentence and back it up with at least two pieces of evidence from different chapters.",
  rubricTags: ["R1","R7","R10"],
  days: {
    mon: D("Chapter 24", "Applying for help; Dad’s ‘request for gratuities’",
      "What can make it hard for someone to accept help? What could make it easier?",
      "What does Mom insist the family do at the start of the chapter, and what does Dad prepare to do about money?",
      "Dad says ‘I’d rather do a little performing than stand in another endless line… waiting for a handout.’ What does this tell you about the difference, for him, between earning money and accepting help?",
      "Write a slogan for a sign that is honest, dignified and kind all at once."),
    tue: D("Chapter 25", "Seven lousy bucks; the fishing sign",
      "Have you ever tried really hard at something and got a poor result? What kept you going?",
      "How much money does Dad earn on his first day, and what does Jackson make for him while they wait in the minivan?",
      "The chapter ends with Jackson telling himself Dad’s wet face ‘was probably just the rain’. What is he really seeing, and why does he tell himself that?",
      "Describe a moment when a small gift (like Jackson’s sign) made someone feel understood. Write it as a short scene."),
    wed: D("Chapters 26–27", "Fifty-six dollars; Crenshaw appears — all of him",
      "When can a small kindness from a stranger make the biggest difference?",
      "How does Dad’s second day on the corner go differently, and what do the drivers give him besides money?",
      "When Mom says ‘Next time, I’ll do it,’ Dad answers ‘No, you won’t.’ Why is it so important to him that he is the one on the corner?",
      "Crenshaw appears at the rest stop after Jackson has been thinking about everything he misses. Write about why you think Crenshaw shows up ‘that night’."),
    thu: D("Chapters 28–31", "Fourteen weeks; riding on the roof; Crenshaw leaves",
      "Imaginary friends, pets and favourite objects can all help us feel brave. Which has helped you feel safe — or which could?",
      "How does the family finally get back into a home, and what happens to Crenshaw on the day Marisol first speaks to Jackson?",
      "Jackson says he was never embarrassed about Crenshaw until the older boys laughed. What does this show about how other people’s opinions affect us — and why might Crenshaw disappear at exactly that moment?",
      "Write two sentences: one about a friend who helped you feel less alone, and one about how you could help someone else."),
  },
  projects: [
    P("poster", "THANK YOU / THINK YOU", "Design a poster celebrating how a sign, a song or a small kindness can change someone’s day, using three details from Chapters 24–31."),
    P("comic", "Fourteen Weeks", "Draw 6 panels showing the change from the first cold, hungry days to the family finally saving enough for an apartment."),
    P("drama", "The Corner", "Act out Dad on the street corner: the drivers passing, the man in the red SUV, the fishing story, and the family counting $56.83."),
    P("journal", "Dear Dad", "Write a letter from Jackson to Dad telling him what he noticed, and what he thinks about Dad’s courage and pride."),
  ],
  quiz: [
    Q("What does Mom say the family must apply for at the start of Chapter 24?", "Assistance — they go to the Social Services office."),
    Q("What does Dad call his cardboard-sign plan?", "A ‘request for gratuities’."),
    Q("Vocabulary: What is a ‘gratuity’?", "A tip — money you give someone like a waiter."),
    Q("True or False: Dad takes Aretha with him on his first day on the corner.", "False — he says ‘No prop puppies’.", "tf"),
    Q("What does Dad’s first sign say, and what does Jackson say it looks like?", "THANK YOU; Jackson says it looks like THINK YOU."),
    Q("Where does Dad stand on the first day, and how much does he earn?", "On the lane divider by the left-hand turn signal at a busy corner near a Starbucks; about seven dollars and some change."),
    Q("What does Jackson draw on the sign he makes for Dad?", "A smiling fish in a canoe with a fishing pole and a floppy hat, with the words ID RATHIR BE FISHING."),
    Q("True or False: Mom says she has seen Dad cry many times.", "False — only three times: at their wedding and when Robin and Jackson were born.", "tf"),
    Q("How much money does Dad collect on day two, and what else do drivers give him?", "$56.83, plus a big cup of coffee and a bag with two slices of lemon pound cake."),
    Q("What does the sign of the man who takes the corner say?", "VET — GOD BLESS (he has a small poodle-like dog in his jacket)."),
    Q("Vocabulary: What is a ‘drought’, as in Jackson’s comment ‘We need the rain… because of the drought’?", "A long period without enough rain."),
    Q("What does Dad say when Mom offers to take a turn on the corner?", "‘No, you won’t.’"),
    Q("Where is the family when Crenshaw first appears all of himself in Part Two?", "At a rest stop off Highway 101, at a picnic table, eating Cheetos and water for dinner."),
    Q("How long does the family live in the minivan?", "Fourteen weeks."),
    Q("How do things start to improve for the family after about a month?", "Dad gets a part-time job at a hardware store, Mom picks up extra waitressing shifts, Dad keeps singing for tips, and they save for a rental deposit."),
    Q("Where does the family move to next, and what does Jackson have to do?", "To an apartment in Swanlake Village about forty miles from their old house; he starts at a new school."),
    Q("According to the library study Jackson finds, what percentage of children have an imaginary friend at age six or seven?", "31 percent."),
    Q("What does Jackson never tell his new friends, not even Marisol?", "That his family had been homeless."),
    Q("Explain why Crenshaw vanishes the day Marisol introduces herself. Use evidence from Chapter 30.", "Open-ended — older kids have just laughed at Jackson for talking to someone nobody can see, he is embarrassed, and right after Marisol arrives he looks round and Crenshaw is gone; perhaps he no longer needs him."),
    Q("State the theme of this week’s reading in one sentence and support it with two details.", "Open-ended — e.g. ‘Pride can make it hard to ask for help’, supported by Dad refusing shelters and handouts but choosing to sing for tips, and by Mom saying ‘We have to apply for assistance’."),
  ],
},
{
  num: 6, title: "Here We Go Again", chapters: "Chapters 32–35",
  LI: "We are learning to make predictions, and check them, using what we know about a character’s worries and habits.",
  SC: "I can make a prediction, give the clues that support it, and say afterwards whether it came true and why.",
  rubricTags: ["R3","R8","R9"],
  days: {
    mon: D("Chapter 32", "The kitty bubble bath is a warning; the raccoon and the old soul",
      "What does it mean to be an ‘old soul’? Would you like to be described that way — why or why not?",
      "Jackson lists things he would miss if the family has to move. Name three. What does his principal call him?",
      "In the raccoon story everyone panics while Jackson calmly opens the door. What does this tell us about the role Jackson plays in his family, and what might it cost him?",
      "Write a short story (5–6 sentences) about one time you, or someone you know, stayed calm when everybody else panicked."),
    tue: D("Chapter 33", "Pancakes, a missing TV and a secret message",
      "What is the difference between selling something because you want to, and because you have to?",
      "What is different about the living room and breakfast that Saturday, and what does Dad say he and Jackson will do about the game?",
      "Jackson tries not to think about Marisol ‘feeling sorry for us’. What does this tell us about how he feels about his family’s situation, and about Marisol?",
      "Predict what will happen at Best Buy. List two clues from the text that led you to your prediction."),
    wed: D("Chapter 34", "Free samples and a cat on TV",
      "Imagine you saw something no one else could see. How would you check whether it was real?",
      "Name three places where Jackson knows you can get free food. What does he see on the TV at Best Buy?",
      "Dad asks ‘You feeling okay, buddy?’ and Jackson gives him ‘an extra-big fake smile’. What does this show about the gap between what Jackson feels and what he shows?",
      "Choose one detail from Jackson’s ‘free food’ list and explain what it reveals about how he sees the world."),
    thu: D("Chapter 35", "The cookie shaped like a cat",
      "Sometimes we do things without knowing why. Describe a time when you said or did something you didn’t plan to.",
      "What does Jackson take from Pet Food Express, and what does he say to the clerk while his heart is racing?",
      "Jackson rambles about dog laughter and tail-wagging while holding the stolen cookie. Why do you think he talks so much about nature facts when he is nervous?",
      "Write the words Jackson might say to himself right after leaving Pet Food Express."),
  },
  projects: [
    P("poster", "Jackson’s Map of Free Finds", "Design a kid’s-eye map of the places Jackson knows for samples and free treats (farmers’ market, bank, hardware store…) with a note on why he knows them so well."),
    P("comic", "A Cat on the Air", "Draw the Best Buy scene: the wall of TVs, the announcers, Crenshaw’s ‘rabbit ears’ and Jackson’s ‘casual’ question to Dad."),
    P("drama", "The Raccoon Invasion", "Perform the raccoon-in-the-kitchen scene with roles for Mom (on the phone), Dad (electric guitar), Robin (baby buggy), Aretha and Jackson’s big whistle."),
    P("journal", "Prediction Log", "Keep a prediction log with three predictions for the next chapters, the evidence for each, and a space to check them later."),
  ],
  quiz: [
    Q("According to Jackson, what might the ‘night of the kitty bubble bath’ be a sign of?", "That the family is about to move again — maybe even become homeless again."),
    Q("Name two things Jackson hoped to do this year if the family didn’t move.", "Any two of: have Ms. Leach for fifth grade (she explodes things for science); keep the dog-walking business going with Marisol; try the new skate park in January; do rec soccer."),
    Q("What did Jackson’s principal call him?", "An ‘old soul’ — wise beyond his years."),
    Q("True or False: Everybody stayed calm when the raccoon got into the apartment.", "False — Aretha barked, Mom called 911, Robin fetched her baby buggy and Dad played a screechy electric guitar.", "tf"),
    Q("What was the raccoon eating?", "A piece of Aretha’s dog chow (dry dog food)."),
    Q("How did Jackson get the raccoon to leave?", "He whistled to get everyone’s attention, sat them on the couch, and opened the front door."),
    Q("What did Mom tell the 911 operator about the raccoon?", "That there was a home invasion — though it was just eating dog food and wasn’t attacking anyone."),
    Q("What was missing from the living room on Saturday morning, and where had it gone?", "The TV; Dad sold it to Marisol’s dad."),
    Q("What shape did Dad make Robin’s pancakes?", "The letter R, for Robin."),
    Q("What did the pieces of Jackson’s sliced pancakes spell?", "C-R-E-N-S-H-A-W."),
    Q("True or False: Dad says he’s sorry Jackson couldn’t go to soccer camp.", "True — ‘Just couldn’t swing it.’", "tf"),
    Q("Where do Jackson and Dad go to watch the Giants game?", "Best Buy."),
    Q("What free treat does Jackson pick up at the bank, and which colour does he choose?", "Two free suckers; he always picks purple (or red if there’s no purple)."),
    Q("Why doesn’t Dad like going to the community-center food pantry, according to Jackson?", "Dad says he doesn’t want to take food from people who really need it, but Jackson thinks it’s because everyone in the line looks so tired and sad."),
    Q("What was the final score of the Giants game?", "The Giants won 6 to 3."),
    Q("What is Crenshaw doing on the TV at Best Buy?", "He is one of the announcers in the booth, waving, making rabbit ears behind the other announcer’s head and standing on his head."),
    Q("What excuse does Jackson give Dad about the cat?", "He says he was just messing around and that he changed the channel to a Friskies commercial."),
    Q("What does Jackson take from Pet Food Express?", "A dog cookie shaped like a cat."),
    Q("Why do you think Jackson takes the cookie ‘without understanding why’?", "Open-ended — he is stressed, worried and out of control of his life, and Crenshaw has just appeared; accept reasoned answers based on the text."),
    Q("Predict: Jackson is keeping secrets from everyone. How might this affect him in the next chapters?", "Open-ended — accept text-supported predictions (e.g. guilt, Crenshaw pressuring him, being caught, breaking down)."),
  ],
},
{
  num: 7, title: "Right and Wrong", chapters: "Chapters 36–41",
  LI: "We are learning to explore a character’s moral choices: what he does, how he explains it to himself, and how he really feels.",
  SC: "I can explain a choice a character makes, how he justifies it, and what the text shows about how he really feels.",
  rubricTags: ["R6","R8","R10"],
  days: {
    mon: D("Chapter 36", "‘Magic Jackson’ — a shoplifter’s confession",
      "How do people explain to themselves when they have done something they know is wrong? Why might that excuse still not make them feel better?",
      "How many times does Jackson say he has shoplifted (counting the dog cookie), and what did he take the first time he stole for Robin?",
      "Jackson says he felt ‘crummy about the stealing’ but ‘even worse about the lying’. Why is lying harder for him than stealing, and what does this show about what he values?",
      "Write two sentences in Jackson’s voice: one explaining why he did it and one saying what he should do about it."),
    tue: D("Chapter 37", "Aretha, the clay statue and Marisol’s sandbox",
      "How do you decide whether to tell a friend something private? What makes a friend trustworthy?",
      "What does Aretha bring to Marisol, and what does Marisol offer Jackson for it? What does she say the statue needs?",
      "Jackson tells Marisol, ‘It wasn’t the truth, not completely. But it wasn’t not the truth.’ What does he mean, and why does he answer ‘Probably not’ when she asks if he is really moving?",
      "Write the first three lines of a message from Jackson to Marisol telling her the truth."),
    wed: D("Chapters 38–39", "The name on the statue; the emptied bedroom; the mug",
      "What do you do with strong feelings that don’t seem to have anywhere to go? Which ways are helpful, and which are not?",
      "What is left in Jackson’s room, and what does he do with the Thomas the Tank Engine mug?",
      "Jackson says ‘It wasn’t about losing my stuff… What bothered me most… was that I couldn’t fix anything.’ Why does that matter more to him than the things?",
      "Write your own metaphor like Jackson’s bumper car: ‘Sometimes I feel like…’ for a time you couldn’t control what was happening."),
    thu: D("Chapters 40–41", "Aretha saw Crenshaw; a frog on the forehead; ‘Are you my conscience?’",
      "If you had a ‘conscience’ who could talk to you, what would it sound like? Would you listen?",
      "What does Jackson realise about Aretha and Crenshaw, and how does Crenshaw answer when Jackson asks how to get rid of him for good?",
      "When Jackson asks ‘Are you my conscience?’ Crenshaw replies ‘That depends. Would you like me to be?’ What does this show about how Crenshaw works?",
      "Write a short dialogue (4–6 lines) between you and your own conscience-cat. What would you argue about?"),
  },
  projects: [
    P("poster", "The Two Columns of Conscience", "Create a poster with ‘What Jackson tells himself’ and ‘What he really feels’ about stealing, citing at least three details from the text."),
    P("comic", "The Cookie in the Pocket", "Draw 6 panels: Jackson in Pet Food Express, the cookie, the clerk, the little boy in dinosaur slippers, and the moment his eyes burn and blur."),
    P("drama", "Court of Conscience", "In a group of four, hold a ‘conscience trial’ where Jackson, Crenshaw, a parent and a shopkeeper each explain what they think should happen next."),
    P("journal", "Magic Jackson Says Sorry", "Write Jackson’s honest, specific apology letter to Safeway or Pet Food Express."),
  ],
  quiz: [
    Q("How does Jackson compare stealing to a magic trick?", "He calls himself ‘Magic Jackson’ — ‘now you see it, now you don’t’."),
    Q("What did Jackson steal when he was five?", "A yo-yo."),
    Q("How many times does Jackson say he has shoplifted, and what for?", "Four times — twice to get food for Robin, once to get gum for himself, and now the dog cookie (the yo-yo when he was five isn’t counted)."),
    Q("True or False: Jackson says the lying felt worse than the stealing.", "True — ‘I felt crummy about the stealing. But I felt even worse about the lying.’", "tf"),
    Q("What food did Jackson steal from Safeway, and why?", "Two jars of Gerber chicken-and-rice baby food; Robin was hungry and Mom had told her to wait, so he slipped the jars into his pockets to ‘fix a problem’."),
    Q("What happened to the baby food after Robin ate it?", "She gobbled it so fast she threw most of it up on Jackson’s book about cheetahs."),
    Q("How does Jackson try to excuse stealing using nature, and why doesn’t it work?", "He says in nature it’s survival of the fittest, eat or be eaten — but he isn’t a lion; he’s a person who knows right from wrong."),
    Q("What does Aretha take from Jackson’s keepsakes bag?", "The clay statue of Crenshaw he made in second grade."),
    Q("What does Marisol like to build?", "Things for animals — birdhouses, bat shelters, dog carriers, cat trees, hamster habitats, ferret houses — including a cat staircase."),
    Q("What was Marisol’s imaginary friend called, and what was she like?", "Whoops — she had red hair, was very naughty, got the blame for everything and liked to eat brussels sprouts."),
    Q("True or False: Marisol offers to buy the statue for three dollars.", "True.", "tf"),
    Q("What does Marisol say the statue needs, and what name does she suggest?", "It needs a name; she says ‘Crenshaw would be a good name for a cat, I think.’"),
    Q("What does Jackson do with the mug from his nightstand, and what picture is on it?", "He throws it against the wall so it shatters; it has a faded picture of Thomas the Tank Engine."),
    Q("What is left of Jackson’s bedroom the night before the yard sale?", "His mattress, one lamp, dents in the carpet; his race-car bed is in pieces with a sticker saying $25 OR BEST OFFER."),
    Q("Vocabulary: What does ‘conscience’ mean?", "The inner voice that tells you what is right and wrong."),
    Q("What wakes Jackson in Chapter 41, and who is sleeping beside him?", "A frog on his forehead; Crenshaw and Aretha are asleep next to him."),
    Q("What does Jackson do with the stolen dog cookie?", "He throws it out the window, hoping squirrels won’t mind eating something stolen."),
    Q("Why does Crenshaw bring up the yo-yo?", "Jackson stole a yo-yo at five, blamed Crenshaw, and his parents made him take it back and apologise to the store — Crenshaw hints he should do the same thing now."),
    Q("Jackson says he liked the noise the mug made. Why do you think he liked it?", "Open-ended — he feels out of control and full of anger; smashing something gives him a feeling of doing something, even if it doesn’t fix anything."),
    Q("Jackson says the biggest problem is that he ‘couldn’t fix anything’. Do you think he is right to feel responsible? Explain.", "Open-ended — accept reasoned answers: he is a child who cannot control money or housing, yet he has taken on an adult’s worries."),
  ],
},
{
  num: 8, title: "Telling the Truth", chapters: "Chapters 42–46",
  LI: "We are learning to compare how different characters respond to hard news, and to explain what a true friend looks like.",
  SC: "I can compare two characters’ reactions to the same situation and use evidence to explain which qualities make a good friend.",
  rubricTags: ["R1","R7","R9"],
  days: {
    mon: D("Chapter 42", "The yard sale and the guitar",
      "If you had to sell something you love, how would you decide what to keep and what to let go?",
      "What things are for sale at the yard sale, and what does the man with the ponytail want to buy? How does Robin react?",
      "Dad says ‘There’s always another guitar around the bend, Jacks’ but he ‘wouldn’t meet my eyes’. Why do you think he decides to sell it, and what does Jackson notice about the deal?",
      "Write about an object with ‘a lot of history’ for someone in your family. What would it be like to sell it?"),
    tue: D("Chapters 43–44", "The eviction notice; telling Marisol everything",
      "When has a friend told you something hard? How did you respond?",
      "What does the landlord bring, and what does Robin say to Jackson? What does Crenshaw whisper when Jackson is walking the dachshunds?",
      "Jackson tells Marisol everything — the worry, the hunger, the fear — and then ‘one more fact’: Crenshaw. Why does he decide to be honest now?",
      "Write the first five sentences of what you think Jackson said to Marisol."),
    wed: D("Chapter 45", "Marisol’s answer: enjoy the magic",
      "Is it better to know how a magic trick is done, or to believe in the magic? What is lost or gained each way?",
      "How does Marisol react when Jackson tells her about Crenshaw, and what does she say about the magician at the school fair?",
      "Marisol says ‘You can’t see sound waves, but you can hear music.’ What does she mean, and how does it connect to Jackson’s need for facts?",
      "Write about something in your life you don’t need to fully understand in order to enjoy."),
    thu: D("Chapter 46", "Crickets, cat-land and Finian",
      "Imagine a place where all imaginary friends wait until they are needed. Describe what it looks like.",
      "Why does Crenshaw say he is bigger now than when Jackson was seven, and how does he describe where imaginary friends stay?",
      "Crenshaw compares imaginary friends to books: ‘created, enjoyed, dog-eared and creased, and then tucked away until we’re needed again’. What does this comparison suggest about the author’s view of imagination?",
      "Write your own comparison in Crenshaw’s style: ‘Friends are like…’."),
  },
  projects: [
    P("poster", "Keepsakes for Keeping", "Design a poster showing five keepsakes from the book (the Lyle book, A Hole Is to Dig, the clay statue, Dad’s guitar, the mug…) with a sentence about what each one means."),
    P("comic", "The Truth on the Sidewalk", "Draw the walk with Marisol and the dachshunds: Jackson’s cover story, Crenshaw’s whisper, the telling, and Marisol’s answer."),
    P("drama", "Marisol Says ‘Enjoy the Magic’", "Act out the conversation between Jackson and Marisol, focusing on how she listens and what she says."),
    P("journal", "What’s in the Hat?", "Write your own reflection on the magician’s rabbit: would you rather know how a trick works or believe in the magic? Use evidence from Chapter 45."),
  ],
  quiz: [
    Q("On what day is the yard sale?", "Sunday."),
    Q("What are two things for sale at the yard sale, and their prices?", "Any two of: a tricycle with sparklers on the wheels for $5; the Candy Land game for 50 cents; a wagon with a $4 sign; Dad’s guitar (not priced)."),
    Q("What does Robin try to give the man with the ponytail instead of Dad’s guitar?", "Her trash can with the blue bunnies."),
    Q("What does Dad do to arrange a possible sale of the guitar?", "Asks the man for his phone number ‘in case we have a change of heart’ and walks him to his car, where they swap scraps of paper."),
    Q("True or False: The family makes plenty of money at the yard sale.", "False — Mom says ‘Not even close to what we need.’", "tf"),
    Q("What words are at the top of the envelope the landlord brings?", "FINAL EVICTION NOTICE."),
    Q("What does Robin say to Jackson when she hears they have to move?", "‘You told me it would be okay, Jacks. You lied.’"),
    Q("True or False: Mom says the eviction is Jackson’s fault.", "False — she says ‘This isn’t Jackson’s fault… Blame us.’", "tf"),
    Q("Where does Jackson go, and what does he do, when he hears the news?", "He runs to his room, sits on his bed next to Crenshaw and buries his face in his fur while Crenshaw purrs."),
    Q("What are the names of the Gouchers’ dachshunds?", "Frank and Beans."),
    Q("What does Crenshaw whisper in Jackson’s ear on the walk?", "‘The truth, Jackson.’"),
    Q("What does Jackson tell Marisol?", "Everything — how worried he has been, how they were sometimes hungry, how afraid he is — and then about Crenshaw."),
    Q("How does Marisol react when she hears about Crenshaw?", "She doesn’t laugh or say he is crazy; she says she doesn’t think he’s going crazy and wishes she could see Crenshaw."),
    Q("Which story about a magician does Marisol tell?", "In second grade a magician at the school fair made a rabbit appear; Jackson figured out the trick (a hole in the hat) and told everybody, which took away the magic for her."),
    Q("What does Marisol say about sound waves?", "You can’t see sound waves, but you can hear music."),
    Q("What fact about swans does Marisol mention, and what does Jackson say?", "Swans stay together for life; Jackson says ‘usually, not always’."),
    Q("What does Crenshaw eat in the backyard, and what nature fact does Jackson tell about it?", "Crickets; Jackson says crickets are considered lucky in China (Crenshaw says delicious in Thailand)."),
    Q("Who is Finian?", "Dad’s imaginary friend — a scrawny dog who plays guitar and trombone."),
    Q("Crenshaw says ‘You need a bigger friend now.’ What does that tell us about Crenshaw and Jackson?", "Open-ended — Crenshaw grows to match how big Jackson’s problems are; imaginary friends appear and change in response to what a person needs."),
    Q("Explain Crenshaw’s comparison of imaginary friends to books in your own words.", "Open-ended — imaginary friends are created, loved and used until they’re worn, then put away on a shelf until someone needs them again."),
  ],
},
{
  num: 9, title: "Enjoy the Magic", chapters: "Chapters 47–52",
  LI: "We are learning to explain an author’s message, and how the ending of a story resolves — and leaves open — its problems.",
  SC: "I can state the author’s main message, give evidence from at least three chapters, and explain what the ending does and does not solve.",
  rubricTags: ["R4","R5","R6"],
  days: {
    mon: D("Chapter 47", "Vampire bats share",
      "Some scientists disagree about whether animals can be kind on purpose. What do you think kindness is?",
      "What does Ms. Malone teach about vampire bats, and what does she say about bats and human beings?",
      "Jackson can’t sleep and thinks about the bats after Crenshaw says ‘Life isn’t always fair’. What idea is he starting to work out about sharing and helping?",
      "Write a ‘no way’ fact you really know about an animal, and add one sentence about what people could learn from it."),
    tue: D("Chapter 48", "The nightmare and the note",
      "What might make a kid decide to run away — and what might make them change their mind?",
      "What does Jackson decide to do after his nightmare, and what does he pack and write?",
      "Crenshaw tells Jackson to ‘tell the truth to the person who matters most… You.’ How does the note Jackson writes show that he is being honest with himself?",
      "Write your own ‘Here are the facts’ note about something you need to tell someone you trust: three honest lines and one hopeful line."),
    wed: D("Chapters 49–50", "Robin at the door; the talk on the floor",
      "What makes it easier to forgive someone who has made mistakes?",
      "What does Jackson do when Robin knocks, and what do his parents say when he wakes up?",
      "Dad draws two lines: a straight line rising and a jiggly line like a mountain range. What is he saying about life, and why does Jackson accept the deal?",
      "Draw or describe your own ‘line of life’ and write a caption for it."),
    thu: D("Chapters 51–52", "Not-so-magic jelly beans; the garage apartment; ‘enjoy the magic’",
      "What does the phrase ‘enjoy the magic while you can’ mean to you?",
      "Where does Robin say the jelly beans really came from, and what news do Jackson’s parents bring from the music store?",
      "The ending doesn’t solve all of the family’s problems. Why might the author have ended it this way, and what does Jackson do differently at the end of the story?",
      "Write the last three sentences of a story about you where something small and magical happens and you decide to enjoy it."),
  },
  projects: [
    P("poster", "Enjoy the Magic", "Design a poster for the book’s main message: one central line and three pieces of evidence from Chapters 47–52."),
    P("comic", "The Note and the Knock", "Draw the moment Jackson chooses between the note and Robin’s knock, panel by panel."),
    P("drama", "The Family Talk", "Act out the morning talk on the mattress: Jackson, Mom, Dad, Robin (asleep) and Crenshaw (silent but listening)."),
    P("journal", "Five Years Later", "Write a letter from Jackson at age fifteen to his younger self about Crenshaw and what he has learned."),
  ],
  quiz: [
    Q("What kind of bats did Ms. Malone talk about in class?", "Vampire bats."),
    Q("What do the bats do when they return to their caves?", "They share food (blood) with bats who didn’t find any."),
    Q("What word does Ms. Malone use for animals that help others even at a risk to themselves?", "Altruists."),
    Q("True or False: Ms. Malone says all scientists agree that vampire bats are altruistic.", "False — some scientists say yes and some say no.", "tf"),
    Q("What does Ms. Malone say she sometimes wonders about bats and human beings?", "Whether bats are better human beings than human beings are."),
    Q("What does Jackson remember of his nightmare?", "He was in a cave, yelling for help, and nobody would listen."),
    Q("How does Crenshaw comfort Jackson after the nightmare?", "He puts a paw on Jackson’s shoulder, butts his head gently against Jackson’s and says ‘I’ll help. I’ll listen.’"),
    Q("What decision does Jackson make in the night?", "To run away and stay with Marisol."),
    Q("What does Jackson pack?", "His pillow, keepsakes bag, some clothes and his toothbrush."),
    Q("What does Jackson write in his note about Aretha and Robin?", "PS: Aretha likes to sleep on a pillow, so don’t forget. PPS: Robin needs to know what’s happening, too."),
    Q("What does Jackson put in the envelope, and what is it for?", "Ten dollars from dog-walking: $7 for Safeway (two jars of baby food) and $3 for Pet Food Express (the cat-shaped cookie)."),
    Q("Who knocks on Jackson’s door and what do they bring?", "Robin, with Spot, her pillow and her Lyle book."),
    Q("What does Jackson do with the note?", "He crumples it up and tosses it aside."),
    Q("True or False: Jackson’s parents find his note.", "True — Dad is holding it, flattened out, on his lap in the morning.", "tf"),
    Q("What ‘facts’ do Mom and Dad tell Jackson about parents?", "Parents make mistakes (a lot); parents try not to burden kids with grown-up problems, but that’s hard."),
    Q("What are the two lines Dad draws in the air, and what do they mean?", "A line going steadily up (what people wish life was like) and a jiggly up-and-down line like a mountain range (what life is really like) — you just have to keep trying."),
    Q("What proverb does Mom quote?", "‘Fall down seven times, get up eight.’"),
    Q("Where did the purple jelly beans really come from, and why did Robin say they were magic?", "From Kylie’s birthday party; Robin wanted Jackson to think they were magic."),
    Q("What good news do Mom and Dad bring from the music store?", "Dad got a part-time job, and they can stay in a garage apartment behind the store for a month."),
    Q("Whole-book review: How does Jackson change from the beginning of the book to the end? Use at least two pieces of evidence.", "Open-ended — from hiding the truth and insisting on facts, to telling Marisol and his parents honestly, letting go of the plan to run away, and choosing to ‘enjoy the magic’ while the family’s problems are still not fully solved."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "‘It’s Okay to Ask for Help’ Campaign", desc: "Create a campaign (posters, slogans and a short speech) that shows the message ‘telling the truth and asking for help is a strength’, using Jackson’s family, Marisol and the neighbours as your evidence. Keep it kind and hopeful — never point at real people." },
    { title: "Extended Drama: The Waiting Room", desc: "Imagine the ‘giant teachers’ lounge’ where imaginary friends wait until they are needed. Perform a scene with Crenshaw, Whoops, Finian and other friends you invent, swapping stories about the kids they wait for — or a scene where Dad meets Finian again." },
    { title: "Character Case File — Jackson", desc: "An in-depth profile (poster + written report + panels) tracking how Jackson changes from Part One to Part Three, with evidence from every part of the book." },
    { title: "‘A ___ Is To ___’ Class Book of First Definitions", desc: "Inspired by the book A Hole Is to Dig and the three epigraphs that open each part of Crenshaw. Each student writes and illustrates two original definitions — for example, ‘Truth is to…’, ‘A friend is to…’, ‘Home is to…’ — and adds a sentence linking it to the story." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via “Glow & Grow” sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: share favourite moments from the term.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events.",
      wt: "Explains some of Jackson’s motivations or relationships, with limited evidence.",
      a: "Explains a theme (honesty, hope, friendship, family love under pressure) and supports it with clear evidence from the book.",
      example: "A Character Case File showing Jackson moving from ‘I only like facts’ and hiding the truth to telling Marisol and his parents, with an event from each of the three Parts." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "An ‘It’s Okay to Ask for Help’ poster with a catchy slogan, three persuasive reasons from the book and a picture that matches the message." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A ‘Waiting Room’ drama with invented imaginary friends, rehearsed and improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
