/* ============================================================
   THE WILD ROBOT ESCAPES — BOOK CLUB APP DATA
   Content data only. No markup/behaviour lives in this file.
   Chapter numbers follow the 90 numbered chapters + Epilogue.
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Courage, Compassion & Belonging", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 3 (Years 5–6).
   "Achieved" = the curriculum expectation has been met.
   curriculum: the achievement objective / competency being assessed
   expect:     what the student should be able to do (teacher language)
   kid:        the same thing as a student "I can" statement
   ask:        one quick question the teacher can ask themselves when marking
   na/wt/ach:  level descriptors
   exemplar:   what an Achieved response looks like (student sample)
   wtSample:   a Working Towards response, for contrast
   evidence:   where in the unit to find the evidence
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas of the story (home and belonging, freedom, being different, courage and compassion) and supports them with events from the book, making links beyond the text to self or the world.",
    kid: "I can explain a big idea from the story and back it up with something that happened in the book.",
    ask: "Does the student explain WHY an event matters — not just WHAT happened?",
    na: "Retells some events but cannot yet explain what they mean. Answers are mostly 'what happened'.",
    wt: "Names a big idea (e.g. 'it's about getting home') with a general reason, but the link to the book is vague or missing.",
    ach: "Explains a big idea and supports it with a specific event from the book. Makes a link beyond the text (to self or the world).",
    wtSample: "The book is about a robot trying to get home to her island.",
    exemplar: "I think the biggest idea is that home isn't only a place, it's where the ones who love you let you be yourself. Roz was cared for on Hilltop Farm, but she still had to hide who she was, so it wasn't home. On the island she can be wild again. It reminds me of my nan's house, where I can be silly and nobody minds.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-away reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of how texts are shaped for different purposes and audiences, and how language features are used for effect.",
    expect: "Notices the choices the author makes — a narrator who speaks to the reader, very short chapters, lists of short lines (Chapter 16), repeated phrases (“Have a nice day!”), sound words like Klik — and explains how they affect the reader.",
    kid: "I can notice how the author wrote the book and explain how it makes the reader think or feel.",
    ask: "Does the student name a writer's choice AND say what effect it has on the reader?",
    na: "Comments only on the plot; does not yet notice how the book is written.",
    wt: "Notices a feature (e.g. 'the chapters are short') but cannot explain its effect.",
    ach: "Names a writer's choice and explains its effect on the reader, using an example from the book.",
    wtSample: "Some of the chapters are really short and there are pictures.",
    exemplar: "In Chapter 72 the police robots keep saying “Have a nice day!” over and over. The repeating makes it sound cheerful but creepy, because Roz is terrified they'll catch her. It made me feel tense even though the words were friendly. The narrator also says “Reader”, so it feels like he's telling me a secret.",
    evidence: "Setting & language questions (esp. Weeks with R2), inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, making connections, summarising — and links earlier chapters to later ones (cause and effect across the book).",
    kid: "I can use reading strategies and link what happened earlier in the book to what happens later.",
    ask: "Can the student connect an earlier event to a later one without being told?",
    na: "Relies on the teacher to explain the story; does not yet connect chapters.",
    wt: "Uses a strategy when prompted (e.g. predicts when asked) and makes simple links between chapters.",
    ach: "Independently uses strategies and explains how an earlier event causes or sets up a later one.",
    wtSample: "The kids helped Roz and then she got away.",
    exemplar: "In Week 5 Jaya and Jad take out Roz's transmitter. That's why, in Week 6, the airship flies right over the wheat field and can't find her — no signal. I predicted it would matter when Jad said her signal was still on the map and Roz gave it to Annabelle.",
    evidence: "Predictions, cause-and-effect questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics.",
    expect: "Writes and shares clear, developed ideas about the book — opinions, explanations and reflections — with supporting detail.",
    kid: "I can share a clear idea or opinion and give reasons to support it.",
    ask: "Is there a clear idea PLUS at least two reasons or details?",
    na: "Answers are one word or unclear; ideas are not explained.",
    wt: "Shares a clear idea but gives little detail or only one reason.",
    ach: "Communicates a clear opinion or idea and develops it with at least two reasons or pieces of evidence.",
    wtSample: "I think Roz was right to trust Dr Molovo because she was nice.",
    exemplar: "I think Roz was right to trust Dr Molovo. First, Dr Molovo listened to Roz's whole story before she decided anything. Second, she saved Roz's mind and promised to keep the island secret, which protects all the animals. It was a big risk, but it worked out.",
    evidence: "Go-away reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Use language features appropriately, showing a developing understanding of their effects; organise texts using a range of structures.",
    expect: "Chooses the right structure and language for the task — a logical robot log in Roz's voice, a persuasive poster, a comic, a script, a list chapter.",
    kid: "I can choose the right kind of writing and words for the job (like a log, a poster or a play script).",
    ask: "Does the writing look and sound like the form it's meant to be?",
    na: "Writing does not match the task; little attempt at structure or language features.",
    wt: "Attempts the right form (e.g. writes a log) but the language or structure is inconsistent.",
    ach: "Uses a suitable structure and language features for the purpose and audience (e.g. a precise, logical voice for Roz's log; persuasive language for a campaign poster).",
    wtSample: "Dear diary, today there was hail and Brightbill got hurt and then we found a hut and there was a skunk in it.",
    exemplar: "LOG ENTRY 58. Location: abandoned hut, mountain valley. Status: fully operational. Brightbill: bruised, resting. Observation: the resident skunk is friendly and only produces odour when nervous. Plan: shelter here until Brightbill has recovered, then resume travel north.",
    evidence: "Poster, comic, drama & journal projects; Week 10 campaign / anthology" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback to improve it.",
    kid: "I can plan my work, improve it, and use feedback to make it better.",
    ask: "Can you see a plan AND a change made because of feedback?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wt: "Plans and drafts with support; makes small changes when prompted.",
    ach: "Independently plans, drafts and revises, and uses feedback (e.g. Glow & Grow) to improve the work.",
    wtSample: "I finished my comic. My teacher said to add colour so I did.",
    exemplar: "My plan had three scenes: the bluff, the wolves backing off, and the wolves leaving. My group's “grow” said my stand-up moment was too quick, so I slowed it right down and added a whisper. Now the drama feels much more tense.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas.",
    expect: "Listens to and builds on others' ideas during group reading and projects, and takes turns fairly.",
    kid: "I can listen to my group, take turns, and build on other people's ideas.",
    ask: "Does the student respond to what others say, not just wait for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt or opt out.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) “I sort of disagree with Mia — I think Thud isn't dangerous, he just can't control his instincts, and he feels terrible every time.” She then asked the quieter group members what they thought.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas.",
    expect: "Makes inferences — works out what characters feel and why — using clues from the text, and thinks creatively about possibilities.",
    kid: "I can use clues in the story to work out things the author doesn't tell me.",
    ask: "Has the student worked something out AND pointed to the clue?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wt: "Makes an inference with prompting but struggles to explain the clue.",
    ach: "Independently infers feelings or motives and points to the clue in the text that shows it.",
    wtSample: "Roz is sad because she is stuck on the farm.",
    exemplar: "The book never says Roz feels trapped, but she keeps watching the hawk and says, “If I were a bird I could fly home myself. But I'm only a robot.” That tells me she wishes she was free like Brightbill and feels stuck.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility.",
    expect: "Contributes ideas in class discussions and projects, and takes responsibility for a role in group work.",
    kid: "I can share my ideas and do my part in group work.",
    ask: "Does the student offer ideas and take on a job without being asked?",
    na: "Rarely contributes to discussions or group projects.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ach: "Offers ideas without being asked, takes responsibility for a role, and encourages others.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 drama group, Tane volunteered to be director, made a scene list, and made sure everyone had a part. He shared two ideas in the reflection circle without being asked.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Courage, Compassion & Belonging", strand: "Values",
    curriculum: "Values: community and participation, respect, and care for others and the environment; courage and integrity.",
    expect: "Connects the book's values — courage, compassion (even towards those who have hurt you), loyalty and finding where you belong — to their own life and actions.",
    kid: "I can connect the book's message about courage, compassion and belonging to my own life.",
    ask: "Has the student linked a value from the book to something real in their own life?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wt: "Names a value (e.g. 'be kind') when asked, with a simple or general link.",
    ach: "Explains a value from the book and connects it to a real experience or action of their own.",
    wtSample: "The book teaches us to be brave and kind.",
    exemplar: "Roz showed compassion when she felt sorry for Shadow even though he'd been trying to hurt her. When I started at a new school, a girl I hardly knew sat with me at lunch. That was small but brave, and I did the same for a new kid this term.",
    evidence: "Go-away reflections, journal entries, Week 10 'My Long Way Home' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 3–4 English, Years 5–6, NZ Curriculum",
  lrv: [
    "Ideas: Show understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show understanding of how texts are shaped for different purposes and audiences.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies confidently to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics.",
    "Structure and Language: Show understanding of language features, using them appropriately.",
    "Processes and Strategies: Select and use processes and strategies to communicate confidently.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Courage, compassion (even for those who have hurt us), loyalty, belonging and finding where home is; being true to yourself.",
  crossCurricular: "Science — Living World (animal migration, seasons, wild and farmed ecosystems) and Technology (robotics, AI and automation, and how machines change human work), plus Social Sciences (how communities, farms and cities work) and Health & PE (coping with loss, change and big feelings).",
};

// Helpers to build data objects
function D(chapters, subtitle, leadIn, comp1, comp2, goAway, care) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway, care: care || "" };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }
function T(q, answer) { return { q: "True or False: " + q, answer, type: "tf" }; }

/* Journey waypoints — each week is a stop on Roz's long way home */
const JOURNEY = [
  { week: 1, place: "Hilltop Farm" },
  { week: 2, place: "The Oak Tree" },
  { week: 3, place: "The Storm Fields" },
  { week: 4, place: "The Old Barn" },
  { week: 5, place: "The Plan" },
  { week: 6, place: "The Mountains" },
  { week: 7, place: "The Bay" },
  { week: 8, place: "Center City" },
  { week: 9, place: "The Airship Home" },
  { week: 10, place: "The Island" },
];

const WEEKS = [
{
  num: 1, title: "Hilltop Farm", chapters: "Chapters 1–10",
  LI: "We are learning to infer what a character is thinking and feeling when they are hiding part of who they are.",
  SC: "I can use what a character says, does and doesn't say to explain what they are really thinking, and back it up with evidence from the text.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapters 1–3", "The delivery truck; the crate; Roz switches on",
      "Have you ever arrived somewhere brand new where nobody knew anything about you? What did you do or say in the first few minutes?",
      "Where does the delivery truck take the crate, and what does the narrator tell us is inside it?",
      "The narrator says Roz's \"new life was about to begin.\" What do you think she is feeling as she is switched on again, and what clues does the author give (or not give)?",
      "Write three sentences about the farm as Roz might describe it in her first report."),
    tue: D("Chapters 4–6", "The Shareef family; a tour of the farm; the monster in the barn",
      "How do you feel when someone tells you \"you belong to me\" or \"you're here to work\"? Is it different when it's a person, a pet, or a tool?",
      "How do Mr. Shareef, Jaya and Jad each treat Roz when they first meet her? Give one example for each.",
      "Roz says \"I understand\" many times to Mr. Shareef. Do you think she always agrees? What might she really be thinking?",
      "The cows call Roz \"the monster\" before she speaks. Write a short cow's-eye view of the moment she stomps in from the storm."),
    wed: D("Chapters 7–8", "Roz tells her story; Roz teaches herself to be a farmer",
      "Have you ever had to say only what people wanted to hear so you'd be safe or accepted? What was that like?",
      "What does Roz tell the cows about her time in the factory, and what does she say she hid from the Makers to pass the test?",
      "Roz says, \"In the wilderness I camouflaged my body to survive. At the robot factory, I camouflaged my personality.\" What does that sentence tell us about how she sees herself?",
      "Annabelle says she also misses her family. Write what you think she'd say to Roz in the quiet moments after the barn goes dark."),
    thu: D("Chapters 9–10", "Roz's first day; the farm routine and her double life",
      "What's one thing you do differently at home compared to at school, or with friends compared to with family?",
      "List some of the jobs Roz does on the farm, and describe how she feels about the work.",
      "Chapter 10 says Roz \"led a double life.\" What are the two lives, and what would happen if they crashed into each other?",
      "Write a diary entry as Roz at the end of her first week on Hilltop Farm. Include one thing she can say to the Shareefs and one she can only say to the cows.",
      "Chapter 5 mentions in passing that Mr. Shareef's wife has died. Some students may have lost someone; keep the discussion light and let students pass if they wish."),
  },
  projects: [
    P("poster", "Welcome to Hilltop Farm", "Design a farm map poster in the style of Mr. Shareef's tour — show the barns, fields, oak tree and hilltop, with small labels from Roz's point of view."),
    P("comic", "Two Roz's", "Create a 6-panel comic that shows Roz's double life: what the Shareefs see on one side, what the cows know on the other."),
    P("drama", "The Barn Meeting", "Act out Chapters 6–7: the cows are afraid of the \"monster\" until she speaks. Focus on tone of voice, pauses and body language."),
    P("journal", "Roz's Secret Log", "Write Roz's first private log entry, in her logical robot voice, about what she can and can't say on the farm and why."),
  ],
  quiz: [
    Q("What does the delivery truck leave at Hilltop Farm?", "A crate containing ROZZUM unit 7134 (Roz)."),
    T("Roz is already awake when the crate is opened.", "False — Mr. Shareef switches her on by pressing a button on the back of her head."),
    Q("Who is Oscar?", "The Shareefs' old dog."),
    Q("Why does Mr. Shareef say Roz is on the farm?", "Because he has a bad leg and can't do the farm work himself; the farm has been in his family for generations."),
    Q("Who are Jaya and Jad?", "Mr. Shareef's daughter and son."),
    Q("What does Mr. Shareef keep on his computer that lets him always know where Roz is?", "Her electronic signal (a map showing her location)."),
    Q("Why does he keep Roz's crate?", "In case he ever has to send her back to the factory."),
    Q("What do the cows first call Roz?", "\"The monster.\""),
    Q("Name two cows in the herd.", "Annabelle, Tess, Lily (any two)."),
    T("Roz tells the cows the truth about her past.", "True.", ),
    Q("What did Roz hide from the Makers during the factory test?", "That she adopted a gosling, could speak with animals, and had fought back against the RECOs."),
    Q("Vocabulary: What does \"camouflage\" mean?", "To hide by blending in with your surroundings (or by pretending to be something else)."),
    Q("What does Roz plan to do \"when the time comes\"?", "Try to escape from the farm."),
    Q("Who is Brightbill?", "Roz's adopted gosling — now her son — back on the island."),
    Q("How does Roz become a farmer overnight?", "She studies the computer Mr. Shareef gives her and stores all the farm information in her computer brain."),
    Q("What embarrassing thing happens to Roz on her first morning?", "She slips on a cow patty and falls flat on her back."),
    Q("Name two of the broken machines Roz repairs in Chapter 9.", "The Herder, the Field Machine, the Drone (any two)."),
    Q("What does Oscar say to Roz at the end of her first day?", "That she stinks like cow patties."),
    Q("Why does Roz have to live a \"double life\"?", "She can be herself with the animals, but must act like a normal robot around humans or risk being destroyed."),
    Q("Evidence-based: Find one moment in Chapters 1–10 where Roz says one thing but you think she means another. What clues tell you?", "Open-ended — e.g. \"I understand\" to Mr. Shareef while planning her escape; accept text-supported answers.", "open"),
  ],
},
{
  num: 2, title: "Homesick", chapters: "Chapters 11–20",
  LI: "We are learning to notice how an author uses structure, lists and pace to show how a character feels about being trapped.",
  SC: "I can explain how the way a chapter is written (short lines, lists, repeated phrases) helps show a character's feelings.",
  rubricTags: ["R2","R3","R10"],
  days: {
    mon: D("Chapters 11–13", "The late geese; a robot with homesickness; the electronic signal",
      "What does the word \"homesick\" feel like for you? Where do you feel it in your body?",
      "What promise does Wingtip make to Roz, and why can't Roz talk to the geese for long?",
      "Chapter 13 ends: \"She understood that she was being monitored constantly. She understood that she was trapped on Hilltop Farm.\" How does repeating \"she understood\" affect the reader?",
      "Write a short scene where Roz meets a flock of wild geese and asks about Brightbill's migration."),
    tue: D("Chapters 14–16", "The sad truth; the children; the robot's dream",
      "If you were stuck somewhere and needed help, how would you decide who you could ask?",
      "Why can't Roz find any information about escaping on the computer? Who does she need help from, and why is it difficult?",
      "Chapter 16 is a list of simple lines with no dialogue: \"The cows grazed. The wind rustled...\" and ends with \"A robot dreamed of escape.\" What effect do the short lines have on the reader, and why is the last line different?",
      "Write your own list chapter of 10 lines about a place you know well, ending with one line that shows a secret feeling."),
    wed: D("Chapters 17–18", "The birds; the amusing robot",
      "Is there an animal or object you sometimes wish you could be, just for a day? Why?",
      "What does Roz tell the cows she misses, and what does Tess suggest she do?",
      "Roz tells Jad and Jaya a story about a robot and a gosling — her own story. Why might she tell it as if it's about someone else?",
      "Rewrite the joke about the chicken and the road. Would Roz understand jokes? Write two lines of dialogue that show her trying."),
    thu: D("Chapters 19–20", "The storyteller; the wild animals arrive",
      "What's a story from your own family or life that you love to hear over and over again?",
      "What do Jaya and Jad tell Roz about their family, and how has the farm changed since their mother died?",
      "Roz \"let unused land go wild\" to bring back helpful animals. What does that choice say about what she wants?",
      "Write a paragraph from Mr. Shareef's point of view describing what he thinks Roz is doing when he sees the wild patches on his map.",
      "Jaya and Jad talk openly about losing their mother. Acknowledge the sadness gently, and remind students they can talk to you or another trusted adult privately."),
  },
  projects: [
    P("poster", "Homesick Map", "Draw a map with Hilltop Farm on one side and Roz's island on the other; add feelings, memories and the distance between them."),
    P("comic", "The Robot's Dream", "Create a comic that turns the Chapter 16 list into pictures — one line, one panel."),
    P("drama", "Storytime Under the Oak", "Perform Roz telling Jad and Jaya a story about a robot and a gosling. Show the kids' reactions and Roz's hidden feelings."),
    P("journal", "A List Chapter of My Own", "Write a Chapter-16-style list about your own home and finish with one line that reveals a secret feeling."),
  ],
  quiz: [
    Q("Who is Wingtip?", "The leader of a flock of late-migrating wild geese."),
    T("Wingtip promises to point Brightbill toward Roz if they ever meet him.", "True."),
    Q("Why does Roz stop talking to the geese?", "The children come along with their dog, and she can't be seen chatting with animals."),
    Q("How does Mr. Shareef know Roz left the farm in Chapter 13?", "Her electronic signal shows on his computer map."),
    Q("What does Mr. Shareef tell Roz never to do?", "Leave the farm without his permission."),
    Q("Why can't Roz find any information on escaping on the computer?", "It only gives her farm information, cutting her off from the outside world."),
    Q("What games do Jaya, Jad and Roz play in Chapter 15?", "Hide-and-seek."),
    Q("Where does Roz hide when it's her turn?", "Camouflaged in the pile of scrap and old farm machinery."),
    Q("Why does Roz hope the children will become her friends?", "Because she needs them — she hopes they might help her escape."),
    Q("What kind of chapter is Chapter 16, and how is it different from the others?", "A list chapter — short lines with no dialogue showing the farm's routine, ending with the robot dreaming of escape."),
    Q("Vocabulary: What does \"monitored\" mean?", "Watched or checked continually."),
    Q("Which bird does Roz watch, wishing she could fly?", "A hawk."),
    Q("What does Tess suggest Roz do about missing the island?", "Think of the farm as her home."),
    Q("What tree do the Shareef children love, and what is carved in it?", "The old oak tree with generations of family initials carved into the bark."),
    Q("What stunts do the children ask Roz to do under the oak tree?", "Backflip, juggle acorns, tell jokes."),
    Q("What story does Roz tell the children?", "A story about a robot and a gosling on an island."),
    Q("Why can't Roz tell the children the story is true?", "It's too risky — they might tell their father, and she could be sent back to the factory."),
    Q("Why did the farm start falling apart, according to the kids?", "Their mother died, their father was injured, and the machines began to break with no one to look after them."),
    Q("What does Roz do with unused land, and why?", "Lets it grow wild to bring back helpful animals like insects, snakes and rodents."),
    Q("Evidence-based: How does the author show Roz's homesickness without simply saying she is sad?", "Open-ended — e.g. watching the hawk, Chapter 16's list ending, telling the story of the gosling; accept text-supported answers.", "open"),
  ],
},
{
  num: 3, title: "Wolves and Whirlwinds", chapters: "Chapters 21–30",
  LI: "We are learning to explain how a character solves a problem by thinking instead of using force.",
  SC: "I can describe a character's choice, explain why it takes courage, and connect it to something bigger in the story.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapters 21–23", "The howl; the wolves attack; the rifle",
      "When is it braver to think first than to act fast?",
      "What happens when the wolves attack Annabelle, and how does Roz help?",
      "Mr. Shareef shouts at Roz to kill the wolves. Why can't she? How does she respond, and what does that show?",
      "Roz notices Shadow's scar and thinks about Oscar's fear of the gun. Write what you think her plan is.",
      "This day includes a wolf attack (an injured cow) and a rifle. Keep the tone calm, name the fear as a class, and make it clear Roz never uses the weapon."),
    tue: D("Chapters 24–25", "The bluff; the summer",
      "Have you ever pretended to be more confident than you felt? How did it turn out?",
      "Describe how Roz sets up her trap for the wolves and what she says to Shadow.",
      "The narrator tells us directly, \"Roz was bluffing.\" Why do you think the author reveals this to the reader?",
      "Write the wolf pack's conversation as they run home after Roz's bluff. Who is scared and who is angry?"),
    wed: D("Chapters 26–27", "The tornado; the broken robot",
      "Has anything ever swept you away — a feeling, a wave, a crowd — so fast you couldn't stop it?",
      "What does Roz do when she sees the tornado, and what happens to her?",
      "When Jad hugs Roz and says sorry, what does that reveal about how the children feel about her now?",
      "Write about the tornado from Jad's point of view, focusing on what he sees, hears and feels.",
      "The tornado may be frightening for students who have experienced severe weather or emergencies. Offer a quiet option and end with the family's safety."),
    thu: D("Chapters 28–30", "The TechLab shop; the aftermath; the gift",
      "What's the best gift you've ever given or received? What made it special?",
      "Who repairs Roz, and how does he do it? What does Mr. Shareef choose not to pay for?",
      "Why doesn't Roz escape when the tornado knocks out the farm's power?",
      "Draw or describe the tool belt the children give Roz, and write a thank-you note from Roz that she would say out loud, and one she would only think."),
  },
  projects: [
    P("poster", "Wolf Warning", "Make a poster that explains the wolf problem on Hilltop Farm and Roz's plan, showing why her bluff worked."),
    P("comic", "The Bluff", "Create a comic of Chapter 24: Roz disguised as grass, the call of the wounded calf, the wolves' arrival and the gun."),
    P("drama", "Wolf Meeting", "Act out Shadow's pack deciding what to do after Roz's bluff. Show who wants to attack and who is more careful."),
    P("journal", "Storm Report", "Write Roz's official log after the tornado: damage, injuries, what she saved and what she chose not to do."),
  ],
  quiz: [
    Q("How many wolves attack the herd in Chapter 22?", "Seven."),
    Q("What is the name of the wolf leader, and how can you recognise him?", "Shadow — he has dark fur and a long pale scar down his side."),
    Q("Which cow do the wolves attack?", "Annabelle."),
    T("Roz is programmed to be violent.", "False — she isn't programmed for violence."),
    Q("What does Mr. Shareef order Roz to do about the wolves?", "Kill them."),
    Q("Why does Oscar hide when he sees the rifle?", "He has seen it used before and is terrified of it."),
    Q("What idea does Roz get when she sees Oscar and remembers Shadow's scar?", "Shadow knows what a gun can do, so she can scare him with one."),
    Q("How does Roz hide herself in Chapter 24?", "Covers her body in mud and grass and camouflages herself as a clump of grass."),
    Q("How does Roz lure the wolves out?", "Imitating the cries of an injured calf."),
    Q("Name two other wolves in Shadow's pack.", "Barb, Slash, Lurk, Fang (any two)."),
    T("Roz really could have fired the rifle.", "False — she was bluffing."),
    Q("Vocabulary: What does \"bluff\" mean?", "To pretend to have power or a plan you don't actually have."),
    Q("What do the wolves do after Roz's bluff?", "They run away; the pack disappears into the night."),
    Q("What season does the story move to in Chapter 25?", "Summer."),
    Q("Why hasn't Roz told the children the truth yet?", "It's still too risky."),
    Q("What does Roz do when the tornado appears?", "She runs from the hay field to help the Shareefs reach the storm shelter."),
    Q("Who does Roz rescue from the tornado, and what happens to her?", "Jad; she is swept up into the tornado and knocked out by a shovel."),
    Q("Where does the family find the broken Roz?", "In a ditch by the road."),
    Q("Who repairs Roz in the TechLab shop, and what is his name?", "A robot named Patch."),
    Q("Evidence-based: Roz is described as not being programmed for violence. Find one way she solves a problem by thinking, not force, and explain why it takes courage.", "Open-ended — the bluff, camouflage and calf-call are strong answers; accept text-supported responses.", "open"),
  ],
},
{
  num: 4, title: "The Old Barn", chapters: "Chapters 31–40",
  LI: "We are learning to explain how a secret being shared changes the way characters trust each other.",
  SC: "I can describe how a character's relationships change after a secret is revealed and use evidence from the text to show why.",
  rubricTags: ["R3","R7","R10"],
  days: {
    mon: D("Chapters 31–33", "The campfire; the old barn and Cyrus's notebook; autumn",
      "What is a family story or tradition that you'd like to pass on one day? Who told it to you?",
      "What does Mr. Shareef tell Roz around the campfire about his family and Jamilla, and what does Roz do with her questions?",
      "Why does Roz keep her questions to herself instead of asking Mr. Shareef more about his wife? What does that show about her double life?",
      "Imagine you are Cyrus Shareef writing in your notebook. Write a short entry about your dreams for the farm's future.",
      "Chapter 31 briefly mentions the death of Jamilla, Jaya and Jad's mother. Keep the focus on Mr. Shareef's memories and on how Roz listens, and let students step back if they want."),
    tue: D("Chapters 34–36", "The joyful geese; memories; the special flock",
      "Have you ever heard a rumour about yourself that turned out to be true? How did it spread?",
      "How do the passing geese learn about Roz, and what news do they bring or not bring about Brightbill?",
      "In Chapter 35 Roz thinks about deleting her memories. What do you think stops her from doing it?",
      "Write the moment Brightbill enters the barn from the point of view of one of the cows."),
    wed: D("Chapters 37–38", "The reunion; the truth",
      "How would you feel if someone you thought you might never see again suddenly walked into the room?",
      "How did Brightbill find Roz, and who else arrives with him?",
      "Jaya and Jad work out Roz's secret. What clues from the last four chapters helped them?",
      "Write the conversation Jaya and Jad have in their bedroom that night after learning the truth."),
    thu: D("Chapters 39–40", "The allies; instincts",
      "Who is one person you trust with your biggest secrets? What makes them trustworthy?",
      "What promise do Jaya and Jad make to Roz, and what problem do they say they will solve?",
      "Roz asks, \"Is being different the same as being defective?\" How do Jaya and Jad answer, and do you agree with them?",
      "Roz and Brightbill say goodbye again as the geese head south. Write a short poem or a letter from Roz to Brightbill that she can't give him yet."),
  },
  projects: [
    P("poster", "Family Tree, Farm Tree", "Design a tree poster that shows the Shareef family line back to Cyrus and adds Roz and Brightbill as the \"found\" branches of the family."),
    P("comic", "The Reunion", "Create a 6-panel comic showing the moment Brightbill lands in the barn, the cows' reactions, Roz's reaction and the children watching from the doorway."),
    P("drama", "The Truth Comes Out", "Perform Chapter 38 — Jaya and Jad learn the truth. Practise how Roz's voice and posture change when she stops hiding."),
    P("journal", "My Secret Is Safe", "Write a letter from Jaya or Jad to a friend about the promise they made to Roz and how it feels to keep it."),
  ],
  quiz: [
    Q("What does Roz use to light the Shareefs' campfire, and how does that compare with her time on the island?", "A lighter; on the island she struck stones together to make sparks."),
    Q("What does Jaya point out in the night sky at the campfire?", "The space station."),
    Q("What does Mr. Shareef tell Roz about Jamilla?", "That she helped run the farm's business and that one of the machines they bought led to her death."),
    Q("What is found in the old barn's chest that Roz keeps?", "Cyrus Shareef's notebook."),
    Q("Who was Cyrus Shareef?", "An ancestor of the Shareef family who built the farm."),
    Q("Why are the passing geese so happy to meet Roz?", "They have heard rumours of a robot who speaks the animals' language and has a goose for a son."),
    Q("Vocabulary: What does \"migration\" mean?", "A regular seasonal journey by animals from one region to another."),
    Q("In Chapter 35, what choice does Roz think about making about her memories?", "Erasing them so the pain of missing home would go away."),
    Q("Why doesn't she do it?", "Without her memories she wouldn't know who she is; she wants to remember her old life."),
    Q("What is unusual about the flock that arrives in Chapter 36?", "It's flying north, not south, and led by a young goose — Brightbill."),
    Q("How did Brightbill find his mother?", "The story of Roz spread from flock to flock until it reached him."),
    Q("Who is Loudwing?", "The old goose who came along with Brightbill."),
    T("Jaya and Jad already knew Roz's secret before Chapter 37.", "False — they figure it out when they see Roz with Brightbill and talking in animal language."),
    Q("What promise do Jaya and Jad make to Roz?", "To keep her secret and to help her escape."),
    Q("What does Roz ask Jaya when she wonders if she is defective?", "\"Is being different the same as being defective?\""),
    Q("What does Jaya reply?", "That she doesn't think so — or maybe we're all a little defective."),
    Q("What does Jad say they need to do to help Roz?", "Research a way for her to escape safely."),
    Q("Why can't Roz simply run away from the farm?", "Mr. Shareef can track her signal; he would think she was malfunctioning and have her destroyed."),
    Q("What signals in Chapter 40 tell the geese it is time to leave?", "Snow on the ground — they follow their instinct to migrate."),
    Q("Evidence-based: Which of Roz's relationships changes most in this section and why?", "Open-ended — Roz with the children (trust) is likely; accept text-supported answers.", "open"),
  ],
},
{
  num: 5, title: "The Plan", chapters: "Chapters 41–50",
  LI: "We are learning to explain how a character feels two opposite things at once and why that makes their choices hard.",
  SC: "I can find evidence that a character has mixed feelings and explain how those feelings shape what they do.",
  rubricTags: ["R1","R7","R9"],
  days: {
    mon: D("Chapters 41–42", "Winter; the plan",
      "When you have a big goal, what do you have to prepare before you can start?",
      "How does Roz spend her winter, and what secret research do Jaya and Jad do?",
      "Why do you think Roz works so hard to leave the farm in perfect shape when she is planning to escape?",
      "Write out Jaya and Jad's plan as a numbered list in the style of a robot instruction manual."),
    tue: D("Chapters 43–45", "The operation; the patient robot; conversations in the barn",
      "What's the hardest thing you've ever tried to fix? Who helped you?",
      "What goes wrong with the children's operation on Roz, and how do they finally fix it?",
      "Roz says she feels guilty for asking so much of the kids. Why does she feel that way, and what do the cows say to comfort her?",
      "Write a scene from the cows' point of view in which they discuss what the barn will be like when Roz is gone."),
    wed: D("Chapters 46–47", "Spring; the dinner",
      "When has someone invited you to join something that made you feel valued?",
      "What does the Shareef family do to include Roz at dinner?",
      "Roz asks herself questions about the chicken. Why does the author put these questions in the book, and what does Roz decide?",
      "Describe the dinner from Oscar's point of view."),
    thu: D("Chapters 48–50", "The return; the goodbye; the free robot",
      "Have you ever had to say goodbye to a place or a person you really cared about? What helped?",
      "Who does Roz say goodbye to, and what does she leave behind with Annabelle?",
      "In Chapter 49 Roz \"shuddered back and forth\" and doesn't leave until Jaya and Jad say, \"We order you to run away.\" What is she feeling, and why does she need that order?",
      "Write the note that Jaya and Jad leave (or don't leave) for their father the next morning.",
      "Chapters 45 and 47 include a mention of harsh conditions on other farms and a chicken dinner. Encourage respectful discussion, since students may hold varied views on eating animals."),
  },
  projects: [
    P("poster", "Escape Blueprint", "Draw a blueprint poster of Roz's body showing the transmitter, the tool belt and the tools the kids found, labelled like an engineer's diagram."),
    P("comic", "The Operation", "Create a comic of the operation: switch-off, wrong parts, argument, lantern idea and success."),
    P("drama", "Goodbye at the Far Field", "Act out the final farewell in Chapter 49. Use pauses and body language to show what each character is not saying."),
    P("journal", "Torn in Two", "Write two diary entries from Roz on the same night: one listing every reason to go, and one listing every reason to stay."),
  ],
  quiz: [
    Q("What does Roz do during the winter to prepare the farm?", "Maintains machines, makes compost, plans crops and checks on the herd, making lists for supplies."),
    Q("What do Jaya and Jad secretly study after homework?", "The design, construction and maintenance of ROZZUM robots."),
    Q("What is the transmitter?", "The device that broadcasts Roz's electronic signal."),
    Q("Where do they decide to do the operation, and why?", "In the old barn, because it's quiet and hidden."),
    Q("When do they perform it?", "At night, when Mr. Shareef is asleep."),
    Q("What goes wrong during the operation?", "They remove the wrong parts, argue, and put Roz back together wrongly — she can't speak, then can't move."),
    Q("What idea helps Jaya find the correct parts?", "She uses a lantern to see numbers engraved on Roz's internal parts."),
    Q("What do the children tell Roz to do with the transmitter until she leaves?", "Keep it with her, since it still works."),
    Q("Why does Roz wait until spring?", "She needs Brightbill to guide her home."),
    Q("Vocabulary: What does \"patient\" mean in the chapter title \"The Patient Robot\"?", "Able to wait calmly without getting upset."),
    Q("What do the calves ask Roz about in the barn?", "Why humans need so much cow's milk, and what desserts are."),
    Q("Why can't Roz describe desserts well?", "Because she can't eat, so she doesn't know their taste."),
    Q("How do the cows react when Roz says she will leave?", "They say they understand and don't want her to feel guilty."),
    Q("What does Mr. Shareef do when he trips carrying groceries?", "Roz helps him up and into the house."),
    Q("What does the family invite Roz to do in Chapter 47?", "Join them at dinner."),
    Q("What does Mr. Shareef play after dinner?", "A violin that belonged to Cyrus Shareef."),
    Q("What does Roz give the family?", "Cyrus Shareef's notebook."),
    Q("What does Roz leave with Annabelle?", "Her transmitter, tucked under Annabelle's collar."),
    Q("What sign will tell the children that Roz reached home?", "A goose visiting the farm and giving them a feather."),
    Q("Why does Roz finally leave when the kids give her a command?", "Because she needs an order to overcome her programming and her guilt."),
  ],
},
{
  num: 6, title: "Into the Mountains", chapters: "Chapters 51–60",
  LI: "We are learning to explain how an author uses setting and weather to build tension and shape what characters do.",
  SC: "I can find details of setting and weather that create a mood, and explain how they affect the characters' choices.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapters 51–53", "The airship; the scout; the farmland",
      "If you had to travel a long way without being seen, what tricks would you use?",
      "What does Roz do when the airship returns and there is nowhere to hide in the open wheat field?",
      "The airship doesn't find Roz even though it flies right over her. Why not? (Think about who she left behind and what she left with them.)",
      "Write one paragraph that Brightbill might tell his flock about scouting ahead for his mother."),
    tue: D("Chapters 54–56", "The mountains; the attack; the torch",
      "Do you think fear can ever be useful? When?",
      "Why does Shadow hunt Roz this time, and how does she escape the wolves in the mountain meadow?",
      "Barb says she is tired of chasing a target that can't be eaten, but she stays loyal to Shadow. What does that show about her?",
      "Roz uses fire, something the wolves have never seen. Describe the scene from Barb's point of view when she wakes up."),
    wed: D("Chapters 57–58", "The hail; the hut and Sprinkles",
      "Have you ever been caught in extreme weather? What did you do to stay safe?",
      "How does Roz protect Brightbill in the hailstorm, and where do they shelter?",
      "Sprinkles says, \"Misunderstood creatures like us have to take care of each other.\" What does she mean, and who else in the book shows the same idea?",
      "Write a thank-you note from Roz to Sprinkles for her hospitality."),
    thu: D("Chapters 59–60", "The strange wilderness; the hunters",
      "How can a place be both wild and full of things left behind by people?",
      "What does Roz and Brightbill's route through the old mining area show about how humans and robots have changed the land?",
      "Roz tells Brightbill, \"I should have stepped in sooner.\" Why does she feel responsible, and do you think she should?",
      "Write the two hunters' conversation as they run away, describing what they think they saw.",
      "Chapters 57 and 60 include hail that hurts birds and hunters aiming a gun at Brightbill. Keep discussion calm and focus on how Roz protects him without harming anyone."),
  },
  projects: [
    P("poster", "Weather Watch: The Mountain Hailstorm", "Create a poster that explains how hail forms and shows the danger it poses to small animals, with a labelled diagram from Brightbill's point of view."),
    P("comic", "Roz and the Torch", "Tell Chapter 56 in a comic: sleeping wolves, Roz's idea, the flame, and the wolves fleeing. Use sound effects and expressions."),
    P("drama", "Sprinkles' Cabin", "Perform the scene in the hut where Roz meets Sprinkles. Show how Sprinkles' welcome changes Roz's mood."),
    P("journal", "Camouflage Field Notes", "Write field notes describing five different camouflages Roz uses in Chapters 51–60 and why each works."),
  ],
  quiz: [
    Q("Where does the airship first appear in Chapter 51?", "Above the wheat fields while Roz and Brightbill are travelling north."),
    Q("Why doesn't the airship find Roz?", "She camouflages herself, and she has no electronic signal because she left her transmitter with Annabelle."),
    Q("What camouflage does Roz use in the wheat field?", "She turns herself into a wheat stalk / stands like a wheat stalk."),
    Q("How does Brightbill help on the journey?", "He scouts ahead from the air and reports the safe route."),
    Q("What are some kinds of farms Roz notices in Chapter 53?", "Crop fields, greenhouses, open pastures, tiny pens, and labs that make meat/milk without animals."),
    Q("What question does Roz ask about the other robots she sees?", "Whether any of them dream of escape or if they're all content."),
    Q("What does Roz do each night in the mountains to keep Brightbill warm?", "Builds small campfires with her lighter."),
    Q("Who attacks them in the mountain meadow?", "Shadow and Barb."),
    Q("What does Shadow say he wants?", "Revenge, not food."),
    Q("How does Roz escape their first attack?", "She leaps in long arcs across the meadow and climbs a tree."),
    Q("What does Roz use to scare the sleeping wolves?", "A burning branch (a torch)."),
    Q("Vocabulary: What does \"instinct\" mean?", "A natural, automatic way of behaving that animals are born with."),
    Q("What kind of weather nearly kills Brightbill in Chapter 57?", "A hailstorm."),
    Q("Where do they shelter?", "An old hut beside a river."),
    Q("Who lives under the hut floor?", "Sprinkles, a skunk."),
    T("Sprinkles smells whenever she is happy.", "False — she only smells when she is nervous."),
    Q("What did Sprinkles say about \"misunderstood creatures\"?", "That they should take care of one another."),
    Q("What does Roz see in the abandoned mining valley?", "Rusting equipment, ruins, abandoned tracks, plus robot crews digging tunnels and dismantling old buildings."),
    Q("What do the hunters Hank and Miguel want to do to Brightbill?", "Shoot him for dinner."),
    Q("Evidence-based: Choose one place from Chapters 51–60 and explain how the author uses weather or setting to make you feel tense or safe.", "Open-ended — hail, wheat field, meadow at dusk, etc.; accept text-supported answers.", "open"),
  ],
},
{
  num: 7, title: "Across the Bay", chapters: "Chapters 61–70",
  LI: "We are learning to compare how different characters deal with the same feeling and explain what that shows about them.",
  SC: "I can compare two characters' reactions to fear, loss or instinct, using evidence from the text.",
  rubricTags: ["R1","R3","R10"],
  days: {
    mon: D("Chapters 61–62", "Thud the ram; the confrontation",
      "Have you ever done something you regretted because you couldn't control a strong feeling?",
      "How does Roz respond each time Thud lashes out, and what does that show about her?",
      "Shadow blames Roz for losing his pack and his mate. How does Roz feel about that, even though he is chasing her?",
      "Write a short scene where Thud explains to the sheep why he says sorry so often."),
    tue: D("Chapters 63–65", "The rowboat; the sea creature; the whale",
      "What are you most afraid of? How do you act when you meet it?",
      "What happens to Roz and the rowboat in Chapter 63, and how does Brightbill react?",
      "How did the whale Coral know who Roz and Brightbill were, and what does that tell you about the power of stories?",
      "Write a diary entry from Brightbill about the moment Roz sank and the moment he saw the whale.",
      "Chapters 63–65 include a near-drowning and a moment where Brightbill believes Roz is lost. Reassure students that Roz survives, and check in on anyone who is uncomfortable around water."),
    wed: D("Chapters 66–68", "The new land; the city; the station",
      "Have you ever had to hide something about yourself in order to fit in? How did that feel?",
      "How does Roz try to blend into the city, and what goes wrong with the dogs?",
      "In Chapter 68 the robots must ride in the windowless final car. What does the author want us to notice about how robots are treated?",
      "Write the moment Roz steps on the train and the doors close, first from her point of view and then from Brightbill's."),
    thu: D("Chapters 69–70", "The train; the march through the city",
      "What is it like to be separated from someone you love? What helps you get through?",
      "How does Roz cope inside the dark train car, and what does she tell herself about Brightbill?",
      "In Chapter 70, Roz sees robots doing nearly every kind of work in the city. What does she notice about how the city runs, and what questions does it raise?",
      "Describe Center City as if you were arriving for the first time. Use at least three senses."),
  },
  projects: [
    P("poster", "Coral's Story Web", "Create a web diagram showing how the story of Roz and Brightbill travelled: geese, shore birds, fish, dolphins, Coral."),
    P("comic", "The Rowboat", "Draw Chapters 62–65 as a comic: the chase, the boat, the wave, the sinking and the whale."),
    P("drama", "Thud's Apology", "Perform Thud and Roz's conversation, showing how each of them feels."),
    P("journal", "Two Fears", "Write a diary entry from Roz about her fear of deep water and one from Shadow about being alone. Compare what they fear and how they respond."),
  ],
  quiz: [
    Q("What does Thud do the first time he meets Roz?", "He rams into her, knocking her over."),
    Q("How does Thud feel afterwards?", "Terrible — he cries and apologises, saying he can't always control his instincts."),
    Q("How does Thud help Roz and Brightbill?", "He guides them out of the mountains along a safe path."),
    Q("What does Thud do at the end of Chapter 61 when his crazed look returns?", "He controls himself this time and says goodbye instead of attacking."),
    Q("Where do Roz and Brightbill hear a wolf's howl in Chapter 62?", "In the fog near the ocean, heading for a coastal village."),
    Q("What does Roz lose to Shadow in the struggle?", "Her tool belt."),
    Q("Why does Shadow say he is now alone?", "His pack and his mate abandoned him."),
    Q("What is Roz's biggest fear?", "Deep water."),
    Q("What do they use to escape Shadow?", "An old rowboat."),
    Q("Why does the rowboat break?", "Roz rows too hard and the oars snap, then a big wave smashes it."),
    Q("What rescues Roz from the sea?", "A whale."),
    Q("What is the whale's name?", "Coral."),
    Q("How did Coral know about them?", "Stories about them had spread from birds to fish and dolphins."),
    Q("What does Brightbill do to wake Roz on the whale?", "He presses the button behind her head."),
    Q("What does Roz worry about at the end of Chapter 65?", "That she will have to cross an entire ocean to reach the island."),
    Q("Who is Pookie?", "A small dog who barks at Roz disguised as weeds."),
    Q("How does Roz disguise herself the next day in the city?", "She cleans off all her camouflage and walks like an ordinary robot."),
    Q("Where must robots ride on the train?", "In the windowless last car."),
    Q("Who is Brightbill's pigeon friend in the city?", "Graybeak."),
    Q("Evidence-based: Compare how Thud and Roz deal with their instincts and how each treats others because of them.", "Open-ended — Thud apologises but still lashes out; Roz overcomes fear/aggression to help others; accept text-supported answers.", "open"),
  ],
},
{
  num: 8, title: "Center City", chapters: "Chapters 71–78",
  LI: "We are learning to explain how an author builds suspense through short sentences, lists, pacing and cliffhangers.",
  SC: "I can point to specific words, sentences and chapter endings that create suspense and explain how each one makes me feel.",
  rubricTags: ["R2","R5","R9"],
  days: {
    mon: D("Chapters 71–72", "The sightings; the police",
      "Have you ever tried to look calm on the outside while feeling frightened inside? What did you do?",
      "Chapter 71 is a list of city scenes ending with \"A wild robot observed it all.\" What does that last line add?",
      "The police robots keep saying \"Have a nice day!\" while their eyes rest on Roz for one, two, three seconds. Why is this tense even though nothing happens?",
      "Write your own 10-line list chapter about a busy place, ending with a line that shows a secret watcher."),
    tue: D("Chapters 73–74", "The pigeons; the sky",
      "Who do you think helps you in ways you may not notice?",
      "What do the pigeons tell Roz about Graybeak, and what do they promise to do?",
      "Roz waits all night for Brightbill and Strutter. How does the author use time passing and the park keeper's footsteps to build worry?",
      "Write a short scene from the park keeper's point of view."),
    wed: D("Chapters 75–76", "The RECOs; the morning",
      "What would you do if you were caught in a crowd that suddenly turned against you?",
      "What do the RECOs say when they first meet Roz, and how does she respond?",
      "In Chapter 76 a woman shouts, \"Something's wrong with her!\" and the crowd stares. Why does the crowd turn on Roz so quickly? What does that say about how people treat what is different?",
      "Write the same street scene from the young woman's point of view."),
    thu: D("Chapters 77–78", "The underground; the chase",
      "Which is scarier for you: a big danger you can see, or a danger you can't see? Why?",
      "Who leads Roz underground, and what does Roz see in the tunnels?",
      "Chapter 78 ends with the word \"down\" repeated and then \"Everything went black.\" How do the repeated words and the ending make you feel? What do you want to happen next?",
      "Write a single-paragraph cliffhanger for your own chapter, using repeated words or lines to build tension.",
      "Chapter 78 includes a chase, a battle between pigeons and airships, and Roz being shot and falling from a rooftop. Some students may find it upsetting. Prepare for the cliffhanger with a calm read, and use the Friday discussion to talk about predictions and feelings."),
  },
  projects: [
    P("poster", "Pigeon Network Map", "Draw a map of Center City showing where Roz travels, where the pigeons help, and the route into the sewers."),
    P("comic", "The Rooftop Chase", "Tell Chapter 78 in a comic, using different panel sizes to show speed and slow-motion moments."),
    P("drama", "Have a Nice Day", "Perform the police scene using the repeated line \"Have a nice day!\" to build suspense with tone of voice, pauses and eye contact."),
    P("journal", "Cliffhanger Craft", "Write your own cliffhanger paragraph and annotate three techniques you used (repetition, short sentences, sound words, pacing)."),
  ],
  quiz: [
    Q("What is unusual about Chapter 71's structure?", "It is a list of short lines describing the city, ending with the wild robot watching."),
    Q("What do the police robots say to every passer-by?", "\"Have a nice day!\""),
    Q("Why does Roz worry about the police?", "They might be working with the RECOs or notice her unit number."),
    Q("What do the pigeons think when Roz speaks to them?", "They are shocked, but curious."),
    Q("What is the name of the curious pigeon?", "Strutter."),
    Q("What happened to Graybeak?", "She died."),
    Q("What do the pigeons promise to do for Roz?", "To search the city for Brightbill."),
    Q("Who does Strutter warn Roz to avoid?", "The park keeper robot."),
    Q("What appears in the sky in Chapter 74?", "A white triangular airship."),
    Q("Who are RECO 4, 5 and 6?", "The robots sent to retrieve Roz."),
    Q("What do the RECOs say when they meet Roz?", "\"Hello, ROZZUM unit 7134. We are the RECOs. Please come with us.\""),
    Q("What does Roz do?", "Runs into the woods, camouflaged."),
    Q("How do the RECOs try to find her?", "By scanning for her electronic signal — which she doesn't have."),
    Q("Why does Roz join a work crew in Chapter 76?", "To blend in with other robots."),
    Q("What does the crowd say when Roz bumps into a woman?", "That she is a defective robot."),
    Q("Who tells Roz to lift the manhole cover?", "Strutter."),
    Q("Who guides Roz underground?", "A rat."),
    Q("What do the RECOs in Chapter 78 want to do?", "Capture Roz if possible without harming her."),
    Q("What do the pigeons do?", "They swarm the airships and attack them."),
    Q("Evidence-based: Choose one chapter from this week and explain how the author builds suspense with sentence length, repetition or chapter endings.", "Open-ended — Chapter 78's repeated \"down\", or the list in Chapter 71; accept text-supported answers.", "open"),
  ],
},
{
  num: 9, title: "The Airship Home", chapters: "Chapters 79–90 & Epilogue",
  LI: "We are learning to identify a book's big themes and explain how the ending brings them together.",
  SC: "I can explain a theme of the whole story and support it with evidence from the beginning, middle and end.",
  rubricTags: ["R1","R4","R10"],
  days: {
    mon: D("Chapters 79–80", "The Designer; the beautiful glitch",
      "If you could ask the person who made you one question, what would it be?",
      "Who is Dr. Molovo, and what does she say her job is?",
      "Roz says, \"If I am defective, then what a beautiful glitch.\" What does she mean, and how does Dr. Molovo respond?",
      "Write three questions Roz asked Dr. Molovo, and the answers you think a maker might give."),
    tue: D("Chapters 81–83", "The meltdown; the secret; the new robot",
      "What does it take to be brave enough to break a rule for someone else?",
      "What do the people of the city see on their screens in Chapter 81, and what is Dr. Molovo's secret?",
      "Roz asks, \"If I am not ROZZUM unit 7134, then who am I?\" How does she answer, and what makes that answer important?",
      "Write a paragraph from Dr. Molovo's point of view explaining why she takes such a risk.",
      "Chapter 81 shows a video of Roz apparently being destroyed. Students may be upset until the twist in Chapter 82; consider previewing that Roz is alive, or pausing briefly between the two chapters."),
    wed: D("Chapters 84–86", "The new mother; the guests; the airship",
      "How do you prove who you are to someone who doesn't recognise you?",
      "How does Brightbill test whether the new robot is really his mother?",
      "Why does Brightbill only believe her after she says, \"You were less than zero\"? What does that answer show?",
      "Describe the view from the airship as Roz sees it, using three details from earlier in the book that she sees again."),
    thu: D("Chapters 87–90 & Epilogue", "The homecoming; the farewell; the island; the feather",
      "What does \"home\" mean to you, and how would you feel if you had to go back after a long time away?",
      "What is bittersweet about Roz's homecoming, and how do the animals recognise her?",
      "Dr. Molovo says, \"You're the wild robot. Go ahead and be wild.\" Why do the animals bow to her? What is the book's final message?",
      "Write the note Jaya and Jad might write in response to the feather in the Epilogue.",
      "Chapter 87 mentions animals that Roz lost while she was away. Keep the discussion gentle: home changes, and this is part of the story's bittersweet truth."),
  },
  projects: [
    P("poster", "Beautiful Glitch", "Design a poster celebrating being different: use Roz's line \"what a beautiful glitch\" as the centre of a design with a quote, an image and three reasons different is powerful."),
    P("comic", "Home at Last", "Create a comic of Chapters 87–90: the homecoming, the animals gathering, the farewell, the sunset."),
    P("drama", "The New Mother Test", "Perform Brightbill's testing of the new Roz. Practise the moment he decides to trust her."),
    P("journal", "Where Do I Belong?", "Write a personal reflection about a place or group where you feel truly yourself, and compare it with Roz's island."),
  ],
  quiz: [
    Q("Where does Roz wake up in Chapter 79?", "In TechLab's robot factory, as a robot head, with her body wrecked."),
    Q("Who is Dr. Molovo?", "The founder of TechLab Industries and the designer of the ROZZUM robots."),
    Q("What does Dr. Molovo want to know?", "How Roz became the way she is."),
    Q("What does Roz say her purpose could be?", "To help others."),
    Q("What does Roz call the way she is?", "A beautiful glitch."),
    Q("What does Dr. Molovo say she must do when they have finished talking?", "Destroy Roz, so that people feel safe."),
    Q("What does the city see in Chapter 81?", "A video showing the defective robot being melted."),
    Q("What is Dr. Molovo's secret?", "She moved Roz's mind into a new robot body before destroying the old one."),
    Q("What does the new Roz not have that the old one did?", "A button on her head and a unit number."),
    Q("What does Roz say when she looks in the mirror?", "\"I'm Roz.\""),
    Q("How did Brightbill find the factory?", "He followed the airship that carried Roz's broken body."),
    Q("Why doesn't Brightbill recognise Roz at first?", "She has a new body."),
    Q("What is the name of Roz and Brightbill's home on the island?", "The Nest."),
    Q("Who is Brightbill's best friend?", "Chitchat, the squirrel."),
    Q("What does Roz say about Brightbill's age when she adopted him?", "That he was zero — actually less than zero, since he was still in his egg."),
    Q("What does Dr. Molovo do to help Roz get home?", "Flies Roz and Brightbill to the island in her airship."),
    Q("How do the island animals recognise Roz?", "By her voice and by seeing her muddy, wild appearance; Brightbill vouches for her."),
    Q("What is bittersweet about her homecoming?", "Some of her friends have died while she was away."),
    Q("What do the animals do to honour Dr. Molovo?", "They bow their heads."),
    Q("What does the goose give Jaya and Jad in the Epilogue?", "A feather — the sign that Roz made it home."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "Home Is Where You're Loved Campaign", desc: "Create a campaign (posters, slogans, a short speech) celebrating the idea that we belong where we are loved and can be ourselves, using Roz, Brightbill and the animals of the island as the model." },
    { title: "Extended Drama/Performance", desc: "Imagine what happens next — Jaya and Jad meeting the new farm robot, Dr. Molovo alone in her apartment, or Shadow's journey after the bay — told with empathy rather than as simple \"villains.\"" },
    { title: "Character Case File — Roz", desc: "An in-depth profile (poster + written report + panels) tracking Roz's journey across the whole book: farm, mountains, bay, city and home, with evidence from each stage." },
    { title: "\"Our Journey Home\" Class Anthology", desc: "Each student contributes one illustrated page titled \"Our Journey Home,\" a real story about a time they felt out of place, found their people or returned somewhere meaningful, echoing Roz's own journey." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: \"Where does the wild robot truly belong?\" (the author's own question) and share the one big idea students will carry forward from this book. Certificates presented. Optional: share favourite moments from the term.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events.",
      wt: "Explains some of Roz's motivations or relationships, with limited evidence.",
      a: "Explains a theme (belonging, courage, identity) and supports it with clear evidence from the book.",
      example: "A Character Case File showing Roz changing from a hidden robot on the farm to the wild robot who returns home, with an event from the beginning, middle and end of the book." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A belonging campaign poster with a catchy slogan, three persuasive reasons and a picture that matches the message." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A drama that adds a new scene from Shadow's point of view, rehearsed and improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
