/* ============================================================
   REFUGEE (Alan Gratz) — BOOK STUDY APP DATA
   Content data only. No markup/behaviour lives in this file.
   Years 7–8 · NZ Curriculum Level 4 English
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Courage, Empathy & Belonging", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 4 (Years 7–8).
   "Achieved" = the curriculum expectation has been met.
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas that run across all three storylines (displacement, courage, found family, what a country owes a refugee) and supports them with events from more than one of the three narratives.",
    kid: "I can explain a big idea that connects Josef's, Isabel's and Mahmoud's stories, and back it up with events from at least two of them.",
    ask: "Does the student compare across storylines, not just retell one of them?",
    na: "Retells events from a single storyline but cannot yet connect it to the others.",
    wt: "Names a shared idea (e.g. 'they all have to leave home') with a general reason, but the comparison is thin or one-sided.",
    ach: "Explains an idea that runs across at least two of the three storylines and supports it with a specific, accurate event from each.",
    wtSample: "All three of them have to run away from their countries because it's dangerous.",
    exemplar: "All three families are pushed out by decisions grown-ups made, not anything the kids did. Josef's family is targeted by a government that hates Jews; Isabel's family is starving because of an embargo and a dictator's politics; Mahmoud's family is caught in a civil war. None of them chose this — which is exactly why the book keeps calling them 'refugees' instead of blaming them.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-deeper reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features on a text's meaning.",
    expect: "Notices the author's structural choice — three interwoven timelines told in short, alternating chapters — and explains what effect that structure has on tension, pace and the reader's understanding.",
    kid: "I can explain why the author tells three stories side by side instead of one at a time, and what effect that has on me as a reader.",
    ask: "Does the student name the structural choice AND explain its effect, not just describe the plot?",
    na: "Comments only on what happens in the plot; does not yet notice how the book is built.",
    wt: "Notices the book switches between characters but cannot explain why, or the explanation is very general ('it's more interesting').",
    ach: "Names the interwoven-timeline structure and explains a specific effect — e.g. it builds suspense by cutting away at a cliffhanger, or it forces the reader to hold three kinds of injustice in mind at once and notice the echoes between eras.",
    wtSample: "The book keeps changing between the three kids and it makes it exciting.",
    exemplar: "Gratz always cuts away right at the worst moment — Hana disappearing under the water, or Josef's father jumping overboard — and jumps to a different decade. That cliffhanger structure forces me to keep three crises going in my head at once, which mirrors how overwhelming and relentless being a refugee actually is. It also means I can't dismiss any one story as 'the past' — 1938, 1994 and 2015 all feel equally urgent.",
    evidence: "Structure & language questions, inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, comparing, synthesising — and links an event in one character's timeline to an event in another's, or an earlier chapter to a later one.",
    kid: "I can use reading strategies to link what's happening to Josef, Isabel or Mahmoud to what's happening to one of the other two, or to something earlier in their own story.",
    ach: "Independently draws a justified connection between two of the three timelines, or between an earlier and later event in the same timeline, without being told to.",
    wt: "Makes a link between timelines or events only when prompted, or the link is superficial (both involve boats).",
    ask: "Can the student explain WHY two events echo each other, not just THAT they do?",
    wtSample: "Isabel's boat and Mahmoud's boat are both dangerous.",
    exemplar: "Isabel's wooden boat nearly sinking in the storm and Mahmoud's rubber raft capsizing both happen at night, both separate a parent from a child figure, and both are caused by boats never designed for the journey being asked of them. Predicting that Mahmoud's family would eventually be as desperate as Isabel's helped me realise Gratz wants us to see 1994 and 2015 as the same emergency repeating.",
    evidence: "Predictions, cross-text comparison questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics, showing an increasing awareness of purpose and audience.",
    expect: "Writes and shares clear, developed opinions and explanations about the book — including on difficult questions (was a country right to turn a ship away? did a character make the right choice?) — with supporting detail from the text and, where relevant, the historical record.",
    kid: "I can share a clear opinion about a hard question the book raises, and back it up with reasons and evidence.",
    ask: "Is there a clear position PLUS at least two reasons or pieces of evidence, including historical context where it's relevant?",
    na: "Answers are one-sided, unclear, or state an opinion with no supporting reason.",
    wt: "Shares a clear opinion but gives only one reason, or does not use evidence from the text.",
    ach: "Communicates a clear, considered opinion and develops it with at least two reasons or pieces of evidence, drawn from the text and/or the author's note.",
    wtSample: "I think Cuba should have let the St. Louis passengers stay because it wasn't fair.",
    exemplar: "I think Captain Schroeder made the right choice to keep searching for a country that would take his passengers, even after Cuba and the US turned them away. First, he risked his own safety and career defying the Nazi agents on board. Second, the author's note shows this wasn't just fiction — real countries really did close their doors, and the ones who eventually took people in (like Britain) saved lives. His stubbornness is the difference between 254 deaths and many more.",
    evidence: "Go-deeper reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts for a range of purposes and audiences.",
    expect: "Chooses the right structure and language for the task — a diary/log entry in a character's voice, a persuasive campaign, a news report, a script — and matches register and tone to 1938 Germany, 1994 Cuba or 2015 Syria as appropriate.",
    kid: "I can choose the right kind of writing and the right voice for the task, and make it sound like it belongs to the right time and place.",
    ach: "Uses a suitable structure and language features for the purpose and audience, and the voice/register fits the character's world (e.g. formal, frightened language for 1938 Berlin; urgent present-tense narration for the raft crossing).",
    wt: "Attempts the right form but the language or structure is inconsistent, or doesn't fit the era/character.",
    ask: "Does the writing look, sound, and feel like it belongs to the character and the time period it claims?",
    na: "Writing does not match the task; little attempt at structure or appropriate language features.",
    wtSample: "Dear diary, today was scary because there was a war and we had to leave our house.",
    exemplar: "14 Aug 2015 — Aleppo. Waleed asleep against my shoulder. Mama counts our money for the third time tonight, like counting it makes more appear. I keep my eyes on the door. Being invisible kept me alive this long. Tonight, for the first time, I want someone to see us.",
    evidence: "Poster, comic, drama & journal projects; Week 9 opinion writing; Week 10 campaign/anthology" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback (Glow & Grow) to improve it, and can explain a specific change made because of that feedback.",
    kid: "I can plan my work, improve a draft, and use feedback to make a specific, named improvement.",
    ach: "Independently plans, drafts and revises, and can point to a specific change made because of feedback.",
    wt: "Plans and drafts with support; makes only small, vague changes when prompted.",
    ask: "Can you see a plan AND one specific change the student can name and explain?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wtSample: "I finished my poster. My partner said to add more colour so I did.",
    exemplar: "My plan had three panels: before, during and after the border crossing. My partner's 'grow' note said my ending felt rushed, so I added a fourth panel showing the Austrians throwing food from the overpass — a real detail from the author's note — which made the ending feel earned rather than sudden.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas — including views on sensitive, real-world issues.",
    expect: "Listens to and builds on others' ideas during group reading and projects, including when discussing difficult or contested topics (border policy, war, prejudice), and disagrees respectfully.",
    kid: "I can listen to my group, take turns, and build on — or respectfully challenge — other people's ideas, even about hard topics.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas, especially on sensitive real-world topics raised by the book.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ask: "Does the student respond to what others say — including disagreeing respectfully — rather than just waiting for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt, dismiss others, or opt out.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I actually see it differently to Amelia — I don't think the Cuban officials were the real villains, because the author's note says they were being manipulated by Nazi agents too. Can we look at that page again?\" She then invited a quieter group member to weigh in.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects, discussion circles — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas, including recognising bias and perspective.",
    expect: "Makes inferences about characters' feelings and motives using clues from the text, and thinks critically about perspective and bias — whose viewpoint a scene is told from, and what is left out.",
    kid: "I can use clues in the story to work out things the author doesn't state directly, and notice whose point of view I'm not getting.",
    ach: "Independently infers feelings or motives and points to the textual clue, AND can identify a perspective the text does not show (e.g. the Cuban officials, the Hungarian police, the German host family) and speculate about it fairly.",
    wt: "Makes an inference with prompting but struggles to explain the clue, or does not yet consider perspectives beyond the protagonist's.",
    ask: "Has the student worked something out, pointed to the clue, AND considered an angle the text doesn't spell out?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wtSample: "Mahmoud feels scared because there is a war.",
    exemplar: "The text never says Mahmoud feels guilty about Hana, but he stops talking, and later tells Frau Rosenberg 'It was my fault. I'm the one who told my mother to do it.' That's a clue the author trusts us to notice, not spell out. It also made me think about the rescuers who took Hana onto their boat — we never hear their story, but they made a split-second, life-changing decision too.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions, discussion" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility, including for topics that connect to real communities beyond the classroom.",
    expect: "Contributes ideas in class discussions and projects, takes responsibility for a role in group work, and connects the book to real communities and current events with care and accuracy.",
    kid: "I can share my ideas, do my part in group work, and connect the book to the real world responsibly.",
    ach: "Offers ideas without being asked, takes responsibility for a role, encourages others, and makes an accurate, respectful connection between the book and a real-world community or issue.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ask: "Does the student offer ideas and take on a job without being asked, and handle real-world connections with care rather than glib comparison?",
    na: "Rarely contributes to discussions or group projects.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 campaign group, Tane researched a real current refugee-support organisation, made sure the group's facts were accurate rather than exaggerated, and made sure everyone had a speaking part in the final presentation.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Courage, Empathy & Belonging", strand: "Values",
    curriculum: "Values: diversity, community and participation, respect, and care for others — recognising courage, empathy across difference, and what it means to belong.",
    expect: "Connects the book's values — courage in the face of forces beyond your control, empathy for people whose circumstances differ hugely from your own, and belonging built through welcome rather than sameness — to their own life, community or actions.",
    kid: "I can connect the book's message about courage, empathy and belonging to my own life or community.",
    ach: "Explains a value from the book and connects it to a real experience, action, or current issue of their own — without minimising the seriousness of what the characters go through.",
    wt: "Names a value (e.g. 'be kind to refugees') when asked, with a simple or general link.",
    ask: "Has the student linked a value from the book to something real, while still respecting how serious the characters' situations are?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wtSample: "The book teaches us to be nice to people from other countries.",
    exemplar: "The Rosenbergs didn't just tolerate Mahmoud's family — they made room in their home and their grief for a family who prayed differently to them. That's the kind of welcome my own community could practise with the refugee families who've resettled near us: not just being polite, but actually making space. Ruthie's line 'they died so all these people could live' made me think about what I owe the people who came before me too.",
    evidence: "Go-deeper reflections, journal entries, Week 10 'connections' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 4 English, Years 7–8, NZ Curriculum",
  lrv: [
    "Ideas: Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics, with increasing awareness of purpose and audience.",
    "Structure and Language: Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Courage under pressure, empathy across difference, belonging and found family, the ethics of welcome and exclusion, resilience.",
  crossCurricular: "Social Sciences — history, place & identity, and human rights (Kristallnacht and the Holocaust, the Cuban rafter crisis and Cold War politics, the Syrian Civil War and the 2015 refugee crisis), since each character's fate is shaped directly by real government decisions of their era.",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "Three Doors Closing", chapters: "Chapters 1–6",
  LI: "We are learning to compare how three characters in three different times and places experience the same kind of danger.",
  SC: "I can describe how Josef, Isabel and Mahmoud are each introduced, and explain one thing their situations share even though their worlds are very different.",
  rubricTags: ["R1","R7","R8"],
  days: {
    mon: D("Chapters 1–2", "Josef: Kristallnacht — Nazis break down the door; Isabel: introduced through the stray kitten and her family's hunger in Havana",
      "If armed strangers broke down your front door tonight with no warning, what is the first thing you think you would do?",
      "Josef: What wakes Josef in the night, and what does his family realise is happening to them?",
      "Isabel: What do the small details in her opening chapter (a hungry kitten, worn-out shoes, whispered arguments) suggest about daily life in Havana in 1994, even before anything dramatic happens?",
      "Write two diary sentences as either Josef or Isabel, describing this very ordinary morning that is about to become extraordinary."),
    tue: D("Chapters 3–4", "Mahmoud: introduced as deliberately \"invisible\" in Aleppo; Josef: the family reaches the train station, ransacked shop, decision to flee",
      "Mahmoud says being invisible is how he survives a war. Can you think of a situation where trying not to be noticed might actually keep someone safe?",
      "Mahmoud: Why has Mahmoud made himself \"invisible\", and what does that reveal about life in a city at war?",
      "Josef: What has happened to his father's shop, and what choice does the family have to make almost overnight?",
      "List three things a family would have to decide, in almost no time at all, if they suddenly had to leave their home for good."),
    wed: D("Chapter 5", "Isabel: hears what she thinks is breaking glass — false alarm, but the tension of the riot is building",
      "Have you ever misheard an ordinary sound as something dangerous, because you were already on edge about something else?",
      "What false alarm does Isabel experience, and what does her reaction tell us about the atmosphere in Havana at this point?",
      "Isabel plays the trumpet in this chapter. Why might the author choose to give her a passion for music before her world falls apart?",
      "Describe a hobby or skill of your own that helps you feel calm, the way music does for Isabel."),
    thu: D("Chapter 6", "Mahmoud: the mosque's call to prayer echoes over bombed-out Aleppo — the day the family's apartment building is hit",
      "What do you think it would feel like to hear something as peaceful as a prayer call over streets full of bomb damage?",
      "What contrast does the author create in this chapter between the sound of the adhan and the sight of the city?",
      "Why might an author deliberately place something peaceful next to something violent, instead of describing only the violence?",
      "Write a short paragraph describing a place you know well using one peaceful detail and one troubling detail, side by side."),
  },
  projects: [
    P("poster", "Three Worlds, One Map", "Design a poster with a world map marking Berlin 1938, Havana 1994 and Aleppo 2015, with one key fact about each setting."),
    P("comic", "The Moment It Changed", "6 panels: 2 each for Josef, Isabel and Mahmoud, showing the exact moment each character's world starts to fall apart."),
    P("drama", "Ordinary Morning", "Act out an ordinary family breakfast in one of the three settings, moments before everything changes."),
    P("journal", "My Version of Invisible", "Write about a time you tried to stay unnoticed, or a time you wished someone had noticed you, and compare it honestly to Mahmoud's survival strategy."),
  ],
  quiz: [
    Q("Where and when does Josef's story begin?", "Berlin, Germany, 1938."),
    Q("Where and when does Isabel's story begin?", "Just outside Havana, Cuba, 1994."),
    Q("Where and when does Mahmoud's story begin?", "Aleppo, Syria, 2015."),
    Q("True or False: All three main characters are adults.", "False — Josef, Isabel and Mahmoud are all children/young teenagers.", "tf"),
    Q("What event wakes Josef and his family in the night?", "Nazis (Brownshirts/soldiers) breaking down their door — the start of Kristallnacht."),
    Q("What historical event is Josef's opening chapter based on?", "Kristallnacht — the \"Night of Broken Glass\", a Nazi attack on Jewish homes, businesses and synagogues."),
    Q("What does Mahmoud mean when he says he wants to be \"invisible\"?", "He avoids drawing attention to himself so he isn't targeted — by soldiers, bombs, or bullies."),
    Q("Vocabulary: What does \"invisible\" mean in Mahmoud's context?", "Not literally unseen, but unnoticed/avoiding attention on purpose."),
    Q("What does Isabel mistake for the sound of breaking glass?", "Cars and bicycles/ordinary street noise."),
    Q("What instrument does Isabel play?", "The trumpet."),
    Q("True or False: Isabel's family is comfortable and well-fed at the start of the book.", "False — there are signs of hunger and hardship in Havana.", "tf"),
    Q("What is damaged or destroyed in Mahmoud's opening chapters?", "His family's apartment building, hit by a missile/bomb strike."),
    Q("Vocabulary: What does \"adhan\" mean?", "The Islamic call to prayer."),
    Q("What has happened to Josef's father's business, and why?", "It has been shut down/ransacked because Jewish people were banned from running businesses under Nazi law."),
    Q("Why might the author choose to open with three separate, unconnected-seeming stories?", "Open-ended — to show the reader that this crisis isn't limited to one place or time, and to build curiosity about how they'll connect."),
    Q("What do Josef's, Isabel's and Mahmoud's families all have in common at this point, even though their situations look different?", "Open — each is being pushed toward leaving home by forces outside their control (persecution, hunger/unrest, war)."),
    Q("Predict: What do you think each family will have to decide by the end of this week's reading?", "Open-ended, text-supported prediction (accept: whether/how to leave)."),
    Q("Whose story is told using short, present-tense, urgent chapters?", "All three — Gratz uses short, tense chapters for each storyline."),
    Q("What is one clue that Mahmoud's city has been at war for some time already?", "Bombed-out streets, families used to the sound of explosions, rubble."),
    Q("What do you think the title Refugee is preparing you to notice as you read all three storylines?", "Open-ended, personal response — accept reference to displacement/forced migration."),
  ],
},
{
  num: 2, title: "Leaving Everything Behind", chapters: "Chapters 7–12",
  LI: "We are learning to explain how a character's decision to leave home is shaped by forces outside their control.",
  SC: "I can describe the specific event that forces each family to decide to flee, and explain why the decision is not really a free choice.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapters 7–8", "Josef: family pushed through the crowd at Lehrter Bahnhof station; Isabel: her injured father is carried home from the riot",
      "If your family had only minutes to pack for a journey with no return date, what one object would you fight to bring?",
      "Josef: Why does the text say Josef and his family feel \"invisible\" moving through the crowded station?",
      "Isabel: What has happened to Isabel's father, and what does his injury suggest about how dangerous Havana has become?",
      "Write a packing list of five items Josef's family might bring, and explain your reasoning for one of them."),
    tue: D("Chapters 9–10", "Mahmoud: the family decides to flee immediately after the missile strike; Josef: aboard the MS St. Louis, his little sister Ruthie is thrilled by the \"paradise\" ship",
      "Would it feel strange to be somewhere beautiful and safe while people you love are still in danger elsewhere? Why?",
      "Mahmoud: What decision does his family make right after the missile strike, and how much time do they have to make it?",
      "Josef: Why might young Ruthie experience the St. Louis so differently to how her parents experience it?",
      "Write two short sentences: one from Ruthie's excited point of view, one from her father's anxious point of view, about the same ship."),
    wed: D("Chapter 11", "Isabel: her family and neighbours are secretly building the boat that will carry them to Florida",
      "What would it take — in trust and teamwork — for a group of neighbours to build something in secret together?",
      "Who is helping Isabel's family build their escape boat, and why does it need to be kept secret?",
      "What does the community effort to build the boat suggest about how ordinary Cubans were responding to the crisis in 1994?",
      "Design a simple diagram of what you imagine Isabel's family's boat looks like, labelling what it's made from."),
    thu: D("Chapter 12", "Mahmoud: the family's car is stopped for fuel near a checkpoint, and the tension of travelling through a war zone becomes clear",
      "What would be the scariest part of driving through a country in the middle of a civil war?",
      "What danger does the family face simply trying to get fuel for their car?",
      "Why might something as ordinary as a petrol station become a place of real danger in Mahmoud's Syria?",
      "Write about a time an ordinary errand (like a petrol stop) felt unexpectedly tense or worrying, however small."),
  },
  projects: [
    P("poster", "What Would You Pack?", "Design a poster showing five items you would take if you had to leave home with only what you could carry, and why."),
    P("comic", "Building in Secret", "Show, panel by panel, Isabel's community secretly building their escape boat."),
    P("drama", "The Checkpoint", "Act out the tense scene of Mahmoud's family being stopped at a checkpoint or fuel stop, staying respectful to the seriousness of the situation."),
    P("journal", "Not Really a Choice", "Write about why you think none of the three families are really making a free choice to leave — what forces are pushing them?"),
  ],
  quiz: [
    Q("Where does Josef's family go to begin their journey out of Germany?", "Lehrter Bahnhof, Berlin's main railway station."),
    Q("What happens to Isabel's father in these chapters?", "He is injured, likely during unrest/rioting, and carried home."),
    Q("True or False: Mahmoud's family has weeks to plan their departure from Aleppo.", "False — they decide to flee almost immediately after the missile strike.", "tf"),
    Q("What is the name of the ship Josef's family boards?", "The MS St. Louis."),
    Q("Vocabulary: What does it mean to say a family is \"pushed through\" a crowd, feeling \"invisible\"?", "They are not noticed or helped by anyone around them, moving anonymously through danger."),
    Q("Who helps Isabel's family build their escape boat?", "Neighbours/community members, including the Castillo family."),
    Q("Why does the boat-building have to happen in secret?", "Leaving Cuba without permission was illegal and dangerous under the government at the time."),
    Q("What does Ruthie (Josef's little sister) think of the ship at first?", "She thinks it's wonderful/like a paradise, not realising the danger her family is in."),
    Q("Why might a young child and an adult experience the same situation so differently?", "Open — a child may not fully understand the danger; adults carry the full weight of the fear and responsibility."),
    Q("What happens when Mahmoud's family stops for fuel?", "They face a tense, dangerous moment near a checkpoint/roadside station."),
    Q("Vocabulary: What does \"checkpoint\" mean, in the context of a country at war?", "A location where soldiers or officials stop and check people/vehicles, often for security or control."),
    Q("True or False: All three families make their decision to leave freely, with no outside pressure.", "False — each is forced by circumstances beyond their control.", "tf"),
    Q("What is one similarity between how Isabel's community responds and how Mahmoud's family responds to danger?", "Open — both show resourcefulness, working together/quickly under pressure."),
    Q("Why do you think the author includes the detail of a shared, secretly built boat rather than a bought or ready-made one?", "Open-ended — highlights community effort, risk and desperation."),
    Q("What does Josef's family's experience at the train station reveal about how Jewish people were being treated in Germany at this time?", "Open — dehumanised, unhelped, treated as unwelcome/invisible."),
    Q("Predict: What kind of dangers do you expect each family to face once they actually set out on their journeys?", "Open-ended, text-supported prediction."),
    Q("Why might the author choose to show the preparation stage in detail, rather than skipping straight to the journey?", "Open-ended — builds tension, shows the cost and risk before departure, humanises the decision."),
    Q("What is one detail from this week that made the danger feel real to you personally?", "Open-ended, personal response."),
    Q("What does the checkpoint scene suggest about ordinary daily life during a civil war?", "Open — nothing is safe or routine anymore, even basic tasks carry risk."),
    Q("Whole-section check: Name the three main characters and one fact about each of their home countries in this period.", "Josef (Nazi Germany, 1938), Isabel (Cuba, 1994), Mahmoud (Syria, 2015) — accept any accurate supporting fact."),
  ],
},
{
  num: 3, title: "Setting Out", chapters: "Chapters 13–18",
  LI: "We are learning to notice how setting off on a journey can feel both hopeful and terrifying at the same time.",
  SC: "I can find evidence in the text that a character feels two opposite emotions about their departure, and explain why both make sense.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 13", "Josef: it is Shabbos — the day Josef becomes a bar mitzvah, at sea aboard the St. Louis",
      "Why might a family insist on celebrating an important tradition even in the middle of a crisis?",
      "What milestone does Josef reach in this chapter, and why does it matter so much to him right now?",
      "Why might celebrating becoming \"a man\" matter even more to Josef given everything his family is going through?",
      "Write about a tradition or milestone in your own life or culture that matters to your family, and why it would still matter during a hard time."),
    tue: D("Chapter 14", "Isabel: helping carry and launch the boat with her neighbours, the escape officially begins",
      "What would it feel like to help carry something that your whole family's future depends on?",
      "What is Isabel physically doing in this chapter, and how does the text show her fear and determination at the same time?",
      "Why might the author focus on the physical effort of carrying the boat rather than just saying \"they left\"?",
      "Write two sentences describing a moment you had to be brave and do something difficult with your body, not just your mind."),
    wed: D("Chapters 15–16", "Mahmoud: the family crosses the Syria–Turkey border on foot, relying on a smuggler and waiting in a long line",
      "What would it be like to have to trust a stranger with your family's safety, simply because you had no other choice?",
      "How does the family manage to cross the border, and what risks are involved in relying on a smuggler?",
      "Why might people fleeing danger sometimes have no choice but to trust people they don't fully know?",
      "Write about a time you had to trust someone you didn't know very well, and how that felt."),
    thu: D("Chapters 17–18", "Josef: meets other kids on the ship's bridge and Captain Schroeder is introduced; Isabel: the boat's engine won't start once they're at sea",
      "Have you ever been in a situation where something you were relying on suddenly stopped working at the worst possible moment?",
      "Josef: What impression do we get of Captain Schroeder in this chapter, compared to other adults in authority Josef has encountered?",
      "Isabel: What goes wrong with the boat, and how does the group respond under pressure?",
      "Write about a time a plan went wrong at a bad moment, and how you or someone else stayed calm (or didn't)."),
  },
  projects: [
    P("poster", "A Send-Off", "Design a poster capturing the mixed emotions — hope and fear — of one family's departure."),
    P("comic", "Crossing the Line", "Show Mahmoud's family's border crossing, panel by panel, including the role of the smuggler."),
    P("drama", "Meeting Captain Schroeder", "Act out Josef meeting Captain Schroeder for the first time, showing why this adult feels different to others Josef has met."),
    P("journal", "Hopeful and Terrified", "Write about a time you felt two completely opposite emotions at once, the way these characters do as they set out."),
  ],
  quiz: [
    Q("What Jewish coming-of-age ceremony does Josef go through at sea?", "His bar mitzvah."),
    Q("True or False: Josef's bar mitzvah happens in a synagogue in Berlin.", "False — it happens aboard the MS St. Louis at sea.", "tf"),
    Q("What is Isabel physically doing to help launch the escape?", "Helping carry the boat to the water."),
    Q("Vocabulary: What does \"smuggler\" mean?", "Someone who helps move people or goods illegally, often across a border, usually for payment."),
    Q("How does Mahmoud's family cross the Syria–Turkey border?", "On foot, with the help of a smuggler, waiting in a long line at the border."),
    Q("Who is the captain of the MS St. Louis?", "Captain Gustav Schroeder."),
    Q("True or False: Captain Schroeder is portrayed as uncaring toward his Jewish passengers.", "False — he is shown as sympathetic and protective of them.", "tf"),
    Q("What problem occurs with Isabel's boat once they are at sea?", "The engine won't start / has trouble."),
    Q("Why might Gratz choose to include a joyful ceremony (the bar mitzvah) in the middle of such a dangerous journey?", "Open-ended — shows resilience, normalcy, hope, and the importance of tradition even in crisis."),
    Q("What does relying on a smuggler suggest about the choices available to refugees?", "Open — often no legal, safe options exist, forcing dangerous reliance on strangers."),
    Q("Vocabulary: What does \"authority\" mean, and how does Captain Schroeder's authority differ from that of the Nazi officials Josef has met?", "Authority = power/right to give orders or make decisions; Schroeder uses his authority to protect rather than harm."),
    Q("Why might carrying a physical boat to the water be a powerful image for the start of Isabel's journey?", "Open-ended — physical effort mirrors the emotional weight of the decision to leave."),
    Q("True or False: All three journeys begin smoothly with no early problems.", "False — Isabel's boat has engine trouble almost immediately.", "tf"),
    Q("What is one risk Mahmoud's family takes by trusting a smuggler?", "Open — being cheated, abandoned, caught, or harmed."),
    Q("Whole-section check: What do the bar mitzvah, the boat launch, and the border crossing all have in common as \"setting out\" moments?", "Open-ended — each marks a formal, irreversible step into the unknown."),
    Q("Why might the author want us to meet a genuinely kind authority figure (Schroeder) at this point in the book?", "Open-ended — offers hope/contrast, shows not all authority is corrupt or cruel."),
    Q("Predict: How do you think Isabel's group will handle the boat trouble?", "Open-ended, text-supported prediction."),
    Q("What emotion do you think is strongest for each character as their journey truly begins — Josef, Isabel, or Mahmoud? Explain your choice for one.", "Open-ended, personal response with text support."),
    Q("Why is a border crossing description often written with short, tense sentences?", "Open-ended — mirrors urgency, fear, and the character's own racing thoughts."),
    Q("What does the phrase \"setting out\" suggest is still ahead for all three families?", "Open-ended — the hardest part of the journey is still to come."),
  ],
},
{
  num: 4, title: "Storms Gather", chapters: "Chapters 19–24",
  LI: "We are learning to identify how tension builds across several chapters through small, escalating warning signs.",
  SC: "I can point to specific details that show danger increasing, rather than just saying a character is \"in trouble\".",
  rubricTags: ["R3","R7","R10"],
  days: {
    mon: D("Chapter 19", "Josef: his father Aaron's trauma from his time in a concentration camp resurfaces aboard ship",
      "What do you think it might do to a person to survive something as traumatic as a concentration camp, even after they've escaped it?",
      "What signs show that Josef's father is struggling psychologically, not just physically?",
      "Why might the author choose to show a parent — usually seen as the strong, protective figure — becoming the one who needs protecting?",
      "Write a short, gentle note Josef might write to comfort his father, without being able to fix what's wrong."),
    tue: D("Chapter 20", "Isabel: a huge oil tanker looms out of the darkness near their small boat",
      "What would it feel like to be in a tiny boat and see something enormous and uncontrollable bearing down on you?",
      "What does the tanker represent in terms of the dangers of the open sea for a small, homemade boat?",
      "Why might the author compare the tanker to a \"leviathan\" (a sea monster)? What effect does that word choice have?",
      "Write a description of something that felt enormous and overwhelming to you, using a comparison (simile or metaphor) like the author does."),
    wed: D("Chapters 21–22", "Mahmoud: the family reaches the Mediterranean coast to prepare for the boat crossing; Josef: his father's condition worsens, and the family's situation aboard ship becomes more desperate",
      "If you had survived a great danger once already, how do you think that would change how you approach the next risk?",
      "Mahmoud: What does the family see and feel as they prepare to cross the Mediterranean Sea?",
      "Josef: What signs suggest that time is running out for Josef's family's situation on the ship to be resolved safely?",
      "Write about a moment of dread — waiting for something you knew would be difficult or frightening."),
    thu: D("Chapters 23–24", "Isabel: the tanker danger passes but the sea remains threatening; Mahmoud: the family witnesses the chaos and danger of the border/coastal crossing area",
      "What's the difference between a danger that suddenly appears and a danger that has been building for a while?",
      "How does the mood of Isabel's chapter shift once the immediate tanker danger has passed?",
      "What do the chaotic scenes Mahmoud witnesses reveal about how many people are trying to make this same dangerous crossing?",
      "Write a paragraph describing a scene with many people all trying to do the same difficult thing at once (a crowded platform, a queue, a rush)."),
  },
  projects: [
    P("poster", "Warning Signs", "Design a poster tracking three separate \"warning signs\" of danger building across this week's reading, one from each storyline."),
    P("comic", "The Tanker", "Show Isabel's boat encountering the huge tanker, panel by panel, building the tension visually."),
    P("drama", "A Father's Struggle", "Act out a sensitive, respectful scene showing how Josef's family responds to his father's distress."),
    P("journal", "Enormous and Overwhelming", "Write about something that once felt too big or too much for you to handle, and how you got through it (or didn't, yet)."),
  ],
  quiz: [
    Q("What psychological struggle does Josef's father face in these chapters?", "Trauma from his time in a Nazi concentration camp resurfacing."),
    Q("Vocabulary: What does \"trauma\" mean?", "Deep emotional/psychological harm caused by a distressing experience."),
    Q("What enormous danger does Isabel's boat encounter?", "A huge oil tanker."),
    Q("True or False: The tanker collides with Isabel's boat.", "False — it is a near miss/close danger, not a direct collision at this point.", "tf"),
    Q("What word does the author use to compare the tanker to something monstrous?", "\"Leviathan\" (a sea monster)."),
    Q("Where does Mahmoud's family go to prepare for the next stage of their journey?", "The Mediterranean coast, to cross by boat/raft."),
    Q("Why might the author show danger building gradually instead of all at once?", "Open-ended — builds suspense and reflects the real, exhausting uncertainty of the journey."),
    Q("What is one small, specific detail (not just \"they are scared\") that shows tension rising in one of the three storylines?", "Open, text-based (accept any accurate specific detail)."),
    Q("Why might seeing a parent struggle psychologically be especially frightening for a child character like Josef?", "Open — children often rely on parents to feel safe; role reversal is destabilising."),
    Q("Vocabulary: What does \"leviathan\" suggest about how small Isabel's boat is by comparison?", "It emphasises how tiny, fragile and vulnerable the boat is."),
    Q("What does the crowded, chaotic coastal scene suggest about the scale of the Syrian refugee crisis?", "Open — huge numbers of people are attempting the same dangerous journey, not just one family."),
    Q("True or False: By the end of this week, all three characters are completely safe from danger.", "False — tension is rising in all three storylines.", "tf"),
    Q("How does the mood shift in Isabel's chapter once the tanker danger passes?", "Open — tension may ease briefly but underlying threat (the sea itself) remains."),
    Q("What does this week suggest about the phrase \"a journey isn't over until it's over\"?", "Open-ended — danger can persist even after one crisis passes."),
    Q("Why might the author choose this point in the book to show more of Josef's father's inner state?", "Open-ended — deepens empathy, raises stakes, prepares for a coming crisis."),
    Q("Predict: What do you think might happen once Mahmoud's family actually gets in a boat to cross the sea?", "Open-ended, text-supported prediction."),
    Q("Give one piece of evidence that the adults in these chapters are also frightened, not just pretending to be strong for the children.", "Open, text-based."),
    Q("What does the author achieve by giving us three different \"storms gathering\" at once, across three different decades?", "Open-ended — shows this isn't a one-off crisis, but a pattern that repeats across history."),
    Q("Vocabulary: What is the difference between \"tension\" and \"danger\"?", "Tension is the feeling of unease/anticipation; danger is the actual threat itself."),
    Q("Whole-section check: Name one specific escalating danger from each of the three storylines so far.", "Open, accept: Josef's father's mental state, Isabel's tanker/sea danger, Mahmoud's crowded/chaotic crossing prep."),
  ],
},
{
  num: 5, title: "Into Deep Water", chapters: "Chapters 25–30",
  LI: "We are learning to explore how celebration and desperation can exist in the very same place at the very same time.",
  SC: "I can explain how a scene can feel joyful on the surface while hiding real fear or danger underneath.",
  rubricTags: ["R2","R9"],
  days: {
    mon: D("Chapter 25", "Josef: the St. Louis throws a lavish party a day out from Cuba, masking the passengers' fear",
      "Why might people put on a brave, cheerful face in public even while they're terrified underneath?",
      "What is happening on the ship during this party, and how does it contrast with what the passengers actually know about their situation?",
      "Why might the author include a party scene instead of skipping straight to the danger?",
      "Write about a time you (or someone you know) smiled or celebrated on the outside while feeling worried on the inside."),
    tue: D("Chapter 26", "Isabel: she falls into the dark ocean at night and discovers the water is disturbingly \"alive\"",
      "What is the scariest thing you can imagine about being in deep, dark water at night, alone?",
      "What does Isabel discover the ocean is \"alive\" with, and why is this discovery so frightening?",
      "Why might the author choose the phrase \"alive\" rather than simply describing the danger directly?",
      "Write a short, tense passage describing total darkness and an unknown danger nearby, without naming exactly what it is."),
    wed: D("Chapters 27–28", "Mahmoud: the family sees the flimsy rubber raft they must cross the sea in; Josef: Josef is confronted by a hostile sailor aboard ship",
      "If you saw the vehicle you were about to risk your life in and it looked completely unsafe, what would you do?",
      "Mahmoud: How does the author describe the \"boat\" the family must use, and why does this description matter?",
      "Josef: What happens between Josef and the sailor, and what does it reveal about how passengers are truly being treated?",
      "Write about a moment you had to do something risky anyway, even though every instinct told you it wasn't safe."),
    thu: D("Chapters 29–30", "Isabel: a brief calm morning at sea, deceptively peaceful; Mahmoud: the family capsizes and baby Hana is swept away in the chaos",
      "How do you think it would feel to lose someone you love in an instant, in circumstances completely beyond your control?",
      "Isabel: Why might a peaceful morning after danger feel unsettling rather than purely relieving?",
      "Mahmoud: What happens to Hana, and how does the family react in the immediate aftermath?",
      "Write about the hardest goodbye or loss you can imagine, and how you think you would try to keep going afterwards."),
  },
  projects: [
    P("poster", "Two Faces", "Design a split poster showing the \"public face\" versus the \"private fear\" of passengers on the St. Louis during the party scene."),
    P("comic", "What the Water Hides", "Show Isabel's frightening night swim, panel by panel, building suspense without over-explaining the danger."),
    P("drama", "The Capsizing", "Act out — with sensitivity and care — the moment of crisis when Mahmoud's family's raft capsizes, focusing on the family's reactions rather than spectacle."),
    P("journal", "Held Together By a Thread", "Write about the theme of this week — that hope and disaster can exist side by side — using evidence from at least two storylines."),
  ],
  quiz: [
    Q("What kind of event does the St. Louis hold in Chapter 25?", "A lavish party/celebration."),
    Q("True or False: The party reflects how genuinely safe and carefree the passengers feel.", "False — it masks real fear about their uncertain future.", "tf"),
    Q("What happens to Isabel in Chapter 26?", "She falls into the dark ocean at night."),
    Q("Vocabulary: What does it mean that the ocean is described as \"alive\"?", "Full of unseen creatures/movement, making the danger feel unpredictable and threatening."),
    Q("What kind of vessel does Mahmoud's family discover they must cross the Mediterranean in?", "A flimsy inflatable rubber raft/dinghy, not a real boat."),
    Q("True or False: Mahmoud's family feels confident and safe about the boat they are given.", "False — they are alarmed by how unsafe it looks.", "tf"),
    Q("What happens between Josef and a sailor aboard the St. Louis?", "The sailor treats him roughly/threateningly, showing hostility toward the Jewish passengers."),
    Q("What tragic event happens to Mahmoud's family at sea?", "Their raft capsizes and baby Hana is swept away/lost in the water."),
    Q("Vocabulary: What does \"capsize\" mean?", "To overturn in the water."),
    Q("Why might the author include a peaceful morning for Isabel right before or after such devastating events elsewhere in the book?", "Open-ended — creates contrast, shows how quickly calm can turn to crisis or vice versa."),
    Q("Why might a party scene actually be one of the saddest moments in Josef's story, rather than a happy one?", "Open-ended — the celebration is hollow/desperate, masking real fear."),
    Q("What does the detail of the ocean being \"alive\" suggest about how much control Isabel has over her situation?", "Open — very little; nature itself is a threat beyond her control."),
    Q("How do you think Mahmoud will change after losing his sister in this way?", "Open-ended, text-supported prediction (accept guilt, grief, determination)."),
    Q("True or False: The loss of Hana is fully resolved by the end of this week's reading.", "False — her fate remains unknown/unresolved at this point.", "tf"),
    Q("Why might Gratz choose to have this tragedy happen to the most vulnerable member of the family (a baby)?", "Open-ended — raises emotional stakes, highlights the indiscriminate cruelty of the crisis."),
    Q("What does the confrontation between Josef and the sailor suggest about safety even for passengers who are \"paying guests\" on the ship?", "Open — no passenger is truly safe or respected under Nazi influence, regardless of ticket status."),
    Q("Give one piece of evidence that adults in these chapters are trying to protect children from the full truth of their situation.", "Open, text-based."),
    Q("Whole-section check: What is the emotional \"low point\" so far for each of the three storylines?", "Open, accept: Josef — hostility/fear aboard ship; Isabel — the terrifying night swim; Mahmoud — losing Hana."),
    Q("Why is \"Into Deep Water\" an appropriate title for this week's chapters, in more than one meaning?", "Open-ended — literal (ocean danger) and figurative (emotional/psychological depth of the crisis)."),
    Q("Predict: How do you think each family will respond in the days immediately following this week's events?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 6, title: "What the Sea Takes", chapters: "Chapters 31–36",
  LI: "We are learning to explore how a crisis moment can reveal a character's deepest fears and truest values.",
  SC: "I can identify a moment of crisis in the text and explain what it shows about a character's fears, values or relationships.",
  rubricTags: ["R1","R7","R10"],
  days: {
    mon: D("Chapter 31", "Josef: his father's mental health crisis worsens; he begins barricading furniture, consumed by paranoia",
      "What do you think it's like for a child to watch a parent lose control of their fear, rather than the other way around?",
      "What specific behaviour does Josef's father show that reveals how much his trauma has taken over?",
      "Why might Josef feel responsible for his father, even though he is still a child himself?",
      "Write about a time you had to be braver or calmer than an adult in a difficult moment, or imagine how that might feel."),
    tue: D("Chapter 32", "Isabel: a calm, silver-sea morning after the storm — deceptive peace",
      "Do you think a calm moment after danger is more relaxing, or more unsettling, because you know more danger could still be coming?",
      "How does the author describe the sea and sky in this calm chapter, and what mood does that create?",
      "Why might this brief calm chapter be placed right before something much worse happens (structurally, in the book)?",
      "Describe a calm-before-the-storm moment you've experienced, where you sensed something was still not right."),
    wed: D("Chapter 33", "Mahmoud: the devastating confirmation that Hana is truly gone; his mother's grief",
      "How do people sometimes respond very differently to the exact same loss?",
      "How does Mahmoud's mother react to losing Hana, and how does Mahmoud himself seem to be coping (or not)?",
      "Why might grief look different for different members of the same family, even though they've lost the same person?",
      "Write about how you think you would want people to support you after a devastating loss, based on what you see in this chapter."),
    thu: D("Chapters 34–36", "Josef: the fallout from his father's suicide attempt and Josef's isolation; Isabel: exhausted, swimming alongside the failing boat; Mahmoud: arrival at the Lesbos tent city refugee camp",
      "What do you imagine it's like to arrive somewhere \"safe\" after a disaster, only to find it's still a struggle?",
      "Josef: How do other passengers treat Josef once they learn what happened to his father?",
      "Mahmoud: What is the refugee camp at Lesbos like, and how does it compare to what Mahmoud might have hoped \"safety\" would look like?",
      "Write about the gap between what you imagine \"reaching safety\" would feel like, and what it might actually feel like based on this week's reading."),
  },
  projects: [
    P("poster", "Calm Before the Storm", "Design a poster contrasting a peaceful scene with the danger you know is coming, using imagery and colour to show the contrast."),
    P("comic", "Arriving Isn't Always Safe", "Show Mahmoud's arrival at the Lesbos tent camp, panel by panel, focusing on the reality versus the hoped-for relief."),
    P("drama", "Supporting Each Other", "Act out a respectful, supportive conversation between family members coping with grief or crisis in one of the three storylines."),
    P("journal", "What Crisis Reveals", "Write about a difficult moment in your own life (big or small) that revealed something true about your own values or fears."),
  ],
  quiz: [
    Q("What worsening behaviour does Josef's father show in Chapter 31?", "He barricades furniture/becomes consumed by paranoia."),
    Q("True or False: Josef's father's mental health steadily improves throughout this week.", "False — it worsens significantly.", "tf"),
    Q("Vocabulary: What does \"paranoia\" mean?", "An intense, often irrational fear or suspicion that something bad will happen."),
    Q("How is the sea described in Isabel's calm chapter?", "Silver, calm, mirror-like."),
    Q("What is confirmed about Hana in Chapter 33?", "That she is truly lost/gone, not merely missing temporarily."),
    Q("How does Mahmoud's mother react to losing Hana?", "With intense grief/wailing (open, text-based detail accepted)."),
    Q("What serious event happens to Josef's father in these chapters?", "He attempts to take his own life by jumping overboard."),
    Q("Vocabulary: What does it mean for someone to be \"isolated\" after a traumatic family event, as Josef is?", "Set apart/avoided by others, left feeling alone."),
    Q("Where does Mahmoud's family end up after their sea crossing?", "A tent city refugee camp on the Greek island of Lesbos."),
    Q("True or False: The refugee camp is described as comfortable and well-resourced.", "False — it is crowded, makeshift, and difficult.", "tf"),
    Q("How does Isabel physically get through this stage of the journey?", "By swimming alongside the boat when it's too full/failing, to lighten the load."),
    Q("Why might the author show a peaceful chapter for Isabel right before showing devastating events for Mahmoud?", "Open-ended — contrast intensifies the emotional impact of both."),
    Q("What does the way other passengers treat Josef after his father's crisis suggest about fear and stigma?", "Open — people may distance themselves from suffering they don't know how to handle, even unintentionally causing more isolation."),
    Q("Vocabulary: What does \"grief\" mean, and how might it look different in different people?", "Deep sorrow over a loss; it can appear as crying, silence, anger, numbness, or other reactions depending on the person."),
    Q("Why might arriving at a refugee camp not feel like true \"safety\" to Mahmoud?", "Open — still crowded, uncertain, lacking basic comforts, future still unknown."),
    Q("What does this week suggest about the idea that \"survival\" and \"safety\" are not the same thing?", "Open-ended."),
    Q("Give one piece of evidence that Josef feels a heavy sense of responsibility beyond what a child should have to carry.", "Open, text-based."),
    Q("Whole-section check: How has each character's emotional state changed since Week 1?", "Open-ended — should reference growing trauma, exhaustion, grief and resilience."),
    Q("Predict: What do you think each character will need in order to keep going after this devastating week?", "Open-ended, text-supported prediction."),
    Q("Why is \"What the Sea Takes\" a fitting title for this week, beyond the literal sea?", "Open-ended — the \"sea\" of the crisis takes more than lives; it takes stability, trust, innocence, and mental health too."),
  ],
},
{
  num: 7, title: "Doors That Open, Doors That Don't", chapters: "Chapters 37–42",
  LI: "We are learning to evaluate how the same act of hope (reaching for safety) can lead to completely different outcomes, and to consider why.",
  SC: "I can compare a moment of hope in one storyline with a moment of rejection in another, and explain what caused the different outcomes.",
  rubricTags: ["R1","R3","R8"],
  days: {
    mon: D("Chapter 37", "Josef: he feels the shame and isolation of being known as \"the boy whose father jumped\"",
      "Have you ever been defined by one difficult moment, in a way that felt unfair?",
      "How do the other passengers now see and treat Josef, and how does he feel about it?",
      "Why might other people's pity sometimes feel worse than their indifference?",
      "Write about a time you were labelled by one moment or mistake, and how you wanted people to see you instead."),
    tue: D("Chapters 38–39", "Isabel: gazing at the stars, emotionally distant even from her own thoughts; Mahmoud: reaching the Macedonian border, facing armed police",
      "How do people sometimes drift into their own thoughts, almost on autopilot, during overwhelming times?",
      "Isabel: What does Isabel's distracted state under the stars suggest about how she's coping with everything that's happened?",
      "Mahmoud: What does Mahmoud feel when he sees armed guards at the Macedonian border, and why does it remind him of home?",
      "Write about a time your mind went somewhere else entirely while your body kept going through the motions of a hard day."),
    wed: D("Chapters 40–41", "Josef: another small boat is spotted sneaking through the flotilla near Cuba, a flicker of hope for a way in; Isabel: her family gets its first glimpse of Miami, glittering like a dream",
      "What do you imagine it would feel like to finally see, with your own eyes, the safe place you've been risking everything to reach?",
      "Josef: What does the small boat sneaking past the flotilla suggest about how some people are trying to get around the official rules?",
      "Isabel: How is Miami described when Isabel's family first sees it, and why might the author use dreamlike language here?",
      "Write about the first time you saw a place you had been looking forward to for a long time, and whether it matched what you imagined."),
    thu: D("Chapter 42", "Mahmoud: a policeman shouts through a loudspeaker; the family is threatened with arrest for continuing their march",
      "What would you do if you were told you'd be arrested for simply trying to keep moving toward safety?",
      "What choice does the crowd of refugees make when threatened with arrest, and why?",
      "Why might staying together as a large group of refugees be both a source of strength and a source of risk?",
      "Write about a time you (or a group you were part of) had to decide whether to keep going despite a warning or threat."),
  },
  projects: [
    P("poster", "Hope and Rejection", "Design a split poster showing one moment of hope and one moment of rejection from this week's reading, from two different storylines."),
    P("comic", "First Glimpse of Miami", "Show Isabel's family's first sight of Miami, panel by panel, capturing the dreamlike, hopeful mood."),
    P("drama", "The Loudspeaker Warning", "Act out the tense moment Mahmoud's group is threatened with arrest, and their decision about what to do next."),
    P("journal", "Labelled by One Moment", "Write about being defined by a single difficult moment (your own experience or an imagined one), like Josef is by his father's crisis."),
  ],
  quiz: [
    Q("How do other passengers now treat Josef, following his father's crisis?", "With pity, distance, or unwanted attention — he feels isolated/labelled."),
    Q("Vocabulary: What does \"stigma\" mean, and how does it relate to how Josef is being treated?", "A mark of shame or disapproval associated with a particular circumstance; Josef is stigmatised for his father's breakdown."),
    Q("What does Isabel do in Chapter 38 that shows her emotional state?", "She stares at the stars, distracted/distant, not truly present."),
    Q("What border does Mahmoud's family approach in these chapters?", "The border into Macedonia."),
    Q("True or False: Mahmoud feels completely unfamiliar with the sight of armed guards at the border.", "False — it reminds him of home/Syria, showing how normalised danger has become for him.", "tf"),
    Q("What does Josef notice near the St. Louis that offers a flicker of hope?", "A small boat sneaking through the flotilla of reporters/officials near Cuba."),
    Q("What city does Isabel's family first glimpse, described almost like a dream?", "Miami."),
    Q("Vocabulary: What does \"flotilla\" mean?", "A group/fleet of boats."),
    Q("What threat does a policeman make to Mahmoud's group in Chapter 42?", "That they will be arrested if they don't stop/turn back."),
    Q("True or False: The refugees in Mahmoud's group immediately turn back when threatened with arrest.", "False — they continue, choosing to keep moving forward.", "tf"),
    Q("Why might the author show hope and rejection so close together in the same week of reading?", "Open-ended — reflects the unpredictable, high-stakes nature of the refugee experience."),
    Q("What does Isabel's dreamlike description of Miami suggest about how much hope she has invested in reaching it?", "Open — an enormous amount; it represents everything she's risked everything for."),
    Q("Why might staying invisible have worked for Mahmoud earlier in the book, but marching visibly as a large group work better here?", "Open-ended — safety in numbers, visibility can sometimes protect through public attention/sympathy rather than always being a risk."),
    Q("What does the small boat \"sneaking through\" near Cuba suggest about how desperate people are to reach safety by any means?", "Open-ended."),
    Q("Vocabulary: What is the difference between how the world treats Josef's crisis (his father) versus how it treats Mahmoud's crisis (the border)?", "Open — personal/family shame versus a public, political obstacle; accept thoughtful comparisons."),
    Q("Predict: Do you think Josef's ship will be allowed to dock, based on the clues so far?", "Open-ended, text-supported prediction."),
    Q("Predict: Do you think Mahmoud's group will be allowed through, based on the clues so far?", "Open-ended, text-supported prediction."),
    Q("Why is \"Doors That Open, Doors That Don't\" an apt title for this week?", "Open-ended — some paths forward work, others are blocked, often for reasons outside the characters' control."),
    Q("What does this week suggest about luck and circumstance versus effort and courage, in whether a refugee reaches safety?", "Open-ended, thoughtful/mature response expected at this level."),
    Q("Whole-section check: What has each character hoped for so intensely this week?", "Open — Josef: acceptance/normalcy again; Isabel: reaching Miami; Mahmoud: safe passage through the border."),
  ],
},
{
  num: 8, title: "The Turning Point", chapters: "Chapters 43–48",
  LI: "We are learning to explain how a single decision or event can become the turning point of an entire storyline.",
  SC: "I can identify the turning point in each storyline this week and explain why it changes everything that follows.",
  rubricTags: ["R4","R6","R8"],
  days: {
    mon: D("Chapter 43", "Josef: watching his sister Ruthie play in the ship's pool, the uncertainty of their fate still unresolved",
      "How do you think it would feel to enjoy a small, ordinary pleasure while your family's entire future still hangs in the balance?",
      "What does Josef notice about Ruthie and the other children in this chapter, and how does it contrast with the adults' mood?",
      "Why might the author include a quiet, almost peaceful scene right before a major turning point in the story?",
      "Write about a small, ordinary joy you'd want to hold onto even during a much bigger crisis."),
    tue: D("Chapter 44", "Isabel: the devastating news that they are being turned back to Cuba",
      "What would it feel like to come so close to safety, only to be told you must go back to the very danger you escaped?",
      "What decision is made about Isabel's family and the other refugees at sea?",
      "Why might this moment be considered the turning point of Isabel's whole storyline so far?",
      "Write about a time you got extremely close to something you wanted badly, only to have it taken away at the last moment."),
    wed: D("Chapter 45", "Mahmoud: confronted at gunpoint by a Serbian taxi driver",
      "What would you do if someone in a position of power over your safety suddenly threatened you with violence?",
      "What happens in this confrontation, and how does the family get through it?",
      "Why might this moment mark a turning point in how Mahmoud sees adults and authority figures in general?",
      "Write about how you imagine your own sense of trust in strangers would change after an experience like this one."),
    thu: D("Chapters 46–48", "Josef: the St. Louis is forced to turn back toward Europe, the passengers' worst fear realised; Isabel: forced onto a path back toward Cuba; Mahmoud: taken to a crowded, muddy refugee camp",
      "Why do you think turning points in a crisis often make things worse before any of the characters can find a way forward?",
      "Compare: what do the setbacks facing Josef and Isabel this week have in common, even though their situations are decades apart?",
      "Why might the author choose to bring all three storylines to a low point in the very same week of reading?",
      "Write your own reflection on which of the three storylines' turning points affected you the most, and why."),
  },
  projects: [
    P("poster", "The Turning Point", "Design a poster identifying and illustrating the single turning-point moment for each of the three storylines this week."),
    P("comic", "Turned Away", "Show, panel by panel, the moment Isabel's family learns they are being sent back toward Cuba."),
    P("drama", "At Gunpoint", "Act out — respectfully and without glorifying violence — the tense confrontation between Mahmoud's family and the taxi driver, focusing on how the family stays calm and gets through it."),
    P("journal", "The Worst Moment, So Far", "Write about which of this week's three turning points felt hardest to read, and explain why, using evidence from the text."),
  ],
  quiz: [
    Q("What does Josef notice Ruthie doing in Chapter 43?", "Playing/splashing happily in the ship's swimming pool."),
    Q("What devastating decision is made about Isabel's family and the other refugees at sea?", "They are being sent/turned back toward Cuba."),
    Q("Vocabulary: What does it mean for a decision to be a \"turning point\" in a story?", "A key moment that changes the direction of events from that point on."),
    Q("Who threatens Mahmoud's family at gunpoint?", "A Serbian taxi driver."),
    Q("True or False: The confrontation with the taxi driver ends in violence against the family.", "False — the family gets through the confrontation without being harmed, though deeply frightened.", "tf"),
    Q("What ultimately happens to the MS St. Louis and its passengers?", "The ship is forced to turn back toward Europe after being refused entry."),
    Q("Where is Mahmoud's family taken in Chapter 48?", "A crowded, muddy refugee camp."),
    Q("Vocabulary: What does \"refused entry\" mean, in the context of the St. Louis?", "Not allowed to dock/disembark passengers in a country."),
    Q("Why might Ruthie's carefree pool scene feel especially poignant, given what we know is about to happen?", "Open-ended — dramatic irony; the reader knows more than the character, heightening emotional impact."),
    Q("What do Josef's and Isabel's setbacks this week have in common?", "Open — both are forced back toward the danger they were trying to escape, by official/government decisions."),
    Q("Why might the author choose to bring all three storylines to a low point in the same week?", "Open-ended — builds maximum tension before the climax, shows how connected/universal these struggles are."),
    Q("Vocabulary: What does \"turning point\" mean when used to describe a character's view of the world, not just the plot?", "A moment that permanently changes how a character understands their situation or other people."),
    Q("How might the gunpoint confrontation change Mahmoud's sense of safety going forward?", "Open-ended — likely increased fear/distrust, but also possibly resolve to keep protecting his family."),
    Q("What does the muddy, crowded refugee camp suggest about the conditions many real refugees face, according to the author's note?", "Open — harsh, under-resourced, difficult conditions common to real refugee camps."),
    Q("True or False: By the end of this week, every character's journey appears to be heading toward a positive resolution.", "False — all three are at or near their lowest point.", "tf"),
    Q("Predict: What do you think it will take for each storyline to move toward resolution from here?", "Open-ended, text-supported prediction."),
    Q("Why might turning points often involve decisions made by people in power, rather than the refugees themselves?", "Open-ended — highlights how little control refugees often have over their own fate."),
    Q("What emotion do you think unites Josef, Isabel and Mahmoud most strongly at this point in the book?", "Open — accept despair, exhaustion, fear, or determination, if justified."),
    Q("Whole-section check: What decision-makers (governments, officials, individuals) have shaped events for each character so far?", "Open, text-based — accept Cuban officials/Nazi agents (Josef), US/Cuban governments (Isabel), border police/smugglers (Mahmoud)."),
    Q("Why does the author title this section around a \"turning point\" rather than a \"disaster\"?", "Open-ended — turning point implies change and possibility, not only loss; sets up the resolution to come."),
  ],
},
{
  num: 9, title: "Three Endings, One Thread", chapters: "Chapters 49–54 (book finishes)",
  LI: "We are learning to evaluate how an author resolves multiple storylines and connects them with a twist, and to form our own justified opinion about the ending.",
  SC: "I can explain how the three storylines are connected at the end of the book, and give my own opinion about the ending, backed up with evidence.",
  rubricTags: ["R4","R6","R10"],
  days: {
    mon: D("Chapter 49", "Josef: the Nazis catch Josef, his mother and Ruthie in the woods; Josef makes the ultimate sacrifice so his sister can go free",
      "If you had to make one impossible choice to protect someone you love, what do you think would help you find the courage to make it?",
      "What choice does Josef make when the soldiers say only one of the children can be spared, and why does he make it?",
      "Why might the author choose to have Josef, who spent the book wanting to \"be a man\", prove it through this ultimate act of self-sacrifice?",
      "Write a short tribute or eulogy for Josef, reflecting on who he became by the end of his story."),
    tue: D("Chapter 50", "Isabel: her baby brother Mariano is born on the boat, and her family is rescued right at the US shoreline",
      "What do you think it means that a new life enters the story at almost the exact same moment the family is fighting hardest to survive?",
      "What happens during the birth of Mariano, and how does the crossing finally end for Isabel's family?",
      "Why might the author choose to have a birth — new life — occur at the story's most dangerous, climactic moment?",
      "Write about the moment Isabel finally reaches the shore, from her own point of view, in her own voice."),
    wed: D("Chapter 51", "Mahmoud: the family joins a mass march of refugees to the Austrian border, and is finally welcomed with open arms",
      "How do you think it would feel to go from being seen as a threat to being welcomed with genuine kindness, almost overnight?",
      "What happens when Mahmoud's family reaches Austria, and how are they treated compared to earlier in their journey?",
      "Why might the author choose to end Mahmoud's main journey with such an overwhelming, positive welcome?",
      "Write a thank-you note from Mahmoud to the Austrian and German strangers who helped his family."),
    thu: D("Chapters 52–54", "Isabel: months later, playing \"The Star-Spangled Banner\" salsa-style at her new school; Mahmoud: arriving at the Rosenberg house in Berlin and discovering the old woman, Ruthie, is Josef's very own sister",
      "What do you think it means to carry your culture and identity with you into a completely new life, rather than leaving it behind?",
      "How does Isabel honour where she came from in her final scene, while also embracing her new home?",
      "What is the twist the author reveals about Frau Rosenberg, and how does it connect Josef's story to Mahmoud's, decades later?",
      "Write your own reflection: which of the three endings did you find most powerful, and why? Use evidence from the text."),
  },
  projects: [
    P("poster", "The Hidden Connection", "Design a poster revealing and explaining the twist that connects Josef's story to Mahmoud's story through Ruthie Rosenberg."),
    P("comic", "Three Endings", "Show one key final image from each of the three storylines' endings, panel by panel, with a one-line caption for each."),
    P("drama", "The Rosenberg Doorway", "Act out — with care and respect — the moment Mahmoud meets Ruthie Rosenberg and learns her story, staying true to the emotional tone of the text."),
    P("journal", "Did the Ending Earn Its Hope?", "Write your own opinion on whether the book's hopeful ending feels earned, given everything the characters went through, using evidence to support your view."),
  ],
  quiz: [
    Q("What choice does Josef make when the Nazis say only one child can be spared?", "He tells them to take him, so his sister Ruthie can go free."),
    Q("True or False: Josef survives to the end of the book.", "False — he sacrifices himself so Ruthie can live.", "tf"),
    Q("What happens to Isabel's family at the very end of their sea crossing?", "Isabel's baby brother, Mariano, is born on the boat, and the family is rescued/reaches the shore together."),
    Q("Vocabulary: What does \"climactic\" mean, and why is Mariano's birth a climactic moment?", "Relating to the most intense, important point in a story; it happens at the peak of danger and resolution together."),
    Q("How is Mahmoud's family treated once they cross into Austria?", "They are welcomed warmly, given food, clothing and support by strangers."),
    Q("What does Isabel play at her new school in Miami, and how does she play it?", "\"The Star-Spangled Banner\", played in a Cuban salsa/son cubano style."),
    Q("What is the surprising twist revealed about the elderly woman who hosts Mahmoud's family in Berlin?", "She is Ruthie — Josef's own sister, now an old woman, who survived the war."),
    Q("True or False: Ruthie Rosenberg has no connection to any other character in the book.", "False — she is revealed to be Josef's sister, connecting all three storylines.", "tf"),
    Q("Why does Josef choose self-sacrifice instead of trying to save himself?", "Open — his love for his sister, and his long-held wish to prove he was 'a man', come together in this final act."),
    Q("Why might the author choose to have Isabel's new life scene focus on music rather than something else?", "Open-ended — music represents identity, heritage and hope carried forward into a new home."),
    Q("What does the Rosenberg twist suggest about how the past and present are connected?", "Open-ended — history repeats and echoes; kindness (or cruelty) can ripple forward across generations."),
    Q("Vocabulary: What does \"legacy\" mean, and how does Josef leave one even though he dies as a child?", "What is left behind/passed on after someone is gone; his sacrifice allows Ruthie to live, marry, have a family, and eventually welcome Mahmoud's family."),
    Q("Do you think the ending of Josef's story is a tragedy, or does it have hope in it too? Explain your view.", "Open-ended, opinion-based, must reference the text."),
    Q("Whole-book review: What is the very first major event that sets each character's journey in motion?", "Josef — Kristallnacht; Isabel — the Havana riots/family hardship; Mahmoud — the missile strike on his apartment."),
    Q("Whole-book review: Name one adult in the book who shows real courage in protecting the children in their care.", "Open — accept Captain Schroeder, Señor Castillo, Josef himself, Mahmoud's parents, etc., with reasoning."),
    Q("Whole-book review: What theme do you think this book explores most strongly?", "Open-ended — e.g. the cost and courage of seeking safety, found family, the long reach of history, empathy across difference."),
    Q("Whole-book review: How does the interwoven structure (three timelines) change the impact of the ending, compared to if the stories had been told separately?", "Open-ended — the connection between Josef and Mahmoud's storylines would be impossible without reading them side by side."),
    Q("Do you agree with how the author chose to end the book? Explain your opinion with evidence.", "Open-ended, opinion-based, must reference the text."),
    Q("What real historical facts from the author's note most changed how you understood the fictional story?", "Open-ended, personal response referencing the author's note."),
    Q("What is the one big idea from this whole book you will remember most?", "Open-ended, personal response."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "Three Journeys, One Message Campaign", desc: "Create a campaign (posters, slogans, a short speech) making the case for what the world owes people fleeing danger, using evidence from Josef's, Isabel's and Mahmoud's stories." },
    { title: "Character Case File", desc: "An in-depth profile (poster + written report + panels) tracking ONE of the three protagonists' whole journey — their fears, choices and growth — with evidence from the beginning, middle and end of their storyline." },
    { title: "Extended Scene: An Untold Perspective", desc: "Write and perform a new scene from a perspective the book doesn't fully show us — a Cuban official, a German host family, the sailors who rescued Hana — told with empathy, not as a simple villain or footnote." },
    { title: "\"How My Family Adapted\" Class Anthology", desc: "Each student contributes one illustrated page titled \"How My Family Adapted\", a real story of a time their own family (or a family they know) had to adapt to major change, echoing the courage shown in the book." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: connect with a real refugee-support organisation as a class action step.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events from one storyline.",
      wt: "Explains some of a character's motivations or relationships, with limited evidence, or from only one storyline.",
      a: "Explains a theme (courage, belonging, sacrifice) and supports it with clear evidence from at least two of the three storylines.",
      example: "A Character Case File showing Mahmoud changing from 'invisible' to visibly welcomed, with an event from the beginning, middle and end of his story." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A campaign poster with a clear message, three persuasive reasons drawn from the text, and imagery that matches the message respectfully." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A scene from an untold perspective that is historically plausible, empathetic, and rehearsed/improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
