/* ============================================================
   THE ONE AND ONLY IVAN — BOOK CLUB APP DATA
   Content data only. No markup/behaviour lives in this file.
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Empathy, Art & Courage", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 3 (Years 5–6).
   "Achieved" = the curriculum expectation has been met.
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas of the story (voice, freedom, chosen family, using what you have) and supports them with events from the book, making links beyond the text to self or the world.",
    kid: "I can explain a big idea from the story and back it up with something that happened in the book.",
    ask: "Does the student explain WHY an event matters — not just WHAT happened?",
    na: "Retells some events but cannot yet explain what they mean. Answers are mostly 'what happened'.",
    wt: "Names a big idea (e.g. 'it's about a gorilla who paints') with a general reason, but the link to the book is vague or missing.",
    ach: "Explains a big idea and supports it with a specific event from the book. Makes a link beyond the text (to self or the world).",
    wtSample: "The book is about a gorilla who paints pictures.",
    exemplar: "I think the biggest idea is that everyone needs a voice, even if they can't use words. Ivan can't talk, but his paintings said 'HOME' louder than anything Mack ever said. It's like my little brother, who uses pictures to show his feelings because he doesn't have the words yet — everyone deserves a way to be heard.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-away reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of how texts are shaped for different purposes and audiences, and how language features are used for effect.",
    expect: "Notices the choices the author makes — Ivan's first-person voice, tiny one-word chapter titles, very short chapters, sparse or fragmented sentences — and explains how they affect the reader.",
    kid: "I can notice how the author wrote the book and explain how it makes the reader think or feel.",
    ask: "Does the student name a writer's choice AND say what effect it has on the reader?",
    na: "Comments only on the plot; does not yet notice how the book is written.",
    wt: "Notices a feature (e.g. 'the chapters are really short') but cannot explain its effect.",
    ach: "Names a writer's choice and explains its effect on the reader, using an example from the book.",
    wtSample: "The chapters are really short and they all have one-word titles.",
    exemplar: "Katherine Applegate writes in Ivan's own quiet voice, using very short chapters — some are just one sentence, like 'gone.' It feels like the careful, patient way Ivan thinks, and the short chapters make the sad parts hit harder because there's nowhere for the feeling to hide.",
    evidence: "Structure/voice questions (esp. Weeks with R2), inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, making connections, summarising — and links earlier chapters to later ones (cause and effect across the book).",
    kid: "I can use reading strategies and link what happened earlier in the book to what happens later.",
    ask: "Can the student connect an earlier event to a later one without being told?",
    na: "Relies on the teacher to explain the story; does not yet connect chapters.",
    wt: "Uses a strategy when prompted (e.g. predicts when asked) and makes simple links between chapters.",
    ach: "Independently uses strategies and explains how an earlier event causes or sets up a later one.",
    wtSample: "Stella asked Ivan to help Ruby and then he did.",
    exemplar: "In Week 3, Stella made Ivan promise to keep Ruby safe before she died. That promise is why, in Week 5, Ivan starts secretly painting at night — he's trying to keep his promise the only way a gorilla behind glass can, with his art, because he can't talk to humans directly.",
    evidence: "Predictions, cause-and-effect questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics.",
    expect: "Writes and shares clear, developed ideas about the book — opinions, explanations and reflections — with supporting detail.",
    kid: "I can share a clear idea or opinion and give reasons to support it.",
    ask: "Is there a clear idea PLUS at least two reasons or details?",
    na: "Answers are one word or unclear; ideas are not explained.",
    wt: "Shares a clear idea but gives little detail or only one reason.",
    ach: "Communicates a clear opinion or idea and develops it with at least two reasons or pieces of evidence.",
    wtSample: "I think Ivan did the right thing because he's a good gorilla.",
    exemplar: "I think Ivan was right to keep painting even when it seemed hopeless. First, giving up would have meant breaking his promise to Stella. Second, art was the only power he actually had — he couldn't unlock a cage, but he could make a picture that no one could ignore. Sometimes the only tool you have is enough.",
    evidence: "Go-away reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Use language features appropriately, showing a developing understanding of their effects; organise texts using a range of structures.",
    expect: "Chooses the right structure and language for the task — a log entry in Ivan's spare, logical voice, a persuasive protest sign, a news report, a comic.",
    kid: "I can choose the right kind of writing and words for the job (like a log entry, a protest sign or a news report).",
    ask: "Does the writing look and sound like the form it's meant to be?",
    na: "Writing does not match the task; little attempt at structure or language features.",
    wt: "Attempts the right form (e.g. writes a diary) but the language or structure is inconsistent.",
    ach: "Uses a suitable structure and language features for the purpose and audience (e.g. Ivan's plain, patient voice for a log; a punchy slogan for a protest sign).",
    wtSample: "Dear diary, today was sad because Stella died and I am sad.",
    exemplar: "DAY 9,876. Stella is gone. I do not have a heart made of ice, whatever she said. I have made a promise. I do not yet know how a gorilla keeps a promise to the human world. I will find out.",
    evidence: "Poster, comic, drama & journal projects; Week 9 final writing" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback to improve it.",
    kid: "I can plan my work, improve it, and use feedback to make it better.",
    ask: "Can you see a plan AND a change made because of feedback?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wt: "Plans and drafts with support; makes small changes when prompted.",
    ach: "Independently plans, drafts and revises, and uses feedback (e.g. Glow & Grow) to improve the work.",
    wtSample: "I finished my poster. My teacher told me to add more colour so I did.",
    exemplar: "My comic plan had three parts: Ivan painting alone, Julia not understanding, then the puzzle clicking into place. My partner's 'grow' said the middle was confusing, so I added a panel showing Julia's face change from confused to excited. Now you can see the exact moment she gets it.",
    evidence: "Project plans, Week 9 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas.",
    expect: "Listens to and builds on others' ideas during group reading and projects, and takes turns fairly.",
    kid: "I can listen to my group, take turns, and build on other people's ideas.",
    ask: "Does the student respond to what others say, not just wait for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt or opt out.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I don't think Mack's a total bad guy — I think he's just always seen Ivan as money, not family, the way George never did.\" She then asked a quieter group member what they thought about Mack.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas.",
    expect: "Makes inferences — works out what characters feel and why — using clues from the text, and thinks creatively about possibilities.",
    kid: "I can use clues in the story to work out things the author doesn't tell me directly.",
    ask: "Has the student worked something out AND pointed to the clue?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wt: "Makes an inference with prompting but struggles to explain the clue.",
    ach: "Independently infers feelings or motives and points to the clue in the text that shows it.",
    wtSample: "Ivan is sad about Stella.",
    exemplar: "The text never says Ivan is grieving, but he says he'd 'give all the yogurt raisins in all the world for a heart made of ice' — that clue tells me he's in so much pain he almost wishes he couldn't feel it, which shows how deeply he loved Stella.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility.",
    expect: "Contributes ideas in class discussions and projects, and takes responsibility for a role in group work.",
    kid: "I can share my ideas and do my part in group work.",
    ask: "Does the student offer ideas and take on a job without being asked?",
    na: "Rarely contributes to discussions or group projects.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ach: "Offers ideas without being asked, takes responsibility for a role, and encourages others.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the mural poster.",
    exemplar: "(Observed) In the Week 9 drama group, Aroha volunteered to play Julia, wrote a running order for every scene, and made sure the quietest group member got to read the 'H-O-M-E' reveal line aloud.",
    evidence: "Class discussions, project work, Week 9 group project & gallery walk" },

  { code: "R10", label: "Empathy, Art & Courage", strand: "Values",
    curriculum: "Values: diversity, community and participation, respect, and care for others and the environment.",
    expect: "Connects the book's values — using whatever you have (even art) to speak up, noticing another's suffering, and finding quiet courage — to their own life and actions.",
    kid: "I can connect the book's message about empathy, art and courage to my own life.",
    ask: "Has the student linked a value from the book to something real in their own life?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wt: "Names a value (e.g. 'be kind to animals') when asked, with a simple or general link.",
    ach: "Explains a value from the book and connects it to a real experience or action of their own.",
    wtSample: "The book teaches us to be kind to animals.",
    exemplar: "Ivan used the one thing he was good at — art — to fight for Ruby's freedom, because he couldn't fight with words or force. That reminded me of when I noticed a kid getting left out at lunch. I didn't have a big plan, but I could invite them to sit with us. You don't need to be the strongest — you just need to use what you have.",
    evidence: "Go-away reflections, journal entries, Week 9 'What I Have to Give' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 3–4 English, Years 5–6, NZ Curriculum",
  lrv: [
    "Ideas: Show understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show understanding of how texts are shaped for different purposes and audiences.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies confidently to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics.",
    "Structure and Language: Show understanding of language features, using them appropriately.",
    "Processes and Strategies: Select and use processes and strategies to communicate confidently.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Empathy across species and difference, courage to act for someone vulnerable, integrity and community, respect for living things.",
  crossCurricular: "Visual Arts — art as communication and testimony — and Social Sciences (animal welfare, media and activism, how ordinary people create real change), since Ivan's secret finger-paintings turn into a real campaign that frees his friend.",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "Hello, I Am Ivan", chapters: "Chapters 1–19",
  LI: "We are learning to notice what a narrator's own words reveal about how he sees himself, even when he doesn't name his feelings directly.",
  SC: "I can find a line where Ivan describes himself or his world and explain what it tells me about how he feels.",
  rubricTags: ["R1","R2","R8"],
  days: {
    mon: D("Chapters 1–5", "Ivan introduces himself, his looks, and the Exit 8 Big Top Mall",
      "If people gave you three different nicknames, would you rather choose your own name instead? Why does a name matter?",
      "What does Ivan say humans call him, and what name does he say is truly his own?",
      "Ivan says 'anger is precious' and that a silverback uses it 'to protect.' What does this tell you about how Ivan sees himself, even though the billboard makes him look fierce and angry?",
      "Draw or describe Ivan's domain using only the details he gives us in these chapters."),
    tue: D("Chapters 6–10", "The Littlest Big Top on Earth; Julia's crayon; Ivan the artist",
      "Have you ever made something — a drawing, a Lego model, a sandcastle — that you were proud of, even if no one else understood it?",
      "What does Julia slip through the broken glass that changes Ivan's days, and what does he do with it?",
      "Ivan says humans don't always recognise what he's drawn, but that he isn't 'drawing for them.' What does this tell us about why art matters to Ivan?",
      "If you could draw anything at all — real or imagined — right now, what would it be, and why?"),
    wed: D("Chapters 11–15", "\"The loneliest gorilla in the world\"; TV; Stella",
      "Has there ever been a time you felt like the 'only one' of something — the only new kid, the only person who liked a certain thing?",
      "What does a little boy call Ivan through the glass, and how does Ivan wish he could respond, even though he can't?",
      "When Ivan sees a wild gorilla on a nature show, he wonders if there's a 'she' out there too. What does this brief moment of hope tell us about what Ivan has been missing?",
      "Write two sentences to the little boy who called Ivan 'the loneliest gorilla in the world,' explaining how Ivan might really feel."),
    thu: D("Chapters 16–19", "A plan; Bob the dog; \"Picasso\"",
      "If you thought people were losing interest in you, what plan — silly or serious — might you come up with to fix it?",
      "What is Ivan's plan to bring in more visitors, and why doesn't it work the way he hopes?",
      "Bob says 'everywhere is my home... I am a wild beast.' What does this tell us about how Bob sees freedom, compared to how Ivan and Stella live?",
      "Write a short introduction of yourself the way Ivan introduces himself in Chapter 1 — plain, honest, and true to who you are."),
  },
  projects: [
    P("poster", "Meet the Big Top Mall", "Design a poster map of the Exit 8 Big Top Mall and Video Arcade, labelling Ivan's domain, Stella's domain, the ring and the gift shop, using only details from the text."),
    P("comic", "A Gorilla's Morning", "6 panels showing a typical day for Ivan: waking up, watching TV with Bob, drawing, and visitors at the glass."),
    P("drama", "The Faded Billboard", "In pairs, act out two mall visitors reading the faded billboard and arguing about whether Ivan really looks as \"angry\" as the picture."),
    P("journal", "My Own Domain", "Describe your own bedroom or a favourite space the way Ivan describes his domain — noticing every small detail, the way only someone who has looked at it for years would."),
  ],
  quiz: [
    Q("What kind of animal is Ivan?", "A gorilla — a silverback."),
    Q("What does Ivan call the mall he lives in?", "The Exit 8 Big Top Mall and Video Arcade."),
    Q("True or False: Ivan says humans can't understand him at all.", "False — he can understand human speech; it's harder the other way around.", "tf"),
    Q("Who is Stella?", "An elephant, one of Ivan's two closest friends."),
    Q("Who is Bob?", "A stray dog who sleeps on Ivan's belly."),
    Q("Vocabulary: What does \"domain\" mean, as Ivan uses it?", "The space he lives in — his enclosure (he prefers this word to \"cage\")."),
    Q("How did the crack in Ivan's glass wall happen?", "He hit it with a baseball bat Mack gave him for his sixth birthday."),
    Q("Who gave Ivan his first crayon?", "Julia."),
    Q("What does Ivan call his stuffed toy gorilla, and why that name?", "Not-Tag — Tag was his twin sister's name."),
    Q("True or False: Ivan's drawings are sold at the mall's gift shop.", "True.", "tf"),
    Q("What nickname does Mack give Ivan when it's time to draw?", "\"Picasso.\""),
    Q("Why does Ivan mostly draw things like banana peels and candy wrappers?", "They're the simple items that fill his domain — and he often eats his subjects before drawing them."),
    Q("What does Ivan see on TV that gives him hope he isn't \"the last gorilla on earth\"?", "A nature show with a wild gorilla."),
    Q("True or False: Stella used to perform in a large, famous circus.", "True.", "tf"),
    Q("What happened to Stella's foot?", "She fell off a pedestal doing a trick; it never healed properly and gets infected."),
    Q("Vocabulary: What is a \"claw-stick\"?", "A stick with a hook, used by some trainers to control or hurt an animal."),
    Q("Why does Mack think Ivan has \"lost his magic\"?", "Fewer visitors are coming to see him; he says Ivan is \"not cute anymore.\""),
    Q("What does Bob say when Ivan invites him to work in the shows like Snickers?", "He refuses — he calls himself a wild beast, and says poodles are \"parasites.\""),
    Q("Inference: Why might the author have Ivan describe human habits — spending money, chattering — the way we might describe animals?", "Open-ended — it flips our perspective, making us see ourselves as strange, the way Ivan sees us."),
    Q("Predict: What do you think \"the plan\" Ivan comes up with in Chapter 16 might be?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 2, title: "Julia, Mack, and a New Neighbour", chapters: "Chapters 20–42",
  LI: "We are learning to notice how repeated small moments build a relationship between two characters, even without one big dramatic event.",
  SC: "I can describe how Ivan and Julia's friendship grows through small, everyday moments, using examples from at least two different days.",
  rubricTags: ["R1","R3","R7"],
  days: {
    mon: D("Chapters 20–26", "Cruel visitors; Julia and George; Bob gets his name",
      "Have you ever done or said something in anger that you regretted straight after? What did you do about it?",
      "What do two child visitors do to Ivan through the glass, and how does he first respond?",
      "Ivan says 'my mother would be ashamed of me' after calling the children 'slimy chimps.' What does this brief apology reveal about Ivan's own values, even in a moment of anger?",
      "Write about Julia and her father George's nightly routine at the mall, using details from the text."),
    tue: D("Chapters 27–32", "A sleepless night; the Jambo story; a hint of change",
      "Do you know all your family's stories the way Stella remembers everything? Why might remembering matter?",
      "In the Jambo story, what does the silverback Jambo do when a human boy falls into his enclosure?",
      "Stella tells Ivan there's a difference between 'can't remember' and 'won't remember.' What might this suggest about why Ivan doesn't remember his early life?",
      "Retell the Jambo story in your own words, as if you were telling it to a younger student."),
    wed: D("Chapters 33–37", "Ruby arrives",
      "Imagine arriving somewhere brand new, tiny and scared, with no family. Who would you want to greet you?",
      "How does Stella help calm the new baby elephant down when she first arrives in the truck?",
      "Stella tells Ivan the baby elephant's circus training was 'to break her spirit.' What does this reveal about how the trainers saw her?",
      "Write Ruby's very first thoughts as she is led, terrified, down the truck ramp."),
    thu: D("Chapters 38–42", "Getting to know Ruby",
      "What questions would a curious younger child ask you about your everyday life, if they'd never seen it before?",
      "What does Ruby ask Ivan about his art, and how does he answer her?",
      "When the billboard is updated with a cute picture of Ruby that 'doesn't even look like an elephant,' what does this suggest about how Mack sees Ruby versus how Ivan sees her?",
      "Write three of Ruby's curious questions and Ivan's patient answers, in your own words."),
  },
  projects: [
    P("poster", "Big Top Mall Field Guide", "Design a field-guide page introducing a new animal (real or invented) to the mall, the way Stella and Ivan try to help Ruby understand her new home."),
    P("comic", "The Jambo Story", "Illustrate Stella's story of the silverback Jambo and the boy who fell into his enclosure, in 6 panels."),
    P("drama", "Ruby's First Morning", "Act out Ruby's first conversation with Ivan and Bob, including her joke about baby elephants."),
    P("journal", "A Question I've Never Asked", "Write about a question you've always wondered but never asked an adult, the way Ruby asks Ivan almost everything."),
  ],
  quiz: [
    Q("What do the two child visitors do to Ivan through the glass?", "They spit and throw pebbles at him."),
    Q("True or False: Ivan feels proud of calling the children \"slimy chimps.\"", "False — he apologises straight after.", "tf"),
    Q("Who is Julia's father, and what is his job at the mall?", "George; he cleans the mall each night."),
    Q("What does Julia give Bob that no one had ever given him before?", "His name."),
    Q("Vocabulary: What does \"cautious\" mean?", "Careful; not taking risks."),
    Q("In the Jambo story, what does the silverback do when the boy falls into his enclosure?", "He examines and gently protects the boy, then leads his troop calmly away."),
    Q("True or False: Stella remembers every detail of her past.", "True.", "tf"),
    Q("What new animal arrives at the mall in this section?", "A baby elephant named Ruby."),
    Q("Vocabulary: What does \"shackle\" mean?", "A chain or restraint used to bind an animal."),
    Q("Why is watching Ruby's arrival so hard for Stella?", "Ruby is chained the same way Stella herself once was, \"to break her spirit.\""),
    Q("True or False: Ruby was born and raised inside a circus, just like Stella.", "False — Ruby was born in the wild and captured young.", "tf"),
    Q("What does Ruby ask Ivan to draw for her?", "A refrigerator, and then a banana."),
    Q("Vocabulary: What does \"forage\" mean?", "To search for and find food."),
    Q("Why does the mall's billboard get a new picture added?", "To attract more visitors, using Ruby's arrival."),
    Q("True or False: The picture of Ruby added to the billboard looks exactly like her.", "False — Ivan says he could have drawn her better.", "tf"),
    Q("What kind of joke do Ivan and Ruby share about elephants?", "Silly logic jokes — like footprints in the butter, and \"baby elephants\" being what elephants have that nothing else does."),
    Q("Inference: Why might Ivan feel a mix of jealousy and tenderness about Ruby getting all the attention?", "Open-ended."),
    Q("What does Stella tell Ivan about Ruby's training at her old circus?", "She was chained by all four feet, twenty-three hours a day, to break her spirit."),
    Q("Predict: How do you think Ivan's role in Ruby's life will change over the coming weeks?", "Open-ended, text-supported prediction."),
    Q("What does Bob mean when he tells Ivan, \"Give it up, Ivan, you're old news\"?", "Visitors' attention has shifted from Ivan to the new baby elephant."),
  ],
},
{
  num: 3, title: "Stella's Promise", chapters: "Chapters 43–59",
  LI: "We are learning to notice how an author uses a single moment — a promise, a death, a memory — to change the direction of a whole story.",
  SC: "I can explain how the promise Ivan makes to Stella changes what he does for the rest of the book.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapters 43–46", "Ruby's rescue story; Ruby performs alone",
      "Do you think you could ever forgive someone if you found out something painful happened by mistake, not on purpose?",
      "What does Ruby say happened to her family, and how did she end up at the Big Top Mall?",
      "Ruby insists 'those humans were good' about the villagers who rescued her, even though other humans killed her family. What does this show about how Ruby sees the world?",
      "Write about a time something confusing happened where the 'good guys' and 'bad guys' weren't so clear."),
    tue: D("Chapters 47–50", "Stella grows ill; the promise; Stella dies",
      "Has anyone ever asked you to promise something really important? How did it feel to say yes?",
      "What does Stella ask Ivan to promise her, late one night?",
      "Ivan says it 'would be easier to promise to stop breathing... than to stop being a gorilla' — yet he still promises. What does this reveal about how seriously Ivan takes his word?",
      "Write about a promise you have made to someone, and whether it was hard to keep."),
    wed: D("Chapters 51–55", "Grief; Ivan begins to remember his past",
      "When someone you love is grieving, what's something small you can do or say to help, even if you can't fix everything?",
      "How does Bob try to comfort Ivan the night after Stella dies?",
      "Ivan begins, 'Once upon a time there was a gorilla named Ivan,' and for the first time deliberately tries to remember his past. What might this show about why grief sometimes makes us look backward?",
      "Write two sentences of comfort you would say to Ruby, if you were Ivan, on the night Stella dies."),
    thu: D("Chapters 56–59", "Ivan's jungle childhood; capture",
      "What is one happy memory from when you were very young that you still remember clearly?",
      "How did young Ivan get his childhood name, \"Mud\"?",
      "Ivan describes his early life as 'a perfect life,' right before the very next chapter, titled simply 'the end.' Why might the author put these two chapters right next to each other?",
      "Draw or describe the moment Ivan's peaceful jungle life ends, using only what the text tells you."),
  },
  projects: [
    P("poster", "Keep the Promise", "Design a poster showing Ivan's promise to Stella as if it were a hero's mission statement."),
    P("comic", "Mud", "Illustrate the moment young Ivan's family discovers his love of drawing and gives him his first name."),
    P("drama", "The Night of the Promise", "Act out the quiet, late-night conversation where Stella asks Ivan to promise to protect Ruby."),
    P("journal", "What I'd Remember", "If you could only keep ten memories for the rest of your life, which ten would you choose, and why?"),
  ],
  quiz: [
    Q("How did Ruby originally get separated from her family and end up captured?", "She fell into a hole villagers had dug near their village while her family searched for food."),
    Q("True or False: Both bad humans and good humans appear in Ruby's own story.", "True.", "tf"),
    Q("What is wrong with Stella's foot at the start of this section?", "It's badly swollen and infected again."),
    Q("What does Stella ask Ivan to promise?", "To take care of Ruby and give her a safe, different life."),
    Q("Vocabulary: What does \"addled\" mean, as Stella describes her own pain-clouded thinking?", "Confused; muddled."),
    Q("True or False: Mack calls a vet the moment Stella first gets sick.", "False — he waits, saying a vet costs money.", "tf"),
    Q("How does Stella die?", "Overnight, off the page; Bob later learns her body was taken away in a garbage truck."),
    Q("What does Ivan say he would trade \"all the yogurt raisins in all the world\" for?", "A heart made of ice — so grief wouldn't hurt so much."),
    Q("What does Bob do to help Ivan remember he is still \"the One and Only Ivan, Mighty Silverback\" after Stella dies?", "He licks Ivan's nose until Ivan says the words himself."),
    Q("What was Ivan's twin sister's name?", "Tag."),
    Q("How did young Ivan get the nickname \"Mud\"?", "He loved drawing with mud on rocks, bark, and his mother's back."),
    Q("Vocabulary: What is a \"troop,\" as gorillas use the word?", "A gorilla family group."),
    Q("Who led Ivan's family troop, and what were his three roles according to Ivan?", "His father, the silverback — a guide, a teacher, and a protector."),
    Q("True or False: Ivan describes his early jungle life as \"a perfect life.\"", "True.", "tf"),
    Q("What one-sentence chapter follows immediately after \"a perfect life,\" and what does it announce?", "\"the end\" — the day the humans came."),
    Q("Inference: Why might the author reveal Ivan's tragic past only after we already know and love him?", "Open-ended — to build sympathy and understanding gradually, rather than starting with trauma."),
    Q("What does this section suggest about how grief can make someone start remembering their past?", "Open-ended."),
    Q("Predict: Now that Ivan has promised to protect Ruby, what do you think he might try to do, given that he cannot leave his domain?", "Open-ended, text-supported prediction."),
    Q("True or False: Ivan finds it easy to talk about what he is \"tired of.\"", "False — he says gorillas are \"not complainers,\" and it's hard to put into words.", "tf"),
    Q("Whole-section review: What is \"the promise,\" and who made it to whom?", "Ivan promised Stella, as she was dying, that he would keep Ruby safe."),
  ],
},
{
  num: 4, title: "What Ivan Remembers", chapters: "Chapters 60–73",
  LI: "We are learning to compare a character's past and present selves, and explain what has changed and what hasn't.",
  SC: "I can compare young Ivan's life with Mack and Helen to his life now, and explain what stayed the same and what changed.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapters 60–64", "Life as a \"temporary human\"; the frosting incident",
      "Have you ever wanted to make or create something so badly that you used materials you weren't supposed to — like frosting, mud, or markers on a wall?",
      "What happened to Ivan's twin sister, Tag, after they were captured?",
      "Ivan says he 'wanted to be an artist again' the moment he sees the still-life painting and starts finger-painting with cake frosting. What does this reveal about how central art has always been to who Ivan is?",
      "Write about a time you got in trouble for making something, even though making it felt important to you."),
    tue: D("Chapters 65–68", "Growing too big for human life; the domain; counting the days",
      "How do you think it would feel to move from a family's house into your very own room for the first time — exciting, lonely, or both?",
      "Why did Mack eventually move Ivan out of the house and into the domain at the mall?",
      "Ivan says he 'always know[s] precisely how many days' he's been in his domain, even though he forgets so much else. What might this obsessive counting reveal about his state of mind?",
      "If you had to count and mark every single day of something in your life, what would it be, and why?"),
    wed: D("Chapters 69–71", "Mack's late-night visit; Ruby's harsh training begins",
      "Have you ever seen someone in charge use fear or threats to try to make someone else obey? How did it make you feel to watch?",
      "What does Mack do to try to make Ruby walk when she refuses, and how does Ruby respond?",
      "Julia says Ruby is just tired, but Mack calls her an 'idiot elephant.' What does this contrast reveal about how differently Mack and Julia see the animals?",
      "Write about the moment Ruby fights back against Mack — from Ruby's own point of view."),
    thu: D("Chapters 72–73", "Watercolours and finger paints; \"a cage,\" not a \"domain\"",
      "Has a smell, a sound, or a texture ever brought back a surprising memory for you?",
      "What new art materials does Julia give Ivan in these chapters?",
      "For the first time, Ivan calls his home 'a cage' instead of 'a domain' when talking to Ruby. Why might this small word change matter so much?",
      "Write about the moment Ivan finally calls his home 'a cage' instead of a 'domain' — why do you think this word change matters so much?"),
  },
  projects: [
    P("poster", "Before and After", "Design a split poster comparing Ivan's life as a \"temporary human\" with Mack and Helen to his life now."),
    P("comic", "The Cake Frosting Incident", "Illustrate Ivan discovering the still-life painting and the frosting disaster that follows, panel by panel."),
    P("drama", "Walk, Ruby", "Act out the claw-stick training scene respectfully, then discuss as a class how it felt to watch."),
    P("journal", "Domain or Cage?", "Write about the moment Ivan changes his word from \"domain\" to \"cage,\" and why the words we choose matter."),
  ],
  quiz: [
    Q("Who was Mack's wife, and what happened to her?", "Helen; she eventually packed a bag and left, and never came back."),
    Q("True or False: Tag survived the capture along with Ivan.", "False — she died in the crate.", "tf"),
    Q("Name two things Ivan broke while living with Mack and Helen as a young gorilla.", "Any two: a crib, glasses, lamps, a couch, shower curtains, a blender, a TV, a radio, his own toes."),
    Q("Vocabulary: What is a \"still life,\" according to Helen?", "A painting of ordinary objects, such as fruit in a bowl."),
    Q("What did Ivan paint with when he snuck into the kitchen?", "Chocolate cake frosting, on the refrigerator door."),
    Q("True or False: Ivan was allowed back in the kitchen after the frosting incident.", "False — he was never allowed in again.", "tf"),
    Q("Why did Mack eventually move Ivan to the domain at the mall?", "Ivan grew too big and strong for human furniture and human life."),
    Q("How many days does Ivan count that he's lived with humans?", "Nine thousand eight hundred and seventy-six."),
    Q("What does Ivan use to mark each day on his painted jungle wall?", "A Magic Marker Julia gave him, making an X for every day."),
    Q("Vocabulary: What does \"sullen\" mean, as used to describe Mack?", "Bad-tempered, gloomy, resentfully silent."),
    Q("What method does Mack use when Ruby refuses to walk during training?", "He yells, pulls her chain, and finally threatens her with the claw-stick."),
    Q("True or False: Ruby eventually strikes Mack with her trunk.", "True.", "tf"),
    Q("What does Julia think is the real reason Ruby won't move?", "She's simply exhausted."),
    Q("What new art supplies does Julia bring Ivan in this section?", "Watercolour-style paints and finger paints."),
    Q("Vocabulary: What does \"punishment\" mean, as the title of Chapter 64 suggests?", "A consequence given for doing something wrong."),
    Q("What word does Ivan use for his home for the first time in this section, instead of \"domain\"?", "A cage."),
    Q("Inference: Why might Ivan have avoided calling his home a \"cage\" for so long, even though Bob calls it that from the start?", "Open-ended — accepting the truth of his situation may have felt too painful."),
    Q("What worry does Ruby ask Ivan directly, near the end of this section?", "Whether she will die in her domain someday, like Stella did."),
    Q("Predict: Now that Ivan has admitted, even just to himself, that he lives in a \"cage,\" what do you think he might start planning?", "Open-ended, text-supported prediction."),
    Q("Whole-section review: How is young Ivan's relationship with Mack similar to, and different from, his relationship with Mack now?", "Open-ended comparison."),
  ],
},
{
  num: 5, title: "The Plan Takes Shape", chapters: "Chapters 74–89",
  LI: "We are learning to track how a character's plan develops in secret, piece by piece, before anyone else understands it.",
  SC: "I can explain, step by step, how Ivan's night-painting plan develops across several chapters.",
  rubricTags: ["R3","R6","R8"],
  days: {
    mon: D("Chapters 74–77", "The \"true story\" Ivan tells Ruby; remembering his family's death",
      "Sometimes telling someone else a story helps you understand your own feelings better. Has that ever happened to you?",
      "What 'true story' does Ivan tell Ruby about a baby elephant who needed to go to a zoo?",
      "Ivan says the zoo story is true, 'I hope.' What does this small phrase reveal about how uncertain and hopeful he really is about his own plan?",
      "Write your own two-line 'once upon a time' story that is secretly about something true and hard in your own life, the way Ivan's story is secretly about Ruby."),
    tue: D("Chapters 78–81", "The ashtray; \"another Ivan\"; night painting begins",
      "Have you ever seen something in a shop that felt shocking or wrong to you, even if other people didn't seem to notice?",
      "What disturbing item does Ivan mention is sold in a shop near his cage?",
      "Ivan describes 'another Ivan' hidden inside him — one who could 'tear a grown man's limbs off' but chooses not to. What does this tell us about the difference between having power and choosing to use it?",
      "Write about the ashtray chapter — why do you think the author included such a disturbing detail in a book for children?"),
    wed: D("Chapters 82–85", "The secret project; frustration; Ruby's decline",
      "Have you ever worked really hard on a creative project that just wasn't turning out the way you imagined? What did you do?",
      "What does Ivan tell Ruby he is working on at night?",
      "Bob says painting is 'unnatural' and doesn't understand Ivan's secret plan, but still supports him. What does this reveal about the nature of their friendship?",
      "Write about a time you kept trying at something even though it 'wasn't right' yet, and what finally helped (or what you're still working on)."),
    thu: D("Chapters 86–89", "The zoo advertisement; hiding paintings in Not-Tag",
      "Has an advertisement or a short video ever changed how you thought about something important?",
      "What does Ivan see in the TV ad that gives him the final piece of his plan?",
      "Ivan says painting is 'different now' because he's 'painting what I see in my head... things that don't exist. At least, not yet.' What does this show about how his art has changed?",
      "Write about the ad Ivan sees for the zoo — describe it the way Ivan describes it, then explain why it matters so much to him."),
  },
  projects: [
    P("poster", "Ivan's Hidden Ivan", "Design a two-sided poster: the calm Ivan visitors see, and the powerful 'other Ivan' hidden inside — and explain what makes him choose peace."),
    P("comic", "The Zoo Ad", "6 panels showing the TV advertisement Ivan sees and how it changes his plan."),
    P("drama", "Story Within a Story", "Act out Ivan telling Ruby his secret 'true story' about the baby elephant who needed a zoo."),
    P("journal", "What I'm Building in Secret", "Write about a plan, hope, or project you've kept quiet about while you worked on it, and why you didn't tell everyone right away."),
  ],
  quiz: [
    Q("What \"true story\" does Ivan tell Ruby, without revealing it's really about her?", "A story about a baby elephant who needed to go to a zoo, helped by a friend who made a promise."),
    Q("True or False: Ivan tells Ruby the zoo story is definitely true, with no doubt.", "False — he says \"I hope\" it's true.", "tf"),
    Q("What disturbing object does Ivan mention is sold in a nearby mall shop?", "An ashtray made from a gorilla's hand."),
    Q("Vocabulary: What does \"revenge\" mean, as Ivan uses it describing \"another Ivan\"?", "Punishing someone in return for harm done."),
    Q("What does Ivan realise as he stares at the billboard and his own red-paint-covered fingers?", "That he now knows how to keep his promise to Stella."),
    Q("True or False: Ivan starts painting secretly during the day, when everyone can see.", "False — he paints only at night.", "tf"),
    Q("Where does Ivan hide his secret paintings so Mack won't find and sell them?", "Under his dirty pool of water, and later stuffed inside Not-Tag."),
    Q("Why does Bob dislike Ivan's night-painting habit?", "It smells terrible, and Bob prefers sleeping on Ivan's stomach, which Ivan offers less often now."),
    Q("Vocabulary: What does \"temperamental\" mean, as Bob accuses Ivan of being about his art?", "Moody; easily upset or overly sensitive about one's work."),
    Q("What does Mack do when he finds one of Ivan's hidden paintings by accident?", "He sells it, and promises more paint supplies if it sells quickly."),
    Q("True or False: The painting Mack finds and sells was always meant for the gift shop.", "False — it was one of Ivan's secret paintings meant for Ruby.", "tf"),
    Q("What does Ivan see in the TV advertisement that finally completes his plan?", "Elephants living together at a real zoo, with rocks, trees, and room to wander."),
    Q("What does Ivan say is different about how he paints now, compared to before?", "He's painting what's in his head — things that don't exist yet — instead of just objects in front of him."),
    Q("Vocabulary: What does the phrase \"a giant puzzle\" mean, as Ivan describes his project?", "His painting is made of many separate pieces of paper that only make sense together."),
    Q("Why does Ivan hollow out Not-Tag?", "To hide his growing collection of secret paintings inside her stuffing."),
    Q("True or False: Ivan tells Bob exactly what his secret plan is from the very beginning.", "False — he can't fully explain it even to Bob.", "tf"),
    Q("Inference: Why might Ivan feel such urgency to finish the 'one more thing' his painting is missing?", "Open-ended — Ruby is getting weaker and more hopeless every day."),
    Q("What does Julia notice when she sees how much paper and paint Ivan has used?", "That he is 'one serious artist.'"),
    Q("Predict: What do you think the 'one more thing' missing from Ivan's giant painting might turn out to be?", "Open-ended, text-supported prediction."),
    Q("Whole-section review: List, in order, three separate ideas or events that come together to form Ivan's final plan.", "Stella's promise, the ashtray/billboard realisation, and the TV zoo advertisement."),
  ],
},
{
  num: 6, title: "H-O-M-E", chapters: "Chapters 90–104",
  LI: "We are learning to explain how a character finally finds a way to communicate something enormous using a completely unexpected method.",
  SC: "I can explain, in order, how Ivan's paintings are discovered and understood to spell 'HOME.'",
  rubricTags: ["R1","R4","R8"],
  days: {
    mon: D("Chapters 90–93", "The idea for the word; laying out the letters",
      "Have you ever had an idea suddenly click into place, seemingly out of nowhere, because of something completely unrelated — a word, a number, a sound?",
      "What word suddenly occurs to Ivan while he watches Julia struggle with her spelling homework?",
      "Ivan lays out sixteen pieces of poster board, 'four down, four across, a perfect square,' before he even tells Bob what he's making. What does this careful preparation reveal about how seriously he's taking this final plan?",
      "If you had to communicate one hugely important message using only pictures and no words at all, what would your message be, and how would you show it?"),
    tue: D("Chapters 94–97", "Showing Julia; she doesn't understand at first; chest-beating",
      "Has anyone ever completely misunderstood something you worked really hard to show or explain? How did you feel?",
      "What is Julia's first reaction when Ivan shows her his paintings, piece by piece?",
      "Ivan silently thinks 'No. It does matter' when Julia says his paintings' meaning 'doesn't matter.' What does this quiet, unspoken protest reveal about how much is at stake for him?",
      "Write about the moment Ivan finally chest-beats in anger and frustration — from the outside (what George and Julia see) and then from the inside (what Ivan is actually feeling)."),
    wed: D("Chapters 98–101", "The puzzle pieces come together; the billboard goes up; Mack's fury",
      "Have you ever solved a puzzle, riddle, or mystery where the pieces suddenly all made sense at once? Describe that feeling.",
      "What word does Julia finally piece together from Ivan's scattered paintings?",
      "George says 'there has to be a logical explanation' even as the evidence piles up in front of him. What does this reveal about how hard it is for adults to believe something extraordinary, even when they can see it?",
      "Write about the exact moment Julia realises what Ivan has painted — try to capture both her excitement and her father's disbelief."),
    thu: D("Chapters 102–104", "The phone call; news coverage begins",
      "How do you think news or attention — good or bad — can completely change how people treat someone?",
      "What does George do that starts the chain of events leading to news coverage?",
      "Ivan gets new nicknames — 'the Ape Artist,' 'the Primate Picasso' — but tells Bob his 'idea isn't working' because nothing has actually changed for Ruby yet. What does this reveal about what Ivan actually cares about, compared to what the public cares about?",
      "Write a short newspaper headline and opening sentence about Ivan's billboard mural, the way a real journalist covering this story might write it."),
  },
  projects: [
    P("poster", "H-O-M-E", "Recreate Ivan's giant billboard mural as a class poster, spelling HOME with a picture of an elephant in a real zoo."),
    P("comic", "Piecing It Together", "Illustrate Julia and George assembling Ivan's scattered paintings into words and pictures, panel by panel."),
    P("drama", "Breaking News", "Act out a TV interview crew arriving at the mall to film Ivan, Ruby, Mack, George and Julia."),
    P("journal", "When No One Understands (Yet)", "Write about persisting with something important even when the people around you don't understand it at first."),
  ],
  quiz: [
    Q("What word suddenly comes to Ivan while watching Julia's spelling homework?", "\"Home.\""),
    Q("How many pieces of poster board does Ivan lay out to begin his mural?", "Sixteen — four down, four across."),
    Q("True or False: Julia understands Ivan's paintings the very first time he shows them to her.", "False — she's confused at first.", "tf"),
    Q("Vocabulary: What does \"chest-beating\" mean for a gorilla, according to Ivan?", "A powerful warning display and sound, made when truly angry or protective."),
    Q("Why does Ivan finally chest-beat for the first time in the book?", "Because his paintings get scattered and knocked around, and he's protecting his message for Ruby."),
    Q("True or False: George immediately believes the paintings spell something meaningful.", "False — he's skeptical, suggesting it's coincidence.", "tf"),
    Q("What letters does Julia identify first among the scattered paintings?", "H, E, O — leading toward HOME."),
    Q("What does Julia's giant painting show, besides the word HOME?", "A picture of Ruby in a zoo, with other elephants, walls, grass and a red-giraffe zoo logo."),
    Q("What does Julia convince George to help her do with the finished mural?", "Put it up on the highway billboard, without Mack's permission."),
    Q("Vocabulary: What does \"publicity\" mean, as Julia uses it to persuade her father?", "Public attention or media coverage."),
    Q("True or False: Mack is thrilled the moment he sees the new billboard the next morning.", "False — he's furious at first.", "tf"),
    Q("How does Mack's attitude change once the phone rings with a reporter asking about the sign?", "He quickly claims the idea for the mural was his own."),
    Q("What is Ivan's new gift-shop painting price after the news coverage begins?", "Sixty-five dollars with frame, up from twenty-five."),
    Q("What nicknames does Ivan gain after the story breaks?", "\"The Ape Artist\" and \"the Primate Picasso.\""),
    Q("True or False: Ivan feels satisfied and finished once the news story airs.", "False — he tells Bob his idea 'isn't working' because nothing's changed for Ruby yet.", "tf"),
    Q("Inference: Why might Ivan feel frustrated even while he's becoming famous?", "Open-ended — fame for himself was never the goal; freeing Ruby was."),
    Q("What does the cameraman focus on during his visit to the mall, besides Ivan and Ruby?", "The claw-stick."),
    Q("Why might this small detail — the camera lingering on the claw-stick — matter so much for what happens next?", "Open-ended — it becomes visible evidence of mistreatment once the story airs."),
    Q("Predict: Now that Ivan's message has reached the public, what kind of response do you think might follow?", "Open-ended, text-supported prediction (accept references to protests/attention)."),
    Q("Whole-section review: Explain, in order, the full chain of events that leads from Ivan's idea to the finished HOME billboard.", "Open-ended, sequence-based."),
  ],
},
{
  num: 7, title: "Free Ruby", chapters: "Chapters 105–119",
  LI: "We are learning to evaluate how public attention and protest can create real change for someone who cannot speak for themselves.",
  SC: "I can explain, using evidence from the text, how the protesters and inspectors change what happens to Ivan and Ruby.",
  rubricTags: ["R1","R7","R10"],
  days: {
    mon: D("Chapters 105–108", "The TV interview; the news airs; protesters arrive",
      "Have you ever seen people protest or campaign for a cause on the news or in your community? What were they trying to change?",
      "What does the TV crew film that later becomes important evidence of how Ruby is treated?",
      "One protest sign reads 'Elephants Are People Too' — Julia calls it her favourite. What might this sign be trying to say, even though it's not literally true?",
      "Design your own protest sign for Ruby's cause, with a short, powerful slogan."),
    tue: D("Chapters 109–112", "Inspection; \"Free Ruby\"; clicker training",
      "Have you ever had an inspector, examiner, or judge check your work using a checklist? How did it feel to be evaluated that way?",
      "What does the inspecting man with the clipboard check when he visits the mall?",
      "Maya uses gentle 'clicker training' with treats to teach Ruby to touch the transport box, rather than force or punishment like Mack used. What does this contrast in methods suggest about the two very different kinds of humans in this story?",
      "Write about the moment Ivan realises the box represents 'the way out' for Ruby, even though it looks frightening — the same way his own first box, taken from the jungle as a baby, once did."),
    wed: D("Chapters 113–116", "The vet visit; George is fired; goodbyes begin",
      "Has something that seemed exciting or positive at first ever also come with a painful goodbye attached?",
      "Why does Mack fire George, and what does this mean for Julia's family?",
      "Julia says leaving is 'a good thing, really it is' even while crying and saying goodbye to Ivan. What does this contradiction reveal about how complicated happy endings can be?",
      "Write Julia's goodbye letter to Ivan, expressing both her sadness and her hope for his future."),
    thu: D("Chapters 117–119", "Ivan steps into the box; respect, not just liking",
      "Have you ever had to do something brave and unfamiliar because you knew it was the right next step, even though it scared you?",
      "What finally convinces Ivan to step into the transport box?",
      "Ivan tells Ruby that as a silverback, other gorillas 'don't have to like me. They have to respect me' — but privately wonders if he can ever earn that respect. What does this reveal about his uncertainty about his own gorilla identity?",
      "Write about a time you did something brave and unfamiliar because you knew, deep down, it was the right next step."),
  },
  projects: [
    P("poster", "Protest Signs", "Design three different protest signs mall visitors might carry for Ruby's cause, each with a different angle or argument."),
    P("comic", "Clicker Training", "Illustrate the contrast between Mack's claw-stick training and Maya's clicker training, panel by panel."),
    P("drama", "Saying Goodbye", "Act out George and Julia's last night at the mall, including their goodbye to Ivan, Ruby, and the search for Bob."),
    P("journal", "Stepping Into the Box", "Write about a time you had to do something unfamiliar or scary because it was the right next step, the way Ivan steps into the transport box."),
  ],
  quiz: [
    Q("What piece of equipment does the cameraman's footage capture that later matters?", "The claw-stick."),
    Q("True or False: Everyone who visits the mall after the news story is a curious paying customer.", "False — protesters also arrive.", "tf"),
    Q("What is the inspector's job when he visits with a clipboard?", "To check the property's conditions — the floor, hay, water bowls — for animal welfare."),
    Q("Vocabulary: What does \"inspect\" mean?", "To look at something closely to check its condition."),
    Q("Who is Maya?", "A woman from the zoo, with kind eyes and a white coat, who evaluates and eventually helps move Ruby and Ivan."),
    Q("What method does Maya use to train Ruby to go near the transport box?", "Clicker training — a click paired with a small treat."),
    Q("True or False: Ruby immediately understands why she should want to go in the box.", "False — she's reluctant and confused at first, saying \"this is my home.\"", "tf"),
    Q("What does the vet say he'll need to do to Ivan before moving him?", "\"Put him under\" — sedate him."),
    Q("Why does Mack fire George?", "Because George and Julia were behind putting up the billboard mural without permission, angering Mack."),
    Q("Vocabulary: What does \"sedate\" mean?", "To calm or make sleepy with medicine, often before a procedure."),
    Q("True or False: Julia is completely happy and not sad at all about leaving the mall.", "False — she cries, even while saying it's \"a good thing.\"", "tf"),
    Q("What final gift does Julia leave for Ivan on her last night?", "A drawing of Ruby and Ivan, in which Ivan is smiling for the first time."),
    Q("What does Bob decide to do when the humans bring boxes for all the animals?", "He hides, refusing to be caught or taken, saying he's a wild beast by choice."),
    Q("What finally convinces Ivan to step into his own transport box?", "A trail of treats and clicks from Maya, and knowing Ruby is watching him from her cage."),
    Q("True or False: Bob successfully sneaks into Ivan's box to travel with him to the zoo.", "False — he says humans would notice, and stays behind.", "tf"),
    Q("What does Ivan give Bob as a final gift before leaving?", "Not-Tag, his stuffed toy gorilla."),
    Q("Inference: Why might Ivan tell Ruby \"Think of all the amazing stories you can share with your new family\" instead of saying he doesn't want her to go?", "Open-ended — he's protecting her from his own sadness so she can leave without guilt."),
    Q("What does Ivan say to Ruby about the other gorillas liking him, when she asks?", "He says they don't have to like him — they have to respect him, as a silverback and leader."),
    Q("Predict: How do you think Ivan will cope with leaving behind everyone and everything he has ever known?", "Open-ended, text-supported prediction."),
    Q("Whole-section review: List, in order, the main steps that lead from protesters arriving to Ivan stepping into the box.", "Open-ended sequencing."),
  ],
},
{
  num: 8, title: "A New Beginning", chapters: "Chapters 120–135",
  LI: "We are learning to notice how a character's feelings of loss and disorientation can be shown through short, fragmented sentences and imagery, rather than being stated directly.",
  SC: "I can find an example of very short or broken sentences in the text and explain what feeling they capture.",
  rubricTags: ["R2","R8","R9"],
  days: {
    mon: D("Chapters 120–123", "Mack's last visit; leaving; sedation",
      "If you had to say goodbye to someone who had raised you, even someone imperfect, what mixed feelings might you have?",
      "What does Mack do and say on his last night with Ivan, before Ivan leaves?",
      "Mack shares an old photo of young Ivan and says 'we had some laughs, didn't we' — showing a softer, sadder side of a man who has also been unkind. What does this complexity suggest about how the author wants us to see Mack?",
      "Write about the mixed feelings Ivan might have leaving behind someone who both raised him and also failed to truly care for him."),
    tue: D("Chapters 124–127", "A new cage; missing Bob",
      "Imagine waking up somewhere completely new and unfamiliar, without your favourite person or thing nearby. What would you miss most?",
      "What does Ivan notice is different, and the same, about his new cage at the zoo?",
      "The chapter 'missing' is only three tiny sentences, ending with 'my belly's cold without him.' What does this extremely short, simple chapter capture about grief and loneliness that longer sentences might not?",
      "Write your own extremely short chapter, 2–3 sentences, capturing a feeling of missing someone or something."),
    wed: D("Chapters 128–131", "A real nature show; meeting a gorilla family on TV",
      "Has watching a nature documentary or animal video ever made you feel a surprising connection to another living creature?",
      "What does Maya show Ivan on his new TV, and how is it different from his old TV shows?",
      "Ivan wonders why 'Mack never put on this channel' when he sees real gorillas being gorillas for the first time. What does this small, simple question reveal about everything Ivan has been missing his whole life?",
      "Write about the moment Ivan first sees a real gorilla family on TV — what do you imagine he's thinking and feeling as he watches?"),
    thu: D("Chapters 132–135", "Face to face with his new troop; Kinyani",
      "Have you ever met someone in real life who you'd only ever seen in a photo or video? How did it feel when it became real?",
      "What does Ivan realise when the wall of wooden slats is finally pulled back?",
      "Ivan describes Kinyani as 'terrifying. And beautiful, like a painting that moves.' What does this comparison — using the language of art to describe a real, living gorilla — suggest about how Ivan sees the world?",
      "Write about the moment Ivan first sees his new gorilla family face-to-face, no longer through a TV screen."),
  },
  projects: [
    P("poster", "Two Worlds", "Design a split poster comparing Ivan's old glass domain at the mall to his new cage and eventual outdoor home at the zoo."),
    P("comic", "Mack's Goodbye", "Illustrate Mack's final quiet visit to Ivan's domain, showing both his kindness and his failures."),
    P("drama", "First Sight", "Act out the moment the wooden wall slides back and Ivan sees his new gorilla family for the first time."),
    P("journal", "Missing Someone in Three Sentences", "Write your own ultra-short chapter, in the style of Ivan's 'missing,' about missing someone or something."),
  ],
  quiz: [
    Q("What does Mack bring out and show Ivan on his last night together?", "An old photo of young Ivan in Mack's convertible."),
    Q("True or False: Mack says a warm goodbye and looks back one last time as he leaves.", "False — he says he'll miss Ivan but doesn't look back.", "tf"),
    Q("What does Ivan's new cage at the zoo have that his old one didn't?", "It's cleaner, with a curtain of wooden slats instead of one solid glass wall."),
    Q("Vocabulary: In \"missing,\" what does Ivan say he misses most of all?", "Bob."),
    Q("What is different about the food at the zoo, according to Ivan?", "It's fine, but there's no soda or cotton candy."),
    Q("True or False: Ivan has many visitors at the zoo, just like at the mall.", "False — he says he has no visitors, only Maya and her team.", "tf"),
    Q("What new show does Maya put on Ivan's TV?", "A nature show about real gorillas being gorillas, with no human voices or ads."),
    Q("How many gorillas are in the family Ivan watches on TV, and what is unusual about the group?", "Three females and a juvenile male — with no silverback to protect them."),
    Q("Vocabulary: What does \"placid\" mean, describing the gorilla family?", "Calm, peaceful, not easily upset."),
    Q("What happens when Maya pulls the string on the wall of wooden slats?", "Ivan sees that the gorilla family from the TV is real, and right there on the other side of the glass."),
    Q("True or False: Ivan immediately feels familiar and comfortable around the new gorillas.", "False — he's shocked and unsure at first.", "tf"),
    Q("What is the name of the female gorilla Ivan is drawn to?", "Kinyani."),
    Q("How does Ivan describe Kinyani?", "Terrifying, and beautiful, \"like a painting that moves.\""),
    Q("Vocabulary: What does \"intact\" mean, as Ivan describes Kinyani's canine teeth?", "Complete; undamaged; whole."),
    Q("True or False: Ivan feels he is definitely bigger and stronger than Kinyani.", "True — but he also thinks she's faster and probably smarter.", "tf"),
    Q("Inference: Why might the author write \"missing\" as such an extremely short chapter?", "Open-ended — the sparse, broken style mirrors the emptiness Ivan feels."),
    Q("What surprises Ivan about the way his new family behaves, compared to what he might have expected?", "Open-ended — they're gentle and ordinary, squabbling like any family, not fierce or frightening."),
    Q("Why does Ivan wonder if Mack ever knew about this real gorilla nature show?", "Open-ended — implies Mack never cared enough to look, or avoided showing Ivan anything that might upset him."),
    Q("Predict: What do you think will happen the first time Ivan actually meets Kinyani and the others face-to-face, outside the glass?", "Open-ended, text-supported prediction."),
    Q("Whole-section review: How has Ivan's understanding of what a \"family\" or \"home\" could look like changed since arriving at the zoo?", "Open-ended."),
  ],
},
{
  num: 9, title: "Home at Last", chapters: "Chapters 136–153 (book finishes)",
  LI: "We are learning to evaluate how an ending resolves a story's central promise, and how an author uses a final image or symbol to bring a story's themes together.",
  SC: "I can explain how the ending fulfils Ivan's promise to Stella, and identify a final symbol or image that ties the book's big ideas together.",
  rubricTags: ["R4","R6","R10"],
  days: {
    mon: D("Chapters 136–139", "Hesitation at the door; stepping outside at last",
      "Have you ever hesitated before doing something new and important, even though you knew you wanted to do it eventually?",
      "Why does Ivan decide 'it's not a good day to socialize' the first time the door to his new family opens?",
      "One whole chapter is just a list of single words — 'Sky. Grass. Tree. Ant...' ending in 'Mine. Mine. Mine.' What does this unusual chapter structure capture about Ivan's first experience of true outdoor freedom?",
      "Write your own 'list poem' chapter, in the style of 'outside at last,' capturing a moment of pure sensory joy or freedom."),
    tue: D("Chapters 140–145", "Testing, pretending, and a happy reunion on TV",
      "Have you ever had to 'fake it,' or act more confident than you actually felt, in order to fit in or be accepted somewhere new?",
      "How does Kinyani test whether Ivan is a 'true silverback' when he first goes outside with the troop?",
      "Ivan 'pretends' to be the silverback his father was, and a young male retreats 'almost as if he believes I'm the silverback I'm pretending to be.' What does this reveal about the relationship between confidence and identity?",
      "Write about the moment Ivan finally sees Ruby again on the zoo's TV nature show, happy and thriving with other elephants — from Ivan's point of view."),
    wed: D("Chapters 146–150", "Romance, storytelling, and exploring the hill",
      "What is something everyone finds a bit awkward or difficult to learn, even though it's supposed to come naturally?",
      "What does Ivan finally do, for the first time in the whole book, when his troop asks him to share a story under the sun?",
      "When Ivan tells his troop the whole story — about Mack, Ruby, Bob, Stella, Julia and George — they 'look away, silent,' and then Kinyani moves closer, her shoulder brushing his. What does this quiet, wordless response suggest about how gorillas show understanding and comfort?",
      "Write about the first time you shared something important or personal with a new group of friends, and how they responded."),
    thu: D("Chapters 151–153", "The mural on the wall; safe; \"Mighty Silverback\"",
      "If you had one enormous blank wall and unlimited time, what would you want to create on it?",
      "What does Ivan paint on the wall at the top of the hill, using mud instead of paint?",
      "In the very last lines, Ivan says 'I turn toward my family, my life, my home' and finally, quietly, calls himself 'Mighty Silverback.' Why does this final line matter so much, compared to how the book begins?",
      "Write about the very last image of the book — Ivan seeing Ruby safe in the distance, and then Julia and Bob visiting him at the zoo. Why do you think the author chose to end the story this way?"),
  },
  projects: [
    P("poster", "The Wall Painting", "Design Ivan's final mud mural on the hillside wall, showing 'lots of movement' and 'not much colour,' as he describes it."),
    P("comic", "Ivan the Silverback", "Illustrate Ivan's journey from being called 'the loneliest gorilla in the world' to whispering 'Mighty Silverback' at the very end."),
    P("drama", "Reunited", "Act out the final scene where Julia and Bob visit Ivan at the zoo and share news of Ruby."),
    P("journal", "My Own Ending", "Write a short epilogue, one year later, imagining what Ivan's life, Ruby's life, and Julia's life might look like."),
  ],
  quiz: [
    Q("Why does Ivan decide not to go through the door the first time it opens?", "He feels he's \"not ready to be a silverback.\""),
    Q("What does the title and content of one whole chapter — a list of single words — capture about Ivan's first moments outdoors?", "\"outside at last\" — words like Sky, Grass, Tree, ending in \"Mine. Mine. Mine,\" capturing overwhelming joy and freedom."),
    Q("True or False: Ivan is immediately welcomed and accepted by his new troop the first time he goes outside.", "False — Kinyani chases and tests him, and he cowers.", "tf"),
    Q("What does Ivan see on the zoo's nature-show TV that fills him with joy?", "Ruby, rolling happily in mud with other young elephants."),
    Q("Vocabulary: What does \"pretending\" suggest about Ivan's silverback behaviour in this section?", "Acting a role, or behaving as if something is true, to see if it becomes true."),
    Q("What does Ivan build for the first time in the outdoor enclosure?", "A nest, out of leaves and sticks, though not as good as a true jungle nest."),
    Q("True or False: Ivan's troop immediately admires his first attempt at a nest.", "False — they grunt disapproval, calling it too small and flimsy, but Ivan still loves sleeping in it.", "tf"),
    Q("What game does Kinyani teach or invite Ivan to play, echoing his childhood with his sister Tag?", "Tag."),
    Q("What does Ivan finally do for the first time, telling his whole troop about Mack, Ruby, Bob, Stella, Julia and George?", "He tells his story aloud, under the sun."),
    Q("Vocabulary: What does \"grooming\" mean, in the context of gorillas?", "Cleaning and caring for another's fur, such as picking out bugs — a bonding activity."),
    Q("Where does Ivan explore that he's never been before, near the end of the book?", "The top of a hill, near a high white wall."),
    Q("What does Ivan create on the wall using mud?", "A large mural — handprints, a noseprint, swoops and swirls, figures and shapes."),
    Q("True or False: Ivan easily climbs the tree near the wall to get a better view of his mural.", "False — he struggles, gasping for breath, before reaching just a few limbs up.", "tf"),
    Q("What does Ivan see beyond the wall, from up in the tree?", "Other zoo animals — giraffes, hippos, deer, a bear — and elephants, including Ruby."),
    Q("What does Ivan whisper to Stella, in his mind, upon seeing Ruby safe in the distance?", "\"She's here, Stella. Ruby's safe. Just like I promised.\""),
    Q("Who visits Ivan at the very end of the book?", "Julia and Bob, with George."),
    Q("What surprising arrangement has Bob made to live with Julia's family?", "George and Julia agreed Bob could live with them; Julia walks extra dogs to pay for his food."),
    Q("What is the very last thing Ivan calls himself, whispered in the final line?", "\"Mighty Silverback.\""),
    Q("Inference: Why might the author end the book with Ivan finally calling himself 'Mighty Silverback' in his own voice, rather than having someone else say it about him?", "Open-ended — it shows Ivan has finally accepted and grown into his true identity, rather than it just being a name on a billboard."),
    Q("Whole-book review: Explain how the ending fulfils the promise Ivan made to Stella all the way back when she was dying.", "Open-ended — must reference Ruby's safety and happiness at the zoo."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "\"Use What You Have\" Campaign", desc: "Create a campaign — posters, slogans, a short speech — celebrating the idea that you don't need to be the strongest or loudest to create change. You just need to use what you have, the way Ivan used his art, using Ivan and Ruby's story as the model." },
    { title: "Extended Drama/Performance", desc: "Imagine a scene one year after the book ends: Ruby's new elephant family welcoming a newcomer, or Mack running the Big Top Mall without any animals, told with empathy rather than simple heroes and villains." },
    { title: "Character Case File — Ivan", desc: "An in-depth profile (poster + written report + panels) tracking Ivan's whole journey and change across the book, with evidence from the beginning, middle and end of the story." },
    { title: "\"What I Have to Give\" Class Anthology", desc: "Each student contributes one illustrated page titled \"What I Have to Give,\" describing a talent, strength or small kindness they could use to help someone else, echoing Ivan's use of his art." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: share favourite moments from the term.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events.",
      wt: "Explains some of Ivan's motivations or relationships, with limited evidence.",
      a: "Explains a theme (empathy, art as voice, courage) and supports it with clear evidence from the book.",
      example: "A Character Case File showing Ivan changing from 'the loneliest gorilla in the world' to a gorilla who whispers 'Mighty Silverback,' with an event from the beginning, middle and end of the book." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A 'Use What You Have' campaign poster with a punchy slogan, three persuasive reasons and a picture that matches the message." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A drama that adds a new scene from Mack's point of view a year later, rehearsed and improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
