/* ============================================================
   GOING SOLO — BOOK STUDY APP DATA
   Content data only. No markup/behaviour lives in this file.
   Book: "Going Solo" by Roald Dahl (memoir, 15 chapters).
   All passages are paraphrased — teachers read from their own copy.
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Courage, Resilience & Empathy", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 3 (Years 5–6).
   "Achieved" = the curriculum expectation has been met.
   curriculum: the achievement objective / competency being assessed
   expect:     what the student should be able to do (teacher language)
   kid:        the same thing as a student "I can" statement
   ask:        one quick question the teacher can ask themselves when marking
   na/wt/ach:  level descriptors
   exemplar:   what an Achieved response looks like (student sample)
   wtSample:   a Working Towards response, for contrast
   evidence:   where in the unit to find the evidence
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasing understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas of the memoir (courage, resilience, luck and loss, the cost of war) and supports them with specific events, making links beyond the text to history, self or the world.",
    kid: "I can explain a big idea from the book, prove it with something that happened, and link it to the wider world.",
    ask: "Does the student explain WHY an event matters and link it to a bigger idea — not just retell WHAT happened?",
    na: "Retells some events from Roald's life but cannot yet explain what they mean. Answers are mostly 'what happened'.",
    wt: "Names a big idea (e.g. 'it's about being brave') with a general reason, but the link to a specific event is vague or missing.",
    ach: "Explains a big idea, supports it with a specific event from the book, and makes a link beyond the text (to history, to self, or to today's world).",
    wtSample: "The book is about courage because Roald flies planes in a war.",
    exemplar: "I think the book shows that courage isn't the same as not being scared. After the Battle of Athens all the pilots' hands were shaking so much they couldn't light a cigarette, but they still went back up. That's like when my dad went to the dentist even though he was terrified — you do the hard thing anyway.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-away reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasing understanding of how texts are shaped for different purposes and audiences, and of how language features are used for effect.",
    expect: "Notices the choices Dahl makes — humour, similes, short sentences in action scenes, letters to his mother, a narrator looking back years later — and explains how they affect the reader.",
    kid: "I can spot the choices the author made and explain the effect they have on the reader.",
    ask: "Does the student name a writer's choice AND explain its effect, using an example?",
    na: "Comments only on what happens; does not yet notice how the book is written.",
    wt: "Notices a feature (e.g. 'he uses similes') but cannot explain its effect.",
    ach: "Names a writer's choice, gives an example, and explains the effect on the reader.",
    wtSample: "He uses lots of describing words when the snake comes in.",
    exemplar: "When the snake-man walks into the room, Dahl slows everything down with time markers like 'a minute went by… two minutes… three'. The short sentences and long silences made me hold my breath, so I felt as tense as the people waiting outside. Then the simile of the sack jumping 'like fifty angry rats' finally lets the tension out.",
    evidence: "Setting & language questions, inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, visualising, summarising, comparing sources — and links earlier chapters to later ones (cause and effect across the memoir).",
    kid: "I can use reading strategies and link what happened earlier in the book to what happens later.",
    ask: "Can the student connect an earlier event to a later one without being told?",
    na: "Relies on the teacher to explain the story; does not yet connect chapters.",
    wt: "Uses a strategy when prompted and makes simple links between chapters.",
    ach: "Independently uses strategies and explains how an earlier event causes or sets up a later one.",
    wtSample: "He learned to fly and then he flew in the war.",
    exemplar: "In Chapter 7 Dahl is thrown into a Gladiator with no proper training. That's why in Chapter 8 he crashes in the desert — he was given wrong directions and had never practised landing in the dark. And because he'd survived that, he was desperate to fly again, which is why he was in Greece in Chapter 9. Each chapter causes the next one.",
    evidence: "Predictions, cause-and-effect questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics.",
    expect: "Writes and shares clear, developed ideas about the memoir — opinions, explanations and reflections — with supporting evidence and thoughtful reasoning.",
    kid: "I can share a clear idea or opinion and support it with reasons and evidence from the book.",
    ask: "Is there a clear idea PLUS at least two reasons or pieces of evidence?",
    na: "Answers are one word or unclear; ideas are not explained.",
    wt: "Shares a clear idea but gives little detail or only one reason.",
    ach: "Communicates a clear opinion or idea and develops it with at least two reasons or pieces of evidence.",
    wtSample: "I think the pilots were brave because they kept flying.",
    exemplar: "I think the pilots in Greece were brave but the people in charge were not fair to them. First, only fifteen Hurricanes were sent to face over a thousand German planes. Second, the pilots were never told why they were moving around, so they couldn't prepare. Being brave doesn't mean you should be sent to do the impossible without help.",
    evidence: "Go-away reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Show an increasing understanding of how language features are used for effect; organise texts using a range of structures.",
    expect: "Chooses the right structure and language for the task — a letter home, a Log Book entry, a newspaper report, a memoir scene with suspense, a persuasive poster.",
    kid: "I can choose the right form and language for the job, like a letter, a log entry or a suspense scene.",
    ask: "Does the writing look and sound like the form it's meant to be, and does the language do a job?",
    na: "Writing does not match the task; little attempt at structure or language features.",
    wt: "Attempts the right form (e.g. writes a letter) but the language or structure is inconsistent.",
    ach: "Uses a suitable structure and deliberate language features for the purpose and audience (e.g. first-person voice, sensory detail and short sentences in a suspense scene).",
    wtSample: "Dear Mama, I am in Africa. It is hot. I saw a snake and it was scary.",
    exemplar: "Dar es Salaam, 3 May 1939. Dear Mama, Don't be alarmed — I've been chased out of my own bathroom by a snake. It was six feet of glossy black, and it moved at the speed of a running man. Salimu stood perfectly still with a rake. Four seconds. Five. Then, whack! I am going to write to you from a much safer part of the house.",
    evidence: "Poster, comic, drama & journal projects; Week 10 campaign / anthology" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback to improve it.",
    kid: "I can plan my work, improve it, and use feedback to make it better.",
    ask: "Can you see a plan AND a change made because of feedback?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wt: "Plans and drafts with support; makes small changes when prompted.",
    ach: "Independently plans, drafts and revises, and uses feedback (e.g. Glow & Grow) to improve the work.",
    wtSample: "I finished my comic. My teacher told me to add colour so I did.",
    exemplar: "My plan had three parts: the alarm, the take-off and the dogfight. My partner's 'grow' said the dogfight was confusing, so I added arrows and a small map showing where each plane was. Now you can follow who is chasing who.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas.",
    expect: "Listens to and builds on others' ideas during group reading and projects, respects different viewpoints, and takes turns fairly.",
    kid: "I can listen to my group, take turns, respect different opinions, and build on other people's ideas.",
    ask: "Does the student respond to what others say, not just wait for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt or opt out.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I sort of disagree with Mia — I don't think the Air Commodore was a bad person, I think he was stuck following orders too.\" She then asked the quieter group members what they thought.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas.",
    expect: "Makes inferences — works out what people feel and why — using clues from the text, questions what a narrator tells us, and thinks creatively about possibilities.",
    kid: "I can use clues in the text to work out things the author doesn't say, and question what the narrator tells me.",
    ask: "Has the student worked something out AND pointed to the clue?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wt: "Makes an inference with prompting but struggles to explain the clue.",
    ach: "Independently infers feelings or motives, points to the clue, and questions whether the narrator is reliable or fair.",
    wtSample: "Roald was scared in the dogfight.",
    exemplar: "Dahl says he felt 'pretty good' after the battle, but he also says his hands shook so much he couldn't light a match. That clue tells me he was more frightened than he admits — he was proud he survived but his body was still in shock.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility.",
    expect: "Contributes ideas in class discussions and projects, and takes responsibility for a role in group work.",
    kid: "I can share my ideas and do my part in group work.",
    ask: "Does the student offer ideas and take on a job without being asked?",
    na: "Rarely contributes to discussions or group projects.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ach: "Offers ideas without being asked, takes responsibility for a role, and encourages others.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 drama group, Tane volunteered to be director, made a scene list, and made sure everyone had a part. He shared two ideas in the reflection circle without being asked.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Courage, Resilience & Empathy", strand: "Values",
    curriculum: "Values: perseverance, respect, empathy for others and their different points of view, and care for people and the environment.",
    expect: "Connects the memoir's values — courage in the face of fear, resilience after setbacks, and empathy for people whose lives and views differ — to their own life and actions.",
    kid: "I can connect the book's messages about courage, resilience and empathy to my own life.",
    ask: "Has the student linked a value from the book to something real in their own life or actions?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wt: "Names a value (e.g. 'be brave') when asked, with a simple or general link.",
    ach: "Explains a value from the book and connects it to a real experience or action of their own.",
    wtSample: "The book teaches us to be brave and never give up.",
    exemplar: "Dahl refused to be sent home when he was blind and badly hurt because he knew he'd never fly again. When I broke my wrist before the swimming champs I felt like giving up too, but I did the physio every day and swam in the relay in the end. Keeping going after a setback is a kind of courage.",
    evidence: "Go-away reflections, journal entries, Week 10 'Going Solo' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 3–4 English, Years 5–6, NZ Curriculum",
  lrv: [
    "Ideas: Show an increasing understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show an increasing understanding of how texts are shaped for different purposes and audiences.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics.",
    "Structure and Language: Show an increasing understanding of how language features are used for effect.",
    "Processes and Strategies: Select and use processes and strategies with increasing confidence to communicate.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Courage in the face of fear, resilience after setbacks, empathy for different points of view, and thinking critically about who tells a story and why.",
  crossCurricular: "Social Sciences — the Second World War, the British Empire and East Africa, the Greek campaign of 1941 and the Middle East (Level 3–4 Social Sciences: how events and places shape people's lives), plus Science (aircraft, flight and the human body under stress) and Health & PE (resilience, recovery and hauora).",
};

// Helper to build a day object (note = teacher-only cue/context)
function D(chapters, subtitle, leadIn, comp1, comp2, goAway, note) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway, note: note || "" };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "Setting Sail", chapters: "Chapters 1–2",
  LI: "We are learning to work out what a person is like from small details and actions, and to explain how an author uses humour to build a character.",
  SC: "I can point to a detail or action that reveals someone's personality, and explain how the author's word choices make that person funny or memorable.",
  rubricTags: ["R2","R5","R8"],
  days: {
    mon: D("Chapter 1 (first part)", "Setting sail on the Mantola; the Major's morning run",
      "Imagine leaving your country for three years, alone, at twenty-two, to start a job on the other side of the world. What would you pack — and what would you be most nervous about?",
      "Where is Roald travelling to, why is he going, and how long is his contract?",
      "Dahl says the Major and his wife are 'guilty of an unforgivable crime' after he makes a joke about polo. What does this tell you about how seriously some passengers took their traditions?",
      "Write two sentences describing a person you have seen on a bus, ferry or plane who made you curious. Use one specific detail about them.",
      "Read from the start of the chapter (the old ship setting off for East Africa in 1938) to the end of the Major's polo incident at breakfast. The Major's morning jog is comic and brief — treat it lightly ('a very early morning run') and move on. Vocabulary: eccentricity, sinewy, bounder."),
    tue: D("Chapter 1 (middle)", "Miss Trefusis and the passenger with the Epsom salts",
      "Do you know someone with a habit or rule that other people find odd (like a strict routine)? Why do people keep habits like that?",
      "What unusual rule does Miss Trefusis follow about how she eats, and how does she explain it?",
      "Why do you think Dahl (as a young man) likes Miss Trefusis more than the Major, even though she is odd? Use evidence.",
      "Invent a harmless quirk for a made-up passenger and write one sentence describing it in a funny way.",
      "Read from Miss Trefusis's first appearance through to Savory's dandruff conversation at the bar. Discuss the term 'boy' (used for servants in the colonial era): explain it is a word from that time that we now see as disrespectful. Vocabulary: ostentatiously, vapid, malevolent."),
    wed: D("Chapter 1 (end)", "The wig secret; a letter home from the Red Sea",
      "Have you ever kept a secret for someone even though it was hard? What made it difficult?",
      "What is Savory hiding, and what reason does he give for hiding it?",
      "Dahl says he kept his promise for years. What does this show about his character, and why might he choose to reveal the secret now, decades later?",
      "Dahl uses funny comparisons to describe the wigs. Write your own comparison for something you might see in a suitcase.",
      "Read from the moment Roald goes back for his pipe to the end of the chapter, including the short letter to his mother. Point out the shift from narrator's voice to letter voice. Vocabulary: ruse, smug, potty."),
    thu: D("Chapter 2", "Arrival in Dar es Salaam; Salimu and the black mamba",
      "What do you picture when you think of arriving in a new country by sea at dawn? What would you see, hear and smell?",
      "Describe two things Dahl notices when he first sees Dar es Salaam from the ship. What does he compare them to?",
      "In the mamba scene, how does Dahl slow down time to build suspense? Find at least two techniques he uses.",
      "Write a six-sentence suspense moment about waiting for something to happen. Use at least one short sentence and one time marker (like 'four seconds… five').",
      "Read the arrival at Dar es Salaam, the introduction to his household (Mdisho, Salimu, Piggy), the Swahili exam and safaris, and the mamba story. You may skip the section about the Italian troop ship during the Red Sea voyage (context about Mussolini in Abyssinia — mention only as background). Vocabulary: lagoon, benighted, impertinent, writhing."),
  },
  projects: [
    P("poster", "Passenger List Poster", "Design a poster for the SS Mantola's 'most unusual passengers', with a picture and three key facts for each character from Chapter 1."),
    P("comic", "The Mamba Moment", "Draw a 6-panel comic of the mamba scene, using panel size and close-ups to slow down the tension."),
    P("drama", "Breakfast on the Mantola", "Act out the breakfast table scene with the Major and the silent passengers — how would each character react?"),
    P("journal", "Dear Mama, I Have Arrived", "Write Roald's first letter home from Dar es Salaam, describing the town, his house and the staff in his own cheerful voice."),
  ],
  quiz: [
    Q("What was the name of the ship that carried Roald to East Africa?", "The SS Mantola."),
    Q("True or False: Roald was travelling to Africa to fight in a war.", "False. He was going to work for the Shell Company.", "tf"),
    Q("How long was Roald's Shell contract meant to last?", "Three years."),
    Q("What sport did the Major play every morning in India?", "Polo."),
    Q("Why did the Major and his wife stop speaking to Roald?", "He made a joke about polo (playing it on bicycles at school)."),
    Q("What unusual rule did Miss Trefusis follow about eating?", "She never touched food with her fingers (she used a knife and fork even for an orange)."),
    Q("What did Savory sprinkle on the shoulders of his dinner jacket?", "Epsom salts (to look like dandruff)."),
    Q("What did Roald discover was really hidden in Savory's black case?", "Wigs (three spares)."),
    Q("Why did Savory need his secret wigs for work in the Punjab?", "The Sikhs he did business with would not respect a bald man."),
    Q("Vocabulary: What does 'eccentric' mean?", "Odd or unconventional in behaviour."),
    Q("True or False: Roald told everyone about Savory's wigs as soon as he landed.", "False. He promised to keep it a secret.", "tf"),
    Q("In which town in Tanganyika did Roald live and work for Shell?", "Dar es Salaam."),
    Q("What was the name of Roald's personal servant in Dar es Salaam?", "Mdisho."),
    Q("What was the name of the gardener who faced the black mamba?", "Salimu."),
    Q("What did Salimu use to pin down the mamba?", "A garden rake."),
    Q("True or False: Dahl says black mambas are afraid of humans and always slither away.", "False. He says they attack on sight.", "tf"),
    Q("What reward did Shell offer for passing the Swahili exam?", "A bonus of 100 pounds (a huge sum at the time)."),
    Q("How does Dahl describe the sound and feeling of time in the mamba scene? Give one technique.", "Open-ended — e.g. counting seconds, short sentences, describing stillness. Accept any technique with an example."),
    Q("What does the way Dahl writes about Miss Trefusis suggest about how he sees people who are 'different'?", "Open-ended — he finds them interesting and likes them if they are intelligent and kind, not just because they are odd."),
    Q("What is one prediction you have about how Roald's life in Africa will change?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 2, title: "Lions, Snakes & Sundowners", chapters: "Chapters 3–4 & the start of Chapter 5",
  LI: "We are learning to identify how an author builds suspense and mixes humour with danger, and to explain what a strange event might mean.",
  SC: "I can name techniques that build suspense, explain how a mix of humour and danger affects the reader, and suggest reasons for events the author doesn't explain.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapter 3 (first part)", "A trader with a huge belly; the District Officer at Tabora; the zorse idea",
      "Which is more interesting to you: a place where there is a lot of everyday life, or a place with almost no people? Explain.",
      "Who is Robert Sanford, and what kind of life does he lead at Tabora?",
      "Dahl says the vultures sit on thorn trees like 'feathered undertakers'. What effect does that comparison have on the mood of the setting?",
      "Robert wonders about breaking in a zebra for his children. Write a short conversation between Robert and Mary about the idea.",
      "Read from Roald's stop at Bagamoyo through the veranda evening at Tabora (gramophone, thorn needle, zorse). This section sets the scene calmly before the lion — it is worth drawing attention to the long, slow pace. Vocabulary: decorticator, protuberant, sinister."),
    tue: D("Chapter 3 (second part)", "The lion and the cook's wife",
      "If you saw something impossible happen right in front of you, what would you do — and who would you tell?",
      "What does the lion do, and how does Robert stop it? Retell the key events in order.",
      "The woman says she 'pretended to be dead' and was carried 'as gently as one of his cubs'. What might explain the lion's behaviour? Give two possible reasons.",
      "Dahl says the event was 'great tragedy and comedy mixed up together'. Write two sentences explaining what he means.",
      "Read from Mdisho's shout of 'Simba!' to the end of the chapter (the newspaper cheque). This is a real event Dahl described as a mystery. Encourage students to offer theories but stress there is no proven answer. Vocabulary: loping, immobile, instantaneously."),
    wed: D("Chapter 4", "The green mamba in the Fullers' house",
      "What do you do to stay calm when something scary is happening? Does it work?",
      "How does Mr Fuller behave when the snake enters his house, and how does he get his family to safety?",
      "How does the snake-man's behaviour show us who he is? Give two examples of his actions and what they tell you.",
      "Find one simile from this chapter and explain what makes it effective.",
      "Read the whole chapter. It is long — about 2,800 words — so use pauses and let students react. The ending mentions the dog's death in a gentle, understated way; check in with students who feel sensitive to animal loss. Vocabulary: unruffled, gauntlet, malevolent."),
    thu: D("Chapter 5 (first part)", "Breakfast, Mdisho and the coming war",
      "Have you ever heard news that you knew would change everything? How did it feel to wait for it?",
      "How does Mdisho react when Roald tells him that war is coming?",
      "Mdisho says that in a war 'there are no rules', but Roald believes there are. What does each character's view show about their background?",
      "Roald teaches Mdisho to read. Write one paragraph on why learning to read might change someone's life.",
      "Read from the ripe pawpaw breakfast to the letter about malaria and temporary army officers. Background: Tanganyika was a German colony until 1919 and many Germans still lived there in 1939. Vocabulary: imminent, askari, blockade."),
  },
  projects: [
    P("poster", "Wanted: Live Snake Catcher", "Design a poster advertising the snake-man's services, including his safety rules and what he does not do."),
    P("comic", "The Lion of Tabora", "Draw the lion incident in 6 panels, with speech bubbles showing the cook, Robert and the woman."),
    P("drama", "Sundowner Stories", "Act out a veranda scene where Robert and Mary retell the lion incident to visitors — each character tells it differently."),
    P("journal", "Eye-Witness Report", "Write a short newspaper article for the East African Standard about the lion, answering who, what, where, when and why."),
  ],
  quiz: [
    Q("What is a decorticator?", "A machine that turns sisal leaves into fibre for rope."),
    Q("True or False: Roald stayed at the house of a British District Officer in Tabora.", "True.", "tf"),
    Q("What was the District Officer's name?", "Robert Sanford."),
    Q("What sat on the thorn trees, waiting?", "Vultures."),
    Q("What did Robert use instead of a steel needle to play his record?", "A thorn needle."),
    Q("What animal did Robert wonder about breaking in for his children?", "A zebra (a 'zorse')."),
    Q("What does 'simba' mean in Swahili?", "Lion."),
    Q("Who did the lion carry off?", "The cook's wife (Pingo's wife)."),
    Q("How did Robert stop the lion?", "He fired a warning shot just ahead of it, so it dropped her and ran."),
    Q("True or False: The woman was seriously injured.", "False. She was unhurt and even smiling.", "tf"),
    Q("Why did Robert decide not to hunt the lion?", "He believed it hadn't meant to hurt her and didn't deserve it."),
    Q("What did the newspaper pay Roald for writing about the lion?", "A cheque for five pounds — his first published work."),
    Q("Whose house did Roald visit in Dar es Salaam when the green mamba arrived?", "The Fullers' house (Freddy Fuller, a Customs officer)."),
    Q("How did Mr Fuller get his children out of the house?", "He lowered them out of an upstairs window by the wrists."),
    Q("What did the snake-man carry to catch the snake?", "An eight-foot pole with rubber prongs, and a sack."),
    Q("True or False: The snake-man bought snakes caught by local people.", "False. He never bought a snake caught by natives because too many were bitten.", "tf"),
    Q("Find one simile from the snake-man scene.", "e.g. 'like a long beautiful shaft of green glass', 'like fifty angry rats', 'like a few pounds of potatoes'."),
    Q("Why do you think Dahl says the lion incident was 'tragedy and comedy mixed up together'?", "Open-ended — it was frightening but also funny and ended safely."),
    Q("What does Mdisho believe about rules in war?", "That there are no rules; winning is all that matters."),
    Q("What is one prediction about what Roald will be asked to do when war begins?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 3, title: "War Arrives in Tanganyika", chapters: "Chapters 5–6",
  LI: "We are learning to look at a difficult event from more than one point of view, and to question how reliable and fair a narrator is.",
  SC: "I can explain how two people see the same event differently, and I can point to places where the narrator might not be telling the whole story or seeing it fairly.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 5 (middle)", "Called to barracks; orders to stop the German civilians",
      "If you were given a serious job you didn't feel ready for, what would you want the people in charge to say to you?",
      "What job is Roald given by the Captain, and what is he told might happen if the Germans try to escape?",
      "Roald says he is 'just a chap who works for Shell'. What does this reveal about how prepared he is for what he's being asked to do?",
      "Write a short diary entry for the night before, from Roald's point of view, describing his worries.",
      "Read from the summons to the barracks through the night on the road with the askaris (the Sergeant cooking, the frogs, the phone call at dawn). Note the Sergeant's quiet competence. You can skip the aside about the bullfrog if you wish. Vocabulary: discretion, deploy, contemptuously."),
    tue: D("Chapter 5 (end)", "The convoy on the coast road",
      "When have you had to make a decision quickly and hoped it was the right one?",
      "Describe what Roald does when the convoy arrives, and how the Germans respond.",
      "Dahl says he could never have ordered the machine-gun to fire on the civilians. Why do you think the Captain gave the order anyway? Consider the Captain's point of view.",
      "The narrator tells us about a shot that comes from the trees. What questions does it leave you with?",
      "Read from the dust cloud on the road to the end of the chapter. This scene includes the death of a man by a single rifle shot; keep the tone factual and steady. Ask students to focus on decisions and consequences rather than the violence. Vocabulary: mesmerized, sullenly, internment."),
    wed: D("Chapter 6 (first part)", "The missing sword",
      "Why might someone give a treasured object to another person? What does the gift show?",
      "What has gone missing from Roald's house, and what is special about it?",
      "How does Dahl let us know something is wrong before Mdisho even speaks? Point to the clues in the scene.",
      "Predict what Mdisho did, using at least two clues from the text.",
      "Read from Roald's arrival home at midnight, through the description of the sword and the conversation with Piggy, up to Mdisho's return at the French windows. STOP before Mdisho begins his account. Vocabulary: scabbard, dhow, ecstatic."),
    thu: D("Chapter 6 (second part)", "Mdisho's account and the conversation about being equal",
      "Is it ever fair to judge someone from another culture by your own rules? Why or why not?",
      "How does Roald react to what Mdisho tells him, and what instruction does he give?",
      "Dahl says Mdisho was 'moulded into a servant' and had 'broken the mould'. What does this suggest about power and respect between Europeans and local people in the colonial era?",
      "Mdisho says that he and Roald are 'exactly equal'. Do you agree with this? Write a short paragraph explaining your view.",
      "TEACHER NOTE: This is the most difficult lesson in the unit. Paraphrase Mdisho's account of what he did (do not read it aloud) — say simply that he attacked a German man who lived nearby, an act of violence. Do not ask questions about the graphic details. Concentrate on the aftermath: Roald's shock and his choice to protect Mdisho, the difference in how they see war, and the idea of equality. Discuss the colonial context critically. Vocabulary: disillusioned, appalled."),
  },
  projects: [
    P("poster", "Two Sides of the Road", "Design a two-sided poster showing the situation from Roald's viewpoint on one side and a German family's viewpoint on the other."),
    P("comic", "The Coast Road Standoff", "Draw the standoff between Roald's platoon and the convoy in 6 panels, showing his thoughts in thought bubbles."),
    P("drama", "Orders from the Captain", "Act out the meeting in the barracks. Then act a second version where Roald questions the orders. What changes?"),
    P("journal", "The Letter Roald Couldn't Send", "Write a private diary page where Roald explains what he really felt about the events of that week, which he could not put in a letter home."),
  ],
  quiz: [
    Q("What is an 'askari'?", "A local African soldier serving in the British colonial army (King's African Rifles)."),
    Q("Who gave Roald his orders at the barracks?", "A British Captain of the King's African Rifles."),
    Q("Where were the German civilians likely to run to?", "Portuguese East Africa (by the coast road)."),
    Q("True or False: Roald had years of military training before this job.", "False. He was a Shell employee with no military training.", "tf"),
    Q("What did the Sergeant cook for the askaris that night?", "Rice and sliced bananas in a huge pot."),
    Q("What did Roald plan to do to stop the convoy without hurting anyone?", "Fire a burst over their heads."),
    Q("What weapon did the leader of the Germans pull out?", "A Luger pistol."),
    Q("True or False: Roald ordered the machine-gun to fire on the convoy.", "False. He could never have done so.", "tf"),
    Q("What happened to the women and children in the convoy?", "They were allowed to go home."),
    Q("What went missing from Roald's house in Chapter 6?", "His silver Arab sword."),
    Q("How much did Roald pay for the sword?", "500 shillings."),
    Q("Who does Roald blame for changing Mdisho?", "Europeans who shaped him into a servant (he doesn't blame Mdisho himself)."),
    Q("What does Roald tell Mdisho to do about what he did?", "Tell no one."),
    Q("What does the Swahili word Roald uses for 'aeroplane' literally mean?", "Bird (Dahl spells it 'ndegi')."),
    Q("What does Roald give Mdisho when he leaves?", "The sword."),
    Q("What does Mdisho say about the two of them at the end of the chapter?", "That they are 'exactly equal'."),
    Q("Why did Dahl write that Mdisho was 'moulded' into a servant?", "Open-ended — European colonial society shaped how people were expected to behave."),
    Q("What is one difference between how Roald and Mdisho think about war?", "Open-ended — e.g. Roald believes in rules; Mdisho believes anything goes and it is about tribal honour."),
    Q("Why is the Sergeant's role in Chapter 5 important?", "Open-ended — he is calm and experienced and keeps the platoon steady while Roald is unsure."),
    Q("What question would you like to ask the narrator about this week's events?", "Open-ended — accept any thoughtful question."),
  ],
},
{
  num: 4, title: "Learning to Fly", chapters: "Chapter 7 & the start of Chapter 8",
  LI: "We are learning to follow a sequence of events over a long journey and to explain how an author's hindsight shapes the way a story is told.",
  SC: "I can put events in order, explain cause and effect between them, and point out where the narrator looks back with hindsight.",
  rubricTags: ["R3","R5","R10"],
  days: {
    mon: D("Chapter 7 (first part)", "Leaving Shell; the drive to Nairobi; joining the RAF",
      "Would you give up a safe, well-paid job for something dangerous that you feel you must do? What would help you decide?",
      "Describe two things Roald sees on his two-day drive to Nairobi and how he reacts to each one.",
      "Dahl says thirteen of the sixteen trainees were later killed in the air. Why do you think he shares this fact now, so many years later?",
      "Write a short letter to a friend from a recruit's first week away from home, mentioning three things you now have to do for yourself.",
      "Read from Roald's decision to join up through the first days of training at Nairobi (Tiger Moths, the instructors, the first letter). The comment about the trainees is a moment of hindsight — pause after it. Vocabulary: magnanimous, exhilarating, affable."),
    tue: D("Chapter 7 (middle)", "Going solo over Kenya; Kampala and Cairo",
      "What is the most nervous you have ever been before doing something completely on your own?",
      "How long did it take Roald to fly solo, and what does he see over Kenya?",
      "Roald is six feet six inches tall. What difficulties does this cause him in the Tiger Moth, and how does he solve them?",
      "Write a paragraph describing what it might feel like to fly alone over a landscape full of wild animals for the first time. Use at least three senses.",
      "Read from Roald's problems with cockpit height through his first solo flight, the letter about looping the loop, and the journey north to Cairo. The title 'Going Solo' links to this lesson — ask students what else the phrase might mean. Vocabulary: languorous, serenity, intrepid."),
    wed: D("Chapter 7 (end)", "Habbaniya, getting wings and a plane he'd never flown",
      "Have you ever been given a job with far too little instruction? How did you cope?",
      "How long did Roald's advanced training at Habbaniya last, and what does he say about living there?",
      "Dahl says he was 'thrown in at the deep end' when handed the Gladiator. What clues in the text suggest he thinks this was unfair or dangerous?",
      "Compare the letter Roald writes to his mother from Habbaniya with what he actually tells us about the place. What does he leave out and why?",
      "Read from the description of Habbaniya to the end of the chapter (the Gladiator handed over in one cockpit). Point out that letters to family often downplay danger. Vocabulary: supercilious, synchronized, abominable."),
    thu: D("Chapter 8 (first part)", "The forced landing in the desert",
      "What would you do if you were lost in unfamiliar country and running out of fuel as the sun set?",
      "What wrong information is Roald given, and what happens when he tries to land?",
      "Dahl says the magazine that printed his story changed the title to imply he'd been shot down. Why does he correct this, and what does it tell us about him as an author?",
      "Write a short paragraph describing the moment of a crash using only sounds and smells. Avoid saying how the person feels.",
      "Read from the opening about the magazine title through the end of the crash and the escape from the burning plane. Stop before the rescue party. The passage describes serious injuries — keep the tone calm and factual, focus on the narrator's determination. Vocabulary: forced landing, galvanized, no-man's-land."),
  },
  projects: [
    P("poster", "Join the Air Force", "Design a recruitment poster for the RAF in Africa in 1939, with a slogan and facts about what pilots must learn."),
    P("comic", "First Solo", "Draw a 6-panel comic of Roald's first solo flight in the Tiger Moth, showing the height problem and the view over Kenya."),
    P("drama", "The Medical Board", "Act out the medical examination in Nairobi where Roald's height is discussed. Show the doctor's reasoning."),
    P("journal", "Log Book Entry", "Write the log-book entry Roald might have written after his first solo, recording date, aircraft, flight time and one memorable observation."),
  ],
  quiz: [
    Q("What company did Roald work for before he joined the RAF?", "Shell."),
    Q("True or False: Shell stopped paying Roald once he joined the RAF.", "False. They kept paying his salary into his bank for as long as the war lasted.", "tf"),
    Q("What type of car did Roald drive to Nairobi?", "A Ford Prefect (his little old car)."),
    Q("How tall was Roald?", "Six feet six inches."),
    Q("What was the training aircraft called?", "The Tiger Moth."),
    Q("What rank did Roald have as a trainee?", "Leading Aircraftman."),
    Q("How many of the sixteen trainees were later killed?", "Thirteen."),
    Q("About how long did it take Roald to fly solo?", "Seven hours and forty minutes."),
    Q("What did he see over Lake Nakuru?", "Pink flamingos."),
    Q("Where did he do his advanced training?", "Habbaniya in Iraq."),
    Q("True or False: Roald had many hours of practice flying the Gladiator before joining his squadron.", "False. He was told to do a few circuits and fly it to his squadron the next day.", "tf"),
    Q("What type of plane was the Gladiator?", "An old-fashioned biplane fighter."),
    Q("What date did Roald take off from Abu Suweir in the Gladiator?", "19 September 1940."),
    Q("What was Roald not given for his flight to the squadron?", "A radio (only a map on his knee)."),
    Q("Why did Roald crash?", "He was given wrong directions and ran out of daylight and fuel, so he had to land in rough desert."),
    Q("What happened to his head during the crash?", "It hit the reflector-sight — he fractured his skull and injured his face."),
    Q("What was 'no-man's-land'?", "The strip between the British and Italian front lines where he crashed."),
    Q("Why did Dahl correct the title of his magazine story?", "Open-ended — to make clear that the crash was not caused by enemy fire."),
    Q("What does the phrase 'going solo' mean in Chapter 7?", "Flying a plane alone for the first time (also foreshadows other meanings of the title)."),
    Q("What is one prediction about Roald's recovery?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 5, title: "Blind but Determined", chapters: "Chapter 8 & the start of Chapter 9",
  LI: "We are learning to explain how an author writes about pain and fear calmly, and how a person's determination is shown through their choices.",
  SC: "I can describe how understatement and sensory detail affect the reader, and I can explain what a character's choices reveal about their determination.",
  rubricTags: ["R2","R6","R10"],
  days: {
    mon: D("Chapter 8 (second part)", "Rescue, the train to Alexandria and the surgeon",
      "What would be the hardest thing about being unable to see for weeks? What would you rely on instead?",
      "How does Roald get from the desert to the hospital in Alexandria?",
      "Dahl says he didn't fear blindness and accepted whatever came. How does this calm tone affect the reader, given how serious his injuries are?",
      "Rewrite one sentence from the operating scene so it sounds panicked. Then explain which version affects you more and why.",
      "Read from the patrol crawling to the wreck through the anaesthetic that doesn't work and the surgeon's promise about his new nose. There is dark humour in the banter between surgeon and anaesthetist — enjoy it. Vocabulary: anaesthetic, contusion, convalescence."),
    tue: D("Chapter 8 (third part)", "The nurse's voice; seeing again; letters home",
      "Have you ever formed a picture of someone from their voice alone? Was the picture right?",
      "How does Roald picture Mary Welland while he is blind, and what changes when he can see her?",
      "Dahl says there is a world of difference between loving a voice and loving a person you can see. What is he suggesting about first impressions?",
      "In his letters Roald tells his mother not to worry. Write two sentences he might have written, and two sentences he might have thought but didn't write.",
      "Read from the nurse who bathes his eyes each morning to the letter about being sent home and his refusal. The short episode about the amputated leg is not necessary — skip it. Vocabulary: dulcet, embossed, infinitesimal."),
    wed: D("Chapter 8 (end)", "Recovering; a Hurricane to fly to Greece",
      "When you really want something, what's the longest you have kept working towards it?",
      "What was Roald's main goal during his months in hospital, and what obstacle did doctors mention?",
      "Why does he refuse to be sent home to Britain? Use two pieces of evidence to explain his reasoning.",
      "Write a short pep talk that Roald might give himself on the morning he is discharged.",
      "Read from the discharge and convalescence at the Peel house through to the long flight to Greece. Emphasise how little training he has on the Hurricane. Vocabulary: petrified, juggernaut, valiantly."),
    thu: D("Chapter 9 (first part)", "Arriving at Elevsis; the Corporal's warning; meeting David Coke",
      "When you arrive somewhere new, how do you want people to treat you in the first hour?",
      "What does the Corporal say about the RAF's chances in Greece?",
      "Roald says he was 'young enough and starry-eyed enough' to see the campaign as an adventure. Why does hindsight make that sentence dramatic?",
      "Write a short description of the airfield using two similes.",
      "Read from the landing in Greece to the advice from David Coke about how to fight the enemy planes. Note the Cockney dialect of the Corporal; ask students to read some of his lines aloud. Vocabulary: extricate, bloomer, aghast."),
  },
  projects: [
    P("poster", "The Anglo-Swiss Hospital", "Design a poster for a hospital ward, showing what patients need most and how nurses help them."),
    P("comic", "Seeing Again", "Draw a 6-panel comic of Roald opening his eyelid to see the nurse's badge for the first time."),
    P("drama", "The Operating Theatre", "Act out the operating-theatre banter between the surgeon and anaesthetist, focusing on tone and timing."),
    P("journal", "Blind Diary", "Write a diary entry from Roald's time in bandages, describing the day only through sound, smell and touch."),
  ],
  quiz: [
    Q("Which city's hospital did Roald wake up in?", "Alexandria (in Egypt)."),
    Q("True or False: Roald could see straight away after the crash.", "False. He was blind for some time.", "tf"),
    Q("Who found Roald's crashed plane?", "A patrol from the Suffolk Regiment."),
    Q("What was the name of the new anaesthetic that failed?", "Sodium pentothal."),
    Q("What was used instead when it failed?", "Nitrous oxide (gas)."),
    Q("What was the nurse's name?", "Mary Welland."),
    Q("What did Roald imagine she looked like?", "A film star, Myrna Loy."),
    Q("What did he see first when his eyelid opened?", "The colourful emblem on the nurse's uniform (crown, anchor, red cross)."),
    Q("What happened to Roald's feelings when he could see Mary?", "He stopped being in love with her, though they stayed friends."),
    Q("True or False: Roald wanted to be invalided home to Britain.", "False. He refused because he knew he wouldn't fly again.", "tf"),
    Q("How long was he in hospital?", "About five months."),
    Q("What plane did he have to learn to fly to reach Greece?", "The Hurricane."),
    Q("Why did the flight to Greece take four hours and forty minutes?", "Extra fuel tanks were fitted because the plane had a limited fuel range."),
    Q("Where did Roald land in Greece?", "Elevsis, near Athens."),
    Q("How many Hurricanes did the RAF have in all of Greece?", "Fifteen."),
    Q("What name did the Corporal give to the German fighter planes?", "'One-O-Nines' (Messerschmitt 109s)."),
    Q("Who was Roald's tent-mate?", "David Coke."),
    Q("Why does Dahl describe himself as calmly accepting danger and blindness?", "Open-ended — it shows his calm mental attitude and helps him cope."),
    Q("What is one difference between how he writes about the hospital and how he writes about the crash?", "Open-ended — more humour and calm; less action."),
    Q("What do you predict will happen in Greece?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 6, title: "The Battle for Greece", chapters: "Chapters 9–11",
  LI: "We are learning to analyse how an author builds tension in action scenes and how he admits mistakes through hindsight.",
  SC: "I can identify words, sentences and structures that create tension, and explain why a narrator might admit his own errors.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapter 9 (second part)", "Advice from David; the mess tent; the lonely pilot",
      "What advice would you want from a more experienced person before doing something risky?",
      "What tips does David give Roald about fighting the German aircraft?",
      "Dahl says there were 'no real friendships' among the pilots except with David. How does the author show us that the pilots are lonely or distant?",
      "Write a short piece of advice you would give a new person joining your school or team, in the same friendly, direct voice David uses.",
      "Read from David's warnings about the odds to the notice-board patrol order for the next morning. You may skip the comic episode about the latrines. Vocabulary: incendiary, tracer, deflection."),
    tue: D("Chapter 9 (end)", "First patrol: the Ju 88 bombers over Khalkis",
      "Would you rather have a long warning before something scary, or no warning at all?",
      "What mistakes does Roald make when he first meets the bombers, and how does he still manage to shoot one down?",
      "The narrator says the whole flight felt 'like ten minutes'. What does this suggest about how time feels in a fight?",
      "Choose one moment and rewrite it in short, sharp sentences to build maximum tension.",
      "Read from the take-off at ten o'clock through the Squadron-Leader's cold reception. Note the similes for tracer bullets. Highlight what the narrator got right and wrong. Vocabulary: astern, unscathed, vector."),
    wed: D("Chapters 10 and 11 (first part)", "The ammunition ship and twelve sorties in four days",
      "What is something so beautiful that it might make you forget danger for a moment?",
      "Why is the ammunition ship such an important target, and what nearly goes wrong for Roald?",
      "Dahl compares the valley to a painting by Van Gogh but almost gets shot down because he's admiring it. Why does the author include beauty in a scene of danger?",
      "List the numbers of sorties flown each day in Chapter 11. Calculate the total and explain how these numbers make you feel.",
      "Read Chapter 10 in full and the opening of Chapter 11 (Log Book entries and the pilots lost) up to the day of the 20th. Emphasise the narrator's honesty: he says 'I had made a mess of it'. Vocabulary: perspex, panorama, calculated risk."),
    thu: D("Chapter 11 (second part)", "The Battle of Athens, 20 April",
      "What does it take to keep going when you are extremely frightened?",
      "What happens to the twelve Hurricanes over Athens, and how many are lost?",
      "After landing, Dahl says he felt 'pretty good', but his hands were shaking. What is the difference between what he says and what his body shows?",
      "Write about the moment David says 'I left a bit of water in the jug just in case you came back.' Why is this line so effective?",
      "Read from the decision to send all twelve aircraft up together to the end of the chapter (David at the washbasin). It is very intense but not graphic. Take time for the conversation at the end. Vocabulary: sortie, ace, doleful."),
  },
  projects: [
    P("poster", "Odds of Survival", "Create a poster with statistics about the odds facing the pilots in Greece, using data from the chapters."),
    P("comic", "The Dogfight", "Draw the dogfight over Athens as a 6-panel comic with sound effects and thought bubbles."),
    P("drama", "The Debrief", "Act out the scene after landing when the pilots try to light their cigarettes. What don't they say?"),
    P("journal", "Sortie Log", "Create a log of the four days of sorties, adding a brief personal comment for each day."),
  ],
  quiz: [
    Q("How many Hurricanes were in Greece when Roald arrived?", "Fifteen (fourteen plus his)."),
    Q("What was Roald's call sign?", "Blue Four."),
    Q("What are Ju 88s?", "German bomber aircraft."),
    Q("What did the Greeks do that acted as the RAF's radar?", "Spotters on mountain-tops telephoned the Ops Room."),
    Q("True or False: Roald shot down a Ju 88 on his first patrol.", "True.", "tf"),
    Q("What was the only damage to his plane after that patrol?", "A single bullet hole in a propeller blade."),
    Q("What did the Squadron-Leader say when he reported the victory?", "He asked whether he had seen it hit the ground; there was no praise."),
    Q("What was on the ship near Khalkis?", "Ammunition (high explosives)."),
    Q("Which painter does Dahl mention when describing the valley?", "Vincent van Gogh."),
    Q("What did Roald do to escape thirty or forty Messerschmitts?", "Dived to almost ground level and flew very low up the valley."),
    Q("How many sorties did Roald fly in four days?", "Twelve."),
    Q("True or False: The odds against surviving each sortie were about even.", "False. Dahl says it was more like five to one against.", "tf"),
    Q("Who led the formation over Athens?", "Flight-Lieutenant Pat Pattle."),
    Q("How many Hurricanes were lost that day?", "Five."),
    Q("About how many Messerschmitts were shot down?", "Twenty-two."),
    Q("Why were the pilots' hands shaking after landing?", "Open-ended — they were in shock after the danger."),
    Q("What does David Coke say about the water jug?", "He left some water in case Roald returned."),
    Q("Why does Dahl include beautiful description in a scene of terror?", "Open-ended — contrast makes the danger more shocking."),
    Q("How does the author show he is not boasting?", "Open-ended — he admits his mistakes and says survival was luck."),
    Q("What do you think will happen to the squadron next?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 7, title: "The Long Retreat", chapters: "Chapter 12 & the start of Chapter 13",
  LI: "We are learning to spot irony and criticism in an author's account, and to explain how orders and communication affect people's safety.",
  SC: "I can identify where the author is being ironic or critical, give evidence, and explain how a lack of information affects the characters.",
  rubricTags: ["R1","R7","R9"],
  days: {
    mon: D("Chapter 12 (first part)", "Strafing at the washbasin; the order to leave Elevsis",
      "What is worse for you: knowing something dangerous will happen, or not being told what is going on?",
      "What happens at the airfield in the minutes after the pilots land, and how do they react?",
      "The Adjutant keeps saying he is 'just passing on orders'. What does Dahl want us to think about how the army is being run?",
      "Write a short conversation between two junior officers who don't understand why they've been told to move in the dark.",
      "Read from the strafing raid at the washbasin to the night briefing at which the seven remaining pilots are told to leave before dawn. The opening has some comedy (caught without clothes) — enjoy it before the tension returns. Vocabulary: strafe, scramble, adjutant."),
    tue: D("Chapter 12 (middle)", "Megara: the hidden landing strip and the burning tanker",
      "Have you ever been somewhere quiet, waiting, knowing something big was about to happen?",
      "Where do the pilots go at dawn, and what do they see happening from the ridge?",
      "One young pilot suggests that someone wants to say the RAF 'fought bravely to the last pilot and last plane'. What is he suggesting about the leaders?",
      "Explain in your own words why the pilots feel that their lives are being used as a gesture.",
      "TEACHER NOTE: The Stuka attack on the tanker includes burning men in the sea. Paraphrase this part in one or two sentences (the ship was bombed and set on fire) and do NOT read the graphic description aloud. Focus on the pilots' feelings and their questions about who is in charge. Vocabulary: apprehensive, conspicuous, vantage."),
    wed: D("Chapter 12 (end)", "The Air Commodore's parcel; Carter; the landing at Argos",
      "If someone gave you a sealed parcel and said not to tell anyone what is inside, how would you feel?",
      "What does the Air Commodore ask Roald to do with the parcel, and who receives it?",
      "Dahl calls the Air Commodore a 'genius' in a sarcastic way. Find one detail in his orders that shows why the narrator does not respect them.",
      "What do you think was in the parcel? Write a short paragraph making your best guess, with reasons.",
      "Read from the arrival of the black car with the Air Commodore to the end of the chapter (the squadron-leader's tent at Argos). Ask students to look for the moment Roald realises Carter may be in serious danger. Vocabulary: compulsive, immaculate, exasperated."),
    thu: D("Chapter 13 (first part)", "Olives and wine at Argos; the twin-engined fighter",
      "What would you predict if you saw an enemy plane scout your base and then fly away?",
      "What do David and Roald deduce after the German fighter passes over three times?",
      "The pilots know what is coming but the commanding officer doesn't. What is the effect of this dramatic irony?",
      "Write a short scene in which two friends calmly predict their own danger. How can you show they are afraid without saying so?",
      "Read from the first paragraph of Chapter 13 (no food, locals selling olives) to the moment Roald and David are in position at 5:55, ready to take off at six. Vocabulary: famished, inferno, reconnoitring."),
  },
  projects: [
    P("poster", "Who Is in Charge?", "Design a satirical poster titled 'The Orders of the Day', showing three contradictory orders the pilots received and the confusion they caused."),
    P("comic", "The Parcel Mystery", "Draw a 6-panel comic following the parcel from the Air Commodore to Carter, leaving its contents a mystery."),
    P("drama", "The Night Briefing", "Act out the conversation between the Adjutant and the pilots about leaving Elevsis. Show his frustration and theirs."),
    P("journal", "Carter's Diary", "Write a diary entry from Carter's point of view on the night he waits at the empty airfield for the parcel."),
  ],
  quiz: [
    Q("What were the pilots doing when the German fighters attacked the airfield?", "Washing at the three-legged basin (with their pants down)."),
    Q("What single weapon did the airfield have for defence?", "One Bofors anti-aircraft gun."),
    Q("What did the pilots find out later that night?", "That they were to fly to a secret strip near Megara at dawn."),
    Q("How many pilots were left?", "Seven."),
    Q("What sort of vehicle rolled the runway at Megara?", "An old steam-roller."),
    Q("What did the pilots watch bomb the tanker?", "Stuka dive-bombers."),
    Q("True or False: The pilots were told exactly why they were moving.", "False. The Adjutant said he was only passing on orders.", "tf"),
    Q("Who arrived at Megara in a large black car?", "The Air Commodore."),
    Q("What did the Air Commodore give Roald?", "A sealed parcel to deliver to a man named Carter."),
    Q("What was Roald told to do if he was shot down?", "Burn the parcel."),
    Q("How did Carter dress?", "In a pale-grey suit and trilby hat."),
    Q("Where did the squadron fly next?", "Argos."),
    Q("What food and drink did the pilots buy from locals at Argos?", "Black olives and retsina."),
    Q("What time were they ordered to take off?", "Six o'clock."),
    Q("Why did Roald and David work out the Germans would attack at six?", "It took them time to get back to base, prepare and return."),
    Q("True or False: The commanding officer allowed them to take off before six.", "False. He refused.", "tf"),
    Q("What is dramatic irony?", "When the audience or characters know something that another person doesn't."),
    Q("Why might Dahl mention the unopened parcel and never reveal its contents?", "Open-ended — it creates mystery and shows how little information the pilots had."),
    Q("How does Dahl show his opinion of the Air Commodore?", "Open-ended — through sarcasm ('genius') and the odd orders."),
    Q("What do you predict happens at six o'clock at Argos?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 8, title: "Out of Greece, Into New Dangers", chapters: "Chapters 13 (end), 14 & the start of 15",
  LI: "We are learning to compare two people's points of view in a conversation, and to read critically when we notice bias or gaps in what a narrator knew.",
  SC: "I can explain what each speaker in a conversation believes and wants, and I can identify language that shows the narrator's own bias or ignorance.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 13 (end)", "No fleet in sight; the Argos raid; escape to Egypt",
      "What is the hardest part of accepting that the plan you followed was a mistake?",
      "What happens to the airfield at six o'clock, and how do Roald and David get out of Greece?",
      "Dahl says it is 'easy to be critical of one's commanders after the event'. What does this tell you about how he wants us to judge the leaders?",
      "Write a short paragraph explaining why the Greek campaign mattered to the wider war, using information from the last page of the chapter.",
      "Read from the flight out to sea at six o'clock through to the end of the chapter (the Peels' house, the letter, and the closing summary). Point out the contrast between the letter's cheerful tone and the reality. Vocabulary: fiasco, bedraggled, annihilate."),
    tue: D("Chapter 14 (first part)", "Vichy France, the drive across Sinai and the scorpion",
      "What is the longest time you have been alone, without seeing another person? How did it feel?",
      "Why did the British have to fight in Syria, and how does Roald get to Haifa?",
      "Dahl calls the campaign against Vichy forces 'unnecessary slaughter'. What clues show his opinion of the war in Syria?",
      "Write a paragraph describing a desert night from the point of view of someone completely alone. Use imagery.",
      "TEACHER NOTE: Explain the Vichy French: they were French forces who worked with Nazi Germany after France fell. Dahl's language about them is angry and one-sided — use this as an opportunity to notice bias. Read from the invasion of Crete and the Syrian campaign to the Rayak airfield raid, including the drive across the Sinai. Vocabulary: Vichy, campaign, chivalry."),
    wed: D("Chapter 14 (second part)", "The cornfield settlement and the man with the beard",
      "What do you think a person needs most in order to feel safe — a home, a country, a family?",
      "Who lives in the cornfield settlement, and what does the man say about his people's situation?",
      "Roald and the man both say they are 'fighting for freedom'. How is each man's idea of freedom different?",
      "Write a short conversation between Roald and one of the children in the settlement, in which Roald learns something he didn't know.",
      "TEACHER NOTE: This lesson deals with Jewish refugees, the Holocaust and Roald's ignorance at the time. Dahl was later criticised for public antisemitic remarks; his family and the Roald Dahl Story Company apologised in 2020. State this briefly and factually, and ask students to read the passage critically. Explain that in 1941 many people did not know what was happening to Jews in Europe. Vocabulary: refugee, homeland, persecution."),
    thu: D("Chapter 15 (first part)", "The headaches; leaving the squadron; the voyage home",
      "How would you feel about going home after a long time away, not knowing what you'd find?",
      "Why is Roald sent home from the squadron, and what happens to David Coke afterwards?",
      "Dahl gives us news about the future of his friends in a single paragraph. What effect does this have on the reader?",
      "Write a short paragraph explaining Roald's feelings as he dials the telephone number in the darkness, using details from the text.",
      "Read from the headaches and the doctor's diagnosis through the voyage home and the phone call at Liverpool docks, ending as he rings his mother from London (STOP at 'Then I rang my mother.'). Vocabulary: invalided, convoy, hazardous."),
  },
  projects: [
    P("poster", "The Cost of a Campaign", "Design a poster listing what was lost in Greece and what the Greek campaign changed for the war in the Middle East."),
    P("comic", "The Cornfield Strip", "Draw a 6-panel comic of Roald's meeting with the children and the bearded man in the settlement."),
    P("drama", "Two Freedoms", "Act out the conversation between Roald and the bearded man, showing each side's point of view with respect."),
    P("journal", "Letter from the Cornfield", "Write a letter from one of the settlement's children about the day the pilot landed."),
  ],
  quiz: [
    Q("Where did the squadron fly from Argos to escape?", "Some flew to Crete; the other pilots flew out in a small passenger plane to Egypt."),
    Q("True or False: The pilots found the British fleet ready to protect them.", "False. There was no fleet in sight.", "tf"),
    Q("What kind of small plane nearly gets shot down by Roald?", "A de Havilland Rapide (RAF markings)."),
    Q("What did Roald lose in the raid on Argos?", "His camera (stolen), though he saved two rolls of film."),
    Q("Whose house did the pilots stay at in Alexandria?", "Major Bobby Peel and his wife."),
    Q("What did Bobby Peel say about the Greek campaign?", "That it was a mistake ('a cock-up') and they should never have gone."),
    Q("Who were the Vichy French?", "French forces that co-operated with Nazi Germany."),
    Q("What did Roald drive across the Sinai Desert?", "His old Morris Oxford car."),
    Q("What creature did he see with babies on her back?", "A scorpion."),
    Q("What does the bearded man call the children?", "Orphans (refugees)."),
    Q("True or False: The settlement's land belonged to the refugees.", "False. It belonged to a Palestinian farmer who let them use it.", "tf"),
    Q("What was the name of the settlement in Roald's Log Book?", "Ramat David."),
    Q("What surprised Roald about the settlement?", "That so many Jewish refugees lived there and how much he didn't know."),
    Q("What sort of headaches did Roald develop?", "Blinding headaches during steep turns in flight."),
    Q("Why could he no longer fly?", "The doctor said it was caused by his head injuries and flying could cause him to lose consciousness."),
    Q("What did Roald bring for his family from Freetown?", "Lemons, limes, tinned marmalade and sugar."),
    Q("What is bias?", "An unfair leaning towards one side."),
    Q("Why might Dahl's opinion of the Vichy French be biased?", "Open-ended — he calls them names and doesn't consider their side."),
    Q("What do the bearded man and Roald disagree about?", "Open-ended — whose problems are bigger and what freedom means."),
    Q("What do you predict will happen when Roald calls his mother?", "Open-ended — accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 9, title: "Home — and Looking Back", chapters: "Chapter 15 (book finishes) & review of the whole book",
  LI: "We are learning to draw the whole book together — to link causes across chapters, compare two kinds of writing, and form a supported opinion about the author and his choices.",
  SC: "I can link events from different parts of the book, compare a letter with the narration, and write an opinion supported with evidence.",
  rubricTags: ["R1","R4","R10"],
  days: {
    mon: D("Chapter 15 (end)", "The phone call to Mama and the reunion at the cottage",
      "Have you ever waited a long time for someone or something? What did you feel when it finally came?",
      "Describe the sequence of events by which Roald finally reaches his mother.",
      "Why does Dahl take so long to describe the final moments (the bus journey and the waiting mother)? What effect does the slow pace create?",
      "Write one paragraph describing a reunion, using both an emotional detail and a physical detail.",
      "Read from 'Then I rang my mother' to the final line of the book. Read slowly, with pauses. This is a good moment for quiet appreciation. Vocabulary: rural, thatched, frantic."),
    tue: D("Whole book (review)", "Letters and narration: comparing two voices",
      "Do you tell your family everything that happens to you? Why might people leave things out?",
      "Compare a letter from one of the earlier chapters with the narration that follows it. What is different?",
      "Why do you think Roald's letters to his mother sound cheerful even when things are dangerous?",
      "Write your own pair: a short cheerful letter home and a short honest diary entry about the same difficult day.",
      "TEACHER NOTE: Choose two or three short letters from the book (for example the Red Sea letter in Chapter 1, the malaria letter in Chapter 5, the hospital letters in Chapter 8, and the Argos letter in Chapter 13) and read short parts aloud. Paraphrase rather than reading at length. Ask students to look at tone, purpose and audience."),
    wed: D("Whole book (review)", "Cause and effect across the memoir",
      "If one small event had been different, what might have changed for Roald?",
      "Name three events from different chapters and explain how each led to the next.",
      "Which event do you think most changed the direction of Dahl's life? Argue for your choice.",
      "Draw a 'chain of events' diagram with at least six links, then write two sentences explaining the strongest link.",
      "Use the class reading journal or a timeline. Students should link across chapters — e.g. the war in Chapter 5 leads to his RAF training in Chapter 7, which leads to the crash in Chapter 8, and then to Greece in Chapters 9–13. Vocabulary: consequence, chain, catalyst."),
    thu: D("Whole book (review)", "Courage, luck and being a critical reader",
      "Is being brave the same as not being afraid? What makes someone brave?",
      "What are two moments in the book where Roald shows courage, and two where luck plays a part?",
      "Dahl was a brilliant storyteller but also made comments in later life that hurt people. How should we read an author's work when we know this?",
      "Write an opinion paragraph: 'Roald Dahl is a reliable narrator of his own life.' Use at least three pieces of evidence.",
      "TEACHER NOTE: Invite a balanced discussion. Students can hold two ideas: the book is a gripping account AND the narrator is not always fair. Refer to bias in Chapter 14 and the colonial attitudes in Chapters 1, 2 and 6. Close with a whole-class reflection on the title 'Going Solo'."),
  },
  projects: [
    P("poster", "The Map of a Journey", "Draw a map of Roald's journey from England to East Africa to Greece and back home, with three annotated stops."),
    P("comic", "Home at Last", "Draw a 6-panel comic of the reunion, showing small gestures rather than speech."),
    P("drama", "The Interview", "Act out an interview with Roald Dahl about his journey. One student is the interviewer; another is Roald."),
    P("journal", "Going Solo — My Own", "Write a short memoir-style page about a time you did something on your own for the first time."),
  ],
  quiz: [
    Q("What is causing Roald's terrible headaches when he flies?", "His earlier head injuries from the crash."),
    Q("Who did Roald telephone first in London to get his mother's number?", "His half-sister (married to Professor Miles)."),
    Q("True or False: His mother knew he was coming.", "False. The censors would not have allowed it to be written in letters.", "tf"),
    Q("What was the name of the village where his mother had moved?", "Grendon Underwood."),
    Q("What sort of house did she live in?", "A small white thatched cottage."),
    Q("Why had they moved from Kent?", "A bomb destroyed their house."),
    Q("What did Roald carry home for his family?", "Lemons, limes, marmalade and sugar."),
    Q("What is a memoir?", "A true account of the writer's own experiences."),
    Q("Name one event from Chapter 1 and one from Chapter 15.", "Open-ended — e.g. the wig reveal and the reunion at the cottage."),
    Q("True or False: The reunion is told very quickly.", "False. The narrator slows it down.", "tf"),
    Q("What is the effect of the book ending at the cottage gate?", "Open-ended — it leaves a strong emotional last image."),
    Q("What does 'going solo' mean in the book?", "Flying alone, but also living independently."),
    Q("Which chapter describes the Battle of Athens?", "Chapter 11."),
    Q("Which chapter describes the crash in the desert?", "Chapter 8."),
    Q("Name one person Dahl admired in the book and say why.", "Open-ended — e.g. David Coke for bravery; Salimu for courage."),
    Q("Name one thing Dahl treated unfairly or with bias.", "Open-ended — e.g. his description of the Vichy French or the word 'boy'."),
    Q("What does the phrase 'reliable narrator' mean?", "A narrator who tells the truth fairly and accurately."),
    Q("Why is a letter different from a diary?", "A letter is written for someone else and may leave things out."),
    Q("What lesson from this book will you take with you?", "Open-ended — accept any thoughtful answer."),
    Q("What would you like to ask Roald Dahl if you could?", "Open-ended — accept any thoughtful question."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "Journey Exhibition", desc: "Create a museum-style display (map, timeline and annotated artefacts such as the Log Book, sword, parcel and camera) that tells the story of Roald's journey and what each stage cost or taught him." },
    { title: "Untold Scene Drama", desc: "Write and perform a scene the book doesn't show — from the point of view of Mdisho, Carter, the Corporal, David Coke, Mrs Dahl or the bearded man — told with empathy and evidence from the text." },
    { title: "Character Case File — Roald", desc: "An in-depth profile (poster + written report + panels) tracking how Roald changes across the whole memoir, with evidence from every part of the book and a section on how reliable a narrator he is." },
    { title: "\"Going Solo\" Class Anthology", desc: "Each student contributes one illustrated page titled \"Going Solo\", a true memoir page about a time they did something new, brave or hard on their own, written with humour, suspense or sensory detail." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: share favourite moments from the term.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic events from the memoir.",
      wt: "Explains some of Roald's choices or feelings, with limited evidence.",
      a: "Explains a big idea (courage, resilience, luck, the cost of war) and supports it with clear evidence from across the book.",
      example: "A Character Case File showing how Roald moves from an excited young traveller to a pilot who has lost many friends, with an event from the beginning, middle and end of the book." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A Journey Exhibition with a labelled map, a timeline and three artefact cards, each with a caption explaining why it matters." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "An Untold Scene drama told from Carter's point of view, rehearsed and improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
