/* ============================================================
   A LONG WALK TO WATER (Linda Sue Park) — BOOK STUDY APP DATA
   Content data only. No markup/behaviour lives in this file.
   Years 7–8 · NZ Curriculum Level 4 English
   Based on a true story: Salva Dut (1985 Sudan, "Lost Boys") and
   Nya (2008–09 Southern Sudan) — two journeys that meet at a well.
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Perseverance, Hope & Service", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 4 (Years 7–8).
   "Achieved" = the curriculum expectation has been met.
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas that connect Salva's 1985 storyline and Nya's 2008–09 storyline (survival, the true cost of walking for water, hope, generosity) and supports them with events from both timelines.",
    kid: "I can explain a big idea that connects Salva's story and Nya's story, and back it up with events from both.",
    ask: "Does the student compare across the two timelines, not just retell one of them?",
    na: "Retells events from only one storyline and cannot yet connect it to the other.",
    wt: "Names a shared idea (e.g. 'they both need water') with a general reason, but the comparison is thin or one-sided.",
    ach: "Explains an idea that runs across both timelines and supports it with a specific, accurate event from each.",
    wtSample: "Salva and Nya both have hard journeys because of water and war.",
    exemplar: "Salva's whole journey across Sudan, Ethiopia and Kenya happens because war took away his home; Nya's daily eight-hour round trip happens because her village has no well. Both stories are really about the same thing — what people are forced to do just to survive — and the book puts them side by side so we feel how connected 'walking for safety' and 'walking for water' really are.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-deeper reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features on a text's meaning.",
    expect: "Notices the author's structural choice — two timelines (1985 and 2008–09) told in short, alternating chapters — and explains what effect that structure has on tension, pace and the reader's understanding, including how it sets up the final twist.",
    kid: "I can explain why the author tells Salva's and Nya's stories side by side instead of one at a time, and what effect that has on me as a reader.",
    ask: "Does the student name the structural choice AND explain its effect, not just describe the plot?",
    na: "Comments only on what happens in the plot; does not yet notice how the book is built.",
    wt: "Notices the book switches between Salva and Nya but cannot explain why, or the explanation is very general ('it's more interesting').",
    ach: "Names the alternating-timeline structure and explains a specific effect — e.g. it builds suspense by cutting away at a cliffhanger, or it lets the ending land as a surprise because we don't expect the two stories to be connected.",
    wtSample: "The book keeps changing between Salva and Nya and it makes it exciting.",
    exemplar: "Park always cuts away from Salva right when things get most dangerous — the rebel camp, the lion, the river — and jumps to Nya's much quieter chapter. That contrast makes Salva's danger feel even more intense, but it also trains me to expect the two stories are echoing each other, so when they finally meet at the well in the last chapter, it doesn't feel random — it feels earned.",
    evidence: "Structure & language questions, inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, comparing, synthesising — and links an event in Salva's timeline to an event in Nya's, or an earlier chapter to a later one.",
    kid: "I can use reading strategies to link what's happening to Salva to what's happening to Nya, or to something earlier in the same story.",
    ach: "Independently draws a justified connection between the two timelines, or between an earlier and later event in the same timeline, without being told to.",
    wt: "Makes a link between timelines or events only when prompted, or the link is superficial (both involve walking).",
    ask: "Can the student explain WHY two events echo each other, not just THAT they do?",
    wtSample: "Salva walks a lot and Nya walks a lot too.",
    exemplar: "Nya's daily walk to the pond and Salva's desert crossing both turn ordinary movement into something dangerous and exhausting, and both stories keep returning to specific numbers (hours, miles, days) to make the reader feel the walking as real distance, not just a phrase. Noticing that pattern early helped me predict that water — not just war — would be the thing that finally connected the two stories.",
    evidence: "Predictions, cross-text comparison questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics, showing an increasing awareness of purpose and audience.",
    expect: "Writes and shares clear, developed opinions and explanations about the book — including on difficult questions (should Salva have kept walking when Uncle Jewiir died? was it right that boys were separated from their families as 'men'?) — with supporting detail from the text and, where relevant, the historical record.",
    kid: "I can share a clear opinion about a hard question the book raises, and back it up with reasons and evidence.",
    ask: "Is there a clear position PLUS at least two reasons or pieces of evidence, including historical context where it's relevant?",
    na: "Answers are one-sided, unclear, or state an opinion with no supporting reason.",
    wt: "Shares a clear opinion but gives only one reason, or does not use evidence from the text.",
    ach: "Communicates a clear, considered opinion and develops it with at least two reasons or pieces of evidence, drawn from the text and/or the author's note.",
    wtSample: "I think Salva was brave to keep walking after his uncle died.",
    exemplar: "I think Salva's decision to keep walking after Uncle Jewiir was killed shows real courage, not just because he was scared, but because he had every reason to give up — he'd already lost his family and now the one adult protecting him. First, the text shows him remembering his uncle's words about walking 'only today' rather than thinking about the whole impossible journey. Second, the author's note confirms this really happened to thousands of boys, which makes his choice to keep going feel even more remarkable — it wasn't just a character's decision, it was a survival strategy real 'Lost Boys' used.",
    evidence: "Go-deeper reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts for a range of purposes and audiences.",
    expect: "Chooses the right structure and language for the task — a diary/log entry in a character's voice, a persuasive campaign, a news report, a script — and matches register and tone to 1985 Sudan/Ethiopia/Kenya or 2008–09 Southern Sudan as appropriate.",
    kid: "I can choose the right kind of writing and the right voice for the task, and make it sound like it belongs to the right time, place and character.",
    ach: "Uses a suitable structure and language features for the purpose and audience, and the voice/register fits the character's world (e.g. short, urgent present-tense narration for Salva's river crossing; plain, physical, repetitive language for Nya's daily walk).",
    wt: "Attempts the right form but the language or structure is inconsistent, or doesn't fit the character/setting.",
    ask: "Does the writing look, sound, and feel like it belongs to the character and the time period it claims?",
    na: "Writing does not match the task; little attempt at structure or appropriate language features.",
    wtSample: "Dear diary, today was scary because there was fighting and we had to leave our home.",
    exemplar: "Day unknown. We walk until the sun goes soft and orange, then we stop because it is too dark to see the path. My feet do not feel like my feet anymore. Uncle says: today, only today. Not the whole desert — just today. I try to believe him. — Salva",
    evidence: "Poster, comic, drama & journal projects; Week 9 opinion writing; Week 10 campaign/anthology" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback (Glow & Grow) to improve it, and can explain a specific change made because of that feedback.",
    kid: "I can plan my work, improve a draft, and use feedback to make a specific, named improvement.",
    ach: "Independently plans, drafts and revises, and can point to a specific change made because of feedback.",
    wt: "Plans and drafts with support; makes only small, vague changes when prompted.",
    ask: "Can you see a plan AND one specific change the student can name and explain?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wtSample: "I finished my poster. My partner said to add more detail so I did.",
    exemplar: "My plan had three panels: before, during and after the well is finished. My partner's 'grow' note said the ending felt too sudden, so I added a fourth panel showing Nya's family collecting rocks for the drilling site — a real detail from the text — which made the celebration at the end feel like something the whole village had worked for, not something that just appeared.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas — including views on sensitive, real-world issues.",
    expect: "Listens to and builds on others' ideas during group reading and projects, including when discussing difficult or contested topics (civil war, forced recruitment of children, unequal access to water and healthcare), and disagrees respectfully.",
    kid: "I can listen to my group, take turns, and build on — or respectfully challenge — other people's ideas, even about hard topics.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas, especially on sensitive real-world topics raised by the book.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ask: "Does the student respond to what others say — including disagreeing respectfully — rather than just waiting for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt, dismiss others, or opt out.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I actually see the rebel camp scene differently to Mia — I don't think the soldier who let Salva go was being kind exactly, I think the text is showing us he just decided Salva was too young to be useful. Can we look at that page again?\" She then invited a quieter group member to weigh in.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects, discussion circles — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas, including recognising bias and perspective.",
    expect: "Makes inferences about characters' feelings and motives using clues from the text, and thinks critically about perspective and bias — whose viewpoint a scene is told from, and what is left out.",
    kid: "I can use clues in the story to work out things the author doesn't state directly, and notice whose point of view I'm not getting.",
    ach: "Independently infers feelings or motives and points to the textual clue, AND can identify a perspective the text does not show (e.g. the Nuer men, the drilling crew's other workers, Nya's mother) and speculate about it fairly.",
    wt: "Makes an inference with prompting but struggles to explain the clue, or does not yet consider perspectives beyond the protagonist's.",
    ask: "Has the student worked something out, pointed to the clue, AND considered an angle the text doesn't spell out?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wtSample: "Salva feels sad because his uncle died.",
    exemplar: "The text never says Salva feels responsible for surviving when Marial and Uncle Jewiir don't, but it tells us he 'knew that both of them would have wanted him to survive' — that's the author trusting us to notice his guilt and his sense of duty without spelling it out. It also made me wonder about the drilling crew members we never hear from directly — what does it feel like to spend your whole working life bringing water to villages that have been suffering for generations?",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions, discussion" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility, including for topics that connect to real communities beyond the classroom.",
    expect: "Contributes ideas in class discussions and projects, takes responsibility for a role in group work, and connects the book to real communities and current events with care and accuracy.",
    kid: "I can share my ideas, do my part in group work, and connect the book to the real world responsibly.",
    ach: "Offers ideas without being asked, takes responsibility for a role, encourages others, and makes an accurate, respectful connection between the book and a real-world community or issue.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ask: "Does the student offer ideas and take on a job without being asked, and handle real-world connections with care rather than glib comparison?",
    na: "Rarely contributes to discussions or group projects.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 campaign group, Aroha researched a real current water-charity organisation, made sure the group's facts about global water access were accurate rather than exaggerated, and made sure everyone had a speaking part in the final presentation.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Perseverance, Hope & Service", strand: "Values",
    curriculum: "Values: community and participation, respect, and care for others — recognising perseverance, hope as an active choice, and generosity as service to others.",
    expect: "Connects the book's values — perseverance through 'just today' thinking, hope kept alive across years of hardship, and generosity that turns personal suffering into service for others — to their own life, community or actions.",
    kid: "I can connect the book's message about perseverance, hope and generosity to my own life or community.",
    ach: "Explains a value from the book and connects it to a real experience, action, or current issue of their own — without minimising the seriousness of what the characters go through.",
    wt: "Names a value (e.g. 'never give up') when asked, with a simple or general link.",
    ask: "Has the student linked a value from the book to something real, while still respecting how serious the characters' situations are?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wtSample: "The book teaches us to never give up and to help other people.",
    exemplar: "Salva didn't just survive his own walk — he spent years afterwards raising money, person by person, church by church, to dig wells so other people wouldn't have to walk the way Nya does. That's a kind of generosity that comes directly out of his own suffering, not despite it. It makes me think about small things in my own community — like foodbank donations or fundraising for a local cause — as connected to the same idea: using what you've survived to make things easier for someone else.",
    evidence: "Go-deeper reflections, journal entries, Week 10 'connections' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 4 English, Years 7–8, NZ Curriculum",
  lrv: [
    "Ideas: Show an increasingly detailed understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show an increasingly detailed understanding of how texts are shaped for different purposes and audiences, and of the effects of language features.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics, with increasing awareness of purpose and audience.",
    "Structure and Language: Show an increasingly detailed understanding of language features and structure, using them appropriately in a range of texts.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies with increasing confidence to identify, form, and express ideas.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Perseverance under extreme hardship, hope as a daily, active choice, generosity and service to community, courage, resilience, and the value of a basic need (clean water) that many students have never had to think about.",
  crossCurricular: "Social Sciences — history and place & identity (the Second Sudanese Civil War, 1983–2005, the resettlement of the 'Lost Boys of Sudan', and global access to clean water and sanitation), since both Salva's and Nya's lives are shaped directly by real historical and present-day forces.",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "Two Ordinary Mornings", chapters: "Chapters 1–2",
  LI: "We are learning to compare how two characters in two different times experience danger and hardship in their daily lives.",
  SC: "I can describe how Salva and Nya are each introduced, and explain one thing their situations share even though their worlds are decades apart.",
  rubricTags: ["R1","R7","R8"],
  days: {
    mon: D("Chapter 1 (Nya, 2008)", "Nya sets out on the long, hot walk to fetch water — thorns, heat and time, with the container still light on the way there",
      "Think about the longest walk you do regularly (to school, to a bus stop). Now imagine doing it twice a day, every day, carrying something heavy on the way back. How would that change your day?",
      "What does Nya carry, and why does the author tell us the walk is \"easy\" going but not coming back?",
      "Why might the author choose to start the book with something as ordinary-sounding as fetching water, rather than with danger?",
      "Write two sentences describing your own morning routine, then two sentences imagining Nya's, side by side."),
    tue: D("Chapter 1 (Salva, 1985)", "Salva daydreams in class about home and his mother's milk — then gunfire erupts and his teacher orders everyone to flee into the bush",
      "If you were sitting in class and suddenly heard something that might be gunfire, what do you think your body would do before your brain caught up?",
      "What is Salva daydreaming about just before the gunfire starts, and why is that detail important?",
      "Why does the teacher tell the boys to run into the bush instead of running home?",
      "Write a one-paragraph account of the moment the gunfire starts, from Salva's point of view, using short, urgent sentences."),
    wed: D("Chapter 2 (Nya, 2008)", "Nya sits to deal with a thorn stuck deep in her heel — a small, constant danger of the walk to the pond",
      "Have you ever had something small (a splinter, a stone in your shoe) become a much bigger problem than it seemed at first?",
      "What has happened to Nya's foot, and how does she try to deal with it herself?",
      "Why might the author spend a whole scene on something as small as a thorn, instead of skipping past it?",
      "Write about a small, everyday discomfort that most people in your life never have to think about."),
    thu: D("Chapter 2 (Salva, 1985)", "Salva runs from the burning school and joins a growing crowd of strangers all walking away from danger, unsure where his family is",
      "Imagine being suddenly separated from your family with no way to contact them. What would be the very first thought in your head?",
      "What has happened to the school and village behind Salva, and what does he not yet know?",
      "Why does the author repeat Salva's worried questions (\"Where are we going? Where is my family?\") in his thoughts as he walks?",
      "Write the three questions you think would loop in your own head if you were suddenly separated from everyone you knew."),
  },
  projects: [
    P("poster", "Two Journeys, One Continent", "Design a poster with a simple map of Southern Sudan marking Nya's village (2008–09) and the area where Salva's journey begins (1985), with one key fact about each."),
    P("comic", "The Moment Everything Changed", "4 panels: 2 for Salva (classroom to gunfire to running), 2 for Nya (setting out, sitting with the thorn) — show both 'ordinary mornings' cracking open."),
    P("drama", "Everyone, Down!", "Act out the classroom scene: the teacher's warning, the panic, and the decision to run into the bush instead of home."),
    P("journal", "My Version of the Walk", "Write about the longest, hardest walk or chore you do regularly, and honestly compare it to Nya's walk for water — what's similar, and what's very different?"),
  ],
  quiz: [
    Q("Where and when does Nya's story begin?", "Southern Sudan, 2008."),
    Q("Where and when does Salva's story begin?", "Southern Sudan, 1985."),
    Q("What is Nya carrying, and what is inside it on the way to the pond?", "A large plastic container; on the way there it holds only air (it's empty)."),
    Q("True or False: Nya's walk is described as equally hard going and coming back.", "False — going is easy (empty container); coming back is much harder (full and heavy).", "tf"),
    Q("What subject is Salva's class studying when the story opens?", "Arabic (the official language of the Sudanese government)."),
    Q("What language does Salva speak at home?", "Dinka."),
    Q("What is Salva daydreaming about in class?", "Walking home and having a bowl of fresh milk from his mother."),
    Q("What sound interrupts the lesson, and what does the class first think it might be?", "A loud crack — they wonder if it's a gunshot or a car backfiring."),
    Q("What does the teacher tell the boys to do, and why not go straight home?", "Run into the bush, not home — because soldiers will be going into the villages."),
    Q("Vocabulary: What does it mean that people were \"scattered\" as they fled?", "Spread out in different directions, not moving as one organised group."),
    Q("What has happened to Nya's foot in Chapter 2?", "A large thorn has broken off and lodged deep in her heel."),
    Q("How does Nya try to deal with the thorn herself?", "She uses another thorn to poke and prod at the skin around it."),
    Q("True or False: Salva immediately finds his family after running into the bush.", "False — he is separated from them and does not know where they are.", "tf"),
    Q("What does Salva see happen to the school as he runs?", "A huge cloud of black smoke and flames rise from it after an explosion; a jet plane flies overhead."),
    Q("Vocabulary: What does the word \"refugee\" mean, based on what you already know or can predict from these chapters?", "Someone forced to leave their home/country, often because of war or danger, to seek safety elsewhere."),
    Q("Why might the author choose to open with two separate, seemingly unconnected stories?", "Open-ended — to build curiosity about how two very different lives will eventually connect, and to show hardship exists in more than one form."),
    Q("What is one thing Salva's and Nya's opening chapters have in common, even though their situations look very different?", "Open — both involve a physically demanding, repeated journey/walk, and both show a character managing pain or fear largely alone."),
    Q("Predict: Why do you think the book is called A Long Walk to Water?", "Open-ended, text-supported prediction — accept references to both characters' journeys."),
    Q("What detail in Chapter 1 tells us Salva's family is relatively well-off in their village?", "His father owns many cattle and is the village judge; Salva is able to attend school."),
    Q("Whole-section check: In one sentence each, what is the biggest problem facing Salva and the biggest problem facing Nya at the end of this week's reading?", "Salva: he is suddenly separated from his family and fleeing danger. Nya: she is in pain from a thorn and still has hours of hard walking ahead of her, every day."),
  ],
},
{
  num: 2, title: "Walking Among Strangers", chapters: "Chapters 3–4",
  LI: "We are learning to explain how a character's safety depends on decisions made by adults and strangers around them.",
  SC: "I can describe a moment where Salva's fate is decided by someone else, and explain what that reveals about being a child in a war.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapter 3 (Nya, 2008)", "Nya arrives at the muddy pond, the only water source for her village, and waits her turn among crowds of others doing the same",
      "What do you picture when you imagine the only water source for an entire village — is it clean, is it close, is it shared fairly?",
      "What condition is the pond water in, and who else is there collecting water alongside Nya?",
      "Why might the author describe the pond in such plain, unflinching detail rather than softening it?",
      "Write a short description of a water source you use every day (a tap, a fridge, a fountain) using the same close, detailed style."),
    tue: D("Chapter 3 (Salva, 1985)", "Salva finds people from his own village, Loun-Ariik, among the crowd of refugees and spends an uneasy night with them by the road",
      "If you were lost in a crowd of strangers, what would it feel like to suddenly hear the name of your own home town called out?",
      "How does Salva find people connected to his own village, and how does that make him feel, even though none of them are close family?",
      "Why is it important to the group that men take turns keeping watch overnight?",
      "Write about a time a small, familiar connection (a name, a place, a face) made you feel less alone in an unfamiliar situation."),
    wed: D("Chapter 4 (Nya, 2008)", "Nya's home life is shown in more detail — her mother, her baby brother, and her five-year-old sister Akeer, whom she is asked to mind on the walk",
      "What extra responsibility do you think it would add to an already-hard chore if you had to look after a much younger sibling at the same time?",
      "Who makes up Nya's immediate family, and what job is Nya given regarding her sister Akeer?",
      "Why might Nya feel frustrated that Akeer is \"too small and walks too slowly\", even though she doesn't say this out loud?",
      "Write about a responsibility you've been given for a younger sibling, cousin or neighbour, and how you balanced it with your own needs."),
    thu: D("Chapter 4 (Salva, 1985)", "The rebel soldiers separate the crowd into two groups — men and boys who look old enough versus women, children and the elderly — and a soldier decides Salva's fate with one look",
      "Imagine a stranger with a weapon deciding, based only on how old you look, which group you belong to. How much control would you have over that moment?",
      "What decision does the soldier make about Salva, and on what basis does he seem to make it?",
      "Why does Salva nearly walk toward the men's group, even though he is only eleven?",
      "Write about a time you were judged or grouped based only on how you looked, not on who you actually were."),
  },
  projects: [
    P("poster", "One Village's Only Water Source", "Design a poster showing the muddy pond Nya's village depends on, labelled with why it is unsafe and how many people rely on it."),
    P("comic", "The Gun's Barrel", "Show, panel by panel, the tense moment a rebel soldier decides whether Salva is a child or a \"man\", ending on how it's resolved."),
    P("drama", "Groups! Men Here, Everyone Else There.", "Act out the moment the crowd of refugees is ordered to split into two groups, staying respectful to how frightening a real version of this would be."),
    P("journal", "Minding Akeer", "Write from Nya's point of view about being asked to look after Akeer on the walk — the parts that would be annoying, and the parts that might actually help."),
  ],
  quiz: [
    Q("What is the only water source available to Nya's village?", "A pond (a muddy, unclean waterhole)."),
    Q("True or False: Nya is completely alone at the pond.", "False — many other people from the area also collect water there.", "tf"),
    Q("What is the name of Salva's home village?", "Loun-Ariik."),
    Q("How does Salva find people connected to his village among the fleeing crowd?", "He hears someone calling out the name \"Loun-Ariik\" and follows the voice."),
    Q("Vocabulary: What does it mean that the villagers \"took shifts\" keeping watch?", "They took turns, so someone was always awake and alert through the night."),
    Q("Who makes up Nya's immediate family, as introduced in Chapter 4?", "Her mother, father, older brother Dep, younger sister Akeer, and a baby brother."),
    Q("What extra job is Nya given on the walk to the pond?", "Looking after (minding) her younger sister Akeer."),
    Q("True or False: Nya is always patient and never frustrated with Akeer.", "False — she feels annoyed that Akeer is small and slow, even though she doesn't say it aloud.", "tf"),
    Q("What two groups are the fleeing villagers separated into by the rebel soldiers?", "Men (including teenage boys) in one group; women, children and the elderly in the other."),
    Q("Why does Salva start to walk toward the men's group even though he is only eleven?", "Because he is from an important family and his father always told him to act like a man / set an example."),
    Q("What stops a soldier from taking Salva into the men's group?", "The soldier lifts Salva's chin with his gun to look at his face and judges him to be too young."),
    Q("Vocabulary: What does \"conscript\" or \"recruit\" mean, in the context of child soldiers?", "To force or persuade someone (often a child, in this context) to join and fight in an army."),
    Q("Why might the author show us Salva's fate being decided in a single, tense physical moment (the gun under his chin)?", "Open-ended — shows how little control a child has, and how arbitrary and terrifying that moment of judgement is."),
    Q("How does the group of adults around Salva change once the men's group leaves?", "It becomes smaller and, apart from an infant, Salva is the only child left in it."),
    Q("What does the pond scene suggest about how many families share the same water problem as Nya's?", "Open — many families in the area rely on the same limited, unsafe source."),
    Q("Predict: Now that Salva is separated even from the other men of his village group, what do you think his journey will depend on?", "Open-ended, text-supported prediction (accept: luck, other adults, his own resilience)."),
    Q("Why might Linda Sue Park choose to show a child's safety decided by an adult stranger's snap judgement?", "Open-ended — highlights how powerless children are in war, and how much depends on chance."),
    Q("What is one similarity between Nya's daily responsibility (minding Akeer) and Salva's situation (being watched over by strangers from his village)?", "Open — both involve care and responsibility for others even amid hardship, and neither child chose their situation."),
    Q("Whole-section check: Name one danger Nya faces and one danger Salva faces this week, and explain how they are different in scale.", "Open — accept e.g. Nya: unsafe water/exhaustion (ongoing, everyday danger); Salva: being conscripted or killed (immediate, life-threatening danger)."),
    Q("What do you think 'home' means differently to Salva now compared to at the start of Chapter 1?", "Open-ended, personal/text-supported response — accept that home now feels lost, uncertain or far away."),
  ],
},
{
  num: 3, title: "The Land of the Lion", chapters: "Chapters 5–6",
  LI: "We are learning to notice how setting and atmosphere are used to build fear and tension across a journey.",
  SC: "I can find specific details the author uses to make a setting feel dangerous, and explain the effect on the reader.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 5 (Nya, 2008)", "Nya's family and community are shown coping with an earlier, worse dry season — memories of hunger before the rains came",
      "Have you ever experienced a shortage of something everyone needs (food, water, power)? What did people do to cope?",
      "What does this chapter reveal about times when the water and food situation was even worse for Nya's community?",
      "Why might the author include memories of hunger, rather than only showing the present-day walk to the pond?",
      "Write about how your own family or community copes when something essential runs short."),
    tue: D("Chapter 6 (Salva, 1985)", "Salva's group enters the territory of the Atuot, known as \"the people of the lion\", and nights become uneasy with the sound of roaring nearby",
      "What is the difference between a fear you can see (like a person) and a fear you can only hear, in the dark, getting closer?",
      "What do the Dinka believe about the Atuot and lions, according to the text?",
      "Why might constant, unseen danger (like distant roaring at night) be more frightening in some ways than a danger you can see clearly?",
      "Write a short paragraph describing a sound that once made you feel afraid, focusing on what you couldn't see."),
    wed: D("Chapter 6 continued (Salva, 1985)", "The group walks for days through lion country, seeing prey and bones along the path, always alert",
      "If you had to travel somewhere genuinely dangerous every single day, how do you think you would train yourself to manage that fear?",
      "What evidence along the path shows the group that they truly are in dangerous predator territory?",
      "Why does the author mention both a successful escape (the topi) and remains of prey that wasn't so lucky?",
      "Write about a routine danger or risk (real or in a video game/sport) where you've had to learn to stay alert without panicking."),
    thu: D("Chapter 5 continued (Nya, 2008)", "A closer look at how little control Nya's family has over the seasons, the rains, and whether there will be enough to go around",
      "What is the difference between a problem you can solve with effort and a problem you can only wait out?",
      "According to the text, what determines whether there is enough food and water for Nya's community — effort, or something else?",
      "Why might it be especially hard, psychologically, to face a hardship that no amount of hard work can fully fix?",
      "Write about something in your own life that depends on circumstances outside your control (weather, other people's decisions, luck)."),
  },
  projects: [
    P("poster", "People of the Lion", "Design a poster illustrating the Dinka legend about the Atuot and lions, and the real dangers Salva's group faces walking through their territory."),
    P("comic", "Sounds in the Dark", "Show, panel by panel, a night in lion country from Salva's point of view — using sound effects and shadow rather than showing a lion directly."),
    P("drama", "Waiting Out the Dry Season", "Act out a family conversation during a hard dry season, showing how Nya's community copes with a hardship they can't simply fix."),
    P("journal", "A Fear I Could Only Hear", "Write about a time an unseen or unclear danger felt scarier than something you could actually see."),
  ],
  quiz: [
    Q("What does Chapter 5 reveal about earlier, harder times for Nya's community?", "There have been periods of even worse hunger and hardship before good rains came."),
    Q("True or False: Nya's community can simply work harder to guarantee enough food and water.", "False — much depends on the rains and seasons, which are outside their control.", "tf"),
    Q("What group's territory does Salva's group enter in Chapter 6?", "The Atuot, called \"the people of the lion\" in the Dinka language."),
    Q("According to Dinka belief described in the text, what happens to an Atuot person when they die?", "They are believed to return to Earth as a lion."),
    Q("What sounds trouble Salva and the group at night in this territory?", "Roars in the distance, and sometimes the death-squeal of an animal caught by a lion."),
    Q("Vocabulary: What does \"prey\" mean, and how is it used in this chapter?", "An animal hunted and killed by another animal for food; used to describe animals lions hunt in this region."),
    Q("What evidence does Salva see along the path that shows the danger is real, not just a story?", "The bones of animals (prey) that were not fortunate enough to escape a lion."),
    Q("True or False: Salva's group sees a lion up close attack a person in this chapter.", "False — at this point they see and hear evidence of lions, but no direct attack on a person yet.", "tf"),
    Q("What animal does the group see escape from a lion in the distance?", "A topi (an antelope)."),
    Q("Why might the author choose to show both a successful escape and remains of an unsuccessful one?", "Open — shows real danger and real chance, building tension without resolving it either way."),
    Q("What does staying \"alert\" mean for Salva's group as they cross this territory?", "Being constantly watchful and cautious, ready to react to any sign of danger."),
    Q("Why might unseen, ongoing danger (like distant roaring at night) affect people differently than a danger they can see clearly?", "Open-ended — not knowing when or where danger will appear can create constant anxiety/hypervigilance."),
    Q("What is one similarity between Nya's family's powerlessness over the rains and Salva's group's vulnerability to lions?", "Open — both face serious threats to survival that are largely outside their control."),
    Q("Vocabulary: What does \"vulnerable\" mean, and who in these chapters could be described that way?", "Easily harmed or at risk; both Nya's community (facing drought) and Salva's group (facing predators) are vulnerable."),
    Q("Why do you think the author places these two \"waiting and enduring\" chapters next to each other in the book's structure?", "Open-ended — reinforces the shared theme of enduring danger/hardship you cannot directly control."),
    Q("Predict: Given how tense this section already feels, what do you expect might happen if the group is truly unlucky in lion territory?", "Open-ended, text-supported prediction."),
    Q("What does the phrase \"the people of the lion\" suggest about how the Dinka understand their relationship with a dangerous animal?", "Open — a mix of fear and respect; the lion is woven into their belief system, not just seen as a threat."),
    Q("How does walking in a group, rather than alone, seem to help Salva and the others in dangerous territory?", "Open — shared watch-keeping, shared knowledge, and support reduce (but don't remove) the danger."),
    Q("What is one detail from this week that made the setting feel real and dangerous to you personally?", "Open-ended, personal response."),
    Q("Whole-section check: Explain, in your own words, why 'enduring' is a good word to describe both Nya's and Salva's experiences this week.", "Open — both must keep going through hardship they cannot quickly solve or escape, day after day."),
  ],
},
{
  num: 4, title: "Uncle Jewiir, and a Night That Changes Everything", chapters: "Chapters 7–8",
  LI: "We are learning to explain how a relationship can change a character's chances of survival.",
  SC: "I can describe how Uncle Jewiir changes Salva's situation, and explain the impact of loss within a group that is trying to survive together.",
  rubricTags: ["R3","R7","R10"],
  days: {
    mon: D("Chapter 7 (Salva, 1985)", "Salva's father's younger brother, Uncle Jewiir — a soldier — recognises him among the refugees and takes him under his protection",
      "What would it feel like to suddenly recognise a familiar face among a crowd of total strangers, after being alone and afraid for days?",
      "How does Uncle Jewiir come to be travelling with the same group as Salva, and what is his relationship to Salva's father?",
      "Why might having one trusted adult make such a big difference to Salva's chances, even though the danger around him hasn't changed?",
      "Write about a person in your own life whose presence alone makes a hard situation feel more manageable, and why."),
    tue: D("Chapter 8 (Nya, 2008)", "Nya's five-year-old sister Akeer becomes seriously ill, and the family faces an agonising decision about the long walk to a medical clinic",
      "If someone you loved was seriously unwell and the only help was a difficult, multi-day walk away, how would your family decide what to do?",
      "What symptoms does Akeer show that worry Nya and her family, and how does this differ from her usual behaviour?",
      "Why is the decision about whether to walk to the clinic described as so difficult, even though Akeer clearly needs help?",
      "Write about a hard decision your family has had to make where every option carried some kind of risk."),
    wed: D("Chapter 7 continued (Salva, 1985)", "Under Uncle Jewiir's care, Salva learns a survival mindset — to focus only on getting through today, not the whole impossible journey",
      "Have you ever faced something that felt impossible until you broke it down into just the very next small step?",
      "What advice or mindset does Uncle Jewiir give Salva about the journey ahead?",
      "Why might thinking only about \"today\" be a more effective survival strategy than thinking about the entire remaining journey?",
      "Write about a big challenge in your own life, and how you might apply Uncle Jewiir's \"just today\" thinking to it."),
    thu: D("Chapter 8 continued (Salva, 1985)", "In the night, a lion attacks the sleeping group and kills a boy named Marial — a devastating loss that shakes Salva deeply",
      "How do you think a group would react, individually and together, after losing one of their own so suddenly and violently?",
      "What happens to Marial, and how does Salva find out?",
      "Why does the text emphasise that no one heard screaming, and that Salva hopes Marial felt no pain?",
      "Write a short tribute or goodbye message Salva might privately say for Marial, even though there's no time to properly grieve."),
  },
  projects: [
    P("poster", "Just Today", "Design a poster illustrating Uncle Jewiir's \"just today\" survival philosophy, using an image that represents breaking an impossible task into one small step."),
    P("comic", "Reunited in the Crowd", "Show, panel by panel, the moment Uncle Jewiir recognises Salva among the refugees and the relief/protection that follows."),
    P("drama", "The Hardest Decision", "Act out Nya's family discussing what to do about Akeer's illness, showing the different worries each family member might raise."),
    P("journal", "A Loss That Changes You", "Write about how you imagine Salva feels the morning after Marial's death, using evidence from the text about grief, guilt, or fear."),
  ],
  quiz: [
    Q("Who is Uncle Jewiir, and how is he related to Salva?", "He is Salva's father's younger brother (Salva's uncle)."),
    Q("What had Uncle Jewiir been doing before he found Salva in the fleeing crowd?", "Serving in the army."),
    Q("True or False: Salva had seen Uncle Jewiir very recently before this reunion.", "False — he hadn't seen him in at least two years.", "tf"),
    Q("What is Akeer's illness, and how does Nya notice something is seriously wrong?", "She becomes very sick and unusually silent/still, no longer complaining as she normally would — a sign her condition is serious."),
    Q("Who tells Nya's family about a medical clinic that could help Akeer?", "Nya's uncle, the chief of their village."),
    Q("Vocabulary: What does it mean that a decision is \"agonising\"?", "Extremely difficult and painful to make, often because every option carries a real cost or risk."),
    Q("What survival mindset does Uncle Jewiir teach Salva?", "To focus only on getting through the present day (\"just today\"), rather than thinking about the whole journey ahead."),
    Q("True or False: Uncle Jewiir tells Salva to think constantly about how far they still have to go.", "False — he encourages Salva to focus only on the present day/step.", "tf"),
    Q("What happens to a boy named Marial during the night?", "He is killed by a lion while the group is sleeping."),
    Q("Why does no one hear Marial scream during the attack?", "It's implied he may have been killed quickly/instantly, or the sound was lost in the night; the text leaves this deliberately uncertain."),
    Q("Vocabulary: What does it mean to say Salva \"clung\" to his uncle after this?", "He held on tightly, both physically and emotionally, relying on him for safety and comfort."),
    Q("Why might the author choose to have Salva reunite with a caring adult (Uncle Jewiir) right before the group suffers a devastating loss (Marial)?", "Open-ended — creates emotional contrast; shows both the comfort of connection and the fragility of safety, even with an adult present."),
    Q("What does the walk to the clinic requiring \"a few days\" suggest about healthcare access in Nya's region?", "Open — healthcare is far away and difficult to reach, unlike in places with nearby hospitals or clinics."),
    Q("How does Uncle Jewiir's promise to protect Salva (\"I have a gun, I will shoot any lion that comes near\") affect Salva emotionally, even though it couldn't save Marial?", "Open — likely offers some comfort/reassurance, even though it highlights the limits of any one person's ability to guarantee safety."),
    Q("What is one similarity between the risk Nya's family faces (walking to a clinic with a very sick child) and the risk Salva's group faces (walking through lion territory)?", "Open — both involve dangerous, exhausting journeys undertaken because there is no safer alternative."),
    Q("Predict: How do you think Marial's death will affect the way the group behaves for the rest of their journey?", "Open-ended, text-supported prediction (accept: increased caution, fear, closer watches)."),
    Q("Why might \"just today\" thinking be useful advice beyond just physical survival journeys?", "Open-ended — applicable to any overwhelming challenge, by breaking it into manageable pieces."),
    Q("What does the family's decision-making around Akeer reveal about the values of Nya's community?", "Open — accept references to care for family, willingness to take real risks/effort for a loved one's health."),
    Q("In your own words, why is losing someone within a small, tightly bonded survival group especially devastating?", "Open-ended — every member matters more when the group is small and depends on mutual support/trust."),
    Q("Whole-section check: Identify one moment of connection/support and one moment of loss from this week's reading, for either character.", "Open — accept e.g. Salva: Uncle Jewiir's reunion (connection) and Marial's death (loss); or Nya: family support in the decision (connection) and Akeer's illness (loss/threat)."),
  ],
},
{
  num: 5, title: "A Feast, Then the Desert", chapters: "Chapters 9–10",
  LI: "We are learning to explain how brief moments of relief make ongoing hardship even more noticeable by contrast.",
  SC: "I can identify a moment of relief in the text and explain how it changes the reader's sense of how hard the surrounding hardship really is.",
  rubricTags: ["R1","R2","R8"],
  days: {
    mon: D("Chapter 9 (Salva, 1985)", "The group reaches a fishing community beside a river, where food is abundant for the first time in weeks — cassava, sugar cane, fish and hippo meat",
      "If you'd been genuinely hungry for weeks, what do you imagine your first proper meal would feel like — physically and emotionally?",
      "What kinds of food does Salva see in the fishing community, and why does this community have so much more than his own village normally does?",
      "Why might the author dedicate a whole chapter to relief and abundance, right in the middle of such a dangerous journey?",
      "Write about the best meal you can remember, and why it felt so good at that particular moment in your life."),
    tue: D("Chapter 9 continued (Salva, 1985)", "That night, thick clouds of mosquitoes rise from the river reeds, turning the peaceful fishing village into a miserable ordeal",
      "Can you think of an example where something good (like living near water) also comes with a serious downside?",
      "What problem do the mosquitoes cause for Salva and the group, and how does the text describe their numbers?",
      "Why might the author follow a moment of relief (the food) so quickly with a moment of new discomfort (the mosquitoes)?",
      "Write about a time something that seemed like a treat or good news came with an unexpected downside."),
    wed: D("Chapter 10 (Nya, 2008)", "Life at Akeer's bedside in the medical tent — doctors, other sick and injured people, and small moments of hope as Akeer slowly improves",
      "What do you imagine it would be like to sit for days in a place full of other people who are sick or hurt, waiting for someone you love to get better?",
      "How does Akeer respond to the medicine over the days at the clinic, and what small moment shows she is recovering?",
      "Why might the nurse's warning to Nya's mother (about needing to prevent this happening again) matter just as much as Akeer getting better this time?",
      "Write about a time you or someone close to you slowly recovered from being unwell, and what small sign told you things were improving."),
    thu: D("Chapter 10 continued (Salva, 1985)", "The group faces the most difficult stretch yet: the Akobo Desert, where nothing green survives and Salva's shoes fall apart within minutes",
      "What do you think would be the hardest part of crossing a genuine desert on foot with almost no supplies?",
      "What happens to Salva's shoes almost immediately in the desert, and what must he do?",
      "Why does Uncle Jewiir tell Salva to focus only on reaching \"that group of bushes\" rather than the whole three-day crossing?",
      "Write about the toughest physical challenge you've faced, and what got you through the hardest moment of it."),
  },
  projects: [
    P("poster", "Feast and Famine", "Design a split poster contrasting the abundance of the fishing village with the harshness of the Akobo Desert that follows it."),
    P("comic", "Clouds of Mosquitoes", "Show, panel by panel, the fishing village's peaceful evening turning into a miserable mosquito ordeal."),
    P("drama", "At Akeer's Bedside", "Act out a scene at the medical clinic, showing Nya's family's mix of worry, hope, and relief as Akeer slowly recovers."),
    P("journal", "One Bush at a Time", "Write about a time you got through something overwhelming by focusing on just the very next small step, the way Salva does in the desert."),
  ],
  quiz: [
    Q("What foods does Salva see in abundance at the fishing community?", "Fish, hippo and crocodile meat, cassava, sugar cane, yams."),
    Q("Why does this fishing community have so much more food than Salva's home village normally does?", "It has a whole river to water crops and provide fish, unlike the dry semidesert region around Loun-Ariik."),
    Q("True or False: Salva had never been hungry before this journey.", "False, in the sense his family was relatively well-off, but the surrounding contrast is still notable — accept discussion; text emphasises his family was among the better-off but this abundance still surprises him.", "tf"),
    Q("What ruins the peaceful evening at the fishing village?", "Huge clouds of mosquitoes rising from the water and reeds."),
    Q("Vocabulary: What does it mean to describe mosquitoes as appearing in \"clouds\"?", "So many of them together that they look like a thick, moving mass, like a cloud."),
    Q("What happens to Akeer at the medical clinic over the following days?", "She responds well to medicine and slowly recovers her strength and even her laugh."),
    Q("What warning does the nurse give Nya's mother?", "That they need to find ways to prevent this kind of illness from happening again (linked to unsafe water)."),
    Q("Vocabulary: What might \"prevention\" mean in a health context, based on this chapter?", "Taking action in advance to stop a problem (like illness) from happening, rather than only treating it afterwards."),
    Q("What region does Salva's group enter that is far harsher than anywhere they've crossed so far?", "The Akobo Desert."),
    Q("What happens to Salva's shoes almost immediately in the desert?", "The rubber-tire-tread soles fall apart, forcing him to go barefoot."),
    Q("True or False: Uncle Jewiir tells Salva to think about the entire three-day desert crossing at once.", "False — he tells Salva to focus only on the next small landmark, like a nearby group of bushes.", "tf"),
    Q("Why might the author place the desert crossing directly after the fishing village's abundance?", "Open-ended — the contrast makes the desert's harshness feel even more extreme, and shows how quickly circumstances can change."),
    Q("What single plant is mentioned as one of the only things that can survive in the Akobo Desert?", "Tiny evergreen acacia bushes."),
    Q("How does Salva's \"just today\" mindset get put into practice literally in the desert?", "Open — he breaks the crossing down into reaching one small landmark (a group of bushes) at a time, rather than thinking about the whole desert."),
    Q("What is one similarity between the fishing village's mosquito problem and Nya's family's water problem?", "Open — both show how something essential (water, in different forms) can bring both benefit and serious harm/danger."),
    Q("Predict: Given how harsh the Akobo Desert already sounds, what further dangers do you expect Salva's group might face crossing it?", "Open-ended, text-supported prediction (accept: exhaustion, dehydration, more loss of life)."),
    Q("Why might a moment of hope (Akeer's recovery) matter so much to a reader at this point in the book?", "Open-ended — provides emotional relief and balance against the intensity of Salva's storyline."),
    Q("What does the size of Akeer's improvement (from silent and weak to laughing) suggest about how serious her illness really was?", "Open — a dramatic recovery implies the illness had been severe and dangerous."),
    Q("Vocabulary: What does \"abundance\" mean, and where do we see it clearly in this week's reading?", "A very large quantity of something; seen in the fishing village's food supply."),
    Q("Whole-section check: Identify one moment of relief and one moment of new hardship from each character's story this week.", "Open — accept e.g. Salva: fishing village food (relief) then mosquitoes/desert (hardship); Nya: Akeer's recovery (relief) balanced against the nurse's warning about future risk (hardship)."),
  ],
},
{
  num: 6, title: "Losing Uncle Jewiir", chapters: "Chapters 11–12",
  LI: "We are learning to explain how the death of a key character changes both the plot and a reader's emotional experience of a story.",
  SC: "I can describe how Uncle Jewiir's death happens and explain its impact on Salva's chances of survival and his state of mind.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 11 (Salva, 1985)", "Nearing the end of the desert crossing, Uncle Jewiir gently tells Salva that his home village was likely attacked and burned, and that his family's fate is unknown",
      "How do you imagine you would want difficult news broken to you, if it were about people you loved?",
      "What does Uncle Jewiir tell Salva about the fate of Loun-Ariik and his family?",
      "Why might Uncle Jewiir choose to tell Salva this news now, near the end of the desert, rather than earlier or later?",
      "Write about how you imagine Salva feels hearing this news, and what he might still choose to hope for despite it."),
    tue: D("Chapter 12 (Nya, 2008)", "Strangers arrive in a jeep asking questions about \"water\" and speak with the village chief, Nya's uncle — the very first hint of the well project to come",
      "What would you think if strangers suddenly arrived in your community asking unusual questions nobody could fully explain yet?",
      "Who arrives in the jeep, and what do they discuss with Nya's uncle?",
      "Why might the author choose to introduce this event through confusion and rumour, rather than explaining exactly what's happening straight away?",
      "Write a paragraph predicting who these strangers are and what \"something about water\" might mean for Nya's village."),
    wed: D("Chapter 11 continued (Salva, 1985)", "The group reaches the edge of Ethiopia and the Itang refugee camp is finally in sight after the desert crossing",
      "After an extremely difficult ordeal, what do you imagine the very first feelings would be on finally seeing safety ahead?",
      "What is Itang, and why does reaching it matter so much after the desert crossing?",
      "Why might relief at reaching a refugee camp still be mixed with sadness or uncertainty for Salva?",
      "Write two sentences describing relief, and two describing the sadness that might exist alongside it, for Salva at this moment."),
    thu: D("Chapter 12 continued (Salva, 1985)", "Just before reaching safety, Uncle Jewiir is murdered by Nuer men in a sudden, senseless act of violence, right in front of Salva",
      "How do you think it would affect someone to lose their protector in the very last stretch before reaching safety?",
      "What happens to Uncle Jewiir, and how does the text describe Salva's reaction?",
      "Why might the author choose to have this loss happen so close to safety, rather than earlier in the desert?",
      "Write about how Salva might use his uncle's own \"just today\" advice to survive even this loss."),
  },
  projects: [
    P("poster", "News From Home", "Design a poster (as if from Salva's imagination) of Loun-Ariik before and after the war reached it, based on Uncle Jewiir's report."),
    P("comic", "The Strangers in the Jeep", "Show, panel by panel, the arrival of the mysterious jeep in Nya's village and the villagers' confused reactions."),
    P("drama", "Losing Uncle Jewiir", "Act out the group's reaction to losing Uncle Jewiir, staying respectful and focusing on grief and resolve rather than graphic violence."),
    P("journal", "Just Today, Without Him", "Write a journal entry as Salva the morning after losing his uncle, using \"just today\" thinking to find a reason to keep walking."),
  ],
  quiz: [
    Q("What news does Uncle Jewiir share with Salva about Loun-Ariik?", "That the village was likely attacked and burned, and the fate of Salva's family is unknown."),
    Q("True or False: Uncle Jewiir tells Salva his family is definitely safe.", "False — he says the village was probably attacked and their fate is unknown.", "tf"),
    Q("Who arrives in a jeep in Nya's village, and what do they ask about?", "Two strangers/men who speak to the village chief (Nya's uncle) about \"something about water\"."),
    Q("Who leads the strangers to the village chief's home?", "Nya's older brother, Dep."),
    Q("What is Itang?", "A refugee camp in Ethiopia, near the border with Sudan."),
    Q("Vocabulary: What does \"refugee camp\" mean?", "A temporary settlement set up to shelter and support people who have been forced to flee their homes."),
    Q("What happens to Uncle Jewiir near the end of this section?", "He is murdered by Nuer men shortly before the group reaches safety."),
    Q("True or False: Salva is far away and does not witness his uncle's death.", "False — it happens right in front of him.", "tf"),
    Q("Vocabulary: What does it mean that Uncle Jewiir's death was \"senseless\"?", "It had no clear purpose or justification — it felt random and unnecessary."),
    Q("Why might the author choose to have Uncle Jewiir die so close to the safety of the refugee camp, rather than earlier in the desert?", "Open-ended — makes the loss feel even more tragic and unfair, right when hope was highest."),
    Q("How does the text suggest Salva finds the strength to keep going after losing both Marial and Uncle Jewiir?", "Open — he draws on the memory/strength of those he's lost, and the \"just today\" mindset Uncle Jewiir taught him."),
    Q("What effect does introducing the well-project strangers through rumour and confusion (rather than clear explanation) have on the reader?", "Open-ended — builds curiosity/mystery, mirrors how confusing and uncertain new information can feel to a community."),
    Q("What is one similarity between the uncertainty Salva feels about his family's fate and the uncertainty Nya's village feels about the strangers' visit?", "Open — both involve not knowing what significant news will mean for the future."),
    Q("Why might it matter to the story that the very first mention of \"water\" strangers happens in the same week Salva loses his last protector?", "Open-ended — sets up the structural echo/connection between the two timelines that pays off later in the book."),
    Q("Predict: How do you think Salva will cope, practically and emotionally, without Uncle Jewiir for the rest of his journey?", "Open-ended, text-supported prediction."),
    Q("What do you think the strangers in the jeep might be planning to do in Nya's village?", "Open-ended, text-supported prediction (accept: survey the land, plan a well)."),
    Q("Vocabulary: What does \"resolve\" mean, and how might Salva show resolve after this loss?", "Firm determination to do something despite difficulty; Salva shows resolve by continuing to walk toward Itang."),
    Q("Why is grief harder to process when someone is still in the middle of a dangerous, ongoing situation?", "Open-ended — there is little time or safety to properly process loss when survival still demands constant attention."),
    Q("What does Salva's arrival at Itang, despite everything, suggest about his character so far?", "Open — resilience, determination, ability to carry on despite repeated loss."),
    Q("Whole-section check: Explain, using evidence, why this week marks a turning point in Salva's journey.", "Open — accept reference to losing his last connection to family/protection (Uncle Jewiir) while also reaching a place of relative safety (Itang) — both loss and arrival at once."),
  ],
},
{
  num: 7, title: "Itang, and the Crossing of the Gilo", chapters: "Chapters 13–14",
  LI: "We are learning to explain how time passing in a story can be shown through change, not just told through dates.",
  SC: "I can identify how the text shows years passing at Itang refugee camp, and describe the danger of the Gilo River crossing using evidence.",
  rubricTags: ["R2","R3","R7"],
  days: {
    mon: D("Chapter 13 (Salva, 1985–91)", "Salva spends years living at the crowded Itang refugee camp, growing from a boy of eleven into a teenager, mostly among other boys and young men who fled alone",
      "What do you imagine it would be like to grow up for years in a temporary camp, waiting and not knowing what comes next?",
      "Who mostly makes up the population of Itang refugee camp, and why?",
      "Why might living for years without a stable home affect a person's sense of who they are or what the future holds?",
      "Write about how you imagine you would try to keep hope alive if you had to live for years in an uncertain, temporary situation."),
    tue: D("Chapter 14 (Nya, 2009)", "The drilling crew begins setting up equipment in Nya's village, and villagers — including Nya's mother — help by gathering rocks for the drilling site",
      "What would it feel like to physically help build something that could change your entire community's future?",
      "What task does Nya's mother do to help the drilling crew, and how is it physically demanding?",
      "Why might the author show ordinary villagers contributing physical labour, rather than the crew doing everything alone?",
      "Write about a time you contributed physical effort toward something bigger than yourself (a working bee, a clean-up, a sports team)."),
    wed: D("Chapter 13 continued (Salva, 1991)", "In 1991, renewed fighting forces the refugees at Itang to flee again, this time toward the dangerous Gilo River on the Ethiopia–Sudan border",
      "How do you think it would feel to finally have some stability, only to be forced to run again after years of relative safety?",
      "What forces the refugees to leave Itang after six years there?",
      "Why is the Gilo River described as especially dangerous, even before anyone starts crossing it?",
      "Write about a time you had to start over after finally settling into a stable routine."),
    thu: D("Chapter 13 continued (Salva, 1991)", "The terrifying crossing of the crocodile-infested, swollen Gilo River, under gunfire, in which Salva survives but many others do not",
      "What would be racing through your mind if you had to cross a dangerous river under gunfire, with no other option?",
      "What multiple dangers does Salva face at once during the river crossing?",
      "Why does the text say that being forced underwater by the current probably saved Salva's life?",
      "Write a short, present-tense paragraph capturing the chaos and fear of the river crossing, from inside Salva's mind."),
  },
  projects: [
    P("poster", "Years at Itang", "Design a poster/timeline showing how Salva changes physically and emotionally across roughly six years at Itang refugee camp."),
    P("comic", "Gathering Stone for the Well", "Show, panel by panel, Nya's mother and other villagers collecting and carrying rocks to the drilling site."),
    P("drama", "Crossing the Gilo", "Act out (safely and respectfully, without graphic violence) the tension and teamwork of a group trying to cross a dangerous river together."),
    P("journal", "Starting Over Again", "Write about how you imagine it feels to have to flee a place you'd finally started to call home, using evidence from Salva's experience at Itang."),
  ],
  quiz: [
    Q("Roughly how many years does Salva spend at Itang refugee camp?", "About six years (1985 to 1991)."),
    Q("Who makes up most of the population at Itang?", "Boys and young men who fled their villages alone when the war came."),
    Q("What task does Nya's mother do to help the drilling crew?", "She and other women collect rocks/stones, bundle them, and carry them on their heads to the drilling site."),
    Q("True or False: The drilling crew does all the physical labour themselves without any help from villagers.", "False — villagers, including Nya's mother, contribute physical labour like gathering rocks.", "tf"),
    Q("What forces the refugees to leave Itang in 1991?", "Renewed fighting/war in the region."),
    Q("What river must the fleeing refugees cross to reach safety?", "The Gilo River, on the Ethiopia–Sudan border."),
    Q("Vocabulary: What does it mean to describe a river as \"swollen\"?", "Larger and more powerful than usual, often due to heavy rain, making it more dangerous."),
    Q("What two separate dangers does Salva face at once during the river crossing?", "Being shot at by soldiers, and being attacked by crocodiles in the water."),
    Q("True or False: Being pushed underwater by the current definitely put Salva in more danger.", "False — the text says being forced underwater probably saved his life (helping him avoid bullets/crocodiles above).", "tf"),
    Q("Approximately how many people are said to have died crossing the river that day?", "At least a thousand people."),
    Q("Vocabulary: What does \"merciless\" mean, and what is described as merciless in this chapter?", "Showing no mercy or kindness; the river's current is described as merciless."),
    Q("Why might the author choose to show years of camp life through change (Salva growing older) rather than simply stating dates?", "Open-ended — makes the passage of time feel real and lived, not just a fact on a page."),
    Q("Why is it significant that ordinary villagers, not just the drilling crew, help build the well?", "Open — suggests the well is a shared community effort/investment, not something simply given to them."),
    Q("What effect does the river crossing scene's short, chaotic sentences have on the reader?", "Open-ended — mirrors the panic, speed and confusion of the moment."),
    Q("What is one similarity between the danger of the Gilo River crossing and the danger Salva faced in the desert crossing earlier in the book?", "Open — both are extreme, life-threatening ordeals with a clear physical goal (reaching the other side/safety) and significant loss of life."),
    Q("Predict: After surviving the Gilo River, what kind of place do you expect Salva will need to find next?", "Open-ended, text-supported prediction (accept: another refugee camp, e.g. in Kenya)."),
    Q("Why might Linda Sue Park choose to have the well-drilling begin in the very same week Salva's story reaches one of its most dangerous, deadly moments?", "Open-ended — reinforces the parallel structure and the theme that survival and hope for water are deeply connected."),
    Q("What does surviving the Gilo River crossing, after everything else Salva has already lost, suggest about his resilience?", "Open — extraordinary endurance and survival instinct built up over years of hardship."),
    Q("Vocabulary: What does \"resilience\" mean, and how does Salva demonstrate it across chapters 1–14?", "The ability to recover from and keep going through difficulty; shown through his repeated survival of loss, danger and displacement."),
    Q("Whole-section check: Explain how this week shows both destruction (the river crossing) and construction (the well beginning) happening at once.", "Open — accept discussion of the two timelines' contrasting movement, one toward devastating loss, one toward eventual hope."),
  ],
},
{
  num: 8, title: "Kakuma, Ifo, and Muddy Water", chapters: "Chapters 15–16",
  LI: "We are learning to compare hardship across different settings and identify what, if anything, actually improves a character's situation.",
  SC: "I can compare Salva's life at two different refugee camps and evaluate whether his situation is truly improving.",
  rubricTags: ["R1","R3","R9"],
  days: {
    mon: D("Chapter 15 (Salva, 1992–96)", "After crossing into Kenya, Salva lives for two harsh years at the barbed-wire-enclosed Kakuma refugee camp, then walks for months to reach Ifo camp instead",
      "If a place that was supposed to offer safety felt more like a prison, what do you think you would do about it?",
      "What is Kakuma like, according to the text, and why does Salva compare it to a prison?",
      "Why does Salva choose to leave Kakuma and walk for months to another camp, when leaving is risky in itself?",
      "Write about a time you chose a harder short-term option because you believed it would lead to something better long-term."),
    tue: D("Chapter 16 (Nya, 2009)", "The drilling crew hits trouble — the drill bag keeps leaking and the muddy first water sprays out brown, not clean — testing the village's patience and hope",
      "How do you think it would feel to be so close to a long-awaited solution, only to keep hitting technical setbacks?",
      "What problems does the drilling crew face, and how does Dep explain the muddy water to Nya?",
      "Why might the author choose to show the well NOT working perfectly straight away, rather than a simple, instant success?",
      "Write about a time something you were excited about took much longer or was much harder to achieve than you expected."),
    wed: D("Chapter 15 continued (Salva, 1996)", "A rumour, then confirmation, spreads through Ifo camp: thousands of young refugees — later called the \"Lost Boys\" — will be resettled in America",
      "How would you react to news that could completely change the direction of your life, if you weren't sure yet whether it applied to you?",
      "What is the rumour that spreads through the camp, and how many people are said to be involved?",
      "Why does Salva worry that \"America doesn't want anyone too old\", and what does that reveal about his hope and fear at once?",
      "Write about a time you waited anxiously to find out if you'd been chosen or selected for something important."),
    thu: D("Chapter 15 continued (Salva, 1996)", "Salva's name appears on the list — he has been chosen to go to America, specifically to a city called Rochester, New York",
      "What do you imagine it would feel like to see your own name on a list that would change the entire rest of your life?",
      "What does Salva learn from the notice posted at the camp's administration tent?",
      "Why might this news feel both wonderful and frightening for Salva at the very same time?",
      "Write a short letter Salva might write to his family (even though he can't send it) telling them the news that he's going to America."),
  },
  projects: [
    P("poster", "Two Camps, Compared", "Design a compare-and-contrast poster showing Kakuma and Ifo refugee camps, using evidence from the text about conditions in each."),
    P("comic", "Muddy Water, Real Hope", "Show, panel by panel, the drilling crew's setbacks and the villagers' mixed reactions to seeing muddy (not yet clean) water for the first time."),
    P("drama", "Reading the List", "Act out the tense, hopeful moment at Ifo camp when the list of names selected for resettlement in America is posted."),
    P("journal", "Chosen, and Afraid", "Write about a moment when good news also brought fear of the unknown, connecting it to how Salva might feel learning he is going to America."),
  ],
  quiz: [
    Q("What refugee camp does Salva live in for two years after crossing into Kenya?", "Kakuma."),
    Q("Why does Salva compare Kakuma to a prison?", "It is enclosed by tall barbed-wire fences, and you weren't allowed to leave unless leaving for good."),
    Q("Approximately how many people lived at Kakuma, according to the text?", "Around seventy thousand (some said eighty or ninety thousand)."),
    Q("What camp does Salva walk to next, and how long does the journey take?", "Ifo camp, in Kenya — a journey of months on foot."),
    Q("True or False: Conditions at Ifo turn out to be much better than at Kakuma.", "False — the text says things were no different than at Kakuma; everyone was hungry and under-resourced.", "tf"),
    Q("What problem does the drilling crew face at Nya's village well site?", "The drilling bag keeps leaking, and progress is difficult and slow."),
    Q("Why does the first water from the borehole come out brown and muddy?", "It's still mixed with old water from the pond; the crew needs to drill deeper to reach clean underground water."),
    Q("Vocabulary: What does \"foundation\" mean in the context of building the well?", "A base or supporting structure (here, gravel and cement) that the pump is built on top of."),
    Q("What rumour spreads through Ifo refugee camp?", "That about three thousand boys and young men will be chosen to go live in America."),
    Q("What worry does Salva have about being selected for America?", "That America might not want anyone \"too old\"."),
    Q("What historical group are these boys later known as?", "The \"Lost Boys\" (of Sudan)."),
    Q("How does Salva find out that he has been selected?", "His name appears on a list posted at the camp's administration tent."),
    Q("Vocabulary: What does \"resettlement\" mean?", "The process of moving people, often refugees, to live permanently in a new country or region."),
    Q("Which American city is Salva assigned to?", "Rochester, New York."),
    Q("Why might the author show the well's construction hitting real setbacks (leaks, muddy water) instead of an instant success?", "Open-ended — makes the eventual success feel more earned and realistic, mirroring how hard real progress actually is."),
    Q("What does Dep's explanation of the muddy water teach Nya (and the reader) about how wells actually work?", "Open — that reaching clean water requires drilling deep enough, and that visible progress (any water at all) doesn't mean the job is finished."),
    Q("Why might leaving a refugee camp on foot, even one as bad as Kakuma, still be a risky decision?", "Open — the journey itself is dangerous, and there's no guarantee the new camp will be better."),
    Q("What is one similarity between Salva waiting to see if his name is on \"the list\" and the village waiting to see if the well will produce clean water?", "Open — both involve anxious waiting for a life-changing outcome that is mostly out of their control."),
    Q("Predict: How do you think Salva's life in America might differ from everything he has experienced so far in the book?", "Open-ended, text-supported prediction."),
    Q("Whole-section check: Using evidence from both storylines, explain why this week is really about hope surviving repeated setbacks.", "Open — accept reference to both Salva's repeated camp hardships/selection hope and the well's technical setbacks/muddy water as evidence of hope tested but not lost."),
  ],
},
{
  num: 9, title: "Two Journeys Meet", chapters: "Chapters 17–18",
  LI: "We are learning to explain how an author brings two separate storylines together for a powerful, meaningful ending.",
  SC: "I can explain how Salva's and Nya's stories connect at the end of the book, and why that connection matters.",
  rubricTags: ["R1","R4","R10"],
  days: {
    mon: D("Chapter 17 (Salva, 1996)", "Salva's long journey to America — planes, a new family, and a completely unfamiliar world of paved roads and endless traffic",
      "What do you imagine would be the strangest, most overwhelming part of moving to a country completely different from your own, with no preparation?",
      "What details does Salva notice that feel most different or overwhelming about America?",
      "Why might something as ordinary as paved roads feel remarkable to Salva?",
      "Write about the most different place you've ever visited or moved to, and what surprised you most about it."),
    tue: D("Chapter 18 (Nya, 2009)", "The well is finally finished — gravel, pump and cement complete — and the whole village gathers to celebrate, including a sign naming the American school that funded it",
      "What do you think it would feel like to watch your whole community finally get access to something you'd been walking hours a day to survive without?",
      "What does the blue canvas sign say, and what does it reveal about how the well was funded?",
      "Why might the workers' leader make sure a photo is taken and sent back to the school that raised the money?",
      "Write a short thank-you message from Nya's village to the students of \"Elm Street School\" who helped fund their well."),
    wed: D("Chapter 17 continued (Salva, 1996–2007)", "Years later, Salva learns his father is alive but seriously ill; he travels back to Sudan, reunites with him, and learns two of his brothers died in the war — then decides to start a well-digging project of his own",
      "If you learned a family member you thought you'd lost was actually alive but very unwell, what would you want to do, whatever the cost or difficulty?",
      "What news does Salva receive about his father, and what does he learn has happened to his brothers Ariik and Kuol?",
      "What idea does Salva decide to pursue after reuniting with his father, and why does his father's illness (caused by contaminated water) make this especially meaningful?",
      "Write about how you imagine Salva feels turning his own suffering into a plan to help others, rather than just being grateful for his own survival."),
    thu: D("Chapter 18 continued — the ending", "At the well's celebration, Nya realises the crew's leader — the man who has helped bring clean water to her village — is Salva Dut himself, and the two storylines finally meet",
      "Why do you think an author might choose to end a book with two characters meeting, rather than showing them meet earlier?",
      "How does the book reveal that the well-drilling crew's leader is connected to Salva's storyline?",
      "Why does the well matter for more than just drinking water — what else changes for Nya's village once it's finished (school, marketplace, disputes resolved fairly)?",
      "Write your own final paragraph for the book, in either Salva's or Nya's voice, reflecting on what this moment means."),
  },
  projects: [
    P("poster", "From Loun-Ariik to Rochester to a Well", "Design a poster/map tracing Salva's entire journey — Loun-Ariik, Itang, the Gilo River, Kakuma, Ifo, Rochester, and back to Sudan to dig wells."),
    P("comic", "The Sign on the Well", "Show, panel by panel, the moment the blue \"In Honor of Elm Street School\" sign is unveiled and the village first uses the clean water."),
    P("drama", "Two Journeys Meet", "Act out the final scene where Nya realises who the well-drilling crew's leader really is, focusing on the emotional weight of the moment rather than dialogue accuracy."),
    P("journal", "What the Well Really Built", "Write about everything beyond water that the well brings to Nya's village (school, marketplace, fairer daily life for girls), and why that matters as much as the water itself."),
  ],
  quiz: [
    Q("What does Salva find most strange or overwhelming when he first arrives in America?", "Paved roads everywhere, fast traffic, and how different everything feels from Sudan."),
    Q("What is the name of Salva's new city in America?", "Rochester, New York."),
    Q("What does the blue canvas sign at the finished well say?", "\"In honor of Elm Street School\" — the American school that raised money for the well."),
    Q("True or False: The well is finished the very first time water sprays out of the borehole.", "False — more work (deeper drilling, pipes, gravel foundation, pump, cement) was needed after the first muddy water appeared.", "tf"),
    Q("What news does Salva eventually receive about his father?", "That he is alive, but seriously ill, in a clinic in southern Sudan."),
    Q("What caused Salva's father's illness?", "Years of drinking contaminated water, leaving him with guinea worms."),
    Q("What does Salva learn happened to his brothers Ariik and Kuol?", "Both died during the war; only his brother Ring survived."),
    Q("Vocabulary: What does it mean that Salva's father's illness was caused by \"contaminated\" water?", "Water that is polluted or unsafe, often carrying disease or parasites."),
    Q("What project does Salva decide to start after reuniting with his father?", "A well-digging project to bring clean water to villages in southern Sudan (Water for Sudan)."),
    Q("Why is it especially meaningful that Salva's own father was harmed by unsafe water?", "Open — it gives Salva a deeply personal reason to dedicate his life to solving exactly this problem for others."),
    Q("At the very end of the book, who does Nya realise the crew leader really is?", "Salva Dut — the boy from the 1985 storyline, now grown up."),
    Q("Name two things, besides water for drinking, that the finished well brings to Nya's village.", "A future school for the children, and eventually plans for a marketplace (accept either, or clinic plans mentioned)."),
    Q("Why might the author choose to reveal the connection between Salva and Nya only in the very final pages?", "Open-ended — creates a powerful, earned surprise and reward for readers who have followed both storylines closely."),
    Q("What does the phrase \"a long walk to water\" mean by the end of the book, now that you've read both storylines fully?", "Open — refers to both Nya's literal daily walk and Salva's much longer, more dangerous years-long walk to eventually bring water to others."),
    Q("Why does the author choose to have real villagers, like Nya's family, help build the well rather than just receiving it passively?", "Open — reinforces the value of shared effort/dignity, not just charity."),
    Q("How does Salva's project turn his personal loss and suffering into something positive for others?", "Open — his own history of hardship (thirst, loss, his father's illness) directly motivates and shapes his mission to help other communities."),
    Q("What is the significance of the well being named after an American school (Elm Street School) that raised the money?", "Open — shows how support and connection can come from people far away who never meet the community directly, until this moment."),
    Q("Predict/Reflect: What do you think happens to the relationship between Nya's village and Salva's organisation after this book ends?", "Open-ended, text-supported reflection (accept reference to the author's note describing ongoing wells being built)."),
    Q("Whole-section check: In your own words, explain how the ending shows that Salva's and Nya's \"separate\" stories were never really separate at all.", "Open — accept discussion of shared themes (walking, water, survival) and the literal, direct connection revealed at the well."),
    Q("What is the biggest single idea you will take away from A Long Walk to Water?", "Open-ended, personal response — accept any well-reasoned, text-supported answer (perseverance, hope, generosity, the value of water, etc.)."),
  ],
},
];

const WEEK10 = {
  options: [
    { title: "A Clean Water Campaign", desc: "Design and run a real awareness campaign for a clean-water cause — posters, a short speech, and a call to action — inspired by Salva's real organisation, Water for Sudan." },
    { title: "An Extended Drama Scene", desc: "Write and perform an extended scene either continuing Nya's story after the well (her first day at the new school) or imagining Salva's first week in Rochester, told with empathy and historical accuracy." },
    { title: "A Character Case File", desc: "Create an in-depth profile — poster, written report and panels — tracking either Salva's or Nya's journey and change across the whole book, using evidence from every part of the story they appear in." },
    { title: "An Original Class Anthology: \"What I Carried\"", desc: "Build a class anthology inspired by the book's core theme of perseverance and generosity — each student contributes one page about something they've carried (literally or emotionally) through a hard time, illustrated with a real-life example." },
  ],
  lessons: [
    { day: "Monday", title: "Choose & Plan", desc: "Choose your project, plan or storyboard your ideas, gather any resources you need, and assign group roles if working with others." },
    { day: "Tuesday", title: "Main Production", desc: "The main production session — writing, drawing, building and rehearsing your project." },
    { day: "Wednesday", title: "Finish & Polish", desc: "Finishing touches, rehearsal and polish, and preparing to present your project to the class." },
  ],
  thursday: "Students present or display their final projects in a gallery walk. Peer feedback is given via \"Glow & Grow\" sticky notes — one thing that shone, one thing to consider next time.",
  friday: "No quiz this week. Whole-class reflection circle: share the one big idea you will carry forward from A Long Walk to Water. Certificates are presented, and students are welcome to share their favourite moments from the unit.",
  rubric: [
    { code: "R-U", criteria: "Understanding of text", na: "Retells basic plot.", wt: "Explains character motivations with some evidence.", a: "Analyses themes (perseverance, hope, generosity) with strong textual evidence.", example: "connects Salva's well-digging directly to his father's illness from contaminated water." },
    { code: "R-C", criteria: "Communication of ideas", na: "Ideas are unclear or underdeveloped.", wt: "Ideas are clear and organised.", a: "Ideas are compelling, well-structured, and audience-aware.", example: "a campaign speech that opens with a real statistic and closes with a clear call to action." },
    { code: "R-E", criteria: "Creativity & effort", na: "Minimal effort or detail.", wt: "Solid effort, clear care taken.", a: "Highly original, exceptional effort and polish.", example: "an anthology page that uses a genuinely personal object or memory, not a generic example." },
    { code: "R-T", criteria: "Collaboration (if group)", na: "Limited teamwork.", wt: "Works cooperatively.", a: "Leads and supports others effectively.", example: "makes sure every group member has a clear role and a speaking part in the presentation." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
