/* ============================================================
   THE BFG — BOOK CLUB APP DATA
   Content data only. No markup/behaviour lives in this file.
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Kindness, Courage & Friendship", desc: "Connects with the book's central value — kindness comes in every size." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 3 (Years 5–6).
   "Achieved" = the curriculum expectation has been met.
   curriculum: the achievement objective / competency being assessed
   expect:     what the student should be able to do (teacher language)
   kid:        the same thing as a student "I can" statement
   ask:        one quick question the teacher can ask themselves when marking
   na/wt/ach:  level descriptors
   exemplar:   what an Achieved response looks like (student sample)
   wtSample:   a Working Towards response, for contrast
   evidence:   where in the unit to find the evidence
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas of the story (kindness in every size, courage, friendship, the power of imagination) and supports them with events from the book, making links beyond the text to self or the world.",
    kid: "I can explain a big idea from the story and back it up with something that happened in the book.",
    ask: "Does the student explain WHY an event matters — not just WHAT happened?",
    na: "Retells some events but cannot yet explain what they mean. Answers are mostly ‘what happened’.",
    wt: "Names a big idea (e.g. ‘it’s about friendship’) with a general reason, but the link to the book is vague or missing.",
    ach: "Explains a big idea and supports it with a specific event from the book. Makes a link beyond the text (to self or the world).",
    wtSample: "The BFG is kind because he is a nice giant.",
    exemplar: "I think the biggest idea is that being small doesn’t stop you being kind or brave. The other giants are huge and cruel, but the BFG — the runt — refuses to hurt anyone and risks everything to help Sophie stop them. It reminds me of a Year 4 at our school who stood up for a kid who was being picked on, even though the bullies were bigger.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-away reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of how texts are shaped for different purposes and audiences, and how language features are used for effect.",
    expect: "Notices the choices Dahl makes — suspense built with short sentences and capitals, invented ‘gobblefunk’ words, exaggeration and humour, the narrator speaking to the reader — and explains how they affect the reader.",
    kid: "I can notice how the author wrote the book and explain how it makes the reader think or feel.",
    ask: "Does the student name a writer’s choice AND say what effect it has on the reader?",
    na: "Comments only on the plot; does not yet notice how the book is written.",
    wt: "Notices a feature (e.g. ‘he uses funny words’) but cannot explain its effect.",
    ach: "Names a writer’s choice and explains its effect on the reader, using an example from the book.",
    wtSample: "Dahl uses funny words like whizzpopper.",
    exemplar: "In Chapter 2 Dahl shows the giant a bit at a time — ‘something tall… something very tall and very black’ — and uses short sentences, so I felt my heart pounding just like Sophie’s. Later he gives the BFG silly invented words like ‘frobscottle’, which makes him seem friendly instead of scary.",
    evidence: "Language questions (esp. Weeks 1, 3, 4 and 7), inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, making connections, summarising — and links earlier chapters to later ones (cause and effect across the book).",
    kid: "I can use reading strategies and link what happened earlier in the book to what happens later.",
    ask: "Can the student connect an earlier event to a later one without being told?",
    na: "Relies on the teacher to explain the story; does not yet connect chapters.",
    wt: "Uses a strategy when prompted (e.g. predicts when asked) and makes simple links between chapters.",
    ach: "Independently uses strategies and explains how an earlier event causes or sets up a later one.",
    wtSample: "The BFG has big ears and later he uses them.",
    exemplar: "In Week 2 the BFG showed off his enormous ears that can hear the tiniest things. That’s why in Week 8 he could hear the Sultan of Baghdad on the Queen’s phone from way up on the piano — the ears were set up early so they’d matter later. I predicted it because he kept saying his ears hear ‘every single twiddly little thing’.",
    evidence: "Predictions, cause-and-effect questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics.",
    expect: "Writes and shares clear, developed ideas about the book — opinions, explanations and reflections — with supporting detail.",
    kid: "I can share a clear idea or opinion and give reasons to support it.",
    ask: "Is there a clear idea PLUS at least two reasons or details?",
    na: "Answers are one word or unclear; ideas are not explained.",
    wt: "Shares a clear idea but gives little detail or only one reason.",
    ach: "Communicates a clear opinion or idea and develops it with at least two reasons or pieces of evidence.",
    wtSample: "I think the Queen was right because she is nice.",
    exemplar: "I think the Queen was right to capture the giants alive. First, she said ‘two wrongs don’t make a right’, so she wouldn’t copy the giants’ cruelty. Second, the pit still stops them hurting anyone. Some people might say the giants deserved worse, but I think a fair punishment is better than revenge.",
    evidence: "Go-away reflections, journal projects, Week 8 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Use language features appropriately, showing a developing understanding of their effects; organise texts using a range of structures.",
    expect: "Chooses the right structure and language for the task — a dream label in the BFG’s voice, a persuasive poster, a comic, a diary, a script.",
    kid: "I can choose the right kind of writing and words for the job (like a diary, a poster or a dream label).",
    ask: "Does the writing look and sound like the form it’s meant to be?",
    na: "Writing does not match the task; little attempt at structure or language features.",
    wt: "Attempts the right form (e.g. writes a dream label) but the language or structure is inconsistent.",
    ach: "Uses a suitable structure and language features for the purpose and audience (e.g. capitals, first person and gobblefunk for a BFG dream label; formal language for the Queen).",
    wtSample: "This dream is about me riding an elephant and it was fun.",
    exemplar: "THIS DREAM IS ABOUT HOW I IS RIDING A WHIZZBANGING ELEFUNT ROUND THE SCHOOL FIELD AND THE WHOLE CLASS IS CHEERING. THEN THE ELEFUNT SNEEZES AND I IS FLYING UP TO THE MOON. THEN I IS HEARING MY MUM SAYING IT IS MONDAY.",
    evidence: "Poster, comic, drama & journal projects; Week 10 campaign / Dream Library" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback to improve it.",
    kid: "I can plan my work, improve it, and use feedback to make it better.",
    ask: "Can you see a plan AND a change made because of feedback?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wt: "Plans and drafts with support; makes small changes when prompted.",
    ach: "Independently plans, drafts and revises, and uses feedback (e.g. Glow & Grow) to improve the work.",
    wtSample: "I finished my comic. My teacher told me to add colour so I did.",
    exemplar: "My plan had three parts: the palace, the breakfast and the ending. My partner’s ‘grow’ said my ending was rushed, so I added two more panels showing the Queen laughing at the whizzpopper. Now the story has a proper finish.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas.",
    expect: "Listens to and builds on others’ ideas during group reading and projects, and takes turns fairly.",
    kid: "I can listen to my group, take turns, and build on other people’s ideas.",
    ask: "Does the student respond to what others say, not just wait for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt or opt out.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others’ ideas.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others’ ideas.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn’t add to their ideas.",
    exemplar: "(Observed) “I sort of disagree with Tama — I think the BFG was brave even though he was terrified, because he still tricked the Bloodbottler.” She then asked the quieter group members what they thought.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas.",
    expect: "Makes inferences — works out what characters feel and why — using clues from the text, and thinks creatively about possibilities.",
    kid: "I can use clues in the story to work out things the author doesn’t tell me.",
    ask: "Has the student worked something out AND pointed to the clue?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wt: "Makes an inference with prompting but struggles to explain the clue.",
    ach: "Independently infers feelings or motives and points to the clue in the text that shows it.",
    wtSample: "The BFG is lonely because he has no friends.",
    exemplar: "The book doesn’t say the BFG is lonely, but he calls himself the only nice giant in Giant Country and he cries a huge tear when Sophie tells him about the orphanage. That clue tells me nobody has ever understood him before, so he really needed a friend like Sophie.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility.",
    expect: "Contributes ideas in class discussions and projects, and takes responsibility for a role in group work.",
    kid: "I can share my ideas and do my part in group work.",
    ask: "Does the student offer ideas and take on a job without being asked?",
    na: "Rarely contributes to discussions or group projects.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ach: "Offers ideas without being asked, takes responsibility for a role, and encourages others.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 drama group, Aroha volunteered to be director, made a scene list, and made sure everyone had a part. She shared two ideas in the reflection circle without being asked.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Kindness, Courage & Friendship", strand: "Values",
    curriculum: "Values: diversity, community and participation, respect, and care for others and the environment.",
    expect: "Connects the book’s values — kindness across difference, courage even when you feel small, friendship and standing up for what is right — to their own life and actions.",
    kid: "I can connect the book’s message about kindness, courage and friendship to my own life.",
    ask: "Has the student linked a value from the book to something real in their own life?",
    na: "Cannot yet name the book’s values or connect them to themselves.",
    wt: "Names a value (e.g. ‘be kind’) when asked, with a simple or general link.",
    ach: "Explains a value from the book and connects it to a real experience or action of their own.",
    wtSample: "The book teaches us to be kind to everyone.",
    exemplar: "The BFG showed me you don’t have to be big to do something brave. When someone in our team was being left out and I felt too small to say anything, I remembered the BFG standing up to the Bloodbottler even though he was scared. So I asked them to let her join, and she did.",
    evidence: "Go-away reflections, journal entries, Week 10 ‘Kindness Comes in Every Size’ work, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 3–4 English, Years 5–6, NZ Curriculum",
  lrv: [
    "Ideas: Show understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show understanding of how texts are shaped for different purposes and audiences.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies confidently to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics.",
    "Structure and Language: Show understanding of language features, using them appropriately.",
    "Processes and Strategies: Select and use processes and strategies to communicate confidently.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Kindness across difference, courage in those who feel small, friendship and found family, imagination and the power of reading, and standing up for what is right without becoming cruel.",
  crossCurricular: "Mathematics — ratio and scale (Mr Tibbs multiplies everything by four for a 24-foot giant); Science — sound and hearing (the BFG’s ears), sleep and dreams; Health & PE — healthy eating (snozzcumbers vs a cooked breakfast), belonging and feeling different; Social Sciences — how people in different places and cultures are talked about, and why respectful language matters; The Arts — drama (reader’s theatre) and visual art.",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "The Witching Hour", chapters: "Chapters 1–5",
  LI: "We are learning to notice how an author builds suspense and fear through word choice, sentence length and detail.",
  SC: "I can find language choices (short sentences, capital letters, the senses, pauses) and explain how each one makes the reader feel tense.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapters 1–2", "The Witching Hour; Who? — Sophie at the window and the tall black figure",
      "Have you ever been awake when everyone else was asleep? What did the house sound and feel like?",
      "Why does Sophie get out of bed, and what does she see coming down the street?",
      "Dahl doesn’t describe the figure all at once — it is ‘something tall… something very tall and very black and very thin’. Why might he reveal it a little at a time? How does it make you feel as a reader?",
      "Write three short sentences about a silent, moonlit night. Use at least two senses — including what you can’t hear."),
    tue: D("Chapter 3", "The Snatch — a hand at the window",
      "What makes a scene scary in a story — the monster itself, or the waiting before it appears? Talk it over in your group.",
      "How does the Giant carry Sophie away, and how does she manage to see what is happening outside the blanket?",
      "The narrator suddenly speaks straight to the reader: ‘If you can think of anything more terrifying than that… let’s hear about it.’ Why might Dahl talk directly to us here? What effect does it have?",
      "Sophie thinks the Giant is running home because he is hungry. Write her thoughts in three sentences: what does she fear, and what does she still hope?"),
    wed: D("Chapter 4", "The Cave — a wild ride to Giant Country",
      "If you were carried somewhere unknown at top speed, what would you notice first when you finally stopped?",
      "Describe the journey to Giant Country and the landscape Sophie sees when the Giant slows down.",
      "Sophie imagines the Giant will eat her raw, boil her or fry her like bacon. What do these guesses show about how she feels? How does Dahl make the fear worse in the moments before the lights come on?",
      "Draw or describe the inside of the cave as if you were Sophie seeing it for the first time. Include at least three details from the text."),
    thu: D("Chapter 5", "The BFG — a giant who doesn’t eat people",
      "Have you ever been really scared of someone who turned out to be kind? What changed your mind?",
      "What does the Giant say about the other giants, and what does Sophie learn about him at the end of the chapter?",
      "The BFG mixes up words (‘human beans’, ‘cannybully’, ‘scrumdiddlyumptious’). Why might Dahl give him this way of speaking? How does it change how we feel about him compared with the figure at the window?",
      "The BFG makes a food joke about where people come from (people from Wellington taste of boots). Invent two puns of your own about places in New Zealand and explain the joke."),
  },
  projects: [
    P("poster", "Beware the Witching Hour!", "Design a warning poster for the orphanage dormitory listing the strange things Sophie noticed (the silence, the moonbeam, the black cloak, the trumpet). Use suspenseful language."),
    P("comic", "The Snatch", "6 panels showing the snatch from Sophie’s point of view: the window, the hand, the blanket, the run, the wind and the cave."),
    P("drama", "‘What Has Us Got Here?’", "Act out Sophie and the BFG’s first conversation in the cave. One voice booms in gobblefunk; the other is polite but terrified."),
    P("journal", "Sophie’s Diary: The Night I Was Snatched", "Write Sophie’s diary entry for the night she was taken. Use short sentences to build suspense, and finish on a cliffhanger."),
  ],
  quiz: [
    Q("What special time of night does Sophie realise it is when she looks out of the window?", "The witching hour — the middle of the night when everyone is fast asleep."),
    Q("Why can’t Sophie sleep at the start of the book?", "A bright moonbeam is shining through a gap in the curtains onto her pillow."),
    Q("True or False: Sophie sleeps in a bedroom on her own.", "False. She sleeps in a dormitory with the other children.", "tf"),
    Q("What does Sophie see coming up the street?", "Something very tall, very black and very thin — a giant figure in a black cloak."),
    Q("What is the Giant carrying?", "A large suitcase and a very long, thin trumpet."),
    Q("What does the Giant do at the Goocheys’ house?", "He pours something from a jar into the trumpet and blows it in through the children’s bedroom window."),
    Q("True or False: The Giant doesn’t notice Sophie watching him.", "False. He turns his head and stares straight at her.", "tf"),
    Q("Vocabulary: What is a ‘dormitory’?", "A large bedroom where many people sleep."),
    Q("How does the Giant take Sophie from her bed?", "A huge hand comes in through the window and lifts her out, blanket and all."),
    Q("True or False: Sophie manages to scream loudly for help.", "False. Her scream is smothered by the blanket.", "tf"),
    Q("How long is each of the Giant’s strides when he runs?", "As long as a tennis court."),
    Q("Describe two features of the landscape in Giant Country.", "Any two: flat, pale yellow ground; great lumps of blue rock; dead trees like skeletons; a dark blue craggy mountain."),
    Q("How does the Giant hide the entrance to his cave?", "He rolls a massive round stone, as big as a house, across it."),
    Q("What does Sophie see when the lights come on in the cave?", "Shelves lined with rows and rows of glass jars, and a table twelve feet high with a chair to match."),
    Q("Inference: Why is Sophie so sure she is going to be eaten?", "She thinks he ran so fast because he was hungry and wanted to get home; a giant who steals a child at night must be a man-eater."),
    Q("Author’s craft: Dahl uses short sentences and capital letters in Chapters 1–3 (e.g. ‘very tall and very black and very thin’). What effect does this have?", "Open-ended — it slows the moment down, builds suspense and makes the reader feel Sophie’s fear."),
    Q("What does the BFG say when Sophie begs ‘please don’t eat me’?", "He laughs. He says giants are man-gobbling, but he is not — he is the only nice giant."),
    Q("Which giant does the BFG say crunches up two people from Turkey every night?", "The Bonecrunching Giant (Bonecruncher)."),
    Q("According to the BFG, what do people from Wellington, New Zealand, taste of?", "Boots (wellington boots)."),
    Q("Predict: What might the BFG do with Sophie now, and what evidence from Chapter 5 supports your idea?", "Open-ended — accept any reasonable prediction backed by evidence (e.g. he says he is the ‘nice and jumbly’ giant, so he probably won’t hurt her)."),
  ],
},
{
  num: 2, title: "Giant Country", chapters: "Chapters 6–8",
  LI: "We are learning to work out what a character is like from what they say and do, and to compare two characters.",
  SC: "I can use a character’s words and actions as evidence for their personality, and compare the BFG with the other giants (or Sophie) using examples from the book.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapter 6", "The Giants — why Sophie was snatched, and the nine giants outside",
      "Is it ever okay to take someone away ‘for their own good’? How would you feel if it happened to you?",
      "Why does the BFG say he had to snatch Sophie, and what will happen if she goes home?",
      "The BFG is twenty-four feet tall, but in Giant Country he calls himself ‘the runt’. How does being smaller than the other giants shape the way he lives and feels?",
      "Sophie says, ‘Why doesn’t someone stop them?’ and the BFG asks, ‘Who is going to be stopping them?’ Write a thought bubble for Sophie that night."),
    tue: D("Chapter 7 (part 1)", "Sophie’s orphanage and the BFG’s tear · stop at ‘Now tell me what you were doing in our village.’",
      "Think of a time you felt sad because of someone else’s problem. What did you do?",
      "What does Sophie tell the BFG about her parents and about Mrs Clonkers’ punishments?",
      "The BFG cries a bucket-sized tear about the cellar — yet a minute earlier he said Sophie’s head was ‘full of squashed flies’. What does this contrast tell us about his character?",
      "The BFG dreams of riding an ‘elefunt’ through green forests. Write three sentences about a dream YOU have that seems too big, and what might make it come true."),
    wed: D("Chapter 7 (part 2)", "Dream-blowing and the marvellous ears · start at ‘If you is really wanting to know…’",
      "If you could hear one thing nobody else can hear, what would you want to listen to?",
      "What does the BFG do while the other giants are hunting, and how does he catch dreams?",
      "Sophie says she believes the BFG about plants screaming and trees moaning, even though it is hard to believe. What does this show about her, and why does trust matter between them?",
      "Choose one ordinary sound (a ladybird’s footsteps, ants chittering, a tree being chopped). Write two sentences describing how the BFG would hear it."),
    thu: D("Chapter 8", "Snozzcumbers — the only food in Giant Country",
      "What is the worst food you have ever tried? Describe it using the strongest words you can.",
      "What is the only thing that grows in Giant Country, and how does the BFG feel about eating it?",
      "Sophie keeps correcting the BFG’s words until he looks forlorn, then she says she loves how he talks. Why does she change, and why is this ‘the nicest present’ he has ever been given?",
      "Write about a time someone corrected you and it hurt, or a time someone said something kind that meant a lot."),
  },
  projects: [
    P("poster", "Field Guide to Giant Country", "Make a poster mapping Giant Country (the yellow wasteland, blue rocks, the cave) with a fact file for each giant we have met (name, size, where he hunts) and the BFG shown as ‘the odd one out’."),
    P("comic", "The Bucket Tear", "6 panels: Sophie tells the BFG about Mrs Clonkers and the cellar, and the BFG’s huge reaction."),
    P("drama", "Marvellous Ears", "Act out the BFG explaining what his ears can hear. One student is the BFG (use your hands as ears); the other is Sophie, slowly becoming a believer."),
    P("journal", "Sophie’s Diary: Day One in Giant Country", "Write Sophie’s diary. Include one piece of evidence that the BFG is kind and one piece that shows he is different from the other giants."),
  ],
  quiz: [
    Q("Why did the BFG snatch Sophie?", "Because she SAW him. Anyone who sees a giant must be taken away, or they would tell the world and start a giant hunt."),
    Q("True or False: According to the BFG, humans believe in giants.", "False. Humans don’t believe giants exist — Sophie only believes because she has seen him.", "tf"),
    Q("What does the BFG say humans would do to him if they caught him?", "Put him in a cage in a zoo."),
    Q("How many man-eating giants live in Giant Country (not counting the BFG)?", "Nine."),
    Q("How tall is the BFG?", "Twenty-four feet."),
    Q("How tall are the other giants at least?", "Fifty feet."),
    Q("True or False: The BFG is the biggest giant in Giant Country.", "False. He is the runt, less than half the size of the others.", "tf"),
    Q("What do the other giants do all day while waiting for night?", "They mooch and footchel about doing nothing until night comes, then gallop off to hunt."),
    Q("What does Sophie tell the BFG about the orphanage?", "She hated it. There were ten girls, and Mrs Clonkers ran it strictly and punished them."),
    Q("How were the orphans punished?", "Locked in the dark cellar for a day and a night with no food or drink, with rats creeping about."),
    Q("True or False: Sophie’s parents died when she was a baby.", "True.", "tf"),
    Q("How does the BFG react when he hears about the cellar?", "He cries a tear big enough to fill a bucket and calls Mrs Clonkers rude names."),
    Q("What does the BFG most want to have?", "An ‘elefunt’ (elephant) to ride through green forests picking peachy fruits."),
    Q("What does the BFG do at night while the other giants go hunting?", "He travels to other places to blow dreams into sleeping children’s bedrooms."),
    Q("What does the BFG use to catch dreams?", "A thirty-foot pole with a net on the end."),
    Q("Name two sounds the BFG says he can hear that humans can’t.", "Any two: a ladybird’s footsteps, ants chittering, music from the stars, plants screaming, trees moaning, mice talking, spiders singing."),
    Q("Inference: Why does the BFG stop talking when Sophie seems not to believe him?", "He is proud and sensitive; he doesn’t want to be called a ‘fibster’. It shows how much he wants to be believed."),
    Q("What is the only vegetable that grows in Giant Country?", "The snozzcumber."),
    Q("What does Sophie say that makes the BFG so happy?", "That she thinks he speaks beautifully — he calls it the nicest present anyone has ever given him."),
    Q("Big picture: Compare the BFG with the other giants using two pieces of evidence.", "Open-ended — e.g. the others eat people, the BFG refuses; the others are huge and cruel, the BFG is small and gentle, cries about the orphanage, blows happy dreams."),
  ],
},
{
  num: 3, title: "A Close Call", chapters: "Chapters 9–11",
  LI: "We are learning to explain how an author uses humour and exaggeration alongside danger to keep readers hooked.",
  SC: "I can point out funny and scary moments in the text and explain how the author blends them (through word play, silly names and over-the-top description).",
  rubricTags: ["R2","R7","R9"],
  days: {
    mon: D("Chapter 9 (part 1)", "The Bloodbottler arrives · stop at ‘She crawled into it.’",
      "When something scary is about to happen, do you ever laugh? Why do people do that?",
      "Who arrives at the cave, and what does he suspect? What does Sophie do to hide?",
      "The Bloodbottler shouts insults like ‘runty little scumscrewer’ and ‘prunty little pogswizzler’. Why might Dahl make a dangerous villain’s insults sound silly?",
      "Invent three silly insults in the giants’ style, using made-up words only (no real hurtful words). Explain what each one ‘means’."),
    tue: D("Chapter 9 (part 2)", "Sophie in the snozzcumber · start at ‘The Bloodbottler and the BFG were coming back towards the table now.’",
      "What is the bravest or cleverest thing you have ever done under pressure?",
      "How does the BFG trick the Bloodbottler into tasting the snozzcumber, and what happens to Sophie?",
      "The BFG is ‘nearly fainting with fear’ but still talks the Bloodbottler into taking a bite. What does this show about his courage? Can you be brave and scared at the same time?",
      "Write a five-sentence news report, ‘GIANT SPITS OUT VEGETABLE!’, from the Bloodbottler’s point of view. Include one exaggeration."),
    wed: D("Chapter 10", "Frobscottle and Whizzpoppers",
      "Imagine a fizzy drink where the bubbles go DOWN. What would be good and bad about that?",
      "Why does the BFG think bubbles going upwards is a ‘catasterous disastrophe’, and what does frobscottle taste like?",
      "The BFG and Sophie disagree about whether whizzpopping is rude. How does Dahl use this to make readers laugh, and what does it show about how different groups have different rules about manners?",
      "Design a frobscottle label: a name, a flavour, a warning and a slogan, all in gobblefunk-style words."),
    thu: D("Chapter 11 (part 1)", "Past the giants, in the BFG’s pocket · stop at ‘Grobby little grub!’",
      "Have you ever seen someone being picked on for being smaller or different? What did you do — or what would you do?",
      "What do the giants do to the BFG when he tries to walk past, and how does Sophie stay hidden?",
      "The giants call him names like ‘runt’ and ‘squib’ and toss him around like a ball. Why do you think they treat him this way? How does it change how we feel about the BFG?",
      "Write a message of encouragement that Sophie could whisper to the BFG from his pocket, using at least two things you admire about him."),
  },
  projects: [
    P("poster", "Frobscottle: The Fizzy Drink That Goes Down!", "Design an advertisement for frobscottle (or a warning label for snozzcumbers). Use persuasive language and at least three invented words."),
    P("comic", "Inside the Snozzcumber", "6 panels showing Sophie’s adventure from hiding inside the snozzcumber to being spat across the cave."),
    P("drama", "The Bloodbottler Visits", "Act out the Bloodbottler scene. Use your voice: one student booms as the Bloodbottler, the other tries to sound calm as the BFG while secretly terrified."),
    P("journal", "Sophie’s Diary: I Was Inside a Giant’s Mouth", "Write Sophie’s diary entry using humour and suspense together."),
  ],
  quiz: [
    Q("Who bursts into the BFG’s cave in Chapter 9?", "The Bloodbottler."),
    Q("How big is the Bloodbottler compared with the BFG?", "About fifty feet tall — more than twice as tall and wide as the BFG."),
    Q("True or False: The Bloodbottler believes the BFG when he says he was only talking to himself.", "False. He guesses the BFG has a human bean hidden in the cave.", "tf"),
    Q("Where does Sophie hide?", "Inside the hollowed-out end of the half-eaten snozzcumber (she scooped out the seeds)."),
    Q("Why does the BFG encourage the Bloodbottler to try the snozzcumber?", "He hopes the disgusting taste will send the Bloodbottler bellowing out of the cave."),
    Q("What happens when the Bloodbottler bites the snozzcumber?", "He yells, spits it all out, and Sophie shoots across the cave."),
    Q("Where does Sophie land?", "In the soft folds of the BFG’s black cloak hanging on the wall."),
    Q("True or False: The Bloodbottler discovers Sophie.", "False.", "tf"),
    Q("Where does the Bloodbottler say he will go that night, and why?", "Chile, because he wants a cold ‘chilly’ meal — though he says he might go to England with the others."),
    Q("What does the BFG say he would like to do about the other giants?", "Find a way of ‘disappearing’ every one of them — and Sophie promises to think of one."),
    Q("What do giants drink instead of water?", "Frobscottle."),
    Q("What is unusual about frobscottle’s bubbles?", "They go downwards instead of up."),
    Q("What is a ‘whizzpopper’?", "A loud rude noise (wind) caused by the bubbles going down, which the giants think is happy music."),
    Q("What flavours does Sophie taste in frobscottle?", "Vanilla and cream with a faint hint of raspberries."),
    Q("What happens to the BFG when he whizzpops after drinking frobscottle?", "The force lifts him right off the ground like a rocket."),
    Q("Vocabulary: What does ‘exaggeration’ mean?", "Making something seem bigger, better or worse than it really is."),
    Q("Where does Sophie ride when the BFG goes dream-catching in the daytime?", "In the pocket of his leather waistcoat, watching through a small hole."),
    Q("Which giant grabs the BFG by the hair?", "The Fleshlumpeater (Fleshlumpeating Giant)."),
    Q("What game do the giants play with the BFG?", "They throw him from giant to giant like a ball (‘Catch him, Manhugger!’), then kick him and throw rocks."),
    Q("Inference: Why do you think Dahl makes the giants’ bullying scene both funny and frightening?", "Open-ended — the silly names keep it playful, but the danger is real, which keeps readers hooked and makes us feel for the BFG."),
  ],
},
{
  num: 4, title: "Dream Country", chapters: "Chapters 11–14",
  LI: "We are learning to work out what invented words mean using context clues and word parts, and to explain why an author invents language.",
  SC: "I can use clues in the sentence and parts of a word (sounds, beginnings, endings) to work out what a ‘gobblefunk’ word means, and explain how invented words change the story.",
  rubricTags: ["R2","R5","R8"],
  days: {
    mon: D("Chapter 11 (part 2)", "How giants hunt, and who kills their own kind · start at ‘At last the BFG got clear of them all.’ · stop after ‘Is you quite cosy down there in my pocket?’",
      "Every group makes rules that suit itself. Can you think of a rule at school or home that might seem unfair from another point of view?",
      "What tricks does the BFG say some giants use to catch people (the Meatdripper and the Gizzardgulper)?",
      "The BFG says human beans are the only animals that kill their own kind, and Sophie falls silent. Why? What is Dahl asking readers to think about?",
      "Write two sentences from Sophie’s point of view after the BFG says ‘One right is not making two lefts.’ What do you think he means?"),
    tue: D("Chapters 11 (end) – 12", "Arrival in Dream Country, and Dream-Catching · start at ‘Then suddenly, once again, the BFG went into that magical top gear.’",
      "Have you ever woken from a dream that felt so real you were surprised it wasn’t? What was it about?",
      "What does Dream Country look and feel like when they arrive, and how does the BFG catch dreams?",
      "The BFG cries ‘Oh mince my maggots! Oh swipe my swoggles!’ when he catches a trogglehumper. Using the context, what do you think a ‘trogglehumper’ is? Which clues in the text helped you?",
      "Invent a new kind of dream (a ‘wobblestorm’? a ‘snuggleflump’?). Write its name, say whether it’s good or bad, and write a clue sentence that lets a reader work out what it means."),
    wed: D("Chapter 13", "A Trogglehumper for the Fleshlumpeater",
      "Have you ever had a great idea suddenly, like a light coming on? What was it?",
      "What idea does the BFG have when he sees the giants sleeping, and how does he put the trogglehumper into the Fleshlumpeater?",
      "The Fleshlumpeater screams about ‘Jack’ and his ‘spikesticking beanstalk’. Which well-known story is Dahl referring to? Why is it funny that giants fear Jack, and why does the author link to a story the reader already knows?",
      "Explain ‘spikesticking’, ‘wack-crackling’ and ‘splash-plunking’ in your own words. Which invented word do you like best, and why?"),
    thu: D("Chapter 14 (part 1)", "Dreams — the BFG’s labels · stop after ‘…it is always fighting to get out.’",
      "If you could have any dream tonight, what would it be about?",
      "How does the BFG label each dream, and how can he tell what a dream will be about just by listening to it?",
      "The BFG’s labels have misspellings like ‘teecher’, and he gets upset when Sophie asks ‘The kiss of what?’ What does this show about how he feels about never having been to school? How does Sophie handle it?",
      "Write your own dream label in the BFG’s style: ‘THIS DREAM IS ABOUT HOW I IS…’ (misspellings and gobblefunk allowed!)."),
  },
  projects: [
    P("poster", "The Gobblefunk Glossary", "Make a poster dictionary of ten gobblefunk words from Chapters 5–14. Give each a definition, a picture clue and the context clue in the story that helped you work it out."),
    P("comic", "A Trogglehumper Strikes", "6 panels from the sleeping giants to the almighty brawl, showing the nightmare spreading from giant to giant."),
    P("drama", "Dream-Catching", "Mime catching a golden phizzwizard, then a trogglehumper: use body, voice and pace to show the difference. Include ‘Ajar! Ajar! Quick quick quick!’"),
    P("journal", "The Dream Label", "Write the label for a dream jar of your own (5–8 sentences) including at least one invented word that is explained by the sentence around it."),
  ],
  quiz: [
    Q("According to the BFG, how do some giants catch children on the beach?", "They swim in from the sea with only their heads showing, then a big hairy hand grabs someone from the sand."),
    Q("How does the Meatdripping Giant catch his victims?", "He pretends to be a tree in a park, holding his arms up like branches, and waits for picnickers."),
    Q("True or False: Giants kill and eat other giants.", "False. Giants fight but never kill or eat each other.", "tf"),
    Q("What does the BFG say is unusual about human beans compared with other animals?", "They are the only animals that kill their own kind."),
    Q("True or False: Sophie easily argues back that humans are better than giants.", "False. She goes quiet and begins to wonder whether humans are any better.", "tf"),
    Q("What does the BFG mean by ‘One right is not making two lefts’?", "He is twisting ‘two wrongs don’t make a right’ — being cruel back isn’t the answer."),
    Q("Describe Dream Country when they arrive.", "Pale, misty and cold; everything grey and white; ashy-grey grass; swirling mists and no sound."),
    Q("What does the BFG bring for dream-catching?", "A suitcase of empty glass jars and a long net."),
    Q("True or False: Sophie and the BFG can see dreams floating in the air.", "False. Dreams are invisible until they are caught.", "tf"),
    Q("What is the first dream the BFG catches?", "A golden phizzwizard — a very good dream."),
    Q("What is the second dream, and how does the BFG react?", "A trogglehumper (a nightmare). He is furious and upset and refuses to let it go."),
    Q("What colour is the trogglehumper inside its jar?", "A faint scarlet (red)."),
    Q("Why does the BFG stop dream-catching for the day?", "He is too upset by catching the nightmare."),
    Q("What are the nine giants doing when the BFG and Sophie get back?", "Sprawled on the ground, fast asleep and snoring."),
    Q("What does the BFG do with the trogglehumper?", "He blows it through his trumpet into the Fleshlumpeater’s face while he sleeps."),
    Q("Who does the Fleshlumpeater dream is attacking him?", "Jack, the famous giant-killer, with his ‘spikesticking beanstalk’."),
    Q("What happens when the Fleshlumpeater thrashes in his sleep?", "He hits and kicks the other giants, they wake up and all nine fight each other."),
    Q("Why does the BFG smile at the brawl?", "He is pleased to see the bullies who tormented him fighting each other."),
    Q("How does the BFG label his dreams, and why?", "He writes a label on each jar so he can find the one he wants quickly."),
    Q("Word detective: Choose one gobblefunk word from the last few chapters. What does it mean, and which context clue helped you work it out?", "Open-ended — accept any reasoned meaning supported by a clue in the sentence."),
  ],
},
{
  num: 5, title: "Dreams and Words", chapters: "Chapters 14–15",
  LI: "We are learning to identify a theme in a text and support it with evidence from more than one place.",
  SC: "I can name a big idea in the story (such as imagination, learning or courage) and find at least two examples in different parts of the book that show it.",
  rubricTags: ["R1","R4","R10"],
  days: {
    mon: D("Chapter 14 (part 2)", "The dream jars · start at ‘The BFG stood up and walked over to one of the many shelves.’ · stop after the tiny labels (‘…rock and roll musik when it flies.’)",
      "What is the best dream you’ve ever had? What made it feel so good when you woke up?",
      "Choose two of the dreams on the BFG’s shelves. What is each about, and how does each one end?",
      "Many of the dreams end with the dreamer waking up to real life (a mum calling for breakfast, a dad saying ‘get up you lazy slob’). Why does Dahl end so many dreams this way? What does it tell us about what dreams are for?",
      "Write a two-sentence dream label of your own: a dream that makes your life better for one night, with a funny ending when you wake up."),
    tue: D("Chapters 14 (end) – 15 (part 1)", "The book from the bedroom, and the giants gallop to England · start at ‘What amazes me,’ Sophie said · stop after ‘…how is you getting in to see the Queen anyway?’",
      "Have you ever taught yourself something (a skill, a word, a game)? How did you do it?",
      "How did the BFG learn to read and write, and what book did he learn from? Where are the giants going that night?",
      "The BFG says he can’t stop the giants because he is a ‘titchy little runty giant’, but Sophie won’t give up. Compare how the two characters respond to feeling helpless.",
      "Sophie says, ‘We can’t just sit here and do nothing!’ Write about a time you refused to do nothing about something that wasn’t right — or something you would do."),
    wed: D("Chapter 15 (part 2)", "‘We’ll make her dream it!’ · start at ‘Now hold on a sec,’ Sophie said · stop after ‘Very close,’ the BFG said.",
      "When someone doesn’t believe you, how can you convince them? Share a strategy.",
      "What is the problem with telling the Queen directly, according to the BFG? What is Sophie’s alternative idea?",
      "The BFG compares mixing dreams to mixing a cake. Explain how this comparison helps Sophie (and us) understand how dreams can be made. Why do authors use comparisons like this?",
      "Write your own comparison to explain something complicated to a friend (‘A dream is like a…’). Explain it in two sentences."),
    thu: D("Chapter 15 (part 3)", "The dream Sophie designs · start at ‘I want the Queen to dream that nine disgusting giants…’",
      "If you were writing a dream to persuade a leader to act, what would you put in it?",
      "List the parts of the dream Sophie asks the BFG to mix for the Queen, and explain how she plans to ‘prove’ it’s real.",
      "Sophie says the window-sill is ‘the lovely part’ because a dream that comes true will make the Queen believe the rest. What does she understand about how people come to believe things?",
      "Sophie promises the BFG he’ll be a hero and never eat snozzcumbers again. How does she persuade him? How could you persuade a shy friend to do something brave?"),
  },
  projects: [
    P("poster", "Phizzwizards Available Here!", "Design an advertisement for the BFG’s dream collection with three sample labels (a girls’ dream, a boys’ dream and a tiny one-line label)."),
    P("comic", "The Dream Comic", "Turn one of the BFG’s dream labels (or your own) into a 6-panel comic, including the ‘waking up’ twist."),
    P("drama", "Argument on the Blue Rock", "Act out Sophie trying to convince the BFG to go to London while he explains why he can’t. Show how each character’s voice changes as the argument goes on."),
    P("journal", "The BFG’s Reading Log", "Write the BFG’s diary about teaching himself to read from one borrowed book, using his own way of spelling and speaking."),
  ],
  quiz: [
    Q("What happens at the end of many of the BFG’s dreams?", "The dreamer wakes up to real life (a parent’s voice, a spelling telling-off)."),
    Q("True or False: The BFG keeps boys’ and girls’ dreams on the same shelf.", "False. He has separate dreams for girls and boys.", "tf"),
    Q("In the dream with the teacher, how does the dreamer put her to sleep?", "By staring at her very hard in a special way."),
    Q("What can the dreamer do with the suction boots?", "Walk up the kitchen wall and across the ceiling."),
    Q("What happens in the dream when the dreamer presses his tummy button?", "He becomes invisible."),
    Q("True or False: The BFG finds writing his labels quick and easy.", "False. He prints slowly with lots of mistakes.", "tf"),
    Q("Vocabulary: What does ‘invisible’ mean?", "Can’t be seen."),
    Q("What book did the BFG learn to read from?", "Nicholas Nickleby."),
    Q("Who does the BFG say wrote it?", "‘Dahl’s Chickens’ (he means Charles Dickens)."),
    Q("How did the BFG get the book?", "He ‘borrowed’ it from a boy’s bedroom table while blowing a dream, about eighty years ago; he plans to put it back."),
    Q("Where do the giants say they are going that night?", "England, to snatch schoolchildren."),
    Q("True or False: The BFG says he and Sophie can chase the giants and warn everyone.", "False. The giants are twice as fast and would finish before they arrived.", "tf"),
    Q("Why does the BFG say he can’t show himself to humans?", "They would put him in a zoo, and they might send Sophie back to an orphanage."),
    Q("Who does Sophie suggest they go to see?", "The Queen of England."),
    Q("Why does the BFG think the Queen won’t believe Sophie?", "Humans don’t believe in giants, so it would sound like a ‘wonky tall story’."),
    Q("What is Sophie’s clever idea?", "To make the Queen dream about the giants using a specially mixed dream."),
    Q("What familiar thing does the BFG compare mixing dreams to?", "Mixing a cake."),
    Q("Name three things Sophie wants to be in the Queen’s dream.", "Any three: nine giants galloping to England; children being snatched; the giants’ names; a Big Friendly Giant who can show where they live; a girl called Sophie on the window-sill."),
    Q("Why must Sophie be on the Queen’s window-sill?", "When the Queen wakes and sees her, part of the dream will have come true, so she’ll believe the rest."),
    Q("What does Sophie promise the BFG if the plan works?", "He’ll be a hero, and he’ll never have to eat snozzcumbers again."),
  ],
},
{
  num: 6, title: "The Great Plan", chapters: "Chapters 16–19",
  LI: "We are learning to explain how each step of a plan leads to the next (cause and effect) and where things might go wrong.",
  SC: "I can explain how one event in the plan causes the next, and predict a problem the characters might face.",
  rubricTags: ["R3","R7","R8"],
  days: {
    mon: D("Chapter 16 (part 1)", "Mixing the Dream · stop after ‘I refuse to sit next to that beastly thing!’",
      "Have you ever followed a recipe or a set of instructions? What happens when one step goes wrong?",
      "Describe the steps the BFG follows to mix the dream (gathering, egg-beater, bubbles, the trogglehumper).",
      "Sophie says ‘I don’t want to give the Queen a nightmare!’ but the BFG says it’s the only way. Do you agree with him? Is it fair to scare one person to save many?",
      "Write your own three-step ‘recipe’ for mixing a dream that would make someone brave. Include ingredients and amounts in gobblefunk."),
    tue: D("Chapters 16 (end) – 17 (part 1)", "The ear ride to London · start at ‘Then where is you going to sit?’ · stop after ‘…seeing things that weren’t there.’",
      "What is the most comfortable place you have ever travelled in? What made it comfortable?",
      "Where does Sophie ride on the journey, and why does she have to whisper?",
      "On the way they see the giants galloping home with ‘bulging stomachs’. How does this encounter change Sophie’s feelings about the mission?",
      "Write two sentences in your ‘under-the-breath’ voice describing London at night as seen from the BFG’s ear."),
    wed: D("Chapters 17 (part 2) – 18", "Hyde Park Corner and the Palace · start at ‘Sophie and the BFG came at last to a large place full of trees.’",
      "What’s the hardest thing you’ve done that needed you to be very, very quiet?",
      "How do Sophie and the BFG cross Hyde Park Corner and get into the Palace garden? How do they find the Queen’s bedroom?",
      "Sophie knows London and the Palace; the BFG has his ears. Give two examples of how they help each other, and explain why teamwork matters in this mission.",
      "The BFG kisses Sophie on the cheek and melts away into the garden. Write two sentences about what each of them is feeling in that moment."),
    thu: D("Chapter 19 (part 1)", "Dawn and the Queen’s nightmare · stop after ‘Please do.’ (just before the curtains are pulled aside)",
      "When something strange happens to you and someone else confirms it, how does that change what you believe?",
      "What does the Queen tell Mary about her dream, and what does Mary show her?",
      "Mary says the newspaper story matches the Queen’s dream. Why does this coincidence help convince the Queen the dream may be true? How does it build tension?",
      "Write a newspaper headline and opening paragraph for the story that shocked Mary. Use formal, factual language."),
  },
  projects: [
    P("poster", "How to Mix a Dream", "Design a step-by-step recipe poster for mixing the Queen’s dream: ingredients, equipment, method and one big warning."),
    P("comic", "Ride in the Ear", "6 panels of the journey from Giant Country to Hyde Park, from the view inside the BFG’s ear."),
    P("drama", "Listening at the Windows", "Act out the BFG listening at each window of the Palace for breathing-voices. Use whisper-only dialogue and freeze-frames."),
    P("journal", "Sophie’s Diary: On the Window-sill", "Write Sophie’s diary from the moment the BFG leaves until the church clock strikes seven."),
  ],
  quiz: [
    Q("What does the BFG use to mix the dreams together?", "A gigantic egg-beater."),
    Q("How big is the jar he mixes them in?", "As big as a washing machine."),
    Q("What happens to the leftover dream-bits after mixing?", "They float out of the cave as coloured bubbles and drift back to Dream Country."),
    Q("What kind of dream does the mixture turn into, and why does Sophie dislike it?", "A trogglehumper (nightmare), because it shows children being eaten and she doesn’t want the Queen to suffer."),
    Q("True or False: The BFG persuades Sophie that the Queen will accept a nightmare if it saves lives.", "True.", "tf"),
    Q("Where does the BFG carry the dream jar?", "In a pocket of his cloak (not the suitcase)."),
    Q("Where does Sophie sit for the journey, and why not with the jar?", "In the BFG’s right ear, because she refuses to sit next to the ‘beastly’ nightmare."),
    Q("Why must Sophie whisper to the BFG?", "His hearing is so sensitive that her normal voice is like thunder and hurts his ears."),
    Q("What do Sophie and the BFG see on the way to England?", "The nine giants galloping home with bulging stomachs."),
    Q("What landmark do they reach in London, and how does the BFG cross it?", "Hyde Park Corner; he leaps right over the arch and the horse and rider."),
    Q("Who guides the BFG through London?", "Sophie — she knows the city because she used to live in a London orphanage."),
    Q("What protects the Palace garden?", "A high brick wall with spikes, and a watchman with a guard-dog."),
    Q("How does the BFG find the Queen’s bedroom?", "He listens at the windows for the sound of breathing until he hears a lady sleeping in the central window."),
    Q("How is the dream delivered?", "He pours it into his trumpet and blows it through the open window while Sophie waits on the window-sill."),
    Q("What time does the church clock strike as Sophie waits?", "Seven."),
    Q("What does the Queen cry out in her sleep?", "‘No! Don’t — someone stop them!’ — she is having the nightmare."),
    Q("Who brings the Queen her breakfast tray?", "Mary, the maid."),
    Q("What do the newspaper headlines say?", "Eighteen girls have vanished from one school and fourteen boys from another, with bones found under the dormitory windows."),
    Q("Inference: Why is Mary so shocked?", "The newspaper story matches the Queen’s dream exactly, so it seems too much to be a coincidence."),
    Q("What happens when Mary draws the curtains?", "Mary screams and Sophie freezes; the Queen sees her on the window-sill."),
  ],
},
{
  num: 7, title: "Meet the Queen", chapters: "Chapters 19–20",
  LI: "We are learning to notice how an author uses different registers of language (formal, casual, invented) to show who a character is and to create humour.",
  SC: "I can find examples of formal and informal language in the text, explain what each tells us about the speaker, and use the right register when I write for a particular audience.",
  rubricTags: ["R2","R5","R7"],
  days: {
    mon: D("Chapter 19 (part 2)", "The Queen sees Sophie · start at ‘With a swish, the great curtains were pulled aside.’ · stop after ‘Take her downstairs and give her some breakfast,’ the Queen said.",
      "Think of a time you had to talk to someone very important (a principal, a grandparent, a stranger). How did you change the way you spoke?",
      "What is the Queen’s first reaction when she sees Sophie on the window-sill, and why does she look frightened rather than surprised?",
      "The Queen says, ‘I dreamed that a giant put you there!’ How does the dream help Sophie convince her? Which of the Queen’s words show she is trying to stay calm and polite?",
      "Write a short exchange (four lines) between Sophie and a very important person she has just met. Use polite, formal language like the Queen’s (‘Your Majesty’, ‘I should be delighted…’)."),
    tue: D("Chapter 19 (end)", "The BFG bows before the Queen · start at ‘Just then, there was a rustle in the bushes beside the lake.’ · stop at the end of the chapter",
      "How do you feel about meeting someone you’ve only heard about? What do you hope they’ll be like?",
      "How does the BFG approach the window, and what does he say to the Queen? What happens to the gardener?",
      "Compare how the BFG speaks (‘Your Majester… I is your humbug servant’) with how the Queen speaks (‘We are very pleased to meet you’). What does each way of speaking tell you about the two characters? Why do you think the Queen never laughs at him?",
      "Write three of the BFG’s greetings to the Queen using his gobblefunk titles (Oh, Ruler of Straight Lines!). Then rewrite one in the way Sophie would say it."),
    wed: D("Chapter 20 (part 1)", "The Royal Breakfast: Mr Tibbs and the giant’s chair · stop after ‘…bicirculers and telescoops to see what is going on at the other end!’",
      "Have you ever had to organise something in a great hurry? What was it, and how did you manage?",
      "What does Mr Tibbs work out when he hears a 24-foot giant is coming to breakfast? List the furniture the footmen build for the BFG.",
      "Mr Tibbs says a six-foot man needs a two-foot-high seat, so a 24-foot giant needs an eight-foot seat: ‘Everything must be multiplied by four.’ Show the maths for the eggs, bacon and toast. How does the narrator use long lists and grand words to make Mr Tibbs funny?",
      "Design a giant-sized item for another giant-sized guest who is 36 feet tall. Show your scale working and the new sizes."),
    thu: D("Chapter 20 (part 2)", "Breakfast with the giant · start at ‘Footmen arrived carrying silver trays…’ · stop after ‘Tell him to bake more,’ the Queen said.",
      "What is the most unusual breakfast you have ever eaten? How did it taste?",
      "How does the BFG react to real food after years of snozzcumbers? What does he say about coffee and about frobscottle?",
      "The Queen keeps calm and hospitable even when the BFG whizzpops. What does Dahl want us to think about her? Find two lines that show her sense of humour and two that show her authority.",
      "Write a formal note from Mr Tibbs to the chef explaining what the giant wants next, then a casual text from the chef to a friend complaining about it. Use the correct register for each."),
  },
  projects: [
    P("poster", "The Giant’s Breakfast Table", "Draw and label Mr Tibbs’s giant-sized breakfast setting (piano, chest-of-drawers, grandfather clocks, ping-pong table) with a scale key showing real size and giant size (×4)."),
    P("comic", "Curtains Open!", "6 panels showing the moment the curtains are drawn: Sophie, the Queen, Mary, the gardener and the BFG all reacting."),
    P("drama", "A Royal Introduction", "Perform the meeting of the Queen and the BFG. Use two registers: the Queen’s formal speech and the BFG’s gobblefunk. Add a freeze-frame for the moment the gardener faints."),
    P("journal", "Mary’s Diary: The Strangest Morning", "Write the maid’s diary for the morning the Queen’s breakfast fell on the floor. Use formal, old-fashioned diary language."),
  ],
  quiz: [
    Q("Who brings the Queen’s breakfast and drops the tray?", "Mary, the maid."),
    Q("What do the newspaper headlines say has happened?", "Eighteen girls vanished from Roedean School and fourteen boys from Eton, with bones found under the dormitory windows."),
    Q("What part of the dream makes the Queen start to believe Sophie?", "She dreamed a little girl would be sitting on her window-sill and that a giant put her there."),
    Q("What does the Queen ask Sophie to prove she is real?", "‘Are you real?’ — she asks Sophie’s name and how she got on to the sill."),
    Q("How tall is the BFG when he walks across the lawn?", "Twenty-four feet."),
    Q("What does the gardener do when he sees the BFG?", "He faints (keels over in a dead faint)."),
    Q("What does the BFG call the Queen?", "Your Majester (and other titles such as Ruler of Straight Lines)."),
    Q("What does Sophie say about the BFG’s speech, and what does the Queen reply?", "‘He never went to school’; the Queen says they must send him to school."),
    Q("Where does the Queen decide breakfast will be served, and why?", "In the Great Ballroom, because it has the highest ceiling."),
    Q("What does Mr Tibbs whisper about the giant’s chair?", "It will be exactly eight feet off the ground (chest-of-drawers on a grand piano)."),
    Q("What does Mr Tibbs decide must be done to everything for the giant?", "Multiply it by four."),
    Q("If two eggs become eight and four rashers of bacon become sixteen, how many pieces of toast come from three?", "Twelve."),
    Q("What pieces of furniture make up the BFG’s table?", "Four twelve-foot grandfather clocks with the young Prince’s ping-pong table on top, covered by a damask tablecloth."),
    Q("What does the Queen pin on Sophie’s dress?", "A superb sapphire brooch."),
    Q("What crashes into the BFG’s head as he walks through the Ballroom?", "An enormous crystal chandelier (Louis the Fifteenth)."),
    Q("What does the BFG use to eat his breakfast?", "A garden spade (and a garden fork), with a great sword as a knife."),
    Q("What does the BFG say coffee tastes like?", "‘Filthsome’ (he asks for frobscottle instead)."),
    Q("What does the BFG do that shocks the Queen, and how does she react?", "He whizzpops; she jumps, says she prefers the bagpipes, but cannot stop smiling."),
    Q("How many fried eggs does the BFG eat before the chef runs out?", "Seventy-two."),
    Q("Inference: Why does the author write the Queen and Mr Tibbs in very formal language while the BFG speaks gobblefunk?", "The contrast makes the scene funny and shows who is grand, who is anxious, and who is simple and kind."),
  ],
},
{
  num: 8, title: "Capture!", chapters: "Chapters 20–22",
  LI: "We are learning to form an opinion about a character’s choices and to justify it with reasons and evidence from the text.",
  SC: "I can say whether I agree or disagree with a decision in the story, give at least two reasons, and support them with a quotation or example.",
  rubricTags: ["R1","R4","R9"],
  days: {
    mon: D("Chapter 20 (end)", "The Queen checks the BFG’s story · start at ‘While all this was going on, Sophie had been telling the Queen everything…’ · stop at the end of the chapter",
      "How would you check whether a strange story is true? Who could you ask, and what could you look for?",
      "What two telephone calls does the Queen make, and what does each person say?",
      "The Queen doesn’t simply believe the BFG: she checks his story with the Kings and Sultans first. Do you think this was a wise decision? Give two reasons, using ideas from the text. (Teacher note: the Sultan’s remarks reflect outdated ideas about a real place; discuss why we should be careful about stereotypes.)",
      "Write the phone call the Queen might have made to a third country, using formal language. What would she ask and what would the reply be?"),
    tue: D("Chapter 21", "The Plan · read the whole chapter",
      "‘Two wrongs don’t make a right.’ What do you think this saying means? Can you give an example?",
      "What plan do the BFG, the Queen and the two military leaders agree on? Who does what?",
      "The Head of the Army wants to ‘mow them down with machine-guns’, but the Queen says ‘we must bring them back alive.’ Whose idea do you agree with, and why? Support your opinion with two reasons.",
      "Write a persuasive paragraph (5–6 sentences) about whether the giants should be captured or punished in some other way. Include a reason, evidence and a closing statement."),
    wed: D("Chapter 22 (part 1)", "The flight to Giant Country · stop after ‘They all moved on.’",
      "Have you ever followed someone without knowing where you were going? How did it feel?",
      "How does the BFG lead the helicopters, and what happens to the Head of the Air Force’s atlas?",
      "The pilot says the two blank pages at the back of an atlas ‘are for new countries. You’re meant to fill them in yourself.’ What do you think he means? How does this show that he thinks differently from the Head of the Air Force?",
      "Draw a map of Giant Country (blue rocks and dead trees!) and write a caption from the young pilot’s point of view."),
    thu: D("Chapter 22 (part 2)", "Trapping the giants and the brooch trick · start at ‘Then they saw them!’ · stop after ‘…wiped the pin and handed it back to Sophie.’",
      "When has a small thing you did solved a big problem?",
      "What does Sophie do to stop the Fleshlumpeater from eating the soldier, and how does the BFG use her trick?",
      "The BFG makes the giant believe he was bitten by a ‘vindscreen viper’. Was tricking the Fleshlumpeater the right thing to do? Explain your opinion using two reasons, referring to what you know about the giants.",
      "Write a short newspaper report on the capture of the giants, including a quote from a soldier who was in the jeep."),
  },
  projects: [
    P("poster", "Wanted: The Nine Giants", "Design a poster in the style of a wanted notice showing the nine giants’ names, sizes and crimes (using descriptions only, no illustrations from the book)."),
    P("comic", "The Vindscreen Viper", "6 panels of the trick: the brooch, the fake snake-bite, the tied ankles and the reveal."),
    P("drama", "The Debate: Bombs or Ropes?", "Stage a debate between the Head of the Army and the Queen about how to deal with the giants. The audience votes and gives reasons."),
    P("journal", "The Pilot’s Log", "Write the young pilot’s log for the flight beyond the atlas, with times, observations and feelings."),
  ],
  quiz: [
    Q("Where did the nine giants go two nights before the Queen’s dream?", "Sweden, for the ‘Sweden sour’ taste."),
    Q("How many people had gone missing in Sweden?", "Twenty-six."),
    Q("What does the King of Sweden say when the Queen says giants ate them?", "‘Are you feeling all right?’ — he thinks she needs a doctor."),
    Q("Where did the BFG say the Fleshlumpeater was going three nights ago?", "Baghdad."),
    Q("Who disappeared from Baghdad, and with whom?", "The Sultan’s uncle, Caliph Haroun al Rashid, with his wife and ten children."),
    Q("What does the Queen say when she is convinced?", "That the BFG’s story is quite true, and she summons the Head of the Army and the Head of the Air Force."),
    Q("What does the Queen say about the Army’s plan to shoot the giants?", "‘Two wrongs don’t make a right.’"),
    Q("What is the ‘Land of Noddy’?", "The Land of Nod — sleep; the giants sleep there every afternoon."),
    Q("What do the soldiers have to do to the giants?", "Tie their arms and legs with ropes and chains while they sleep."),
    Q("How are the giants to be carried to England?", "Slung underneath nine helicopters like torpedoes (‘porteedos’)."),
    Q("Why can’t the BFG show the pilots where Giant Country is on a map?", "He has never heard of maps; he just knows the way by galloping there."),
    Q("Where does Sophie ride during the journey?", "In the BFG’s right ear."),
    Q("What does the BFG ask the Queen if he can bring back to England?", "His whole collection of dreams."),
    Q("What do the blank pages at the back of the atlas represent, according to the pilot?", "New countries that you fill in yourself."),
    Q("What does the BFG say the loud rumbling noises are?", "The giants snortling (snoring) in their sleep."),
    Q("How many soldiers and jeeps are there for each giant?", "Six soldiers per giant and one jeep per helicopter (nine jeeps)."),
    Q("Which giant wakes up, and why?", "The Fleshlumpeater, because the soldiers pull at his arm."),
    Q("What does Sophie use to stop the Fleshlumpeater?", "The sapphire brooch — she rams its pin into his ankle."),
    Q("What story does the BFG tell the Fleshlumpeater about his ankle?", "That a ‘poisnowse vindscreen viper’ has bitten him."),
    Q("How many jars of dreams are loaded up from the BFG’s cave?", "About fifty thousand."),
  ],
},
{
  num: 9, title: "The Author", chapters: "Chapters 22–24",
  LI: "We are learning to evaluate an ending and to compare how a story’s beginning and end show change in its characters.",
  SC: "I can explain how the ending resolves the problem, compare the first and last chapters, and say whether I think the ending is satisfying and why.",
  rubricTags: ["R4","R6","R10"],
  days: {
    mon: D("Chapters 22 (end) – 23", "Trussed up, the pit and the snozzcumbers · start at ‘Curiously, not one of the other eight snoring giants had woken up during this shimozzle.’ · read to the end of Chapter 23",
      "Think about a time when justice was done fairly. What made it fair?",
      "How are the giants carried home, and what happens in the pit? What does the BFG bring from Giant Country?",
      "The giants are imprisoned and fed snozzcumbers ‘for ever’. Is that a fair ending for them? Explain your view using at least two reasons, considering what they did and what the Queen said about murder.",
      "Write a sign for the fence around the pit, and a short notice from the head keeper explaining the rules in formal language."),
    tue: D("Chapter 24", "The Author · read the whole chapter",
      "What is the best way to say thank you to someone who has done something great for you?",
      "What honours and presents do the BFG and Sophie receive, and how does the BFG change after he learns to read?",
      "The BFG chooses to write a book and keep his name off it. What does this tell you about his character? What has changed in him since Chapter 1?",
      "Write a paragraph beginning ‘The BFG never put his own name on the book because…’ using at least two pieces of evidence."),
    wed: D("Chapters 1 and 24 (bookends)", "Re-read the opening page of Chapter 1 and the closing page of Chapter 24 and compare",
      "Look at the first line of a favourite book and its last. Do they ‘talk’ to each other?",
      "Where are Sophie and the BFG at the start and at the end? What has changed about their lives?",
      "Compare the mood of Chapter 1 (silence, moonlight, fear, a tall black figure) with the last chapter. How does Dahl show that fear has become friendship? Which words in each part help you feel the difference?",
      "Write a paragraph comparing the two chapters. Use the sentence stems ‘At the start…’, ‘By the end…’, and ‘This shows that…’."),
    thu: D("Reader’s theatre", "A performance of key scenes from the whole book",
      "Which scene in the book would you most like to perform, and why?",
      "Which scenes did your group choose, and how will you show the character’s voice?",
      "Which character has changed the most in the story? Support your view with evidence from at least two chapters.",
      "Write a short reflection: what did you learn about the story and about yourself as a reader?"),
  },
  projects: [
    P("poster", "The Pit of Snozzcumbers", "Design an information poster for tourists visiting the pit: rules, feeding times and what not to do."),
    P("comic", "From Orphan to Friend", "8 panels charting Sophie’s journey from the moonlit dormitory to the cottage at Windsor."),
    P("drama", "The Book Is Published", "Act out the moment the BFG shows the Queen his book and she reads it aloud to her grandchildren."),
    P("journal", "The Author’s Note", "Write an author’s note from the BFG explaining why he wrote the book and why he used someone else’s name."),
  ],
  quiz: [
    Q("What is the name of the witching hour, and what happens during it?", "A moment in the middle of the night when everyone is in a deep sleep and dark things come out."),
    Q("What does Sophie hold that she needs to see clearly?", "Her glasses, with steel rims and thick lenses."),
    Q("Who is Sophie’s worst tormentor at the orphanage?", "Mrs Clonkers, the matron."),
    Q("How tall is the BFG compared with the other giants?", "Twenty-four feet tall; the others are fifty feet or more."),
    Q("What does the BFG do for a living?", "He catches dreams and blows them into children’s bedrooms through a trumpet."),
    Q("What does frobscottle do differently from ordinary fizzy drinks?", "The bubbles go down, so it causes whizzpopping."),
    Q("What is the only thing the BFG has eaten before meeting the Queen?", "Snozzcumbers."),
    Q("Which giant is the biggest and cruellest?", "The Fleshlumpeater."),
    Q("What are the nine giants’ names?", "Fleshlumpeater, Bonecruncher, Manhugger, Childchewer, Meatdripper, Gizzardgulper, Maidmasher, Bloodbottler, Butcher Boy."),
    Q("What happens in Dream Country?", "The BFG catches dreams in a net."),
    Q("What does the BFG mix for the Queen?", "A trogglehumper — a nightmare that shows the disappearances."),
    Q("What did the BFG used to call Charles Dickens before he learned to read?", "Dahl’s Chickens."),
    Q("What does the Queen say about murder?", "‘I do not approve of murder … Two wrongs don’t make a right.’"),
    Q("What lets Sophie save the soldier from the Fleshlumpeater?", "The Queen’s sapphire brooch used as a pin."),
    Q("Where are the giants imprisoned?", "In a huge pit, about twice the size of a football field and five hundred feet deep."),
    Q("What do the giants get to eat in the pit?", "Snozzcumbers only."),
    Q("What title does the Queen give the BFG?", "The Royal Dream-Blower."),
    Q("Where do the BFG and Sophie live at the end?", "Beside the Queen’s castle in Windsor Great Park, in a specially built house and cottage."),
    Q("Who taught the BFG to read and write, and what did he become?", "Sophie taught him, and he became a tremendous reader and a writer."),
    Q("Why didn’t the BFG put his own name on the book?", "He was very modest, so he used someone else’s name (the author, Roald Dahl)."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "Kindness Comes in Every Size Campaign", desc: "Create a campaign (posters, slogans, a short speech) celebrating the idea that kindness and courage are not measured in feet, using the BFG and Sophie's friendship as the model." },
    { title: "Extended Drama/Performance", desc: "Imagine a new dream-blowing adventure for the BFG and Sophie after the book ends, or dramatise a scene from a child's point of view as the dream arrives, told with humour and heart." },
    { title: "Character Case File — The BFG", desc: "An in-depth profile (poster + written report + panels) tracking the BFG's journey and change across the whole book, with evidence from every part of the story he appears in." },
    { title: "\"My Own Gobblefunk\" Class Anthology", desc: "Each student contributes one illustrated page with an invented word, its meaning, and a sentence that gives context clues, echoing the BFG's own way with words." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: enjoy a class 'frobscottle' (lemonade) toast and share favourite moments from the term.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events.",
      wt: "Explains some of the BFG's or Sophie's motives or relationships, with limited evidence.",
      a: "Explains a theme (kindness, courage, friendship, being different) and supports it with clear evidence from the book.",
      example: "A Character Case File showing the BFG changing from a lonely giant to the Royal Dream-Blower, with an event from the beginning, middle and end of the book." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A campaign poster with a catchy slogan, three persuasive reasons and a picture that matches the message." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A drama that adds a new dream-blowing scene, rehearsed and improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
